import test,{before,after} from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {homedir} from 'node:os'
import {join} from 'node:path'
import {Pool} from 'pg'
import {PostgreSqlContainer,type StartedPostgreSqlContainer} from '@testcontainers/postgresql'
import {MarketContentStore,initializeMarketContents} from '../src/market/content-store.ts'
import {IndustryLoadService,initializeIndustryLoads} from '../src/work/industry-loads.ts'
import {createIndustryLoadSource} from '../src/work/industry-load-source.ts'
import {IndustryWorkSource} from '../src/work/industry-work-source.ts'
import {IndustryTaskService,initializeIndustryTasks} from '../src/work/industry-tasks.ts'
import {TaskService,initializeTasks} from '../src/work/tasks.ts'
import {initializeRoles,RoleService} from '../src/work/roles.ts'
import {IndustryRoleSource} from '../src/work/industry-role-source.ts'
import {IndustryRoleService,initializeIndustryRoles} from '../src/work/industry-roles.ts'
import {RoleLifecycleService,initializeRoleLifecycle} from '../src/work/role-lifecycle.ts'
import {initializeObjectConversations,ObjectConversationService} from '../src/work/object-conversations.ts'
import {initializeTaskRuns,TaskRunService} from '../src/work/task-runs.ts'
import {testRoleResponsibility} from './role-test-fixture.ts'
import {initializeCollaboration} from '../src/work/collaboration.ts'
import {initializeGroupAgentGrants} from '../src/work/group-agent-grants.ts'

let container:StartedPostgreSqlContainer,pool:Pool
const identity={id:randomUUID,now:()=>new Date().toISOString()},enc=new TextEncoder()
before(async()=>{process.env.DOCKER_HOST='unix://'+join(homedir(),'.orbstack/run/docker.sock');process.env.TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE='/var/run/docker.sock';container=await new PostgreSqlContainer('postgres:17-alpine').start();pool=new Pool({connectionString:container.getConnectionUri()});await initializeMarketContents(pool);await initializeRoles(pool);await initializeCollaboration(pool);await initializeGroupAgentGrants(pool);await initializeTasks(pool);await initializeIndustryLoads(pool);await initializeIndustryRoles(pool);await initializeIndustryTasks(pool);await initializeRoleLifecycle(pool);await initializeObjectConversations(pool);await initializeTaskRuns(pool)},{timeout:180_000})
after(async()=>{await pool?.end();await container?.stop()})
async function fixture(db:Pool,bytes=enc.encode(JSON.stringify({format:'teloa.work-template/v1',id:'review',title:'资料核对',version:'1.0.0',domain:'general',description:'逐项核对资料',requirements:['资料','范围'],output:'研究简报',skills:[{id:'brief',title:'简报',version:'1.0.0'}]}))){const owner=randomUUID(),market=new MarketContentStore(db,identity),manifest={format:'teloa.business-package/v2',id:'work',title:'工作',version:'1.0.0',domain:'general',description:'工作',resources:[{id:'review',kind:'work-template',title:'资料核对',version:'1.0.0',required:true,source:{kind:'local',path:'work.json'}},{id:'analyst',kind:'role',title:'分析岗',version:'1.0.0',required:true,source:{kind:'local',path:'role.json'}}],relations:[{kind:'role-work',from:'analyst',to:'review'}],entrypoints:['review']},saved=await market.import({ownerId:owner,kind:'human'},{kind:'industry-template',requestId:randomUUID(),source:{kind:'upload',name:'工作'},manifestPath:'teloa.json',files:[{path:'teloa.json',bytes:enc.encode(JSON.stringify(manifest))},{path:'work.json',bytes},{path:'role.json',bytes:enc.encode(JSON.stringify({format:'teloa.role/v1',name:'分析岗',kind:'employee',duty:'核对',dataScope:'资料',executionScope:'代拟',runtimeConfig:{agentPresetId:'industry-analyst'}}))}],references:[]}),loads=new IndustryLoadService(db,identity,createIndustryLoadSource(market)),load=await loads.create(owner,{requestId:randomUUID(),contentId:saved.content.id,contentHash:saved.content.hash,target:{kind:'new',spaceId:randomUUID(),name:'工作空间'}}),item=load.items.find(row=>row.localId==='review')!,tasks=new TaskService(db,identity),service=new IndustryTaskService(db,identity,new IndustryWorkSource(market,loads),tasks);return {owner,load,item,tasks,service,market,loads,roleItem:load.items.find(row=>row.localId==='analyst')!}}

test('固定预览与同模板多任务，单请求并发只创建一次',async()=>{const f=await fixture(pool),preview=await f.service.preview(f.owner,{loadId:f.load.id,itemInstanceId:f.item.instanceId});assert.deepEqual(preview.requirements,['资料','范围']);const input={requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'核对今天资料',inputs:['路径 A','最近一天']},[a,b]=await Promise.all([f.service.create(f.owner,input),f.service.create(f.owner,input)]);assert.equal(a.task.id,b.task.id);assert.equal(a.task.scope,f.load.space.scope);assert.equal((await f.service.source(f.owner,{taskId:a.task.id}))!.method,'逐项核对资料');const c=await f.service.create(f.owner,{...input,requestId:randomUUID()});assert.notEqual(c.task.id,a.task.id);assert.equal((await pool.query('select count(*)::int n from teloa_tasks where owner_id=$1',[f.owner])).rows[0].n,2)})

test('同请求改输入冲突且不能收养普通任务',async()=>{const f=await fixture(pool),requestId=randomUUID(),base={requestId,loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'核对',inputs:['A','B']};await f.service.create(f.owner,base);await assert.rejects(f.service.create(f.owner,{...base,inputs:['X','B']}),{code:'teloa/conflict'});const other=randomUUID();await f.tasks.create(f.owner,{requestId:other,fields:{title:'资料核对',goal:'核对',scope:f.load.space.scope}});await assert.rejects(f.service.create(f.owner,{...base,requestId:other}),{code:'teloa/conflict'})})

test('COMMIT已成功但回包丢失时同请求恢复同一任务',async()=>{
 const f=await fixture(pool),input={requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'核对',inputs:['A','B']};let lose=true
 const raw={query:pool.query.bind(pool),connect:async()=>{const client=await pool.connect();return {query:async(...args:Parameters<typeof client.query>)=>{const result=await (client.query as (...values:Parameters<typeof client.query>)=>ReturnType<typeof client.query>)(...args);if(lose&&typeof args[0]==='string'&&args[0].toLowerCase()==='commit'){lose=false;throw Error('回包丢失')}return result},release:client.release.bind(client)}}};
 const lossy=raw as unknown as Pool,service=new IndustryTaskService(lossy,identity,new IndustryWorkSource(new MarketContentStore(lossy,identity),f.loads),f.tasks)
 await assert.rejects(service.create(f.owner,input));const recovered=await f.service.create(f.owner,input);assert.equal(recovered.task.id,recovered.source.taskId);assert.equal((await pool.query('select count(*)::int n from teloa_tasks where owner_id=$1',[f.owner])).rows[0].n,1)
})

test('任务合法编辑后保留固定来源，普通任务来源为null，坏来源显式失败',async()=>{const f=await fixture(pool),saved=await f.service.create(f.owner,{requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'原目标',inputs:['A','B']}),edited=await f.tasks.edit(f.owner,{taskId:saved.task.id,expectedVersion:1,fields:{title:'新标题',goal:'新目标'}});assert.equal((await f.service.source(f.owner,{taskId:edited.id}))!.inputs[0],'A');const plain=await f.tasks.create(f.owner,{requestId:randomUUID(),fields:{title:'普通',goal:'普通',scope:f.load.space.scope}});assert.equal(await f.service.source(f.owner,{taskId:plain.id}),null);await pool.query("update teloa_industry_task_sources set source_snapshot=jsonb_set(source_snapshot,'{inputs,0}','\"篡改\"') where task_id=$1",[saved.task.id]);await assert.rejects(f.service.source(f.owner,{taskId:saved.task.id}),{code:'teloa/storage-corrupt'})})

test('严格来源拒绝未知字段、非法UTF8和超限文件且不留任务',async()=>{for(const bytes of [enc.encode(JSON.stringify({format:'teloa.work-template/v1',id:'review',title:'资料核对',version:'1.0.0',domain:'general',description:'方法',requirements:['资料'],output:'报告',skills:[],scope:'general'})),new Uint8Array([0xff]),new Uint8Array(128*1024+1).fill(32)]){const f=await fixture(pool,bytes);await assert.rejects(f.service.create(f.owner,{requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'目标',inputs:['输入']}),{code:'teloa/source-unavailable'});assert.equal((await pool.query('select count(*)::int n from teloa_tasks where owner_id=$1',[f.owner])).rows[0].n,0)}})

test('真实行业来源进入执行固定输入并在领取时复核',async()=>{const f=await fixture(pool),roles=new RoleService(pool,identity),roleInstance=await new IndustryRoleService(pool,identity,f.loads,new IndustryRoleSource(f.market,f.loads),{get:async()=>{throw Error('无知识关系')}},roles).instantiate(f.owner,{requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.roleItem.instanceId}),active=(await new RoleLifecycleService(pool,identity).change(f.owner,{roleId:roleInstance.role!.id,expectedVersion:roleInstance.role!.version,action:'resume',reason:'执行验收'})).role,saved=await f.service.create(f.owner,{requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'核对今天资料',inputs:['路径 A','最近一天'],assignee:{roleId:active.id,expectedVersion:active.version}}),sessionId=randomUUID(),conversationId=randomUUID(),inspect=async()=>({id:conversationId,sessionId,ownerId:f.owner,status:'ready'});await new ObjectConversationService(pool,inspect,identity.now).change(f.owner,{requestId:randomUUID(),kind:'task',objectId:saved.task.id,expectedObjectVersion:1,sessionId,expectedLinkVersion:0,action:'link'});const runs=new TaskRunService(pool,identity,inspect,{allowedTools:[],industryContext:f.service.executionContextInTransaction.bind(f.service)}),run=await runs.prepare(f.owner,{requestId:randomUUID(),taskId:saved.task.id,expectedTaskVersion:1,roleId:active.id,expectedRoleVersion:active.version,sessionId,expectedLinkVersion:1});const input=JSON.parse(run.inputText);assert.equal(input.industryContext.method,'逐项核对资料');assert.deepEqual(input.industryContext.inputs,['路径 A','最近一天']);assert.equal(input.industryContext.output,'研究简报');assert.equal((await runs.claim(f.owner,{runId:run.id})).dispatch,true)
 const other=await roles.create(f.owner,{requestId:randomUUID(),fields:{name:'另一岗位',kind:'employee',scopes:[f.load.space.scope],duty:'核对',dataScope:'资料',executionScope:'代拟',skills:[],knowledge:[],responsibility:testRoleResponsibility}}),before=(await pool.query('select count(*)::int n from teloa_tasks where owner_id=$1',[f.owner])).rows[0].n;await pool.query('update teloa_industry_role_instances set role_id=$2 where id=$1',[roleInstance.id,other.id]);await assert.rejects(f.service.create(f.owner,{requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'不应创建',inputs:['A','B'],assignee:{roleId:other.id,expectedVersion:other.version}}),{code:'teloa/conflict'});assert.equal((await pool.query('select count(*)::int n from teloa_tasks where owner_id=$1',[f.owner])).rows[0].n,before)
})

test('max=1事务复用不死锁',async()=>{const db=new Pool({connectionString:container.getConnectionUri(),max:1,connectionTimeoutMillis:1500});try{const f=await fixture(db),saved=await f.service.create(f.owner,{requestId:randomUUID(),loadId:f.load.id,itemInstanceId:f.item.instanceId,goal:'目标',inputs:['A','B']});assert.equal(saved.task.state,'ready')}finally{await db.end()}})
