import test from 'node:test'
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import type {PoolClient} from 'pg'
import type {TaskRun} from '../src/work/task-runs.ts'
import {assertNativeRunAbortProof,readNativeRunSettlement,recordNativeRunAbortProof,recordNativeRunResourceSettlement,type NativeRunAbortProof} from '../src/work/task-run-abort-proof.ts'
const run={id:'run',taskId:'task',sessionId:'session',nativeRequestId:'rpc',state:'ended',evidence:{state:'ended',turn:0,messageSeq:1,endSeq:2,reason:'aborted'},stopRequestedAt:'2026-09-30'} as TaskRun
const digest=(text:string)=>createHash('sha256').update(text).digest('hex')
function fixture(){let saved:Record<string,unknown>|undefined,resource:Record<string,unknown>|undefined;const children:Record<string,unknown>[]=[],links:Record<string,unknown>[]=[];const row={id:'run',owner_id:'owner',task_id:'task',session_id:'session',native_request_id:'rpc',state:'ended',evidence:run.evidence,stop_requested_at:'2026-09-30'};const queries:string[]=[];const db={query:async(sql:string,args:unknown[])=>{queries.push(sql);if(sql.includes('from teloa_task_run_subagents'))return {rows:children};if(sql.includes('from teloa_task_run_runtime_links'))return {rows:links};if(sql.startsWith('select')&&sql.includes('from teloa_task_runs'))return {rows:[row]};if(sql.startsWith('select')&&sql.includes('from teloa_task_run_abort_proofs'))return {rows:saved?[saved]:[]};if(sql.startsWith('select')&&sql.includes('from teloa_task_run_native_settlements'))return {rows:resource?[resource]:[]};if(sql.startsWith('insert into teloa_task_run_native_settlements')){resource={observations:JSON.parse(args[2] as string),association_hash:args[3]};return {rows:[resource],rowCount:1}};if(sql.startsWith('insert into teloa_task_run_abort_proofs')){if(!saved)saved={proof:JSON.parse(args[2] as string),settlement:args[3]};return {rows:[saved],rowCount:1}};throw Error(sql)}} as unknown as PoolClient;return {db,row,children,links,queries}}
async function proof(f:ReturnType<typeof fixture>):Promise<NativeRunAbortProof>{return {runId:run.id,sessionId:run.sessionId,nativeRequestId:run.nativeRequestId,turn:0,ownedEndTurn:0,messageSeq:1,endSeq:2,logCut:2,inheritedEventCount:0,reason:'aborted',source:'native-turn-end',eventHash:'a'.repeat(64),settlementHash:digest(await readNativeRunSettlement(f.db,'owner',run))}}
test('missing_proof_is_rejected',async()=>{const f=fixture();await assert.rejects(assertNativeRunAbortProof(f.db,'owner',run),/证明/)})
test('precise_proof_is_append_only_and_revalidated_on_same_client',async()=>{const f=fixture(),p=await proof(f);await recordNativeRunAbortProof(f.db,'owner',run,p);await assertNativeRunAbortProof(f.db,'owner',run);await recordNativeRunAbortProof(f.db,'owner',run,p);assert.ok(!f.queries.some(q=>/^(begin|commit|rollback)$/i.test(q)));await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,{...p,eventHash:'b'.repeat(64)}))})
test('wrong_tuple_or_synthetic_end_seq_is_rejected',async()=>{const f=fixture(),p=await proof(f);for(const patch of [{runId:'other'},{endSeq:3},{turn:1},{source:'idle'}])await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,{...p,...patch} as NativeRunAbortProof))})
test('background_or_child_outstanding_is_rejected',async()=>{const f=fixture(),p=await proof(f);f.children.push({reservation_id:'reserved',state:'reserved'});await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,p))})
test('association_change_invalidates_saved_proof',async()=>{const f=fixture(),p=await proof(f);await recordNativeRunAbortProof(f.db,'owner',run,p);f.links.push({kind:'browser',native_id:'b',session_id:'session',payload:{status:'closed'}});await assert.rejects(assertNativeRunAbortProof(f.db,'owner',run))})
test('browser_dirty_old_owner_blocks',async()=>{const f=fixture();f.links.push({kind:'browser',native_id:'b',session_id:'session',payload:{status:'dirty'}});await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,await proof(f)))})
test('old_runtime_missing_job_is_unknown',async()=>{const f=fixture();f.links.push({kind:'job',native_id:'owner:old',payload:{record:'owner',runtimeId:'old'}});await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,await proof(f)))})
test('team_pending_mailbox_or_task_blocks',async()=>{const f=fixture();f.links.push({kind:'team',native_id:'team',payload:{name:'member'}});await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,await proof(f)))})
test('current_runtime_precise_owner_facts_survive_proof_reinspection',async()=>{const f=fixture();f.links.push({kind:'job',native_id:'owner:current:session',session_id:'session',payload:{record:'owner',runtimeId:'current',requestId:'rpc'}});const before=await readNativeRunSettlement(f.db,'owner',run);const observations={source:'native-maintenance-jobs' as const,owners:[{nativeId:'owner:current:session',runtimeId:'current',observedRuntimeId:'current',sessionId:'session',requestId:'rpc',logCut:2,inbox:{nextTurn:[],nextStep:[]},jobs:[]}]};await recordNativeRunResourceSettlement(f.db,'owner',run,before,observations);await recordNativeRunAbortProof(f.db,'owner',run,await proof(f));await assertNativeRunAbortProof(f.db,'owner',run)})
test('old_runtime_or_inexact_live_jobs_cannot_create_resource_facts',async()=>{const f=fixture();f.links.push({kind:'job',native_id:'owner:old:session',session_id:'session',payload:{record:'owner',runtimeId:'old',requestId:'rpc'}});const before=await readNativeRunSettlement(f.db,'owner',run);await assert.rejects(recordNativeRunResourceSettlement(f.db,'owner',run,before,{source:'native-maintenance-jobs',owners:[{nativeId:'owner:old:session',runtimeId:'old',observedRuntimeId:'new',sessionId:'session',requestId:'rpc',logCut:2,inbox:{nextTurn:[],nextStep:[]},jobs:[]}]}))})
test('resource_and_native_proof_must_use_the_same_log_cut',async()=>{const f=fixture();f.links.push({kind:'job',native_id:'owner:current:session',session_id:'session',payload:{record:'owner',runtimeId:'current',requestId:'rpc'}});await recordNativeRunResourceSettlement(f.db,'owner',run,await readNativeRunSettlement(f.db,'owner',run),{source:'native-maintenance-jobs',owners:[{nativeId:'owner:current:session',runtimeId:'current',observedRuntimeId:'current',sessionId:'session',requestId:'rpc',logCut:4,inbox:{nextTurn:[],nextStep:[]},jobs:[]}]});await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,await proof(f)))})
for(const verifiedOwner of [false,true])test('orphan_terminal_job_requires_exact_owner_facts_'+verifiedOwner,async()=>{
 const f=fixture()
 f.links.push({kind:'job',native_id:'old:job',session_id:'session',payload:{record:'job',runtimeId:'old',requestId:'rpc',jobId:'job',status:'killed'}})
 if(verifiedOwner){
  f.links.push({kind:'job',native_id:'owner:current:session',session_id:'session',payload:{record:'owner',runtimeId:'current',requestId:'rpc'}})
  // 模拟升级前保存的可信 current-owner facts，旧 terminal job 仍无相应 owner。
  const before=await readNativeRunSettlement(f.db,'owner',run)
  await f.db.query('insert into teloa_task_run_native_settlements(owner_id,run_id,observations,association_hash) values($1,$2,$3,$4)',['owner',run.id,JSON.stringify({source:'native-maintenance-jobs',owners:[{nativeId:'owner:current:session',runtimeId:'current',observedRuntimeId:'current',sessionId:'session',requestId:'rpc',logCut:2,inbox:{nextTurn:[],nextStep:[]},jobs:[]}]}),digest(before)])
 }
 const fixed=await proof(f),settlement=await readNativeRunSettlement(f.db,'owner',run)
 await assert.rejects(recordNativeRunAbortProof(f.db,'owner',run,fixed),{code:'teloa/conflict'})
 // 有完整匹配hash的旧proof也不能在冷读取时绕过孤立job。
 await f.db.query('insert into teloa_task_run_abort_proofs(owner_id,run_id,proof,settlement) values($1,$2,$3,$4)',['owner',run.id,JSON.stringify(fixed),settlement])
 await assert.rejects(assertNativeRunAbortProof(f.db,'owner',run),{code:'teloa/conflict'})
})
