import type {LocalizedMetadata} from '@teloa/contract'
import type {AtomicSkillContent} from './atomic-skill.ts'
import type {MarketItem,MarketItemLocalized} from './market-preview.ts'

// 单个技能条目的说明文字（白话，十语）。原先写「Skill 内容」「待 DSH 核验」这类工程说法。
type Ten=readonly [string,string,string,string,string,string,string,string,string,string]
const ten=(values:Ten):LocalizedMetadata=>({original:values[0],defaultLocale:'en',locales:{'zh-CN':values[0],'zh-Hant':values[1],en:values[2],ja:values[3],ko:values[4],vi:values[5],es:values[6],fr:values[7],de:values[8],pt:values[9]}})
const copy={
 importedSummary:['单独导入的技能，还没检查能不能运行。','單獨匯入的技能，還沒檢查能不能執行。','A skill imported on its own; not yet checked whether it can run.','単独で取り込んだスキルです。動くかどうかはまだ確認していません。','단독으로 가져온 스킬입니다. 실행할 수 있는지 아직 확인하지 않았습니다.','Kỹ năng được nhập riêng; chưa kiểm tra xem có chạy được không.','Habilidad importada por separado; aún no se ha comprobado si funciona.','Compétence importée seule ; son fonctionnement n’a pas encore été vérifié.','Einzeln importierte Fähigkeit; noch nicht geprüft, ob sie läuft.','Competência importada à parte; ainda não se verificou se funciona.'],
 storedSummary:['已保存的单个技能，打开详情可核对原文。','已儲存的單個技能，開啟詳情可核對原文。','A saved skill; open the details to check the original text.','保存済みのスキルです。詳細を開くと原文を確認できます。','저장된 스킬입니다. 세부 정보를 열어 원문을 확인할 수 있습니다.','Kỹ năng đã lưu; mở chi tiết để đối chiếu bản gốc.','Habilidad guardada; abre los detalles para revisar el texto original.','Compétence enregistrée ; ouvrez les détails pour vérifier le texte d’origine.','Gespeicherte Fähigkeit; öffnen Sie die Details, um den Originaltext zu prüfen.','Competência guardada; abra os detalhes para verificar o texto original.'],
 requirement:['核对技能内容、依赖和会用到的工具','核對技能內容、依賴和會用到的工具','Check the skill content, dependencies, and tools it uses','スキルの内容、依存関係、使うツールを確認する','스킬 내용, 의존성, 사용할 도구를 확인하기','Kiểm tra nội dung kỹ năng, phụ thuộc và công cụ sẽ dùng','Revisar el contenido, las dependencias y las herramientas que usa','Vérifier le contenu, les dépendances et les outils utilisés','Inhalt, Abhängigkeiten und verwendete Werkzeuge prüfen','Verificar o conteúdo, as dependências e as ferramentas usadas'],
 output:['按技能的方法做出可审阅的成果','按技能的方法做出可審閱的成果','A reviewable result made with the skill’s method','スキルの手順に沿った、確認できる成果物','스킬의 방법대로 만든 검토 가능한 결과물','Kết quả có thể xem lại, làm theo cách của kỹ năng','Un resultado revisable hecho con el método de la habilidad','Un résultat vérifiable produit selon la méthode de la compétence','Ein prüfbares Ergebnis nach der Methode der Fähigkeit','Um resultado revisável feito com o método da competência'],
 importedCompatibility:['文件已读取；格式和运行条件还没检查，尚未安装。','檔案已讀取；格式和執行條件還沒檢查，尚未安裝。','Files have been read; format and run requirements are not checked yet, and it is not installed.','ファイルは読み込み済みです。形式と動作条件は未確認で、まだインストールしていません。','파일을 읽었습니다. 형식과 실행 조건은 아직 확인하지 않았고 설치되지 않았습니다.','Đã đọc tệp; chưa kiểm tra định dạng và điều kiện chạy, chưa cài đặt.','Archivos leídos; el formato y los requisitos para funcionar aún no se han comprobado y no está instalada.','Fichiers lus ; le format et les conditions de fonctionnement ne sont pas encore vérifiés, et elle n’est pas installée.','Dateien gelesen; Format und Laufvoraussetzungen noch nicht geprüft, nicht installiert.','Ficheiros lidos; o formato e os requisitos para funcionar ainda não foram verificados e não está instalada.'],
 storedCompatibility:['内容已保存；还没打开详情，也还没安装。','內容已儲存；還沒開啟詳情，也還沒安裝。','Content is saved; details have not been opened and it is not installed.','内容は保存済みです。詳細はまだ開いておらず、インストールもしていません。','내용이 저장되었습니다. 세부 정보를 아직 열지 않았고 설치하지도 않았습니다.','Đã lưu nội dung; chưa mở chi tiết và chưa cài đặt.','Contenido guardado; aún no se han abierto los detalles ni está instalada.','Contenu enregistré ; les détails n’ont pas été ouverts et elle n’est pas installée.','Inhalt gespeichert; Details noch nicht geöffnet und nicht installiert.','Conteúdo guardado; os detalhes ainda não foram abertos e não está instalada.'],
 importedStatus:['原文和附带文件已读取；运行条件待检查','原文和附帶檔案已讀取；執行條件待檢查','Original text and attached files read; run requirements to be checked','原文と添付ファイルは読み込み済み。動作条件は確認待ち','원문과 첨부 파일을 읽었습니다. 실행 조건 확인 대기','Đã đọc bản gốc và tệp kèm; chờ kiểm tra điều kiện chạy','Texto original y archivos adjuntos leídos; requisitos para funcionar pendientes de revisar','Texte d’origine et fichiers joints lus ; conditions de fonctionnement à vérifier','Originaltext und Begleitdateien gelesen; Laufvoraussetzungen noch zu prüfen','Texto original e ficheiros anexos lidos; requisitos para funcionar por verificar'],
 storedStatus:['内容已保存；运行条件待检查','內容已儲存；執行條件待檢查','Content saved; run requirements to be checked','内容は保存済み。動作条件は確認待ち','내용 저장됨. 실행 조건 확인 대기','Đã lưu nội dung; chờ kiểm tra điều kiện chạy','Contenido guardado; requisitos para funcionar pendientes de revisar','Contenu enregistré ; conditions de fonctionnement à vérifier','Inhalt gespeichert; Laufvoraussetzungen noch zu prüfen','Conteúdo guardado; requisitos para funcionar por verificar'],
} satisfies Record<string,Ten>

/** 单个技能条目的说明字段与本地化：`imported` 是刚导入（文件已读取），`stored` 是已保存在本机、详情还没读取。 */
export function atomicSkillCopy(kind:'imported'|'stored',name:{title:string;localizedTitle?:LocalizedMetadata|undefined}):Pick<MarketItem,'summary'|'requirements'|'output'|'compatibility'>&{status:string;localized:MarketItemLocalized}{
 const summary=kind==='imported'?copy.importedSummary:copy.storedSummary,compatibility=kind==='imported'?copy.importedCompatibility:copy.storedCompatibility,status=kind==='imported'?copy.importedStatus:copy.storedStatus
 return {summary:summary[0],requirements:[copy.requirement[0]],output:copy.output[0],compatibility:compatibility[0],status:status[0],localized:{
  ...(name.localizedTitle?{title:name.localizedTitle}:{}),summary:ten(summary),requirements:[ten(copy.requirement)],output:ten(copy.output),compatibility:ten(compatibility),
  components:[{name:name.localizedTitle??{original:name.title,defaultLocale:'und',locales:{}},status:ten(status)}],
 }}
}

export function atomicSkillItem(content:AtomicSkillContent):MarketItem{
 const {status,...text}=atomicSkillCopy('imported',{title:content.title,localizedTitle:content.localized?.title})
 return {id:'atomic-'+content.hash,kind:'skill',resourceKind:'skill',title:content.title,version:content.version,scope:'general',visibility:'personal',...text,author:'本人导入',license:'来源许可待核对',source:{kind:'upload',name:content.entryPath,size:content.files.reduce((sum,file)=>sum+file.bytes.length,0)},owner:'DSH',components:[{name:content.title,required:true,status}],hash:content.hash,capabilityCategories:[...content.categories],atomicSkill:structuredClone(content)}
}
