import {useRef,useState} from 'react'
import type {BusinessDashboardResourceApi} from './business-dashboard-resource-api.js'
import {packageBusinessDashboardResource} from './business-dashboard-resource-api.js'
import type {BusinessShareApi} from './business-share-flow.js'
import type {MarketItem} from './market-preview.js'
import {useI18n} from './i18n/provider.js'
import css from './BusinessShareForm.module.css'
/** 导出以宿主当前权威配置为准；组件只编辑资源身份和门面信息。 */
export function BusinessDashboardShareForm({scope,api,share,openMarket}:{scope:string;api:BusinessDashboardResourceApi;share:BusinessShareApi;openMarket:(id?:string)=>void}){
 const {t}=useI18n(),running=useRef(false)
 const [id,setId]=useState(scope.toLowerCase()+'-dashboard'),[version,setVersion]=useState('1.0.0'),[title,setTitle]=useState(t('business.share.defaultName',{scope})),[description,setDescription]=useState(t('business.share.defaultSummary')),[englishTitle,setEnglishTitle]=useState(''),[englishDescription,setEnglishDescription]=useState('')
 const [item,setItem]=useState<MarketItem>(),[excluded,setExcluded]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(false),[fixed,setFixed]=useState<string>()
 const act=async(run:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(true);setError(false);try{await run()}catch{setError(true)}finally{running.current=false;setBusy(false)}}
 const generate=()=>act(async()=>{const exported=await api.export({scope,id,version});const value=await packageBusinessDashboardResource(exported.resource,{title,description,...(englishTitle.trim()&&englishDescription.trim()?{english:{title:englishTitle,description:englishDescription}}:{})});setItem(value);setExcluded(exported.excluded)})
 const download=()=>act(async()=>{if(!item)return;const archive=await share.download(item),url=URL.createObjectURL(new Blob([Uint8Array.from(archive.bytes)],{type:'application/zip'})),anchor=document.createElement('a');anchor.href=url;anchor.download=archive.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),10000)})
 return <section className={css.panel} aria-label={t('business.share.title')}><header><div><h2>{t('business.share.title')}</h2><p>{t('market.dashboard.shareBoundary')}</p></div></header>{error&&<p role="alert">{t('business.share.failed')}</p>}
  {!item?<><div className={css.form}><label>{t('business.share.packageId')}<input value={id} disabled={busy} onChange={event=>setId(event.target.value)}/></label><label>{t('business.share.version')}<input value={version} disabled={busy} onChange={event=>setVersion(event.target.value)}/></label><label>{t('business.share.name')}<input value={title} disabled={busy} onChange={event=>setTitle(event.target.value)}/></label><label>{t('business.share.summary')}<textarea value={description} disabled={busy} onChange={event=>setDescription(event.target.value)}/></label></div><details><summary>{t('business.share.english')}</summary><div className={css.form}><label>{t('business.share.englishName')}<input value={englishTitle} onChange={event=>setEnglishTitle(event.target.value)}/></label><label>{t('business.share.englishSummary')}<textarea value={englishDescription} onChange={event=>setEnglishDescription(event.target.value)}/></label></div></details><footer><button type="button" disabled={busy||!id.trim()||!version.trim()||!title.trim()||!description.trim()} onClick={()=>void generate()}>{t('business.share.generate')}</button></footer></>:<><p>{item.title} · v{item.version}</p><p>{t('market.dashboard.shareBoundary')}</p>{!englishTitle.trim()&&<p>{t('business.share.localOnly')}</p>}<ul>{excluded.map((value,index)=><li key={index}>{value}</li>)}</ul><footer><button type="button" disabled={busy} onClick={()=>void download()}>{t('business.share.download')}</button><button type="button" disabled={busy||!!fixed} onClick={()=>void act(async()=>{setFixed((await share.fix(item)).id)})}>{t('business.share.fix')}</button><button type="button" disabled={busy} onClick={()=>{setItem(undefined);setFixed(undefined)}}>{t('business.share.back')}</button>{fixed&&<button type="button" onClick={()=>openMarket(fixed)}>{t('business.share.openMarket')}</button>}</footer></>}
 </section>
}
