import {useEffect,useId,useRef,useState,useSyncExternalStore,type ReactNode} from 'react'
import {readBusinessImportMapping,readBusinessRichFieldValue,type BusinessImportMapping,type BusinessImportMappingV2,type BusinessImportIssue,type BusinessImportSourceColumn,type BusinessImportCellV2} from '@teloa/contract'
import {BusinessImportFlow,type BusinessImportDefinition,type BusinessImportState} from './business-import-flow.js'
import {useI18n} from './i18n/provider.js'
import css from './BusinessImportPanel.module.css'
type ColumnChoice={column:string;trim:boolean}
type Choices={primaryKey:ColumnChoice[];title:ColumnChoice;summary:ColumnChoice;fields:Record<string,ColumnChoice&{currency:string;currencyColumn:ColumnChoice}>}
const blank=():ColumnChoice=>({column:'',trim:false})
function choices(mapping?:BusinessImportMapping|BusinessImportMappingV2):Choices{
 const column=(value?:BusinessImportSourceColumn)=>value?{column:String(value.column),trim:value.trim}:blank()
 return {primaryKey:mapping?mapping.primaryKey.map(column):[blank()],title:column(mapping?.title),summary:column(mapping?.summary),fields:Object.fromEntries((mapping?.fields??[]).map(field=>[field.field,{...column(field.value),currency:field.currency?'fixed'in field.currency?field.currency.fixed:'column':'',currencyColumn:field.currency&&'column'in field.currency?column(field.currency):blank()}]))}
}
function toMapping(value:Choices,delimiter:BusinessImportMapping['delimiter'],definition:BusinessImportDefinition,columns:number):BusinessImportMapping|undefined{
 const source=(input:ColumnChoice)=>({column:input.column===''?-1:Number(input.column),trim:input.trim})
 try{return readBusinessImportMapping({delimiter,headerRow:1,primaryKey:value.primaryKey.map(source),title:source(value.title),...(value.summary.column===''?{}:{summary:source(value.summary)}),fields:definition.fields.flatMap(field=>{
  const input=value.fields[field.name];if(!input||input.column==='')return []
  return [{field:field.name,value:source(input),...(field.type==='money'?{currency:input.currency==='column'?source(input.currencyColumn):{fixed:input.currency}}:{})}]
 })},columns)}catch{return undefined}
}
const busy=(state:BusinessImportState)=>state.phase.endsWith('ing')||state.phase==='checking-workbook'
const rawCell=(value:string|BusinessImportCellV2)=>typeof value==='string'?value:value.text
function normalized(field:BusinessImportDefinition['fields'][number],raw:string,state:BusinessImportState,pendingLabel:string,archivedLabel:string):string{
 const relation=(id:string)=>{const value=state.relations[JSON.stringify([field.type==='reference'||field.type==='multi-reference'?field.referenceType:'',id])];return value?value.title+(value.archived?archivedLabel:''):pendingLabel}
 if(!raw)return '—'
 if(field.type==='reference')return relation(raw)
 if('format'in field){
  try{const value=readBusinessRichFieldValue(field,raw)
   if(value?.type==='money')return value.currency+' '+value.decimal
   if(value?.type==='multi-enum')return value.values.join('、')
   if(value?.type==='multi-reference'&&field.type==='multi-reference')return value.ids.map(relation).join('、')
  }catch{return pendingLabel}
 }
 return raw
}
export function BusinessImportPanel({flow,scope,type,definition}:{flow:BusinessImportFlow;scope:string;type:string;definition:BusinessImportDefinition}){
 const {locale}=useI18n(),en=locale==='en',say=(zh:string,english:string)=>en?english:zh
 const state=useSyncExternalStore(flow.subscribe,flow.getSnapshot,flow.getSnapshot),id=useId(),panel=useRef<HTMLElement>(null),fileGeneration=useRef(0)
 const [delimiter,setDelimiter]=useState<''|BusinessImportMapping['delimiter']>(state.mapping&&'delimiter'in state.mapping?state.mapping.delimiter:''),[form,setForm]=useState<Choices>(()=>choices(state.mapping)),[confirmed,setConfirmed]=useState(false),[file,setFile]=useState<File>(),[localError,setLocalError]=useState<string>()
 const target=scope===flow.scope&&type===flow.type&&definition.domain===scope&&definition.id===type&&flow.isCurrent(),inFlight=busy(state),unknown=state.phase==='unknown',blocked=!target||inFlight||unknown||state.phase==='recovery-error'||state.phase==='cancelled'||state.phase==='applied'
 const inspection=state.inspection,preview=state.preview,xlsx=state.draft?.format==='teloa.business-record-import/v2'||state.phase==='selecting-sheet',effectiveDelimiter=xlsx?',':delimiter
 const confirmDelimiterMismatch=preview&&!('format'in preview)&&delimiter!==preview.mapping.delimiter
 const mapped=inspection?.canMap&&effectiveDelimiter?toMapping(form,effectiveDelimiter,definition,inspection.columns.length):undefined
 const mapping=mapped&&xlsx?(({delimiter:_,...value})=>value)(mapped):mapped
 useEffect(()=>{if(target)flow.configure(definition)},[flow,definition,target])
 useEffect(()=>{setForm(choices(state.mapping));if(state.mapping&&'delimiter'in state.mapping)setDelimiter(state.mapping.delimiter)},[flow,state.draft?.id,state.draft?.mapping])
 useEffect(()=>{setConfirmed(false)},[flow,preview?.digest,state.phase])
 const act=async(run:()=>Promise<unknown>|void)=>{setLocalError(undefined);try{await run()}catch{if(flow.isCurrent())setLocalError(say('操作未完成，请先核对原请求。','The operation is incomplete. Check the original request.'))}}
 const change=(next:Choices)=>{setForm(next);setConfirmed(false);if(inspection?.canMap&&effectiveDelimiter){const value=toMapping(next,effectiveDelimiter,definition,inspection.columns.length);void act(()=>flow.changeMapping(value&&xlsx?(({delimiter:_,...rest})=>rest)(value):value))}}
 const readFile=async(selected:File,generation:number)=>{
  if(!/\.(csv|xlsx)$/i.test(selected.name)||selected.size>2_097_152)throw Error()
  const bytes=new Uint8Array(await selected.arrayBuffer());if(!flow.isCurrent()||fileGeneration.current!==generation)return
  let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte)
  const input={name:selected.name,bytes:bytes.length,dataBase64:btoa(binary)}
  if(unknown)await flow.retryStage(input);else if(selected.name.toLowerCase().endsWith('.xlsx'))await flow.inspectWorkbook(input);else await flow.stage(input)
 }
 const selectSheet=async(sheet:NonNullable<BusinessImportState['workbook']>['sheets'][number])=>{
  if(!file)throw Error('original file missing')
  const selected=file,generation=fileGeneration.current,bytes=new Uint8Array(await selected.arrayBuffer());if(!flow.isCurrent()||fileGeneration.current!==generation)return
  let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte)
  if(fileGeneration.current!==generation)return
  await flow.stage({name:selected.name,bytes:bytes.length,dataBase64:btoa(binary)},{kind:'xlsx',sheet})
 }
 const cell=(value:string):ReactNode=>value.length>100?<details><summary>{say('查看完整内容','View full text')}</summary><span className={css.raw}>{value}</span></details>:<span className={css.raw}>{value||'—'}</span>
 const columnInput=(label:string,value:ColumnChoice,onChange:(value:ColumnChoice)=>void)=><div className={css.column}><label><span>{label}</span><select aria-label={label} value={value.column} disabled={blocked||!inspection?.canMap} onChange={event=>onChange({...value,column:event.target.value})}><option value="">{say('请选择列','Choose a column')}</option>{inspection?.columns.map(source=><option key={source.column} value={source.column}>{say(`第${source.column+1}列 · ${source.header||'空表头'}`,`Column ${source.column+1} · ${source.header||'Empty header'}`)}</option>)}</select></label><label className={css.check}><input type="checkbox" aria-label={label+say('去除首尾空白',' trim surrounding whitespace')} checked={value.trim} disabled={blocked||!inspection?.canMap} onChange={event=>onChange({...value,trim:event.target.checked})}/>{say('去除首尾空白','Trim surrounding whitespace')}</label></div>
 const issues=[...(inspection?.issues??[]),...(preview?.issues??[])]
 const focusIssue=(issue:BusinessImportIssue,index:number)=>{
  const row=panel.current?.querySelector<HTMLElement>(`[data-preview-row="${issue.rowNumber}"]`)??panel.current?.querySelector<HTMLElement>(`[data-source-row="${issue.rowNumber}"]`)??panel.current?.querySelector<HTMLElement>(`[data-issue="${index}"]`)
  row?.focus();row?.scrollIntoView({block:'nearest'})
 }
 return <section ref={panel} className={css.panel} aria-labelledby={id} aria-busy={inFlight}>
  <header className={css.header}><h2 id={id}>{say('导入表格','Import a table')}</h2><p>{definition.title} · {say('CSV 或 XLSX，每批1–50行，最大2 MiB。','CSV or XLSX, 1–50 rows per batch, up to 2 MiB.')}</p></header>
  <ol className={css.steps} aria-label={say('导入步骤','Import steps')}><li>{say('1 上传','1 Upload')}</li><li>{say('2 映射','2 Map')}</li><li>{say('3 确认','3 Confirm')}</li></ol>
  {!target&&<p role="alert" className={css.error}>{say('本人或业务连接已变化，请返回原业务核对。','Your identity or business connection changed. Check the original business.')}</p>}
  {unknown&&<div role="status" className={css.notice}><p>{say('原请求结果未知，文件和映射已冻结。空回执不代表未受理。','The original request outcome is unknown. The file and mapping are frozen. An empty receipt does not mean it was rejected.')}</p><div className={css.actions}><button type="button" disabled={!target||inFlight} onClick={()=>void act(()=>flow.reconcile())}>{say('核对原请求','Check original request')}</button>{state.pending?.phase==='apply'&&<button type="button" disabled={!target||inFlight} onClick={()=>void act(()=>flow.retryApply())}>{say('按原请求重递送','Resend original request')}</button>}{state.pending?.phase==='stage'&&<button type="button" disabled={!target||inFlight||!file} onClick={()=>void act(()=>readFile(file!,fileGeneration.current))}>{say('用原文件重递送','Resend with original file')}</button>}</div></div>}
  {state.phase==='recovery-error'&&<p role="alert" className={css.error}>{say('原请求恢复记录无法核对，请保留此页并返回原本人业务。','The recovery record cannot be verified. Keep this page and return to the original identity and business.')}</p>}
  {(localError||state.errorCode)&&<p role="alert" className={css.error}>{localError??(state.errorCode==='teloa/too-late'?say('此批次已导入，取消不能撤销记录。','This batch is already imported. Cancelling cannot undo the records.'):preview&&!state.relationsReady?say('关联记录尚未核对，请重新生成预览后确认。','Related records are unverified. Generate a fresh preview before confirming.'):say('操作未完成，请核对原请求或重新生成预览。','The operation is incomplete. Check the original request or generate a fresh preview.'))}</p>}
  {preview&&!state.relationsReady&&!state.errorCode&&!inFlight&&<p role="alert" className={css.error}>{say('关联记录尚未核对或已归档，不能确认导入。','Related records are unverified or archived. Import is blocked.')}</p>}
  {issues.length>0&&<div className={css.error} role="alert"><p>{say('请修正全部问题后重新预览。','Resolve all issues and preview again.')}</p><ul>{issues.map((issue,index)=><li key={index}><button type="button" data-issue={index} onClick={()=>focusIssue(issue,index)}>{[issue.rowNumber?say(`第${issue.rowNumber}行`,`Row ${issue.rowNumber}`):'',issue.column!==undefined?say(`第${issue.column+1}列`,`Column ${issue.column+1}`):''].filter(Boolean).join(' · ')}{issue.rowNumber||issue.column!==undefined?'：':''}{issue.message}</button></li>)}</ul></div>}
  <section className={css.step} aria-labelledby={id+'-upload'}><h3 id={id+'-upload'}>{say('1 上传表格','1 Upload a table')}</h3><label className={css.upload}>{say('CSV 或 XLSX 文件','CSV or XLSX file')}<input aria-label={say('CSV 或 XLSX 文件','CSV or XLSX file')} type="file" accept=".csv,text/csv,.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={!target||inFlight||state.phase==='recovery-error'||unknown&&state.pending?.phase!=='stage'} onChange={event=>{const selected=event.target.files?.[0],generation=++fileGeneration.current;setFile(selected);if(selected&&!unknown)void act(()=>readFile(selected,generation))}}/></label>
   {state.draft&&<p className={css.note}>{say('文件已保存','File saved')}：{state.draft.file.name}</p>}
   {state.phase==='selecting-sheet'&&state.workbook&&<div className={css.sheetPicker} role="group" aria-label={say('选择工作表','Choose a worksheet')}><p className={css.note}>{say('请选择要导入的工作表。','Choose the worksheet to import.')}</p><div className={css.sheetChoices}>{state.workbook.sheets.map(sheet=><button type="button" key={sheet.sheetId} disabled={!file||!target||inFlight} onClick={()=>void act(()=>selectSheet(sheet))}>{sheet.name}</button>)}</div></div>}
   <div className={css.actions}>{!xlsx&&<label>{say('分隔符','Delimiter')}<select aria-label={say('分隔符','Delimiter')} value={delimiter} disabled={blocked} onChange={event=>{setDelimiter(event.target.value as typeof delimiter);setConfirmed(false)}}><option value="">{say('请选择','Choose')}</option><option value=",">{say('逗号','Comma')}</option><option value=";">{say('分号','Semicolon')}</option><option value={'\t'}>{say('制表符','Tab')}</option></select></label>}<button type="button" disabled={blocked||!state.draft||!effectiveDelimiter} onClick={()=>void act(()=>flow.inspect(xlsx?undefined:delimiter as BusinessImportMapping['delimiter']))}>{say('读取表头与样例','Read headers and sample')}</button></div>
   {inspection?.complete&&<><p className={css.note}>{say(`已完整读取${inspection.dataRows}行数据；以下仅为前${inspection.sampleRows.length}行样例，另${inspection.sampleRowsOmitted}行未展示。`,`Read all ${inspection.dataRows} data rows. Only the first ${inspection.sampleRows.length} complete sample rows are shown; ${inspection.sampleRowsOmitted} rows are omitted.`)}</p><div className={css.tableWrap} tabIndex={0} aria-label={say('原始样例表格','Original sample table')}><table><thead><tr><th>{say('行号','Row')}</th>{inspection.columns.map(column=><th key={column.column}>{say(`第${column.column+1}列`,`Column ${column.column+1}`)}<span>{column.header||say('空表头','Empty header')}</span></th>)}</tr></thead><tbody>{inspection.sampleRows.map(row=><tr key={row.rowNumber} data-source-row={row.rowNumber} tabIndex={-1}><th>{row.rowNumber}</th>{row.cells.map((value,index)=><td key={index}>{cell(rawCell(value))}{typeof value!=='string'&&<small>{({blank:say('空白','Blank'),string:say('文本','Text'),number:say('数字','Number'),boolean:say('布尔值','Boolean')})[value.kind]}</small>}</td>)}</tr>)}</tbody></table></div></>}
  </section>
  <section className={css.step} aria-labelledby={id+'-map'}><h3 id={id+'-map'}>{say('2 选择主键与字段映射','2 Choose primary key and field mapping')}</h3><p className={css.note}>{say('按列序号区分重名或空表头。主键顺序和每列空白处理分别固定；多选字段只接受JSON数组，关联须为已有记录。','Column numbers distinguish duplicate or empty headers. Key order and whitespace handling are explicit. Multiple values require JSON arrays; relations must target existing records.')}</p>
   <div className={css.mapping}>{form.primaryKey.map((value,index)=><div key={index}>{columnInput(say(`主键第${index+1}列`,`Primary key column ${index+1}`),value,next=>change({...form,primaryKey:form.primaryKey.map((item,i)=>i===index?next:item)}))}{index>0&&<button type="button" disabled={blocked} onClick={()=>change({...form,primaryKey:form.primaryKey.filter((_,i)=>i!==index)})}>{say('移除此主键列','Remove key column')}</button>}</div>)}{form.primaryKey.length<3&&<button type="button" disabled={blocked||!inspection?.canMap} onClick={()=>change({...form,primaryKey:[...form.primaryKey,blank()]})}>{say('增加组合主键列','Add key column')}</button>}{columnInput(say('标题列','Title column'),form.title,next=>change({...form,title:next}))}{columnInput(say('说明列（可选）','Summary column (optional)'),form.summary,next=>change({...form,summary:next}))}
   {definition.fields.map(field=>{const value=form.fields[field.name]??{...blank(),currency:'',currencyColumn:blank()},set=(next:typeof value)=>change({...form,fields:{...form.fields,[field.name]:next}});return <div key={field.name}>{columnInput(field.label+say('来源列',' source column'),value,next=>set({...value,...next}))}{field.type==='money'&&<><label>{field.label+say('币种',' currency')}<select aria-label={field.label+say('币种',' currency')} disabled={blocked||value.column===''} value={value.currency} onChange={event=>set({...value,currency:event.target.value})}><option value="">{say('明确选择币种','Choose currency explicitly')}</option>{field.currencies.map(currency=><option key={currency} value={currency}>{currency}</option>)}<option value="column">{say('使用独立币种列','Separate currency column')}</option></select></label>{value.currency==='column'&&columnInput(field.label+say('币种来源列',' currency source column'),value.currencyColumn,next=>set({...value,currencyColumn:next}))}</>}</div>})}</div>
   <button type="button" disabled={blocked||!inspection?.canMap||!mapping||inspection.format==='teloa.business-import-inspection/v1'&&delimiter!==inspection.delimiter} onClick={()=>void act(()=>flow.preview(mapping!))}>{say('生成全部行预览','Preview all rows')}</button>
  </section>
  <section className={css.step} aria-labelledby={id+'-confirm'}><h3 id={id+'-confirm'}>{say('3 核对全部行并确认','3 Review all rows and confirm')}</h3>
   {preview&&<><p className={css.note}>{say(`全部${preview.rows.length}行规范结果`,`All ${preview.rows.length} normalized rows`)}</p><p className={css.note}>{say('原值比较仅使用上方完整样例；以下结果包含全部行。','Original-value comparisons use the complete samples above. Results below include every row.')}</p><div className={css.tableWrap} tabIndex={0} aria-label={say('全部规范结果','All normalized results')}><table><thead><tr><th>{say('行号','Row')}</th><th>{say('主键','Primary key')}</th><th>{say('标题','Title')}</th><th>{say('说明','Summary')}</th>{definition.fields.map(field=><th key={field.name}>{field.label}</th>)}</tr></thead><tbody>{preview.rows.map(row=>{const sample=inspection?.sampleRows.find(sample=>sample.rowNumber===row.rowNumber);return <tr key={row.rowNumber} data-preview-row={row.rowNumber} tabIndex={-1}><th>{row.rowNumber}</th><td>{sample&&<small>{cell(JSON.stringify(preview.mapping.primaryKey.map(key=>rawCell(sample.cells[key.column]!))))} {say('规范值：','Normalized: ')}</small>}{cell(JSON.stringify(row.primaryKey))}</td><td>{cell(row.operation.title)}</td><td>{cell(row.operation.summary)}</td>{definition.fields.map(field=>{const raw=row.operation.fields.find(value=>value.name===field.name)?.value??'',mapped=preview.mapping.fields.find(value=>value.field===field.name);return <td key={field.name}>{sample&&mapped&&field.type!=='reference'&&field.type!=='multi-reference'&&<small>{cell(sample.cells[mapped.value.column]===undefined?'':rawCell(sample.cells[mapped.value.column]!))} {say('规范值：','Normalized: ')}</small>}{cell(normalized(field,raw,state,say('关联尚未核对','Relation unverified'),say('（已归档）',' (archived)')))}</td>})}</tr>})}</tbody></table></div></>}
   {state.receipt?<div className={css.notice} role="status"><p>{say(`已导入批次：${state.receipt.created}条记录`,`Imported batch: ${state.receipt.created} records`)}</p>{state.receipt.canonicalRequestId!==state.receipt.requestId&&<p>{say('此文件与已有固定批次一致，已返回原批次。','This file matches an existing fixed batch. The original batch was returned.')}</p>}</div>:<><label className={css.check}><input type="checkbox" checked={confirmed} disabled={blocked||!preview?.canApply||!state.relationsReady||!mapping} onChange={event=>setConfirmed(event.target.checked)}/>{say('我已核对全部行并确认导入','I reviewed every row and confirm the import')}</label><button type="button" className={css.primary} disabled={blocked||!confirmed||!preview?.canApply||!state.relationsReady||!mapping||confirmDelimiterMismatch} onClick={()=>void act(()=>flow.apply())}>{state.phase==='applying'?say('正在导入','Importing'):say('确认导入','Confirm import')}</button></>}
  </section>
  {state.phase==='cancelled'?<div className={css.notice}><p>{say('草案已取消，文件和映射仍保留。','Draft cancelled. Its file and mapping are preserved.')}</p><button type="button" disabled={!target||inFlight} onClick={()=>void act(()=>flow.resume())}>{say('恢复草案','Resume draft')}</button></div>:state.draft&&state.phase!=='applied'&&<button type="button" disabled={blocked} onClick={()=>void act(()=>flow.cancel())}>{say('取消此草案','Cancel this draft')}</button>}
 </section>
}
