import type {WorkResource} from '@teloa/contract'
import {recoveryStorageError} from './recovery-error.ts'

type Call=(method:string,payload:unknown)=>Promise<unknown>
export type IndustryKnowledgeRequest={requestId:string;loadId:string;itemInstanceId:string}
export type IndustryKnowledgeInstance={id:string;ownerId:string;loadId:string;itemInstanceId:string;itemLocalId:string;title:string;scope:string;sourceId:string;sourceVersion:string;revision:number;state:'pending'|'active'|'withdrawn'|'failed';resource:WorkResource|null;failure:{code:string;message:string}|null;createdAt:string;updatedAt:string}
export type IndustryKnowledgeJournal={read:()=>string|null;write:(value:string)=>void;clear:()=>void}

const uuid=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
const id=(value:unknown,max=128):value is string=>typeof value==='string'&&value.length<=max&&/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(value)
const errorCode=(value:unknown):value is string=>typeof value==='string'&&value.length<=160&&/^teloa\/[a-z0-9-]+$/.test(value)
const text=(value:unknown,max:number):value is string=>typeof value==='string'&&!!value.trim()&&value.length<=max
const positive=(value:unknown):value is number=>Number.isSafeInteger(value)&&Number(value)>0&&Number(value)<=2147483647
const hash=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value)
const stamp=(value:unknown):value is string=>typeof value==='string'&&new Date(value).toISOString()===value
/** 业务范围标签（模板 `domain`）取代了 `space-<id>`：只核对 1–80 的标签文本。 */
const scope=(value:unknown):value is string=>typeof value==='string'&&!!value.trim()&&value.length<=80
const exact=(value:unknown,keys:readonly string[])=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(key=>!keys.includes(key)))throw Error();return value as Record<string,unknown>}

function readRequest(value:unknown):IndustryKnowledgeRequest{try{const row=exact(value,['requestId','loadId','itemInstanceId']);if(!uuid(row.requestId)||!uuid(row.loadId)||!uuid(row.itemInstanceId))throw Error();return {requestId:row.requestId.toLowerCase(),loadId:row.loadId.toLowerCase(),itemInstanceId:row.itemInstanceId.toLowerCase()}}catch{throw Error('行业知识实例化请求格式不正确。')}}
function readResource(value:unknown):WorkResource{const row=exact(value,['id','ownerId','title','sourceId','sourceVersion','scopeIds','version','status','createdAt','updatedAt']);if(!uuid(row.id)||!text(row.ownerId,128)||!text(row.title,200)||!id(row.sourceId)||!hash(row.sourceVersion)||!Array.isArray(row.scopeIds)||row.scopeIds.length!==1||!scope(row.scopeIds[0])||!positive(row.version)||row.status!=='active'&&row.status!=='withdrawn'||!stamp(row.createdAt)||!stamp(row.updatedAt)||Date.parse(row.createdAt)>Date.parse(row.updatedAt))throw Error();return row as unknown as WorkResource}
function readInstance(value:unknown):IndustryKnowledgeInstance{try{const row=exact(value,['id','ownerId','loadId','itemInstanceId','itemLocalId','title','scope','sourceId','sourceVersion','revision','state','resource','failure','createdAt','updatedAt']);if(!uuid(row.id)||!text(row.ownerId,128)||!uuid(row.loadId)||!uuid(row.itemInstanceId)||typeof row.itemLocalId!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(row.itemLocalId)||!text(row.title,200)||!scope(row.scope)||row.sourceId!==`industry_${row.loadId.toLowerCase()}_${row.itemInstanceId.toLowerCase()}`||!hash(row.sourceVersion)||!positive(row.revision)||!['pending','active','withdrawn','failed'].includes(String(row.state))||!stamp(row.createdAt)||!stamp(row.updatedAt)||row.updatedAt<row.createdAt)throw Error();const resource=row.resource===null?null:readResource(row.resource);const failure=row.failure===null?null:exact(row.failure,['code','message']);if(failure&&(!errorCode(failure.code)||!text(failure.message,2000)))throw Error();if(row.state==='active'||row.state==='withdrawn'){if(!resource||resource.status!==row.state||resource.ownerId!==row.ownerId||resource.title!==row.title||resource.sourceId!==row.sourceId||resource.sourceVersion!==row.sourceVersion||resource.scopeIds[0]!==row.scope||failure!==null)throw Error()}else{if(resource!==null)throw Error();if(row.state==='failed'?!failure:failure!==null)throw Error()}return {...row,resource,failure} as unknown as IndustryKnowledgeInstance}catch{throw Error('行业知识实例化记录格式不正确。')}}

export type IndustryKnowledgeApi=ReturnType<typeof createIndustryKnowledgeApi>
export function createIndustryKnowledgeApi(call:Call,journal?:IndustryKnowledgeJournal){
 let pending:IndustryKnowledgeRequest|undefined,recoveryError:ReturnType<typeof recoveryStorageError>|undefined,busy=false
 try{const raw=journal?.read();if(raw){if(raw.length>1000)throw Error();const saved=exact(JSON.parse(raw),['schema','request']);if(saved.schema!=='teloa.industry-knowledge/v1')throw Error();pending=readRequest(saved.request)}}catch{recoveryError=recoveryStorageError()}
 const send=async()=>{if(recoveryError)throw recoveryError;if(!pending)throw Error('没有待核对的行业知识实例化请求。');if(busy)throw Error('行业知识实例化正在核对。');busy=true;try{journal?.write(JSON.stringify({schema:'teloa.industry-knowledge/v1',request:pending}));const result=readInstance(await call('industry-knowledge/instantiate',pending));if(result.loadId!==pending.loadId||result.itemInstanceId!==pending.itemInstanceId)throw Error('行业知识实例化响应与原请求不一致。');if(result.state==='active'||result.state==='withdrawn'){journal?.clear();pending=undefined}return result}finally{busy=false}}
 return {pending:()=>pending?structuredClone(pending):undefined,recoveryMessage:()=>recoveryError,
  /** 丢弃只清本地恢复记录，不通知服务端（规格 §二 D4）。 */
  discard(){const had=pending!==undefined||recoveryError!==undefined;try{journal?.clear()}catch{/* 清不掉不该变成第二道墙 */}pending=undefined;recoveryError=undefined;return had},
  recover:send,async instantiate(value:IndustryKnowledgeRequest){if(recoveryError)throw recoveryError;const normalized=readRequest(value);if(pending&&JSON.stringify(pending)!==JSON.stringify(normalized))throw Error('请先核对原行业知识实例化请求。');pending??=normalized;return send()},async get(instanceId:string){if(!uuid(instanceId))throw Error('行业知识实例身份不正确。');const normalized=instanceId.toLowerCase(),result=readInstance(await call('industry-knowledge/get',{instanceId:normalized}));if(result.id.toLowerCase()!==normalized)throw Error('行业知识实例响应与目标身份不一致。');return result},async list(){const response=await call('industry-knowledge/list',{});let row:Record<string,unknown>;try{row=exact(response,['items']);if(!Array.isArray(row.items))throw Error()}catch{throw Error('行业知识实例目录格式不正确。')}const items=row.items.map(readInstance),lower=(value:string)=>value.toLowerCase();if(new Set(items.map(item=>lower(item.id))).size!==items.length||new Set(items.map(item=>`${lower(item.loadId)}:${lower(item.itemInstanceId)}`)).size!==items.length||new Set(items.flatMap(item=>item.resource?[lower(item.resource.id)]:[])).size!==items.filter(item=>item.resource).length)throw Error('行业知识实例目录身份重复。');return items}}
}
