import {readScheduleTrigger,type ScheduleTrigger} from '@teloa/contract'
import type {PlanNotificationPolicy,SavedPlan} from './plan-api.js'
import type {IndustryWorkSnapshot} from './industry-task-api.js'
import {recoveryStorageError} from './recovery-error.ts'
type Call=(method:string,payload:unknown)=>Promise<unknown>
export type IndustryPlanRequest={requestId:string;loadId:string;itemInstanceId:string;goal:string;delivery:string;notificationPolicy:PlanNotificationPolicy;trigger:ScheduleTrigger;roleId:string;expectedRoleVersion:number}
export type IndustryPlanSnapshot={loadId:string;itemInstanceId:string;itemLocalId:string;contentId:string;contentHash:string;planVersion:string;planFileHash:string;title:string;work:IndustryWorkSnapshot;dataScope:string;trigger:ScheduleTrigger;scope:string}
export type IndustryPlanRecord=IndustryPlanSnapshot&{planId:string;ownerId:string;requestId:string;goal:string;delivery:string;notificationPolicy?:PlanNotificationPolicy;createdRole:{roleId:string;roleVersion:number};selectedTrigger:ScheduleTrigger;createdAt:string}
type Journal={read:()=>string|null;write:(s:string)=>void;clear:()=>void}
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v),text=(v:unknown,n:number):v is string=>typeof v==='string'&&!!v.trim()&&v.length<=n,hash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),pos=(v:unknown):v is number=>Number.isSafeInteger(v)&&(v as number)>0&&(v as number)<=2147483647,stable=(v:unknown):v is string=>typeof v==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(v),semver=(v:unknown):v is string=>typeof v==='string'&&v.length<=80&&/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(v),stamp=(v:unknown):v is string=>typeof v==='string'&&new Date(v).toISOString()===v
const exact=(v:unknown,keys:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))throw Error();return v as Record<string,unknown>}
const notificationPolicy=(v:unknown):v is PlanNotificationPolicy=>typeof v==='string'&&['always','attention','failure','silent'].includes(v)
const trigger=(v:unknown)=>readScheduleTrigger(v)
function request(v:unknown):IndustryPlanRequest{try{const r=exact(v,['requestId','loadId','itemInstanceId','goal','delivery','notificationPolicy','trigger','roleId','expectedRoleVersion']);if(!uuid(r.requestId)||!uuid(r.loadId)||!uuid(r.itemInstanceId)||!text(r.goal,8000)||!text(r.delivery,8000)||!notificationPolicy(r.notificationPolicy)||!uuid(r.roleId)||!pos(r.expectedRoleVersion))throw Error();return {requestId:r.requestId,loadId:r.loadId,itemInstanceId:r.itemInstanceId,goal:r.goal.trim(),delivery:r.delivery.trim(),notificationPolicy:r.notificationPolicy,trigger:trigger(r.trigger),roleId:r.roleId,expectedRoleVersion:r.expectedRoleVersion}}catch{throw Error('行业持续计划创建请求格式不正确。')}}
function work(v:unknown):IndustryWorkSnapshot{const r=exact(v,['loadId','itemInstanceId','itemLocalId','contentId','contentHash','templateId','templateVersion','fileHash','title','method','requirements','output','skills','scope']);if(!uuid(r.loadId)||!uuid(r.itemInstanceId)||!stable(r.itemLocalId)||!uuid(r.contentId)||!hash(r.contentHash)||!stable(r.templateId)||!semver(r.templateVersion)||!hash(r.fileHash)||!text(r.title,120)||!text(r.method,2000)||!text(r.output,2000)||!text(r.scope,80)||!Array.isArray(r.requirements)||r.requirements.length<1||r.requirements.length>100||r.requirements.some(x=>!text(x,500))||!Array.isArray(r.skills)||r.skills.length>100)throw Error();const skills=r.skills.map(value=>{const x=exact(value,['id','title','version']);if(!stable(x.id)||!text(x.title,120)||!semver(x.version))throw Error();return {id:x.id,title:x.title,version:x.version}});return {...r,requirements:r.requirements as string[],skills} as unknown as IndustryWorkSnapshot}
function snapshot(v:unknown):IndustryPlanSnapshot{try{const r=exact(v,['loadId','itemInstanceId','itemLocalId','contentId','contentHash','planVersion','planFileHash','title','work','dataScope','trigger','scope']);if(!uuid(r.loadId)||!uuid(r.itemInstanceId)||!uuid(r.contentId)||!hash(r.contentHash)||!stable(r.itemLocalId)||!semver(r.planVersion)||!hash(r.planFileHash)||!text(r.title,120)||!text(r.dataScope,8000)||!text(r.scope,80))throw Error();const parsedWork=work(r.work);if(parsedWork.loadId!==r.loadId||parsedWork.contentId!==r.contentId||parsedWork.contentHash!==r.contentHash||parsedWork.scope!==r.scope)throw Error();return {...r,work:parsedWork,trigger:trigger(r.trigger)} as unknown as IndustryPlanSnapshot}catch{throw Error('行业持续计划预览格式不正确。')}}
function record(v:unknown):IndustryPlanRecord{try{const r=exact(v,['loadId','itemInstanceId','itemLocalId','contentId','contentHash','planVersion','planFileHash','title','work','dataScope','trigger','scope','planId','ownerId','requestId','goal','delivery','notificationPolicy','createdRole','selectedTrigger','createdAt']),base=snapshot(Object.fromEntries(['loadId','itemInstanceId','itemLocalId','contentId','contentHash','planVersion','planFileHash','title','work','dataScope','trigger','scope'].map(key=>[key,r[key]]))),role=exact(r.createdRole,['roleId','roleVersion']),hasPolicy=Object.hasOwn(r,'notificationPolicy');if(!uuid(r.planId)||!text(r.ownerId,128)||!uuid(r.requestId)||!text(r.goal,8000)||!text(r.delivery,8000)||hasPolicy&&!notificationPolicy(r.notificationPolicy)||!uuid(role.roleId)||!pos(role.roleVersion)||!stamp(r.createdAt))throw Error();return {...base,planId:r.planId,ownerId:r.ownerId,requestId:r.requestId,goal:r.goal,delivery:r.delivery,...(hasPolicy?{notificationPolicy:r.notificationPolicy as PlanNotificationPolicy}:{}),createdRole:{roleId:role.roleId,roleVersion:role.roleVersion},selectedTrigger:trigger(r.selectedTrigger),createdAt:r.createdAt} as IndustryPlanRecord}catch{throw Error('行业持续计划来源格式不正确。')}}
export type IndustryPlanApi=ReturnType<typeof createIndustryPlanApi>
export function createIndustryPlanApi(call:Call,journal:Journal|undefined,readPlan:(value:unknown)=>SavedPlan){let pending:IndustryPlanRequest|undefined,error:ReturnType<typeof recoveryStorageError>|undefined,busy=false;try{const raw=journal?.read();if(raw){if(raw.length>100000)throw Error();const r=exact(JSON.parse(raw),['schema','request']);if(r.schema!=='teloa.industry-plan/v1')throw Error();pending=request(r.request)}}catch{error=recoveryStorageError()}const send=async()=>{if(error)throw error;if(!pending)throw Error('没有待核对的行业持续计划创建请求。');if(busy)throw Error('行业持续计划正在核对。');busy=true;try{journal?.write(JSON.stringify({schema:'teloa.industry-plan/v1',request:pending}));const r=exact(await call('industry-plans/create',pending),['plan','source']),plan=readPlan(r.plan),source=record(r.source);if(plan.id!==source.planId||plan.ownerId!==source.ownerId||plan.notificationPolicy!==source.notificationPolicy||source.requestId!==pending.requestId||source.loadId!==pending.loadId||source.itemInstanceId!==pending.itemInstanceId||source.goal!==pending.goal||source.delivery!==pending.delivery||source.notificationPolicy!==pending.notificationPolicy||JSON.stringify(source.selectedTrigger)!==JSON.stringify(pending.trigger)||source.createdRole.roleId!==pending.roleId||source.createdRole.roleVersion!==pending.expectedRoleVersion)throw Error('行业持续计划响应与原请求不一致。');journal?.clear();pending=undefined;return {plan,source}}catch(e){if(e&&typeof e==='object'&&'rejected'in e&&e.rejected===true&&'code'in e&&['teloa/invalid-input','teloa/forbidden','teloa/version-conflict','teloa/source-unavailable'].includes(String(e.code))){journal?.clear();pending=undefined}throw e}finally{busy=false}}
return {pending:()=>pending?structuredClone(pending):undefined,recoveryMessage:()=>error,
/** 丢弃只清本地恢复记录，不通知服务端（规格 §二 D4）。 */
discard(){const had=pending!==undefined||error!==undefined;try{journal?.clear()}catch{/* 清不掉不该变成第二道墙 */}pending=undefined;error=undefined;return had},
create:async(v:IndustryPlanRequest)=>{const x=request(v);if(pending&&JSON.stringify(pending)!==JSON.stringify(x))throw Error('请先核对原行业持续计划创建请求。');pending??=x;return send()},recover:send,preview:async(loadId:string,itemInstanceId:string)=>{const x=snapshot(await call('industry-plans/preview',{loadId,itemInstanceId}));if(x.loadId!==loadId||x.itemInstanceId!==itemInstanceId)throw Error('行业持续计划预览身份不一致。');return x},source:async(planId:string)=>{if(!uuid(planId))throw Error('计划身份不正确。');const v=await call('industry-plans/source',{planId});if(v===null)return null;const x=record(v);if(x.planId!==planId)throw Error('行业持续计划来源身份不一致。');return x},list:async(loadId?:string)=>{const r=exact(await call('industry-plans/list',loadId?{loadId}:{}),['items']);if(!Array.isArray(r.items))throw Error('行业持续计划目录格式不正确。');const rows=r.items.map(record);if(new Set(rows.map(x=>x.planId)).size!==rows.length||new Set(rows.map(x=>x.requestId)).size!==rows.length||loadId&&rows.some(x=>x.loadId!==loadId))throw Error('行业持续计划目录身份不一致。');return rows}}}
