import {taskDefinition,taskInput,type WorkTask} from '@teloa/contract'
import {recoveryStorageError} from './recovery-error.ts'
type Call=(method:string,payload:unknown)=>Promise<unknown>
export type IndustryTaskCreateInput={requestId:string;loadId:string;itemInstanceId:string;goal:string;inputs:string[];assignee?:{roleId:string;expectedVersion:number}}
export type IndustryWorkSnapshot={loadId:string;itemInstanceId:string;itemLocalId:string;contentId:string;contentHash:string;templateId:string;templateVersion:string;fileHash:string;title:string;method:string;requirements:string[];output:string;skills:Array<{id:string;title:string;version:string}>;scope:string}
export type IndustryTaskSource=IndustryWorkSnapshot&{taskId:string;ownerId:string;inputs:string[];createdAssignee:{roleId:string;roleVersion:number}|null;createdAt:string}
export type IndustryTaskJournal={read:()=>string|null;write:(value:string)=>void;clear:()=>void}
const uuid=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
const positive=(value:unknown):value is number=>Number.isSafeInteger(value)&&Number(value)>0&&Number(value)<=2147483647
const text=(value:unknown,max:number):value is string=>typeof value==='string'&&!!value.trim()&&value.length<=max
const hash=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value)
const semver=(value:unknown):value is string=>typeof value==='string'&&value.length<=80&&/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(value)
const stamp=(value:unknown):value is string=>typeof value==='string'&&new Date(value).toISOString()===value
/** 业务范围标签（模板 `domain`）取代了 `space-<id>`：只核对 1–80 的标签文本。 */
const scope=(value:unknown):value is string=>typeof value==='string'&&!!value.trim()&&value.length<=80
const exact=(value:unknown,keys:readonly string[])=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(key=>!keys.includes(key)))throw Error();return value as Record<string,unknown>}
function input(value:unknown):IndustryTaskCreateInput{try{const row=exact(value,['requestId','loadId','itemInstanceId','goal','inputs','assignee']);if(!uuid(row.requestId)||!uuid(row.loadId)||!uuid(row.itemInstanceId)||!text(row.goal,8000)||!Array.isArray(row.inputs)||row.inputs.length>100||row.inputs.some(value=>!text(value,4000)))throw Error();let assignee:IndustryTaskCreateInput['assignee'];if(row.assignee!==undefined){const value=exact(row.assignee,['roleId','expectedVersion']);if(!uuid(value.roleId)||!positive(value.expectedVersion))throw Error();assignee={roleId:value.roleId.toLowerCase(),expectedVersion:value.expectedVersion}}return {requestId:row.requestId.toLowerCase(),loadId:row.loadId.toLowerCase(),itemInstanceId:row.itemInstanceId.toLowerCase(),goal:row.goal.trim(),inputs:row.inputs.map(value=>(value as string).trim()),...(assignee?{assignee}:{})}}catch{throw Error('行业工作任务创建请求格式不正确。')}}
function task(value:unknown):WorkTask{try{const row=taskInput(value,['id','ownerId','version','state','createdAt','updatedAt','title','goal','scope','assigneeRoleId','assigneeRoleVersion'].concat(['groupId','skills'])),{id,ownerId,version,state,createdAt,updatedAt,assigneeRoleId,assigneeRoleVersion,...fields}=row;if(!uuid(id)||!text(ownerId,128)||!positive(version)||!['ready','running','paused','waiting','blocked','completed','cancelled'].includes(String(state))||!stamp(createdAt)||!stamp(updatedAt)||updatedAt<createdAt)throw Error();if(assigneeRoleId===null?assigneeRoleVersion!==null:!uuid(assigneeRoleId)||!positive(assigneeRoleVersion))throw Error();return {...taskDefinition(fields),id,ownerId,version,state:state as WorkTask['state'],createdAt,updatedAt,assigneeRoleId:assigneeRoleId as string|null,assigneeRoleVersion:assigneeRoleVersion as number|null}}catch{throw Error('行业工作任务格式不正确。')}}
function source(value:unknown):IndustryTaskSource{try{const row=exact(value,['taskId','ownerId','loadId','itemInstanceId','itemLocalId','contentId','contentHash','templateId','templateVersion','fileHash','title','method','requirements','inputs','output','skills','scope','createdAssignee','createdAt']);if(!uuid(row.taskId)||!text(row.ownerId,128)||!uuid(row.loadId)||!uuid(row.itemInstanceId)||typeof row.itemLocalId!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(row.itemLocalId)||!uuid(row.contentId)||!hash(row.contentHash)||typeof row.templateId!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(row.templateId)||!semver(row.templateVersion)||!hash(row.fileHash)||!text(row.title,120)||!text(row.method,2000)||!Array.isArray(row.requirements)||row.requirements.length<1||row.requirements.length>100||row.requirements.some(value=>!text(value,500))||!Array.isArray(row.inputs)||row.inputs.length!==row.requirements.length||row.inputs.some(value=>!text(value,4000))||!text(row.output,2000)||!scope(row.scope)||!stamp(row.createdAt)||!Array.isArray(row.skills)||row.skills.length>100)throw Error();const skills=row.skills.map(value=>{const skill=exact(value,['id','title','version']);if(typeof skill.id!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(skill.id)||!text(skill.title,120)||!semver(skill.version))throw Error();return skill as unknown as IndustryTaskSource['skills'][number]});let createdAssignee:IndustryTaskSource['createdAssignee']=null;if(row.createdAssignee!==null){const value=exact(row.createdAssignee,['roleId','roleVersion']);if(!uuid(value.roleId)||!positive(value.roleVersion))throw Error();createdAssignee={roleId:value.roleId,roleVersion:value.roleVersion}}return {...row,skills,createdAssignee} as unknown as IndustryTaskSource}catch{throw Error('行业工作任务来源格式不正确。')}}
function snapshot(value:unknown):IndustryWorkSnapshot{try{const row=exact(value,['loadId','itemInstanceId','itemLocalId','contentId','contentHash','templateId','templateVersion','fileHash','title','method','requirements','output','skills','scope']);const synthetic={...row,taskId:'11111111-1111-4111-8111-111111111111',ownerId:'preview',inputs:row.requirements,createdAssignee:null,createdAt:'2026-01-01T00:00:00.000Z'},parsed=source(synthetic);const {taskId,ownerId,inputs,createdAssignee,createdAt,...result}=parsed;return result}catch{throw Error('行业任务模板预览格式不正确。')}}
export type IndustryTaskApi=ReturnType<typeof createIndustryTaskApi>
export function createIndustryTaskApi(call:Call,journal?:IndustryTaskJournal){let pending:IndustryTaskCreateInput|undefined,recoveryError:ReturnType<typeof recoveryStorageError>|undefined,busy=false;try{const raw=journal?.read();if(raw){if(raw.length>2500000)throw Error();const saved=exact(JSON.parse(raw),['schema','request']);if(saved.schema!=='teloa.industry-task/v1')throw Error();pending=input(saved.request)}}catch{recoveryError=recoveryStorageError()}
 const send=async()=>{if(recoveryError)throw recoveryError;if(!pending)throw Error('没有待核对的行业工作任务创建请求。');if(busy)throw Error('行业工作任务正在核对。');busy=true;try{journal?.write(JSON.stringify({schema:'teloa.industry-task/v1',request:pending}));let raw:unknown;try{raw=await call('industry-tasks/create',pending)}catch(error){if(error&&typeof error==='object'&&'rejected' in error&&error.rejected===true&&'code' in error&&['teloa/invalid-input','teloa/forbidden','teloa/version-conflict','teloa/source-unavailable'].includes(String(error.code))){journal?.clear();pending=undefined}throw error}const response=exact(raw,['task','source']),savedTask=task(response.task),savedSource=source(response.source);if(savedSource.taskId.toLowerCase()!==savedTask.id.toLowerCase()||savedSource.ownerId!==savedTask.ownerId||savedSource.loadId.toLowerCase()!==pending.loadId||savedSource.itemInstanceId.toLowerCase()!==pending.itemInstanceId||savedSource.scope!==savedTask.scope||JSON.stringify(savedSource.inputs)!==JSON.stringify(pending.inputs)||savedSource.createdAssignee?.roleId.toLowerCase()!==(pending.assignee?.roleId??undefined)||savedSource.createdAssignee?.roleVersion!==(pending.assignee?.expectedVersion??undefined))throw Error('行业工作任务响应与原请求不一致。');journal?.clear();pending=undefined;return {task:savedTask,source:savedSource}}finally{busy=false}}
 return {pending:()=>pending?structuredClone(pending):undefined,recoveryMessage:()=>recoveryError,
  /** 丢弃只清本地恢复记录，不通知服务端（规格 §二 D4）。 */
  discard(){const had=pending!==undefined||recoveryError!==undefined;try{journal?.clear()}catch{/* 清不掉不该变成第二道墙 */}pending=undefined;recoveryError=undefined;return had},
  recover:send,async preview(loadId:string,itemInstanceId:string){if(!uuid(loadId)||!uuid(itemInstanceId))throw Error('行业任务模板身份不正确。');const target={loadId:loadId.toLowerCase(),itemInstanceId:itemInstanceId.toLowerCase()},result=snapshot(await call('industry-tasks/preview',target));if(result.loadId.toLowerCase()!==target.loadId||result.itemInstanceId.toLowerCase()!==target.itemInstanceId)throw Error('行业任务模板预览与目标身份不一致。');return result},async create(value:IndustryTaskCreateInput){if(recoveryError)throw recoveryError;const normalized=input(value);if(pending&&JSON.stringify(pending)!==JSON.stringify(normalized))throw Error('请先核对原行业工作任务创建请求。');pending??=normalized;return send()},async source(taskId:string){if(!uuid(taskId))throw Error('任务身份不正确。');const normalized=taskId.toLowerCase(),value=await call('industry-tasks/source',{taskId:normalized});if(value===null)return null;const result=source(value);if(result.taskId.toLowerCase()!==normalized)throw Error('行业工作任务来源与目标任务不一致。');return result}}
}
