import {Clock3,FileText,Folder,Star} from 'lucide-react'
import type {LibraryPreferences,LibraryRow,LibraryView} from './library-views.js'
import {useI18n} from './i18n/provider.js'
import css from './ResourceManager.module.css'
export function LibraryViews({view,onChange}:{view:LibraryView;onChange:(view:LibraryView)=>void}){
 const {t}=useI18n()
 return <nav className={css.views} aria-label={t('library.views')}>{([['recent',Clock3],['star',Star],['mine',FileText],['local',Folder]] as const).map(([key,Icon])=><button key={key} type="button" aria-current={view===key?'page':undefined} onClick={()=>onChange(key)}><Icon size={16}/>{t(`library.${key}`)}</button>)}</nav>
}
export function LibraryList({rows,view,query,preferences,open,favorite,clear,loading,browseAll,add}:{rows:LibraryRow[];view:LibraryView;query:string;preferences:LibraryPreferences;open:(row:LibraryRow)=>void;favorite:(id:string)=>void;clear:()=>void;loading:boolean;browseAll:()=>void;add:()=>void}){
 const {locale,t}=useI18n(),time=(at:number)=>new Intl.DateTimeFormat(locale,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(at)
 if(!rows.length)return <section className={css.emptyDetail}><h2>{t(loading?'knowledge.role.loading':query.trim()?'library.noMatch':view==='recent'?'library.noRecent':'library.empty')}</h2><p>{!loading&&!query.trim()&&t(view==='recent'?'library.emptyRecent':view==='star'?'library.emptyStar':view==='local'?'library.emptyLocal':'knowledge.manager.emptyDescription')}</p>{query.trim()&&<button className={css.button} onClick={clear}>{t('library.clear')}</button>}{!loading&&!query.trim()&&view==='recent'&&<div className={css.actions}><button type="button" className={css.button} onClick={browseAll}>{t('library.browseAll')}</button><button type="button" className={css.button} onClick={add}>{t('library.add')}</button></div>}</section>
 return <><p className={css.listCount}>{t('library.count',{count:rows.length})}</p><div className={css.tableScroll}><table className={css.fileTable}><thead><tr><th>{t('library.name')}</th><th>{t('library.location')}</th><th>{t('library.status')}</th><th>{t('library.visited')}</th><th aria-label={t('library.star')}/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><button type="button" className={css.fileName} data-teloa-entry={row.id} onClick={()=>open(row)}><FileText size={17}/>{row.title}</button></td><td><span className={css.fileLocation} title={row.location}>{row.location||'—'}</span></td><td>{t(row.status==='draft'?'knowledge.manager.statusDraft':row.status==='active'?'library.available':'knowledge.manager.statusWithdrawn')}</td><td>{row.visitedAt===undefined?t('library.unvisited'):time(row.visitedAt)}</td><td><button type="button" className={css.favorite} aria-pressed={preferences.favorites.includes(row.id)} aria-label={t(preferences.favorites.includes(row.id)?'library.unfavorite':'library.favorite',{name:row.title})} onClick={()=>favorite(row.id)}><Star size={16} fill={preferences.favorites.includes(row.id)?'currentColor':'none'}/></button></td></tr>)}</tbody></table></div></>
}
