import {useEffect,useRef,useState} from 'react'
import {ArrowLeft,RefreshCw} from 'lucide-react'
import type {MarketPluginInstallPreview,MarketPluginRegistrySource} from '@teloa/contract'
import type {MarketPluginInstallApi,MarketPluginInstallation} from './market-plugin-install-api.js'
import {marketPluginCanEnable,marketPluginEnableSpec,marketPluginInstallAction,marketPluginInstallStatus,mergeMarketPluginInstallation} from './market-plugin-install-state.js'
import {EnableConfirm,PluginInstallConfirm as Confirm,PluginPreviewFacts as Preview,trustKey,trustNoticeKey} from './PluginInstallConsent.js'
import {useI18n} from './i18n/provider.js'
import {localizeWorkError} from './i18n/errors.js'
import css from './RealSkillInstallations.module.css'

type Props={api:MarketPluginInstallApi;source:MarketPluginRegistrySource;title:string;onSaved?:()=>void;onInstalled?:(record:MarketPluginInstallation)=>void}
const key=(source:MarketPluginRegistrySource)=>source.packageName+'@'+source.version
/** 与其它组件级测试同样的取巧：导出纯函数与纯展示组件，供 renderToStaticMarkup 直接核对。 */
export {EnableConfirm,trustKey,trustNoticeKey}
export const statusKey=(key:ReturnType<typeof marketPluginInstallStatus>['key'])=>key==='active'?'market.plugin.install.state.active':key==='preparing'?'market.plugin.install.state.preparing':key==='pending-enable'?'market.plugin.install.state.pendingEnable':key==='pending-enable-interrupted'?'market.plugin.status.pendingEnableInterrupted':key==='restart-required'?'market.plugin.install.state.enabledRestart':key==='failed'?'market.plugin.install.state.failed':'market.plugin.install.state.unknown' as const

export function MarketPluginInstallControl({api,source,title,onSaved,onInstalled}:Props){
  const {locale,t}=useI18n()
  const [preview,setPreview]=useState<MarketPluginInstallPreview>(),[record,setRecord]=useState<MarketPluginInstallation>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirming,setConfirming]=useState(false),[enableAck,setEnableAck]=useState(false),[discarded,setDiscarded]=useState(false)
  const recoveryError=api.recoveryMessage?.()
  const sequence=useRef(0)
  useEffect(()=>{let active=true;void api.list().then(({items})=>{if(active)setRecord(items.find(item=>key(item.preview.source)===key(source)))},()=>{});return()=>{active=false}},[api,source.packageName,source.version])
  const prepare=async()=>{const token=++sequence.current;setBusy(true);setError('');try{const next=await api.preview(source);if(token===sequence.current)setPreview(next)}catch(cause){if(token===sequence.current)setError(localizeWorkError(locale,cause))}finally{if(token===sequence.current)setBusy(false)}}
  const install=async()=>{if(!preview)return;const token=++sequence.current;setBusy(true);setError('');try{const saved=await api.install({schema:'teloa.market-plugin-install-spec/v1',requestId:crypto.randomUUID(),preview});if(token===sequence.current){setRecord(current=>mergeMarketPluginInstallation(current,saved));setConfirming(false);onSaved?.();onInstalled?.(saved)}}catch(cause){if(token===sequence.current)setError(localizeWorkError(locale,cause))}finally{if(token===sequence.current)setBusy(false)}}
  const reconcile=async()=>{if(!record)return;const token=++sequence.current;setBusy(true);setError('');try{const saved=await api.reconcile(record.id);if(token===sequence.current){setRecord(saved);onSaved?.()}}catch(cause){if(token===sequence.current)setError(localizeWorkError(locale,cause))}finally{if(token===sequence.current)setBusy(false)}}
  const enable=async()=>{if(!record||!enableAck)return;const token=++sequence.current;setBusy(true);setError('');try{const spec=marketPluginEnableSpec(record,crypto.randomUUID());const saved=await api.install(spec);if(token===sequence.current){setRecord(current=>mergeMarketPluginInstallation(current,saved));setEnableAck(false);onSaved?.()}}catch(cause){if(token===sequence.current)setError(localizeWorkError(locale,cause))}finally{if(token===sequence.current)setBusy(false)}}
  const status=record?marketPluginInstallStatus(record):undefined
  const pendingEnable=record?marketPluginCanEnable(record):false
  return <section className={css.sheet} aria-label={t('market.plugin.install.title')}><h3>{t('market.plugin.install.title')}</h3><strong>{title}</strong>{error&&<p role="alert" className={css.error}>{error}</p>}{recoveryError&&<p role="alert" className={css.error}>{localizeWorkError(locale,recoveryError)} {t('recovery.nextStep')}</p>}{recoveryError&&<button type="button" onClick={()=>{api.discard();setDiscarded(true)}}>{t('recovery.discard')}</button>}{discarded&&<p role="status">{t('recovery.discarded')}</p>}{record&&<p><strong>{t('market.plugin.install.field.status')}</strong> {t(statusKey(status!.key))}</p>}{record&&<p><strong>{t('market.plugin.install.field.trust')}</strong> {record.preview.trust.status==='rejected'?<span className={css.warn}>{t(trustKey('rejected'))}</span>:t(trustKey(record.preview.trust.status))} — {t(trustNoticeKey(record.preview.trust.status))}</p>}{record?.state==='unknown'&&<p role="alert">{t('market.plugin.install.state.unknownNotice')}</p>}{pendingEnable&&<EnableConfirm preview={record!.preview} ack={enableAck} setAck={setEnableAck} busy={busy} enable={()=>void enable()}/>}{preview?<Preview value={preview}/>:<button type="button" disabled={busy||record?.state==='unknown'} onClick={()=>void prepare()}>{busy?t('market.plugin.install.status.loading'):t('market.plugin.install.action.preview')}</button>}{preview&&<div className={css.buttons}><button type="button" disabled={busy||record?.state==='unknown'} onClick={()=>setConfirming(true)}>{t('market.plugin.install.action.prepare')}</button>{record&&<button type="button" disabled={busy} onClick={()=>void reconcile()}>{t('market.plugin.install.action.reconcile')}</button>}</div>}{record&&!preview&&status?.canReconcile&&<button type="button" disabled={busy} onClick={()=>void reconcile()}>{t('market.plugin.install.action.reconcile')}</button>}{confirming&&<Confirm preview={preview!} busy={busy} cancel={()=>setConfirming(false)} install={install}/>}</section>
}


export function MarketPluginInstallations({api,selected,select,onBrowse}:{api:MarketPluginInstallApi;selected:string|null;select:(id?:string)=>void;onBrowse:()=>void}){
  const {locale,t}=useI18n();const [items,setItems]=useState<MarketPluginInstallation[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0)
  useEffect(()=>{let active=true;setLoading(true);void api.list().then(value=>{if(active){setItems(value.items);setError('')}},cause=>{if(active)setError(localizeWorkError(locale,cause))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[api,revision,locale])
  const record=items.find(item=>item.id===selected)
  if(record)return <section className={css.page} aria-label={t('market.plugin.install.maintenance.title')}><button type="button" className={css.back} onClick={()=>select()}><ArrowLeft size={15}/>{t('market.plugin.install.action.back')}</button><h1>{t('market.plugin.install.record.title')}</h1><MarketPluginInstallControl api={api} source={record.preview.source} title={record.preview.source.packageName} onSaved={()=>setRevision(value=>value+1)}/>{record.failure&&<p role="alert">{t('market.plugin.install.failure')} · {t(statusKey(marketPluginInstallStatus(record).key))}</p>}<p>{t('market.plugin.install.attempt')} · {record.attempt}</p></section>
  return <section className={css.page} aria-label={t('market.plugin.install.maintenance.title')}><header className={css.header}><div><h1>{t('market.plugin.install.maintenance.title')}</h1><p>{t('market.plugin.install.title')}</p></div><div className={css.buttons}><button type="button" onClick={onBrowse}>{t('market.plugin.install.action.back')}</button><button type="button" disabled={loading} onClick={()=>setRevision(value=>value+1)}><RefreshCw size={14}/>{t('market.plugin.install.action.refresh')}</button></div></header>{error&&<p role="alert" className={css.error}>{error}</p>}{loading&&!items.length&&<p role="status">{t('market.plugin.install.status.loading')}</p>}<div className={css.list}>{items.map(item=>{const status=marketPluginInstallStatus(item);return <button type="button" key={item.id} onClick={()=>select(item.id)}><span><strong>{item.preview.source.packageName}</strong><small>{item.preview.source.version}</small></span><span>{t(statusKey(status.key))}</span></button>})}</div>{!loading&&!error&&!items.length&&<p>{t('market.plugin.install.empty')}</p>}</section>
}
