import type {SkillInstallationRecord,SkillInstallObservation,SkillInstallSourceIdentity,SkillInstallSourceInput,SkillInstallUsage} from './skill-install-api.js'
export type InstallationFilter='all'|'installed'|'preparing'
export type InstallationView={items:SkillInstallationRecord[];usages:SkillInstallUsage[];directoryLoaded:boolean;loading:boolean;error:string;detail?:{record:SkillInstallationRecord;observation?:SkillInstallObservation};detailError:string;observationError:string;detailLoading:boolean;detailToken:number}
export type InstallationViewAction={type:'observation-clear';token:number}|{type:'list-start';token:number}|{type:'list-ok';token:number;items:SkillInstallationRecord[];usages:SkillInstallUsage[]}|{type:'list-error';token:number;error:string}|{type:'select';id:string;token:number}|{type:'detail-ok';token:number;record:SkillInstallationRecord}|{type:'observation-ok';token:number;observation:SkillInstallObservation}|{type:'observation-error';token:number;error:string}|{type:'detail-error';token:number;error:string}
export const initialInstallationView:InstallationView={items:[],usages:[],directoryLoaded:false,loading:true,error:'',detailError:'',observationError:'',detailLoading:false,detailToken:0}
const canonical=(value:unknown):string=>JSON.stringify(value,(_,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a<b?-1:a>b?1:0)):item)
export function reduceInstallationView(state:InstallationView|undefined,action:InstallationViewAction):InstallationView{const current=state??initialInstallationView;if(action.type==='list-start')return {...current,loading:true,error:''};if(action.type==='list-ok')return {...current,items:action.items,usages:action.usages,directoryLoaded:true,loading:false,error:''};if(action.type==='list-error')return {...current,loading:false,error:action.error};if(action.type==='select'){const {detail:previous,...rest}=current;return {...rest,...(previous?.record.id===action.id?{detail:previous}:{}),detailError:'',observationError:'',detailLoading:true,detailToken:action.token}}if(action.token!==current.detailToken)return current;if(action.type==='detail-ok'){const previous=current.detail?.record;if(previous?.id===action.record.id){if(action.record.version<previous.version)return {...current,detailLoading:false};if(action.record.version===previous.version&&canonical(action.record)!==canonical(previous))return {...current,detailLoading:false,detailError:'同一版本的安装记录不一致，请重新核对。'}}const same=current.detail?.record.id===action.record.id&&current.detail.record.version===action.record.version;return {...current,detail:{record:action.record,...(same&&current.detail?.observation?{observation:current.detail.observation}:{})},detailLoading:false,detailError:'',observationError:''}}if(action.type==='observation-clear')return current.detail?{...current,detail:{record:current.detail.record},observationError:''}:current;if(action.type==='observation-ok')return current.detail?{...current,detail:{...current.detail,observation:action.observation},observationError:''}:current;if(action.type==='observation-error')return {...current,observationError:action.error};return {...current,detailLoading:false,detailError:action.error}}
export function installationSourceInput(source:SkillInstallSourceIdentity):SkillInstallSourceInput{return source.kind==='atomic'?{kind:'atomic',contentId:source.contentId}:{kind:'industry',loadId:source.loadId,itemInstanceId:source.itemInstanceId}}
export function filterSkillInstallations(items:readonly SkillInstallationRecord[],query:string,filter:InstallationFilter){const needle=query.trim().toLocaleLowerCase();return items.filter(item=>(filter==='all'||item.state===filter)&&(!needle||[item.native.name,item.source.resourceVersion,item.id].some(value=>value.toLocaleLowerCase().includes(needle))))}
