import {useEffect,useRef,useState} from 'react'
import type {IndustryLoadRecord} from './industry-load-api.js'
import type {IndustryRoleInstance} from './industry-role-api.js'
import type {IndustryTaskApi,IndustryTaskCreateInput,IndustryWorkSnapshot} from './industry-task-api.js'
import {canReceiveTask} from './role-preview.js'
import type {RoleDelegationRead} from './role-delegation-api.js'
import {openDialog} from './dialog-focus.js'
import {useI18n} from './i18n/provider.js'
import css from './TaskPage.module.css'

export function SavedIndustryTaskForm({load,itemInstanceId,roles,api,close,create,executionAccess}:{load:IndustryLoadRecord;itemInstanceId:string;roles:readonly IndustryRoleInstance[];executionAccess?:Readonly<Record<string,RoleDelegationRead>>;api:IndustryTaskApi;close:()=>void;create:(input:IndustryTaskCreateInput)=>Promise<void>}){
 const {t}=useI18n()
 const dialog=useRef<HTMLDialogElement>(null),[preview,setPreview]=useState<IndustryWorkSnapshot>(),[error,setError]=useState<string>(),[busy,setBusy]=useState(false),[goal,setGoal]=useState(''),[inputs,setInputs]=useState<string[]>([]),[assignee,setAssignee]=useState(''),[previewRevision,setPreviewRevision]=useState(0)
 useEffect(()=>{const dispose=openDialog(dialog.current);let live=true;setError(undefined);void api.preview(load.id,itemInstanceId).then(value=>{if(live){setPreview(value);setInputs(value.requirements.map(()=>''))}},()=>{if(live)setError(t('market.industry.taskForm.previewFailed'))});return()=>{live=false;dispose()}},[api,load.id,itemInstanceId,previewRevision,t])
 const linked=new Set(load.relations.filter(link=>link.kind==='role-work'&&link.to===itemInstanceId).map(link=>link.from)),linkedItems=load.items.filter(item=>item.kind==='role'&&linked.has(item.instanceId)),candidates=roles.filter(instance=>instance.loadId===load.id&&linked.has(instance.itemInstanceId)),eligible=candidates.filter(instance=>instance.role&&preview&&canReceiveTask({...instance.role,workAccess:executionAccess?.[instance.role.id]},preview.scope))
 const submit=async()=>{if(!preview||busy)return;const selected=eligible.find(instance=>instance.role!.id===assignee);if(assignee&&!selected){setError(t('market.industry.taskForm.ownerChanged'));return}setBusy(true);setError(undefined);try{await create({requestId:crypto.randomUUID(),loadId:load.id,itemInstanceId,goal,inputs,...(selected?.role?{assignee:{roleId:selected.role.id,expectedVersion:selected.role.version}}:{})});close()}catch{setError(t('market.industry.taskForm.failed'))}finally{setBusy(false)}}
 const unavailable=(instance:IndustryRoleInstance|undefined)=>!instance?t('market.industry.taskForm.roleMissing'):instance.state==='paused'?t('role.state.paused'):instance.state==='retired'?t('role.state.retired'):instance.state==='pending'?t('market.industry.taskForm.rolePending'):instance.state==='failed'?t('market.industry.taskForm.roleFailed'):instance.role?.kind==='twin'?t('roleDelegation.requiresDelegation'):t('market.industry.taskForm.roleIneligible')
 return <dialog ref={dialog} className={css.dialog} aria-label={t('market.industry.taskForm.aria')} onCancel={event=>{if(busy)event.preventDefault();else close()}}><form className={css.form} onSubmit={event=>{event.preventDefault();void submit()}}><h2>{preview?.title??t('market.industry.taskForm.loading')}</h2><p>{t('market.industry.taskForm.help')}</p>{error&&<p role="alert">{error} {!preview&&<button type="button" onClick={()=>setPreviewRevision(value=>value+1)}>{t('market.industry.taskForm.retry')}</button>}</p>}{preview&&<><details open><summary>{t('market.industry.taskForm.method')}</summary><p>{preview.method}</p><p>{t('market.industry.taskForm.delivery',{value:preview.output})}</p>{preview.skills.length>0&&<p>{t('market.industry.taskForm.skills',{skills:preview.skills.map(skill=>skill.title+' · '+skill.version).join(', ')})}</p>}</details><label>{t('market.industry.taskForm.goal')}<textarea required rows={3} maxLength={8000} value={goal} onChange={event=>setGoal(event.target.value)}/></label>{preview.requirements.map((requirement,index)=><label key={index}>{index+1}. {requirement}<textarea required aria-label={t('market.industry.taskForm.inputAria',{index:index+1,requirement})} rows={2} maxLength={4000} value={inputs[index]??''} onChange={event=>setInputs(current=>current.map((value,i)=>i===index?event.target.value:value))}/></label>)}<label>{t('market.industry.taskForm.owner')}<select aria-label={t('market.industry.taskForm.ownerAria')} value={assignee} onChange={event=>setAssignee(event.target.value)}><option value="">{t('market.industry.taskForm.unassigned')}</option>{eligible.map(instance=><option key={instance.role!.id} value={instance.role!.id}>{instance.role!.name} · v{instance.role!.version}</option>)}</select></label>{linkedItems.map(item=>{const instance=candidates.find(row=>row.itemInstanceId===item.instanceId);if(instance&&eligible.includes(instance))return null;return <p key={item.instanceId}>{item.title} · {unavailable(instance)}</p>})}</>}<footer className={css.buttons}><button type="button" disabled={busy} onClick={close}>{t('market.common.cancel')}</button><button type="submit" disabled={busy||!preview||!goal.trim()||inputs.some(value=>!value.trim())}>{t(busy?'market.industry.taskForm.creating':'market.industry.taskForm.create')}</button></footer></form></dialog>
}
