import {createSkillAvailabilityApi,type SkillAvailabilityPreview} from './skill-availability-api.ts'
import {createSkillInstallApi,type SkillInstallationRecord,type SkillInstallPreview,type SkillInstallSourceInput,type SkillInstallSourceIdentity} from './skill-install-api.ts'
import {readManagedRunSkill} from './task-run-managed-skill.ts'
import {recoveryStorageError} from './recovery-error.ts'

export type SkillUpgradeFile={path:string;change:'added'|'removed'|'modified'|'unchanged';before:{hash:string;size:number}|null;after:{hash:string;size:number}|null}
export type SkillUpgradePreview={current:SkillAvailabilityPreview;target:SkillInstallPreview;files:SkillUpgradeFile[];sameResourceId:boolean;blockers:('installation-not-installed'|'same-source'|'native-name-mismatch')[]}
export type SkillUpgradeUsage={loadId:string;itemInstanceId:string}
export type SkillUpgradeApplyInput={currentInstallationId:string;target:SkillInstallSourceInput;expectedTargetBundleHash:string;expectedTargetTrustHash?:string;industryUsages:SkillUpgradeUsage[]}
export type SkillUpgradeApplyResult={installation:SkillInstallationRecord;selection:{ownerId:string;nativeName:string;installationId:string;version:number;updatedAt:string};migratedIndustryUsages:SkillUpgradeUsage[]}
type Journal={read:()=>string|null;write:(value:string)=>void;clear:()=>void}
type SelectionCommand={requestId:string;nativeName:string;currentInstallationId:string;targetInstallationId:string;expectedSelectionVersion:number;expectedCurrentBundleHash:string;expectedTargetBundleHash:string;expectedImpactDigest:string;industryUsages:SkillUpgradeUsage[]}
type Pending={installRequestId:string;switchRequestId:string;currentInstallationId:string;target:SkillInstallSourceInput;expectedTargetBundleHash:string;expectedTargetTrustHash?:string;industryUsages:SkillUpgradeUsage[];command?:SelectionCommand}
const invalid=()=>Error('技能升级预览身份或文件差异不完整，请重新核对。')
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(key=>!keys.includes(key)))throw invalid();return value as Record<string,unknown>}
const uuid=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value)
const hash=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value)
const name=(value:unknown):value is string=>typeof value==='string'&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)
const positive=(value:unknown):value is number=>Number.isSafeInteger(value)&&Number(value)>0&&Number(value)<=2147483647
const canonical=(s:SkillInstallSourceIdentity)=>JSON.stringify(s.kind==='industry-public'?['atomic',s.sourceContentId,s.sourceContentHash,s.sourceResourceId,s.sourceResourceVersion]:[s.kind==='atomic'?'atomic':'industry-local',s.contentId,s.contentHash,s.resourceId,s.resourceVersion])
const resourceId=(s:SkillInstallSourceIdentity)=>s.kind==='industry-public'?s.sourceResourceId:s.resourceId
const digest=async(files:{path:string;hash:string}[])=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(files.map(file=>[file.path,file.hash]))))),byte=>byte.toString(16).padStart(2,'0')).join('')
function side(value:unknown):SkillUpgradeFile['before']{if(value===null)return null;const row=exact(value,['hash','size']);if(typeof row.hash!=='string'||!/^[a-f0-9]{64}$/.test(row.hash)||!Number.isSafeInteger(row.size)||Number(row.size)<0||Number(row.size)>2*1024*1024)throw invalid();return {hash:row.hash,size:row.size as number}}
function sourceInput(value:unknown):SkillInstallSourceInput{const row=exact(value,['kind','contentId','loadId','itemInstanceId']);if(row.kind==='atomic'&&uuid(row.contentId)&&Object.keys(row).length===2)return {kind:'atomic',contentId:row.contentId.toLowerCase()};if(row.kind==='industry'&&uuid(row.loadId)&&uuid(row.itemInstanceId)&&Object.keys(row).length===3)return {kind:'industry',loadId:row.loadId.toLowerCase(),itemInstanceId:row.itemInstanceId.toLowerCase()};throw invalid()}
function usages(value:unknown):SkillUpgradeUsage[]{if(!Array.isArray(value)||value.length>1000)throw invalid();const result=value.map(item=>{const row=exact(item,['loadId','itemInstanceId']);if(!uuid(row.loadId)||!uuid(row.itemInstanceId))throw invalid();return {loadId:row.loadId.toLowerCase(),itemInstanceId:row.itemInstanceId.toLowerCase()}}).sort((a,b)=>(a.loadId+':'+a.itemInstanceId).localeCompare(b.loadId+':'+b.itemInstanceId));if(new Set(result.map(item=>item.loadId+':'+item.itemInstanceId)).size!==result.length)throw invalid();return result}
function applyInput(value:unknown):SkillUpgradeApplyInput{const row=exact(value,['currentInstallationId','target','expectedTargetBundleHash','expectedTargetTrustHash','industryUsages']);if(!uuid(row.currentInstallationId)||!hash(row.expectedTargetBundleHash)||row.expectedTargetTrustHash!==undefined&&!hash(row.expectedTargetTrustHash))throw invalid();return {currentInstallationId:row.currentInstallationId.toLowerCase(),target:sourceInput(row.target),expectedTargetBundleHash:row.expectedTargetBundleHash,...(row.expectedTargetTrustHash?{expectedTargetTrustHash:row.expectedTargetTrustHash}:{}),industryUsages:usages(row.industryUsages)}}
function selection(value:unknown){const row=exact(value,['ownerId','nativeName','installationId','version','updatedAt']);if(typeof row.ownerId!=='string'||!row.ownerId.trim()||!name(row.nativeName)||!uuid(row.installationId)||!positive(row.version)||typeof row.updatedAt!=='string'||new Date(row.updatedAt).toISOString()!==row.updatedAt)throw invalid();return {ownerId:row.ownerId,nativeName:row.nativeName,installationId:row.installationId.toLowerCase(),version:row.version,updatedAt:row.updatedAt}}
function command(value:unknown):SelectionCommand{const row=exact(value,['requestId','nativeName','currentInstallationId','targetInstallationId','expectedSelectionVersion','expectedCurrentBundleHash','expectedTargetBundleHash','expectedImpactDigest','industryUsages']);if(!uuid(row.requestId)||!name(row.nativeName)||!uuid(row.currentInstallationId)||!uuid(row.targetInstallationId)||!positive(row.expectedSelectionVersion)||!hash(row.expectedCurrentBundleHash)||!hash(row.expectedTargetBundleHash)||!hash(row.expectedImpactDigest))throw invalid();return {requestId:row.requestId.toLowerCase(),nativeName:row.nativeName,currentInstallationId:row.currentInstallationId.toLowerCase(),targetInstallationId:row.targetInstallationId.toLowerCase(),expectedSelectionVersion:row.expectedSelectionVersion,expectedCurrentBundleHash:row.expectedCurrentBundleHash,expectedTargetBundleHash:row.expectedTargetBundleHash,expectedImpactDigest:row.expectedImpactDigest,industryUsages:usages(row.industryUsages)}}
function pendingRequest(value:unknown):Pending{const row=exact(value,['installRequestId','switchRequestId','currentInstallationId','target','expectedTargetBundleHash','expectedTargetTrustHash','industryUsages','command']);if(!uuid(row.installRequestId)||!uuid(row.switchRequestId)||!uuid(row.currentInstallationId)||!hash(row.expectedTargetBundleHash)||row.expectedTargetTrustHash!==undefined&&!hash(row.expectedTargetTrustHash))throw invalid();const result:Pending={installRequestId:row.installRequestId.toLowerCase(),switchRequestId:row.switchRequestId.toLowerCase(),currentInstallationId:row.currentInstallationId.toLowerCase(),target:sourceInput(row.target),expectedTargetBundleHash:row.expectedTargetBundleHash,...(row.expectedTargetTrustHash?{expectedTargetTrustHash:row.expectedTargetTrustHash}:{}),industryUsages:usages(row.industryUsages)};if(row.command!==undefined)result.command=command(row.command);return result}
export type SkillUpgradeApi=ReturnType<typeof createSkillUpgradeApi>
export function createSkillUpgradeApi(call:(method:string,payload:unknown)=>Promise<unknown>,journal?:Journal){let pending:Pending|undefined,recoveryError:ReturnType<typeof recoveryStorageError>|undefined,busy=false;try{const raw=journal?.read();if(raw){if(raw.length>20000)throw invalid();const row=exact(JSON.parse(raw),['schema','request']);if(row.schema!=='teloa.skill-upgrade/v1')throw invalid();pending=pendingRequest(row.request)}}catch{recoveryError=recoveryStorageError()}
 const save=()=>{if(pending)journal?.write(JSON.stringify({schema:'teloa.skill-upgrade/v1',request:pending}))}
 const send=async():Promise<SkillUpgradeApplyResult>=>{if(recoveryError)throw recoveryError;if(!pending)throw Error('没有待恢复的技能升级。');if(busy)throw Error('技能升级正在执行。');busy=true;try{
  save();const installApi=createSkillInstallApi(call),installed=await installApi.install({requestId:pending.installRequestId,source:pending.target,expectedBundleHash:pending.expectedTargetBundleHash,...(pending.expectedTargetTrustHash?{expectedTrustHash:pending.expectedTargetTrustHash}:{})});if(installed.id===pending.currentInstallationId)throw Error('技能目标版本与当前版本相同。')
  if(!pending.command){const raw=exact(await call('skill-selections/preview',{currentInstallationId:pending.currentInstallationId,targetInstallationId:installed.id}),['selection','current','target','impact','impactDigest']),selected=selection(raw.selection),current=exact(raw.current,['id','ownerId','source','bundleHash','native','state','version','createdAt','updatedAt']),target=exact(raw.target,['id','ownerId','source','bundleHash','native','state','version','createdAt','updatedAt']),impact=exact(raw.impact,['nativeName','selection','current','target','industryUsages']);if(current.id!==pending.currentInstallationId||target.id!==installed.id||target.bundleHash!==pending.expectedTargetBundleHash||selected.installationId!==pending.currentInstallationId||impact.nativeName!==selected.nativeName||!hash(raw.impactDigest))throw invalid();const available=new Set(usages(impact.industryUsages).map(item=>item.loadId+':'+item.itemInstanceId));if(pending.industryUsages.some(item=>!available.has(item.loadId+':'+item.itemInstanceId)))throw Error('待迁移的行业引用已变化，请重新预览。');pending.command={requestId:pending.switchRequestId,nativeName:selected.nativeName,currentInstallationId:pending.currentInstallationId,targetInstallationId:installed.id,expectedSelectionVersion:selected.version,expectedCurrentBundleHash:current.bundleHash as string,expectedTargetBundleHash:pending.expectedTargetBundleHash,expectedImpactDigest:raw.impactDigest,industryUsages:pending.industryUsages};save()}
  const response=exact(await call('skill-selections/change',pending.command),['receipt','current']),receipt=exact(response.receipt,['requestId','nativeName','before','result','migratedIndustryUsages','impact','impactDigest','createdAt']),result=selection(receipt.result);if(receipt.requestId!==pending.switchRequestId||result.installationId!==installed.id||result.nativeName!==pending.command.nativeName||receipt.impactDigest!==pending.command.expectedImpactDigest||JSON.stringify(usages(receipt.migratedIndustryUsages))!==JSON.stringify(pending.industryUsages))throw invalid();journal?.clear();pending=undefined;return {installation:installed,selection:result,migratedIndustryUsages:usages(receipt.migratedIndustryUsages)}
 }catch(error){if(error&&typeof error==='object'&&'rejected'in error&&error.rejected===true&&'code'in error&&['teloa/invalid-input','teloa/forbidden','teloa/conflict','teloa/version-conflict'].includes(String(error.code))){journal?.clear();pending=undefined}throw error}finally{busy=false}}
 return {
 async preview(input:{installationId:string;target:SkillInstallSourceInput}):Promise<SkillUpgradePreview>{
  const request=exact(input,['installationId','target']);if(!uuid(request.installationId))throw invalid()
  const source=exact(request.target,['kind','contentId','loadId','itemInstanceId'])
  let targetInput:SkillInstallSourceInput
  if(source.kind==='atomic'&&uuid(source.contentId)&&Object.keys(source).length===2)targetInput={kind:'atomic',contentId:source.contentId.toLowerCase()}
  else if(source.kind==='industry'&&uuid(source.loadId)&&uuid(source.itemInstanceId)&&Object.keys(source).length===3)targetInput={kind:'industry',loadId:source.loadId.toLowerCase(),itemInstanceId:source.itemInstanceId.toLowerCase()}
  else throw invalid()
  const installationId=request.installationId.toLowerCase(),row=exact(await call('skill-upgrades/preview',{installationId,target:targetInput}),['current','target','files','sameResourceId','blockers'])
  // 复用已有两条严格读取边界；这里注入已收到的数据，不产生额外网络请求。
  const current=await createSkillAvailabilityApi(async()=>row.current).preview(installationId),target=await createSkillInstallApi(async()=>row.target).preview(targetInput)
  if(!Array.isArray(row.files)||!row.files.length||row.files.length>1000||typeof row.sameResourceId!=='boolean'||!Array.isArray(row.blockers))throw invalid()
  let previous=''
  const files=row.files.map(value=>{const f=exact(value,['path','change','before','after']);if(typeof f.path!=='string'||f.path<=previous)throw invalid();previous=f.path;const before=side(f.before),after=side(f.after);if(!before&&!after)throw invalid();const change=!before?'added':!after?'removed':before.hash===after.hash&&before.size===after.size?'unchanged':'modified';if(f.change!==change)throw invalid();return {path:f.path,change,before,after} as SkillUpgradeFile})
  const before=files.flatMap(file=>file.before?[{path:file.path,...file.before}]:[]),after=files.flatMap(file=>file.after?[{path:file.path,...file.after}]:[])
  readManagedRunSkill({installationId,bundleHash:current.installation.bundleHash,files:before});readManagedRunSkill({installationId,bundleHash:target.bundleHash,files:after})
  const fileShape=(values:{path:string;hash:string;size:number}[])=>JSON.stringify(values.map(file=>[file.path,file.hash,file.size]))
  if(await digest(before)!==current.installation.bundleHash||await digest(after)!==target.bundleHash||fileShape(after)!==fileShape(target.files))throw invalid()
  const blockers:SkillUpgradePreview['blockers']=[]
  if(current.installation.state!=='installed')blockers.push('installation-not-installed')
  if(canonical(current.installation.source)===canonical(target.source))blockers.push('same-source')
  if(current.installation.native.name!==target.native.name)blockers.push('native-name-mismatch')
  if(row.sameResourceId!==(resourceId(current.installation.source)===resourceId(target.source))||row.blockers.length!==blockers.length||new Set(row.blockers).size!==row.blockers.length||row.blockers.some(value=>!blockers.includes(value as SkillUpgradePreview['blockers'][number])))throw invalid()
 return {current,target,files,sameResourceId:row.sameResourceId,blockers}
 },
 apply:async(value:SkillUpgradeApplyInput)=>{const input=applyInput(value);if(pending&&JSON.stringify({...pending,installRequestId:undefined,switchRequestId:undefined,command:undefined})!==JSON.stringify({...input,installRequestId:undefined,switchRequestId:undefined,command:undefined}))throw Error('请先恢复或核对上一项技能升级。');pending??={installRequestId:crypto.randomUUID(),switchRequestId:crypto.randomUUID(),...input};return send()},
 recover:send,
 pending:()=>pending?structuredClone(pending):undefined,
 recoveryMessage:()=>recoveryError,
 /** 丢弃只清本地恢复记录，不通知服务端（规格 §二 D4）。 */
 discard(){const had=pending!==undefined||recoveryError!==undefined;try{journal?.clear()}catch{/* 清不掉不该变成第二道墙 */}pending=undefined;recoveryError=undefined;return had},
}}
