import type {MarketTrust} from './market-preview.ts'
import {recoveryStorageError} from './recovery-error.ts'
type Call=(method:string,payload:unknown)=>Promise<unknown>
export type SkillInstallSourceInput={kind:'atomic';contentId:string}|{kind:'industry';loadId:string;itemInstanceId:string}
export type SkillInstallSourceIdentity={kind:'atomic';contentId:string;contentHash:string;resourceId:string;resourceVersion:string}|{kind:'industry-local';loadId:string;itemInstanceId:string;contentId:string;contentHash:string;resourceId:string;resourceVersion:string}|{kind:'industry-public';loadId:string;itemInstanceId:string;contentId:string;contentHash:string;sourceContentId:string;sourceContentHash:string;sourceResourceId:string;sourceResourceVersion:string;resourceId:string;resourceVersion:string}
export type SkillInstallNative={name:string;description:string;modelInvocable:boolean;userInvocable:boolean;bodyHash:string}
export type SkillInstallPreview={source:SkillInstallSourceIdentity;bundleHash:string;native:SkillInstallNative;files:Array<{path:string;hash:string;size:number}>;trust?:MarketTrust;trustHash?:string;installationPlan?:{skills:{id:string;version:string;path:string}[];plugins:MarketTrust['plugins'];connections:MarketTrust['externalCapabilities'];permissions:MarketTrust['permissions']}}
export type SkillInstallationRecord={id:string;ownerId:string;source:SkillInstallSourceIdentity;bundleHash:string;native:SkillInstallNative;trust?:MarketTrust;trustHash?:string;state:'preparing'|'installed';version:number;createdAt:string;updatedAt:string}
export type SkillInstallUsage={loadId:string;itemInstanceId:string;installationId:string}
export type SkillInstallObservation={installationId:string;scope:'default-workspace';state:'available'|'shadowed'|'missing'|'disabled';reason?:'different-source'|'content-changed';current:null|SkillInstallNative&{provider:string;source:string}}
export type SkillInstallRequest={requestId:string;source:SkillInstallSourceInput;expectedBundleHash:string;expectedTrustHash?:string}
type Journal={read:()=>string|null;write:(value:string)=>void;clear:()=>void}
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v),hash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),stable=(v:unknown):v is string=>typeof v==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(v),semver=(v:unknown):v is string=>typeof v==='string'&&v.length<=80&&/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(v),positive=(v:unknown):v is number=>Number.isSafeInteger(v)&&(v as number)>0&&(v as number)<=2147483647,stamp=(v:unknown):v is string=>typeof v==='string'&&new Date(v).toISOString()===v
const exact=(v:unknown,keys:readonly string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))throw Error();return v as Record<string,unknown>},normalizedUuid=(v:unknown)=>{if(!uuid(v))throw Error();return v.toLowerCase()}
function sourceInput(v:unknown):SkillInstallSourceInput{try{const r=exact(v,['kind','contentId','loadId','itemInstanceId']);if(r.kind==='atomic'){const contentId=normalizedUuid(r.contentId);if(Object.keys(r).length!==2)throw Error();return {kind:'atomic',contentId}}const loadId=normalizedUuid(r.loadId),itemInstanceId=normalizedUuid(r.itemInstanceId);if(r.kind!=='industry'||Object.keys(r).length!==3)throw Error();return {kind:'industry',loadId,itemInstanceId}}catch{throw Error('技能安装来源请求格式不正确。')}}
function identity(v:unknown):SkillInstallSourceIdentity{const r=exact(v,['kind','contentId','contentHash','resourceId','resourceVersion','loadId','itemInstanceId','sourceContentId','sourceContentHash','sourceResourceId','sourceResourceVersion']);const common={contentId:normalizedUuid(r.contentId),contentHash:r.contentHash,resourceId:r.resourceId,resourceVersion:r.resourceVersion};if(!hash(common.contentHash)||!stable(common.resourceId)||!semver(common.resourceVersion))throw Error();if(r.kind==='atomic'){if(Object.keys(r).length!==5)throw Error();return {kind:'atomic',...common} as SkillInstallSourceIdentity}const industry={loadId:normalizedUuid(r.loadId),itemInstanceId:normalizedUuid(r.itemInstanceId)};if(r.kind==='industry-local'){if(Object.keys(r).length!==7)throw Error();return {kind:'industry-local',...industry,...common} as SkillInstallSourceIdentity}if(r.kind!=='industry-public'||Object.keys(r).length!==11||!hash(r.sourceContentHash)||!stable(r.sourceResourceId)||!semver(r.sourceResourceVersion))throw Error();return {kind:'industry-public',...industry,...common,sourceContentId:normalizedUuid(r.sourceContentId),sourceContentHash:r.sourceContentHash,sourceResourceId:r.sourceResourceId,sourceResourceVersion:r.sourceResourceVersion} as SkillInstallSourceIdentity}
const sourceMatches=(given:SkillInstallSourceInput,actual:SkillInstallSourceIdentity)=>given.kind==='atomic'?actual.kind==='atomic'&&actual.contentId===given.contentId:actual.kind!=='atomic'&&actual.loadId===given.loadId&&actual.itemInstanceId===given.itemInstanceId
const canonical=(value:SkillInstallSourceIdentity)=>value.kind==='industry-local'?JSON.stringify(['industry-local',value.contentId,value.contentHash,value.resourceId,value.resourceVersion]):value.kind==='industry-public'?JSON.stringify(['atomic',value.sourceContentId,value.sourceContentHash,value.sourceResourceId,value.sourceResourceVersion]):JSON.stringify(['atomic',value.contentId,value.contentHash,value.resourceId,value.resourceVersion])
function native(v:unknown):SkillInstallNative{const r=exact(v,['name','description','modelInvocable','userInvocable','bodyHash']);if(typeof r.name!=='string'||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.name)||typeof r.description!=='string'||r.description.length<1||r.description.length>2*1024*1024||typeof r.modelInvocable!=='boolean'||typeof r.userInvocable!=='boolean'||!hash(r.bodyHash))throw Error();return r as unknown as SkillInstallNative}
function trust(v:unknown):MarketTrust{const r=exact(v,['publisher','repository','license','signature','compatibility','plugins','externalCapabilities','permissions','review']);if(typeof r.publisher!=='string'||!r.publisher||!r.license||!r.signature||!r.compatibility||!Array.isArray(r.plugins)||!Array.isArray(r.externalCapabilities)||!Array.isArray(r.permissions)||!r.review)throw Error();return r as unknown as MarketTrust}
function preview(v:unknown):SkillInstallPreview{try{if(!v||typeof v!=='object'||Array.isArray(v))throw Error();const raw=v as Record<string,unknown>,hasTrust=raw.trust!==undefined||raw.trustHash!==undefined||raw.installationPlan!==undefined,r=exact(raw,hasTrust?['source','bundleHash','native','files','trust','trustHash','installationPlan']:['source','bundleHash','native','files']);if(!hash(r.bundleHash)||!Array.isArray(r.files)||!r.files.length||r.files.length>500)throw Error();const files=r.files.map(v=>{const f=exact(v,['path','hash','size']);if(typeof f.path!=='string'||!f.path||f.path.includes('\\')||f.path.startsWith('/')||f.path.split('/').some(x=>!x||x==='.'||x==='..')||f.path.length>500||!hash(f.hash)||!Number.isSafeInteger(f.size)||(f.size as number)<0||(f.size as number)>2*1024*1024)throw Error();return f as {path:string;hash:string;size:number}});if(files.reduce((sum,file)=>sum+file.size,0)>20*1024*1024||new Set(files.map(f=>f.path)).size!==files.length||!files.some(f=>f.path==='SKILL.md')||files.some((file,index)=>index>0&&files[index-1]!.path>=file.path))throw Error();const base={source:identity(r.source),bundleHash:r.bundleHash,native:native(r.native),files};if(!hasTrust)return base;const plan=exact(r.installationPlan,['skills','plugins','connections','permissions']);if(!Array.isArray(plan.skills)||!Array.isArray(plan.plugins)||!Array.isArray(plan.connections)||!Array.isArray(plan.permissions))throw Error();return {...base,trust:trust(r.trust),trustHash:hash(r.trustHash)?r.trustHash:(()=>{throw Error()})(),installationPlan:plan as unknown as NonNullable<SkillInstallPreview['installationPlan']>}}catch{throw Error('技能安装预览格式不正确。')}}
function record(v:unknown):SkillInstallationRecord{try{if(!v||typeof v!=='object'||Array.isArray(v))throw Error();const raw=v as Record<string,unknown>,hasTrust=raw.trust!==undefined||raw.trustHash!==undefined,r=exact(raw,hasTrust?['id','ownerId','source','bundleHash','native','trust','trustHash','state','version','createdAt','updatedAt']:['id','ownerId','source','bundleHash','native','state','version','createdAt','updatedAt']);if(!uuid(r.id)||typeof r.ownerId!=='string'||!r.ownerId.trim()||r.ownerId.length>128||!hash(r.bundleHash)||!['preparing','installed'].includes(String(r.state))||!positive(r.version)||!stamp(r.createdAt)||!stamp(r.updatedAt)||r.updatedAt<r.createdAt)throw Error();return {id:r.id,ownerId:r.ownerId,source:identity(r.source),bundleHash:r.bundleHash,native:native(r.native),...(hasTrust?{trust:trust(r.trust),trustHash:hash(r.trustHash)?r.trustHash:(()=>{throw Error()})()}:{}),state:r.state as SkillInstallationRecord['state'],version:r.version,createdAt:r.createdAt,updatedAt:r.updatedAt}}catch{throw Error('技能安装记录格式不正确。')}}
function observation(v:unknown):SkillInstallObservation{try{const r=exact(v,['installationId','scope','state','reason','current']);if(!uuid(r.installationId)||r.scope!=='default-workspace'||!['available','shadowed','missing','disabled'].includes(String(r.state)))throw Error();if(r.reason!==undefined&&!['different-source','content-changed'].includes(String(r.reason)))throw Error();if(r.state==='available'&&r.reason!==undefined||(r.state==='missing'||r.state==='disabled')&&(r.reason!==undefined||r.current!==null))throw Error();let current:null|SkillInstallObservation['current']=null;if(r.current!==null){const x=exact(r.current,['name','description','modelInvocable','userInvocable','bodyHash','provider','source']);const base=native({name:x.name,description:x.description,modelInvocable:x.modelInvocable,userInvocable:x.userInvocable,bodyHash:x.bodyHash});if(typeof x.provider!=='string'||!x.provider||typeof x.source!=='string'||!x.source)throw Error();current={...base,provider:x.provider,source:x.source}}if(r.state==='available'&&!current||r.state==='shadowed'&&(!current||r.reason===undefined))throw Error();return {installationId:r.installationId,scope:'default-workspace',state:r.state as SkillInstallObservation['state'],...(r.reason?{reason:r.reason as 'different-source'|'content-changed'}:{}),current}}catch{throw Error('技能默认工作区观测格式不正确。')}}
function request(v:unknown):SkillInstallRequest{try{const r=exact(v,['requestId','source','expectedBundleHash','expectedTrustHash']);if(!uuid(r.requestId)||!hash(r.expectedBundleHash)||r.expectedTrustHash!==undefined&&!hash(r.expectedTrustHash))throw Error();return {requestId:r.requestId.toLowerCase(),source:sourceInput(r.source),expectedBundleHash:r.expectedBundleHash,...(r.expectedTrustHash?{expectedTrustHash:r.expectedTrustHash}:{})}}catch{throw Error('技能安装请求格式不正确。')}}
export type SkillInstallApi=ReturnType<typeof createSkillInstallApi>
export function createSkillInstallApi(call:Call,journal?:Journal){let pending:SkillInstallRequest|undefined,recoveryError:ReturnType<typeof recoveryStorageError>|undefined,busy=false;try{const raw=journal?.read();if(raw){if(raw.length>3000)throw Error();const r=exact(JSON.parse(raw),['schema','request']);if(r.schema!=='teloa.skill-install/v1')throw Error();pending=request(r.request)}}catch{recoveryError=recoveryStorageError()}const send=async()=>{if(recoveryError)throw recoveryError;if(!pending)throw Error('没有待核对的技能安装请求。');if(busy)throw Error('技能安装正在核对。');busy=true;try{journal?.write(JSON.stringify({schema:'teloa.skill-install/v1',request:pending}));const response=exact(await call('skill-installations/install',pending),['installation','source']),saved=record(response.installation),actualSource=identity(response.source);if(saved.bundleHash!==pending.expectedBundleHash||pending.expectedTrustHash!==undefined&&saved.trustHash!==pending.expectedTrustHash||!sourceMatches(pending.source,actualSource)||canonical(saved.source)!==canonical(actualSource))throw Error('技能安装响应与原请求不一致。');journal?.clear();pending=undefined;return saved}catch(e){if(e&&typeof e==='object'&&'rejected'in e&&e.rejected===true&&'code'in e&&['teloa/invalid-input','teloa/forbidden','teloa/version-conflict','teloa/source-unavailable'].includes(String(e.code))){journal?.clear();pending=undefined}throw e}finally{busy=false}};return {pending:()=>pending?structuredClone(pending):undefined,recoveryMessage:()=>recoveryError,
 /** 丢弃只清本地恢复记录，不通知服务端（规格 §二 D4）。 */
 discard(){const had=pending!==undefined||recoveryError!==undefined;try{journal?.clear()}catch{/* 清不掉不该变成第二道墙 */}pending=undefined;recoveryError=undefined;return had},
 preview:async(source:SkillInstallSourceInput)=>{const input=sourceInput(source),result=preview(await call('skill-installations/preview',{source:input}));if(!sourceMatches(input,result.source))throw Error('技能安装预览与请求来源不一致。');return result},install:async(v:SkillInstallRequest)=>{const next=request(v);if(pending&&JSON.stringify(pending)!==JSON.stringify(next))throw Error('请先核对原技能安装请求。');pending??=next;return send()},recover:send,get:async(id:string)=>{const installationId=normalizedUuid(id),result=record(await call('skill-installations/get',{installationId}));if(result.id!==installationId)throw Error('技能安装记录身份不一致。');return result},observe:async(id:string)=>{const installationId=normalizedUuid(id),result=observation(await call('skill-installations/observe',{installationId}));if(result.installationId!==installationId)throw Error('技能默认工作区观测身份不一致。');return result},list:async()=>{const r=exact(await call('skill-installations/list',{}),['items','usages']);if(!Array.isArray(r.items)||!Array.isArray(r.usages))throw Error('技能安装目录格式不正确。');const items=r.items.map(record),usages=r.usages.map(v=>{const x=exact(v,['loadId','itemInstanceId','installationId']);return {loadId:normalizedUuid(x.loadId),itemInstanceId:normalizedUuid(x.itemInstanceId),installationId:normalizedUuid(x.installationId)}});if(new Set(items.map(x=>x.id)).size!==items.length||new Set(items.map(x=>x.ownerId)).size>1||new Set(usages.map(x=>x.loadId+':'+x.itemInstanceId)).size!==usages.length||usages.some(x=>!items.some(item=>item.id===x.installationId)))throw Error('技能安装目录身份不一致。');return {items,usages}}}}
