import {createSkillInstallApi,type SkillInstallationRecord} from './skill-install-api.ts'
import {recoveryStorageError} from './recovery-error.ts'
export type SkillAvailability={installationId:string;ownerId:string;availability:'enabled'|'disabled';version:number;updatedAt:string}
export type SkillAvailabilityImpact={installation:{id:string;version:number;bundleHash:string;nativeName:string};availability:{value:'enabled'|'disabled';version:number};industryUsages:{loadId:string;itemInstanceId:string}[];roles:{roleId:string;version:number;state:'active'|'paused'|'retired';name:string}[];plans:{planId:string;version:number;state:'paused'|'active'|'archived';roleId:string}[];tasks:{taskId:string;version:number;state:string;assigneeRoleId:string|null}[];runs:{runId:string;taskId:string;roleId:string;state:string}[];ordinarySessions:{status:'unknown'}}
export type SkillAvailabilityPreview={installation:SkillInstallationRecord;availability:SkillAvailability;impact:SkillAvailabilityImpact;impactDigest:string;blockers:'installation-not-installed'[]}
export type SkillAvailabilityRequest={requestId:string;installationId:string;expectedVersion:number;expectedBundleHash:string;expectedImpactDigest:string;action:'disable'|'enable';reason?:string}
export type SkillAvailabilityReceipt={requestId:string;installationId:string;action:'disable'|'enable';reason:string;impact:SkillAvailabilityImpact;impactDigest:string;result:SkillAvailability;createdAt:string}
export type SkillAvailabilityChange={receipt:SkillAvailabilityReceipt;current:SkillAvailability}
type Journal={read:()=>string|null;write:(value:string)=>void;clear:()=>void}
const invalid=()=>Error('技能启停记录格式或身份不一致。')
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(key=>!keys.includes(key)))throw invalid();return value as Record<string,unknown>}
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(v)
const id=(v:unknown)=>{if(!uuid(v))throw invalid();return v.toLowerCase()}
const hash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const positive=(v:unknown):v is number=>Number.isSafeInteger(v)&&Number(v)>0&&Number(v)<=2147483647
const text=(v:unknown):v is string=>typeof v==='string'&&!!v.trim()
const stamp=(v:unknown):v is string=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v
const enabled=(v:unknown)=>v==='enabled'||v==='disabled'
function availability(value:unknown):SkillAvailability{const r=exact(value,['installationId','ownerId','availability','version','updatedAt']);if(!text(r.ownerId)||r.ownerId.length>128||!enabled(r.availability)||!positive(r.version)||!stamp(r.updatedAt))throw invalid();return {installationId:id(r.installationId),ownerId:r.ownerId,availability:r.availability as SkillAvailability['availability'],version:r.version,updatedAt:r.updatedAt}}
function impact(value:unknown):SkillAvailabilityImpact{
 const r=exact(value,['installation','availability','industryUsages','roles','plans','tasks','runs','ordinarySessions']),installation=exact(r.installation,['id','version','bundleHash','nativeName']),current=exact(r.availability,['value','version'])
 if(!uuid(installation.id)||!positive(installation.version)||!hash(installation.bundleHash)||!text(installation.nativeName)||!enabled(current.value)||!positive(current.version)||exact(r.ordinarySessions,['status']).status!=='unknown')throw invalid()
 const arrays=[['industryUsages',['loadId','itemInstanceId']],['roles',['roleId','version','state','name']],['plans',['planId','version','state','roleId']],['tasks',['taskId','version','state','assigneeRoleId']],['runs',['runId','taskId','roleId','state']]] as const
 for(const [name,keys] of arrays){const rows=r[name];if(!Array.isArray(rows)||rows.length>1000)throw invalid();const seen=new Set<string>();for(const value of rows){const item=exact(value,[...keys]);for(const key of keys){const field=item[key];if(key==='assigneeRoleId'){if(field!==null&&!uuid(field))throw invalid()}else if(key.endsWith('Id')){if(!uuid(field))throw invalid()}else if(key==='version'){if(!positive(field))throw invalid()}else if(!text(field))throw invalid()}if(name==='roles'&&!['active','paused','retired'].includes(String(item.state))||name==='plans'&&!['paused','active','archived'].includes(String(item.state)))throw invalid();const key=name==='industryUsages'?item.loadId+':'+item.itemInstanceId:String(item[keys[0]]);if(seen.has(key))throw invalid();seen.add(key)}}
 return structuredClone(r) as SkillAvailabilityImpact
}
function request(value:unknown):SkillAvailabilityRequest{const r=exact(value,['requestId','installationId','expectedVersion','expectedBundleHash','expectedImpactDigest','action','reason']);if(!positive(r.expectedVersion)||!hash(r.expectedBundleHash)||!hash(r.expectedImpactDigest)||!['enable','disable'].includes(String(r.action))||r.reason!==undefined&&(typeof r.reason!=='string'||r.reason.trim().length>4000))throw invalid();return {requestId:id(r.requestId),installationId:id(r.installationId),expectedVersion:r.expectedVersion,expectedBundleHash:r.expectedBundleHash,expectedImpactDigest:r.expectedImpactDigest,action:r.action as SkillAvailabilityRequest['action'],...(typeof r.reason==='string'&&r.reason.trim()?{reason:r.reason.trim()}:{})}}
function change(value:unknown,spec:SkillAvailabilityRequest):SkillAvailabilityChange{
 const r=exact(value,['receipt','current']),row=exact(r.receipt,['requestId','installationId','action','reason','impact','impactDigest','result','createdAt']),fixed=impact(row.impact),result=availability(row.result),current=availability(r.current)
 if(row.requestId!==spec.requestId||row.installationId!==spec.installationId||row.action!==spec.action||row.reason!==(spec.reason??'')||row.impactDigest!==spec.expectedImpactDigest||!stamp(row.createdAt)||fixed.installation.id!==spec.installationId||fixed.installation.bundleHash!==spec.expectedBundleHash||fixed.availability.version!==spec.expectedVersion||result.installationId!==spec.installationId||result.version!==spec.expectedVersion+1||result.availability!==(spec.action==='disable'?'disabled':'enabled')||current.installationId!==spec.installationId||current.ownerId!==result.ownerId||current.version<result.version||current.version===result.version&&JSON.stringify(current)!==JSON.stringify(result))throw invalid()
 return {receipt:{requestId:spec.requestId,installationId:spec.installationId,action:spec.action,reason:row.reason as string,impact:fixed,impactDigest:row.impactDigest as string,result,createdAt:row.createdAt},current}
}
export type SkillAvailabilityApi=ReturnType<typeof createSkillAvailabilityApi>
export function createSkillAvailabilityApi(call:(method:string,payload:unknown)=>Promise<unknown>,journal?:Journal){
 let pending:SkillAvailabilityRequest|undefined,recoveryError:ReturnType<typeof recoveryStorageError>|undefined,busy=false
 try{const raw=journal?.read();if(raw){if(raw.length>7000)throw invalid();const saved=exact(JSON.parse(raw),['schema','request']);if(saved.schema!=='teloa.skill-availability/v1')throw invalid();pending=request(saved.request)}}catch{recoveryError=recoveryStorageError()}
 const send=async()=>{if(recoveryError)throw recoveryError;if(!pending)throw Error('没有待核对的技能启停请求。');if(busy)throw Error('原技能启停请求正在核对。');const spec=structuredClone(pending);busy=true;try{journal?.write(JSON.stringify({schema:'teloa.skill-availability/v1',request:spec}));const result=change(await call('skill-availability/change',spec),spec);journal?.clear();pending=undefined;return result}catch(error){if(error&&typeof error==='object'&&'rejected'in error&&error.rejected===true&&'code'in error&&['teloa/invalid-input','teloa/forbidden','teloa/version-conflict','teloa/conflict','teloa/source-unavailable'].includes(String(error.code))){journal?.clear();pending=undefined}throw error}finally{busy=false}}
 return {
  pending:()=>pending?structuredClone(pending):undefined,recoveryMessage:()=>recoveryError,
  /** 丢弃只清本地恢复记录，不通知服务端（规格 §二 D4）。 */
  discard(){const had=pending!==undefined||recoveryError!==undefined;try{journal?.clear()}catch{/* 清不掉不该变成第二道墙 */}pending=undefined;recoveryError=undefined;return had},
  get:async(installationId:string)=>{const normalized=id(installationId),result=availability(await call('skill-availability/get',{installationId:normalized}));if(result.installationId!==normalized)throw invalid();return result},
  preview:async(installationId:string):Promise<SkillAvailabilityPreview>=>{const normalized=id(installationId),r=exact(await call('skill-availability/preview',{installationId:normalized}),['installation','availability','impact','impactDigest','blockers']);const installed=await createSkillInstallApi(async()=>r.installation).get(normalized),current=availability(r.availability),fixed=impact(r.impact);if(current.installationId!==normalized||installed.ownerId!==current.ownerId||fixed.installation.id!==normalized||fixed.installation.version!==installed.version||fixed.installation.bundleHash!==installed.bundleHash||fixed.installation.nativeName!==installed.native.name||fixed.availability.version!==current.version||fixed.availability.value!==current.availability||!hash(r.impactDigest)||!Array.isArray(r.blockers)||r.blockers.some(v=>v!=='installation-not-installed')||new Set(r.blockers).size!==r.blockers.length||(installed.state!=='installed')!==r.blockers.includes('installation-not-installed'))throw invalid();return {installation:installed,availability:current,impact:fixed,impactDigest:r.impactDigest,blockers:r.blockers as SkillAvailabilityPreview['blockers']}},
  change:async(value:SkillAvailabilityRequest)=>{const next=request(value);if(pending&&JSON.stringify(next)!==JSON.stringify(pending))throw Error('请先核对原技能启停请求。');pending??=next;return send()},
  recover:async(installationId:string)=>{if(pending?.installationId!==installationId)throw Error('待核对请求不属于当前安装，请打开原安装。');return send()},
 }
}
