import {ArrowRight} from 'lucide-react'
import {useEffect,useReducer,useRef,useState} from 'react'
import type {SkillInstallationRecord,SkillInstallSourceIdentity} from './skill-install-api.js'
import type {MarketContentApi} from './market-content-api.js'
import type {MarketItem} from './market-preview.js'
import type {SkillUpgradeApi,SkillUpgradeFile,SkillUpgradePreview} from './skill-upgrade-api.js'
import {reduceSkillUpgradeView,upgradeCandidates} from './skill-upgrade-state.js'
import css from './RealSkillInstallations.module.css'
import {useI18n} from './i18n/provider.js'
import {localizeWorkError} from './i18n/errors.js'
import {localizedMarketItemCopy} from './market-home-presentation.js'

const version=(source:SkillInstallSourceIdentity)=>source.kind==='industry-public'?source.sourceResourceVersion:source.resourceVersion
const resource=(source:SkillInstallSourceIdentity)=>source.kind==='industry-public'?source.sourceResourceId:source.resourceId
export function SkillUpgradePanel({api,marketContentApi,record,revision:externalRevision=0,onChanged}:{api:SkillUpgradeApi;marketContentApi:MarketContentApi;record:SkillInstallationRecord;revision?:number;onChanged?:(installationId:string)=>void}){
 const {locale,t}=useI18n(),message=(error:unknown)=>localizeWorkError(locale,error)
 const [items,setItems]=useState<MarketItem[]>([]),[directoryError,setDirectoryError]=useState(''),[directoryLoading,setDirectoryLoading]=useState(true),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[revision,setRevision]=useState(0)
 const [migrations,setMigrations]=useState<string[]>([]),[applying,setApplying]=useState(false),[applyError,setApplyError]=useState(''),[applied,setApplied]=useState(''),[discarded,setDiscarded]=useState(false)
 const [view,dispatch]=useReducer(reduceSkillUpgradeView,{contentId:'',generation:0,loading:false,error:''}),generation=useRef(0)
 const recoveryError=api.recoveryMessage()
 useEffect(()=>{let live=true;setDirectoryLoading(true);setDirectoryError('');void marketContentApi.list().then(values=>{if(live)setItems(values)},error=>{if(live)setDirectoryError(message(error))}).finally(()=>{if(live)setDirectoryLoading(false)});return()=>{live=false}},[marketContentApi,revision])
 useEffect(()=>{const token=++generation.current;dispatch({type:'target',contentId:selected,generation:token});if(selected)void api.preview({installationId:record.id,target:{kind:'atomic',contentId:selected}}).then(preview=>{if(token===generation.current)dispatch({type:'result',generation:token,preview})},error=>{if(token===generation.current)dispatch({type:'error',generation:token,error:message(error)})});return()=>{generation.current++}},[api,record.id,record.version,record.bundleHash,selected,revision,externalRevision])
 const candidates=upgradeCandidates(items,query),allCandidates=upgradeCandidates(items,''),chosen=allCandidates.find(item=>item.contentStorage?.contentId===selected),preview=view.preview
 const choose=(contentId:string)=>{generation.current++;dispatch({type:'target',contentId,generation:generation.current});setSelected(contentId);setMigrations([]);setApplyError('');setApplied('')}
 const appliedMessage=(recovered:boolean,id:string,count:number)=>`${t(recovered?'market.skill.upgrade.recovered.installationPrefix':'market.skill.upgrade.applied.installationPrefix')} ${id}${t('market.skill.upgrade.applied.migrationPrefix')} ${count} ${t('market.skill.upgrade.applied.migrationSuffix')}`
 const apply=async()=>{if(!preview||preview.blockers.length||preview.target.source.kind!=='atomic')return;setApplying(true);setApplyError('');setApplied('');try{const chosen=new Set(migrations),result=await api.apply({currentInstallationId:record.id,target:{kind:'atomic',contentId:preview.target.source.contentId},expectedTargetBundleHash:preview.target.bundleHash,...(preview.target.trustHash?{expectedTargetTrustHash:preview.target.trustHash}:{}),industryUsages:preview.current.impact.industryUsages.filter(item=>chosen.has(item.loadId+':'+item.itemInstanceId))});setApplied(appliedMessage(false,result.installation.id,result.migratedIndustryUsages.length));onChanged?.(result.installation.id)}catch(error){setApplyError(message(error))}finally{setApplying(false)}}
 const recover=async()=>{setApplying(true);setApplyError('');try{const result=await api.recover();setApplied(appliedMessage(true,result.installation.id,result.migratedIndustryUsages.length));onChanged?.(result.installation.id)}catch(error){setApplyError(message(error))}finally{setApplying(false)}}
 return <section className={css.sheet} aria-label={t("market.skill.upgrade.skill.real.upgrade.preview")}><h3>{t("market.skill.upgrade.version.and.file.differences")}</h3><p>{t("market.skill.upgrade.select.a.new.saved.version.of.skill.to")}</p>
  {recoveryError&&<p role="alert">{localizeWorkError(locale,recoveryError)} {t('recovery.nextStep')}</p>}{recoveryError&&<button type="button" onClick={()=>{api.discard();setDiscarded(true)}}>{t('recovery.discard')}</button>}{discarded&&<p role="status">{t('recovery.discarded')}</p>}{api.pending()&&<div className={css.buttons}><button type="button" disabled={applying} onClick={()=>void recover()}>{applying?t("market.skill.upgrade.restored"):t("market.skill.upgrade.restore.last.upgrade")}</button></div>}
  <div className={css.buttons}><button type="button" disabled={directoryLoading||view.loading} onClick={()=>setRevision(value=>value+1)}>{t("market.skill.upgrade.upgrade.destination.directory")}</button></div>
  {directoryLoading&&<p role="status">{t("market.skill.upgrade.reading.your.own.fixed.skill.directory")}</p>}{directoryError&&<p role="alert">{directoryError} {t("market.skill.upgrade.the.directory.shown.is.the.last.read.result")}</p>}
  <div className={css.upgradeFields}><label>{t("market.skill.upgrade.search.target")}<input aria-label={t("market.skill.upgrade.search.for.skill.upgrade.target")} placeholder={t("market.skill.upgrade.name.or.version")} value={query} onChange={event=>setQuery(event.target.value)}/></label><label>{t("market.skill.upgrade.select.target.version")}<select aria-label={t("market.skill.upgrade.skill.upgrade.target.version")} value={selected} onChange={event=>choose(event.target.value)}><option value="">{t("market.skill.upgrade.select.saved.skill")}</option>{selected&&!candidates.some(item=>item.contentStorage?.contentId===selected)&&<option value={selected}>{chosen?localizedMarketItemCopy(chosen,locale).title+' · '+chosen.version:t("market.skill.upgrade.the.original.target.is.no.longer.in.the")}</option>}{candidates.map(item=><option key={item.contentStorage!.contentId} value={item.contentStorage!.contentId}>{localizedMarketItemCopy(item,locale).title} · {item.version} · {item.hash?.slice(0,10)}</option>)}</select></label></div>
  {!directoryLoading&&!directoryError&&!candidates.length&&<p>{allCandidates.length?t("market.skill.upgrade.there.is.no.match.please.adjust.the.name"):t("market.skill.upgrade.there.are.no.saved.atoms.skill.save.the")}</p>}
  <p>{t("market.skill.upgrade.the.current.selector.only.records.the.real.saved")}</p>
  {view.loading&&<p role="status">{t("market.skill.upgrade.reading.fixed.files.and.checking.discrepancies")}{preview?t("market.skill.upgrade.below.is.a.preview.of.last.success"):''}</p>}
  {view.error&&<p role="alert">{view.error}{preview?t("market.skill.upgrade.other.organiser"):''}<button type="button" disabled={view.loading} onClick={()=>setRevision(value=>value+1)}>{t("market.skill.upgrade.retry.upgrade.preview")}</button></p>}
  {preview&&<><UpgradeComparison preview={preview}/><section className={css.migration} aria-label={t("market.skill.upgrade.select.industry.reference.migration.range")}><h4>{t("market.skill.upgrade.submit.version.switch")}</h4><p>{t("market.skill.upgrade.the.current.global.version.will.switch.to.the")}</p>{preview.current.impact.industryUsages.length?<ul>{preview.current.impact.industryUsages.map(item=>{const key=item.loadId+':'+item.itemInstanceId;return <li key={key}><label><input type="checkbox" checked={migrations.includes(key)} disabled={applying} onChange={event=>setMigrations(values=>event.target.checked?[...values,key].sort():values.filter(value=>value!==key))}/>{t("market.skill.upgrade.load")} {item.loadId} {t("market.skill.upgrade.catalogue.items")} {item.itemInstanceId}</label></li>})}</ul>:<p>{t("market.skill.upgrade.there.is.no.industry.reference.for.the.current")}</p>}<div className={css.buttons}><button type="button" disabled={applying||preview.blockers.length>0} onClick={()=>void apply()}>{applying?t("market.skill.upgrade.installing.and.switching"):t("market.skill.upgrade.install.and.switch.global.versions")}</button></div>{applyError&&<p role="alert">{applyError}</p>}{applied&&<p role="status">{applied}</p>}</section></>}
 </section>
}
function UpgradeComparison({preview}:{preview:SkillUpgradePreview}){
 const {t}=useI18n(),sourceLabel=(source:SkillInstallSourceIdentity)=>source.kind==='atomic'?t('market.skill.upgrade.source.atomic'):source.kind==='industry-public'?t('market.skill.upgrade.source.public'):t('market.skill.upgrade.source.industry')
 const blockLabels={'installation-not-installed':t('market.skill.upgrade.block.incomplete'),'same-source':t('market.skill.upgrade.block.sameSource'),'native-name-mismatch':t('market.skill.upgrade.block.nameMismatch')}
 const old=preview.current.installation,next=preview.target,impact=preview.current.impact,changed=preview.files.filter(file=>file.change!=='unchanged'),unchanged=preview.files.filter(file=>file.change==='unchanged')
 return <section aria-label={t("market.skill.upgrade.fixed.skill.upgrade.difference")}><h4>{t("market.skill.upgrade.current.status.of.this.preview.read")}</h4><p>{preview.current.availability.availability==='enabled'?t("market.skill.upgrade.enabled"):t("market.skill.upgrade.disabled")} {t("market.skill.upgrade.status.version")} {preview.current.availability.version} {t("market.skill.upgrade.installation.of.record.versions")} {old.version}</p>
  <dl><dt>{t("market.skill.upgrade.current.fixed.version")}</dt><dd>{sourceLabel(old.source)} · {resource(old.source)} · {version(old.source)}</dd><dt>{t("market.skill.upgrade.target.fixed.version")}</dt><dd>{sourceLabel(next.source)} · {resource(next.source)} · {version(next.source)}</dd><dt>{t("market.skill.upgrade.current.package.summary")}</dt><dd>{old.bundleHash}</dd><dt>{t("market.skill.upgrade.objective.package.summary")}</dt><dd>{next.bundleHash}</dd></dl>
  <details><summary>{t("market.skill.upgrade.check.for.fixed.source.identity.on.both.sides")}</summary><p>{t("market.skill.upgrade.current.installation")}{old.id}</p><p>{t("market.skill.upgrade.current.content")}{old.source.contentId} · {old.source.contentHash}</p>{old.source.kind==='industry-public'&&<p>{t("market.skill.upgrade.current.public.sources")}{old.source.sourceContentId} · {old.source.sourceContentHash}</p>}<p>{t("market.skill.upgrade.objectives")}{next.source.contentId} · {next.source.contentHash}</p></details>
  <p>{preview.sameResourceId?t("market.skill.upgrade.the.resource.markers.are.identical.on.both.sides"):t("market.skill.upgrade.the.resource.identifiers.are.different.on.both.sides")}</p>
  {preview.blockers.map(code=><p key={code} role="alert">{blockLabels[code]}</p>)}
  <h4>{t("market.skill.upgrade.native.definition.and.call.conditions")}</h4><dl><dt>{t("market.skill.upgrade.native.name")}</dt><dd>{old.native.name} <ArrowRight size={12} role="img" aria-label={t("presentation.changeTo")} className={css.changeArrow}/> {next.native.name}</dd><dt>{t("market.skill.upgrade.annotations")}</dt><dd>{old.native.description} <ArrowRight size={12} role="img" aria-label={t("presentation.changeTo")} className={css.changeArrow}/> {next.native.description}</dd><dt>{t("market.skill.upgrade.model.call")}</dt><dd>{old.native.modelInvocable?t("market.skill.upgrade.allow"):t("market.skill.upgrade.not.permitted")} <ArrowRight size={12} role="img" aria-label={t("presentation.changeTo")} className={css.changeArrow}/> {next.native.modelInvocable?t("market.skill.upgrade.allow"):t("market.skill.upgrade.not.permitted")}</dd><dt>{t("market.skill.upgrade.user.call")}</dt><dd>{old.native.userInvocable?t("market.skill.upgrade.allow"):t("market.skill.upgrade.not.permitted")} <ArrowRight size={12} role="img" aria-label={t("presentation.changeTo")} className={css.changeArrow}/> {next.native.userInvocable?t("market.skill.upgrade.allow"):t("market.skill.upgrade.not.permitted")}</dd><dt>{t("market.skill.upgrade.parsing.body.summary")}</dt><dd>{old.native.bodyHash} <ArrowRight size={12} role="img" aria-label={t("presentation.changeTo")} className={css.changeArrow}/> {next.native.bodyHash}</dd></dl>
  <p>{t("market.skill.upgrade.the.body.summary.corresponds.to.the.parsed.skill")}</p>
  <h4>{t("market.skill.upgrade.full.file.differences")}{preview.files.length} {t("market.skill.upgrade.item")}</h4><p>{t("market.skill.upgrade.add")} {preview.files.filter(file=>file.change==='added').length} {t("market.skill.upgrade.remove")} {preview.files.filter(file=>file.change==='removed').length} {t("market.skill.upgrade.changes")} {preview.files.filter(file=>file.change==='modified').length} {t("market.skill.upgrade.unchanged")} {unchanged.length}</p>
  <FileDifferences files={changed}/>{unchanged.length>0&&<details><summary>{t('market.skill.upgrade.unchangedSummary',{count:unchanged.length})}</summary><FileDifferences files={unchanged}/></details>}
  <h4>{t("market.skill.upgrade.existing.usage.relationships.and.historical.reservations")}</h4><p>{t("market.skill.upgrade.the.following.is.a.true.impact.snapshot.of")}</p>
  <ImpactRows title={t("market.skill.upgrade.industry.reference")} rows={impact.industryUsages.map(row=>({id:row.loadId+':'+row.itemInstanceId,text:t("market.skill.upgrade.load")+row.loadId+t("market.skill.upgrade.catalogue.items")+row.itemInstanceId}))}/>
  <ImpactRows title={t("market.skill.upgrade.position")} rows={impact.roles.map(row=>({id:row.roleId,text:row.name+' · '+row.state+' · '+row.roleId}))}/>
  <ImpactRows title={t("market.skill.upgrade.planned")} rows={impact.plans.map(row=>({id:row.planId,text:row.planId+' · '+row.state}))}/>
  <ImpactRows title={t("market.skill.upgrade.tasks")} rows={impact.tasks.map(row=>({id:row.taskId,text:row.taskId+' · '+row.state}))}/>
  <ImpactRows title={t("market.skill.upgrade.fixed.execution.reference")} rows={impact.runs.map(row=>({id:row.runId,text:row.runId+' · '+row.state+t("market.skill.upgrade.taskPrefix")+row.taskId}))}/>
  <p>{t("market.skill.upgrade.the.scope.of.use.of.regular.primary.sessions")}</p>
 </section>
}
function FileDifferences({files}:{files:SkillUpgradeFile[]}){const {t}=useI18n();const labels={added:t('market.skill.upgrade.change.added'),removed:t('market.skill.upgrade.change.removed'),modified:t('market.skill.upgrade.change.modified'),unchanged:t('market.skill.upgrade.change.unchanged')};return <ul>{files.map(file=><li key={file.path}><strong>{file.path} · {labels[file.change]}</strong><span>{t('market.skill.upgrade.file.before',{value:file.before?file.before.size+' '+t('market.skill.upgrade.file.bytes')+' · '+file.before.hash:t('market.skill.upgrade.file.missing')})}</span><span>{t('market.skill.upgrade.file.after',{value:file.after?file.after.size+' '+t('market.skill.upgrade.file.bytes')+' · '+file.after.hash:t('market.skill.upgrade.file.missing')})}</span></li>)}</ul>}
function ImpactRows({title,rows}:{title:string;rows:{id:string;text:string}[]}){const {t}=useI18n();return <details><summary>{t('market.skill.upgrade.impact.summary',{title,count:rows.length})}</summary>{rows.length?<ul>{rows.map(row=><li key={row.id}>{row.text}</li>)}</ul>:<p>{t('market.skill.upgrade.impact.none')}</p>}</details>}
