import type {SkillInstallationRecord,SkillInstallObservation} from './skill-install-api.js'
import css from './MarketPage.module.css'
import {useI18n} from './i18n/provider.js'

export function SkillInstallationStatus({record,observation,pending,error,refresh,install,recover,observe,reuse,reuseLabel,continueInstall}:{record?:SkillInstallationRecord;observation?:SkillInstallObservation;pending:boolean;error?:string;refresh?:()=>void;install?:()=>void;recover?:()=>void;observe?:()=>void;reuse?:()=>void;reuseLabel?:string;continueInstall?:()=>void}){
 const {t}=useI18n()
 const observed=observation?.state==='available'?t('market.skill.status.available'):observation?.state==='shadowed'?(observation.reason==='different-source'?t('market.skill.status.shadowedSource'):t('market.skill.status.changed')):observation?.state==='disabled'?t('market.skill.status.disabled'):observation?.state==='missing'?t('market.skill.status.missing'):undefined
 const state=record?.state==='installed'?(observation?t('market.skill.state.installed'):t('market.skill.status.installedUnverified')):record?.state==='preparing'||pending?t('market.skill.state.review'):t('market.skill.status.notInstalled')
 return <section className={css.sheet} aria-label={t('market.skill.status.aria')}><h3>{t('market.skill.currentHost')}</h3><p>{state}</p>{record&&<><p>{record.native.name} · {t('market.skill.directory.recordVersion',{version:record.version})}</p><small>{t('market.skill.status.contentHash',{hash:record.bundleHash})}</small></>}{reuse&&<p>{t('market.skill.status.notLinked')}</p>}{observed&&<p role="status">{observed}</p>}<p>{t('market.skill.status.boundary')}</p>{error&&<p role="alert">{error} {refresh&&<button type="button" onClick={refresh}>{t('market.skill.status.refresh')}</button>}</p>}<div className={css.buttons}>{pending&&recover?<button type="button" onClick={recover}>{t('market.skill.status.recover')}</button>:reuse?<button type="button" onClick={reuse}>{reuseLabel}</button>:continueInstall?<button type="button" onClick={continueInstall}>{t('market.skill.status.continue')}</button>:!record&&install?<button type="button" onClick={install}>{t('market.skill.status.install')}</button>:null}{record?.state==='installed'&&observe&&<button type="button" onClick={observe}>{t('market.skill.status.observe')}</button>}</div></section>
}
