import {useEffect,useState} from 'react'
import type {TaskRunFlow} from '@teloa/contract'
import type {ConfirmedFlowApi} from './flow-api.js'
import {useI18n} from './i18n/provider.js'
import {localizeWorkError} from './i18n/errors.js'
import css from './TaskPage.module.css'
type Sources=Awaited<ReturnType<ConfirmedFlowApi['sources']>>
/** 沿任务详情原有流程区域确认；普通顺序工作继续使用 Goal。 */
export function TaskRunFlowSetup({runId,api,flow,changed}:{runId:string;api:ConfirmedFlowApi;flow?:TaskRunFlow;changed:()=>void}){
 const {t,locale}=useI18n(),[mode,setMode]=useState<'parallel'|'checkpoint'|'material'>('parallel'),[sources,setSources]=useState<Sources>(),[sourceId,setSourceId]=useState(''),[stepId,setStepId]=useState(''),[left,setLeft]=useState(''),[right,setRight]=useState(''),[final,setFinal]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const waits=flow?.steps.filter(s=>s.state==='waiting'&&(s.kind==='human_checkpoint'||s.kind==='wait_external'))??[],step=waits.find(s=>s.id===stepId)??waits[0],binding=sources?.bindings.find(s=>s.stepId===step?.id),kind=flow?(step?.kind==='human_checkpoint'?'approval-result':'material-version'):mode==='checkpoint'?'approval-result':'material-version',items=kind==='approval-result'?sources?.approvals:sources?.materials
 useEffect(()=>{let active=true;setSources(undefined);setSourceId('');void api.sources(runId).then(value=>{if(active)setSources(value)},cause=>{if(active)setError(localizeWorkError(locale,cause))});return()=>{active=false}},[api,runId,flow?.flowId,flow?.updatedAt,locale])
 const act=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await work();setConfirmed(false);changed()}catch(cause){setError(localizeWorkError(locale,cause))}finally{setBusy(false)}}
 if(flow&&!waits.length&&!api.pending())return null
 return <details className={css.runContext}><summary>{t(flow?'planWork.flow.rebind':'planWork.flow.setup')}</summary><p>{t('planWork.flow.boundary')}</p>{error&&<p role="alert">{error}</p>}{api.recoveryMessage()&&<p role="alert">{localizeWorkError(locale,api.recoveryMessage())}</p>}{api.pending()&&<div className={css.buttons}><span>{t('planWork.flow.unknown')}</span><button type="button" disabled={busy} onClick={()=>void act(()=>api.recover())}>{t('planWork.recover')}</button><button type="button" disabled={busy} onClick={()=>{api.discard();setError('')}}>{t('recovery.discard')}</button></div>}
 <form onSubmit={event=>{event.preventDefault();if(!confirmed||api.pending())return;void act(async()=>{if(flow){if(!step||!binding||!sourceId)throw Error('请选择当前等待的真实来源。');return api.rebind({runId,flowId:flow.flowId,stepId:step.id,expectedAttempts:step.attempts,expectedBindingVersion:binding.version,sourceKind:kind,sourceId})}const work=(id:string,inputSummary:string,dependsOn:string[]=[])=>({id,title:inputSummary.slice(0,120),kind:'work' as const,dependsOn,inputSummary});return api.create(runId,{definitionVersion:1,steps:mode==='parallel'?[work('left',left),work('right',right),work('join',final,['left','right'])]:[{id:'wait',title:final.slice(0,120),kind:mode==='checkpoint'?'human_checkpoint':'wait_external',dependsOn:[],inputSummary:final},work('continue',left,['wait'])]},mode==='parallel'?[]:[{stepId:'wait',sourceKind:kind,sourceId}])})}}>
 {!flow?<><label>{t('planWork.flow.kind')}<select disabled={busy||!!api.pending()} value={mode} onChange={event=>{setMode(event.target.value as typeof mode);setSourceId('');setConfirmed(false)}}><option value="parallel">{t('planWork.flow.parallel')}</option><option value="checkpoint">{t('taskExecution.flow.kind.review')}</option><option value="material">{t('planWork.flow.material')}</option></select></label>{mode==='parallel'&&<label>{t('planWork.flow.second')}<textarea required maxLength={4000} value={right} disabled={busy} onChange={event=>setRight(event.target.value)}/></label>}<label>{t(mode==='parallel'?'planWork.flow.first':'planWork.flow.after')}<textarea required maxLength={4000} value={left} disabled={busy} onChange={event=>setLeft(event.target.value)}/></label><label>{t(mode==='parallel'?'planWork.flow.join':'planWork.flow.wait')}<textarea required maxLength={4000} value={final} disabled={busy} onChange={event=>setFinal(event.target.value)}/></label></>:<label>{t('planWork.flow.wait')}<select value={step?.id??''} disabled={busy} onChange={event=>{setStepId(event.target.value);setSourceId('');setConfirmed(false)}}>{waits.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>}
 {(flow||mode!=='parallel')&&<label>{t('planWork.flow.source')}<select required disabled={busy||!sources} value={sourceId} onChange={event=>{setSourceId(event.target.value);setConfirmed(false)}}><option value="">{t('planWork.flow.choose')}</option>{items?.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>}
 <label><input type="checkbox" checked={confirmed} disabled={busy||!!api.pending()} onChange={event=>setConfirmed(event.target.checked)}/>{t('planWork.flow.confirm')}</label><button type="submit" disabled={busy||!confirmed||!!api.pending()||!!api.recoveryMessage()||!!flow&&!binding}>{t(flow?'planWork.flow.rebind':'planWork.flow.save')}</button></form></details>
}
