import {readWorkBudgetPolicy,taskInput,workUuid,type WorkBudgetPolicy} from '@teloa/contract'
import {recoveryStorageError} from './recovery-error.ts'
type Journal={read:()=>string|null;write:(v:string)=>void;clear:()=>void}
export type BudgetView={version:number;policy:WorkBudgetPolicy;usedTokens:number;usedRounds:number;concurrent:number;moneyMinorUnits:null;budgetAccountId?:string}
type Command={kind:'account'|'owner';requestId:string;expectedVersion:number;policy:WorkBudgetPolicy;budgetAccountId?:string}
const positive=(v:unknown):v is number=>Number.isSafeInteger(v)&&Number(v)>0
function readCommand(value:unknown):Command{const r=taskInput(value,['kind','requestId','expectedVersion','policy','budgetAccountId']);if(!['account','owner'].includes(String(r.kind))||!workUuid(r.requestId)||!positive(r.expectedVersion)||r.kind==='account'&&!workUuid(r.budgetAccountId)||r.kind==='owner'&&r.budgetAccountId!==undefined)throw Error('额度恢复请求不正确。');return {...r,policy:readWorkBudgetPolicy(r.policy)} as Command}
function readView(value:unknown,id?:string):BudgetView{const r=taskInput(value,['budgetAccountId','version','policy','usedTokens','usedRounds','concurrent','moneyMinorUnits']);if(!positive(r.version)||['usedTokens','usedRounds','concurrent'].some(k=>!Number.isSafeInteger(r[k])||Number(r[k])<0)||r.moneyMinorUnits!==null||(id===undefined?r.budgetAccountId!==undefined:r.budgetAccountId!==id))throw Error('额度回包不属于当前工作或格式不正确。');return {...r,policy:readWorkBudgetPolicy(r.policy)} as BudgetView}
export function createWorkBudgetApi(call:(method:string,payload:unknown)=>Promise<unknown>,journal?:Journal,newId=()=>crypto.randomUUID()){
 let pending:Command|undefined,error:Error|undefined,busy=false
 try{const raw=journal?.read();if(raw){const r=taskInput(JSON.parse(raw),['schema','request']);if(r.schema!=='teloa.work-budget-command/v1')throw Error();pending=readCommand(r.request)}}catch{error=recoveryStorageError()}
 const clear=()=>{journal?.clear();pending=undefined},readAccount=async(id:string)=>readView(await call('work-budgets/read',{budgetAccountId:id}),id),readOwner=async()=>readView(await call('work-budgets/owner/read',{}))
 const send=async()=>{if(error)throw error;if(!pending||busy)throw Error('请先核对原额度请求。');busy=true;const command=pending;try{journal?.write(JSON.stringify({schema:'teloa.work-budget-command/v1',request:command}));const {kind,...request}=command,r=taskInput(await call(kind==='owner'?'work-budgets/owner/configure':'work-budgets/configure',request),['budgetAccountId','version','policy']),policy=readWorkBudgetPolicy(r.policy);if(r.version!==command.expectedVersion+1||Object.entries(command.policy).some(([key,value])=>JSON.stringify(value)!==JSON.stringify(policy[key as keyof WorkBudgetPolicy]))||(kind==='account'?r.budgetAccountId!==command.budgetAccountId:r.budgetAccountId!==undefined))throw Error('额度回执与原请求不一致。');const current=kind==='owner'?await readOwner():await readAccount(command.budgetAccountId!);if(current.version<Number(r.version))throw Error('额度状态尚未反映原回执。');clear();return current}catch(cause){if(cause&&typeof cause==='object'&&'rejected'in cause&&cause.rejected===true)clear();throw cause}finally{busy=false}}
 return {read:readAccount,readOwner,pending:()=>pending?structuredClone(pending):undefined,recoveryMessage:()=>error,recover:send,discard(){clear();error=undefined},configure(current:BudgetView,policy:WorkBudgetPolicy){if(pending)throw Error('请先核对原额度请求。');pending=readCommand({kind:current.budgetAccountId?'account':'owner',requestId:newId(),expectedVersion:current.version,policy,...(current.budgetAccountId?{budgetAccountId:current.budgetAccountId}:{})});return send()}}
}
export type WorkBudgetApi=ReturnType<typeof createWorkBudgetApi>
