import {useEffect,useState} from 'react'
import type {WorkBudgetPolicy} from '@teloa/contract'
import type {BudgetView,WorkBudgetApi} from './work-budget-api.js'
import {useI18n} from './i18n/provider.js'
import {localizeWorkError} from './i18n/errors.js'
import css from './TaskPage.module.css'
const keys=['maxGoalRounds','maxTokens','maxConcurrent','maxElapsedMs','maxRetries','stagnationRounds'] as const
const labels={'maxGoalRounds':'planWork.rounds','maxTokens':'planWork.tokens','maxConcurrent':'planWork.concurrent','maxElapsedMs':'planWork.elapsed','maxRetries':'planWork.retries','stagnationRounds':'planWork.stagnation'} as const
export function WorkBudgetPanel({api,budgetAccountId}:{api:WorkBudgetApi;budgetAccountId:string}){
 const {t,locale}=useI18n(),[account,setAccount]=useState<BudgetView>(),[owner,setOwner]=useState<BudgetView>(),[scope,setScope]=useState<'account'|'owner'>('account'),[policy,setPolicy]=useState<WorkBudgetPolicy>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),current=scope==='account'?account:owner
 const accept=async(value:BudgetView)=>{if(value.budgetAccountId&&value.budgetAccountId!==budgetAccountId){const [a,o]=await Promise.all([api.read(budgetAccountId),api.readOwner()]);setAccount(a);setOwner(o)}else if(value.budgetAccountId)setAccount(value);else setOwner(value)}
 useEffect(()=>{let live=true;setAccount(undefined);setOwner(undefined);setError('');void Promise.all([api.read(budgetAccountId),api.readOwner()]).then(([a,o])=>{if(live){setAccount(a);setOwner(o)}},cause=>{if(live)setError(localizeWorkError(locale,cause))});return()=>{live=false}},[api,budgetAccountId,locale])
 useEffect(()=>{setPolicy(current?.policy);setConfirmed(false)},[current?.version,scope,budgetAccountId])
 const act=async(work:()=>Promise<BudgetView>)=>{if(busy)return;setBusy(true);setError('');try{await accept(await work());setConfirmed(false)}catch(cause){setError(localizeWorkError(locale,cause))}finally{setBusy(false)}}
 const refresh=()=>act(async()=>{const [a,o]=await Promise.all([api.read(budgetAccountId),api.readOwner()]);setOwner(o);return a})
 return <details className={css.block}><summary>{t('planWork.budget.title')}</summary><p>{t('planWork.budget.boundary')}</p>{account&&<p>{t('planWork.budget.account')}：{t('planWork.budget.used',{tokens:account.usedTokens,tokenLimit:account.policy.maxTokens,rounds:account.usedRounds,roundLimit:account.policy.maxGoalRounds,concurrent:account.concurrent,concurrentLimit:account.policy.maxConcurrent})}</p>}{owner&&<p>{t('planWork.budget.owner')}：{t('planWork.budget.used',{tokens:owner.usedTokens,tokenLimit:owner.policy.maxTokens,rounds:owner.usedRounds,roundLimit:owner.policy.maxGoalRounds,concurrent:owner.concurrent,concurrentLimit:owner.policy.maxConcurrent})}</p>}{error&&<p role="alert">{error}</p>}{api.recoveryMessage()&&<p role="alert">{localizeWorkError(locale,api.recoveryMessage())}</p>}{api.pending()&&<div className={css.buttons}><span>{t('planWork.budget.unknown')}</span><button type="button" disabled={busy} onClick={()=>void act(()=>api.recover())}>{t('planWork.recover')}</button><button type="button" disabled={busy} onClick={()=>{api.discard();setError('')}}>{t('recovery.discard')}</button></div>}
 <button type="button" disabled={busy} onClick={()=>void refresh()}>{t('taskExecution.refresh')}</button>
 {current&&policy&&<form className={css.form} onSubmit={event=>{event.preventDefault();if(!confirmed||api.pending()||busy)return;void act(()=>api.configure(current,policy))}}><label>{t('planWork.budget.scope')}<select disabled={busy} value={scope} onChange={event=>setScope(event.target.value as typeof scope)}><option value="account">{t('planWork.budget.account')}</option><option value="owner">{t('planWork.budget.owner')}</option></select></label>{keys.map(key=><label key={key}>{t(labels[key])}<input required type="number" min={1} step={1} disabled={busy} value={key==='maxElapsedMs'?policy[key]/60000:policy[key]} onChange={event=>{const value=Number(event.target.value);setPolicy({...policy,[key]:key==='maxElapsedMs'?value*60000:value});setConfirmed(false)}}/></label>)}<label><input required type="checkbox" disabled={busy||!!api.pending()} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t('planWork.budget.confirm')}</label><button type="submit" disabled={busy||!confirmed||!!api.pending()||!!api.recoveryMessage()||keys.some(k=>!Number.isSafeInteger(policy[k])||policy[k]<1)}>{t(busy?'continuous.common.saving':'planWork.budget.save')}</button></form>}
 </details>
}
