type Values=readonly [string,string,string,string,string,string,string,string,string,string]
type Row<K extends string=string>=readonly [K,...Values]
const r=<K extends string>(key:K,...values:Values):Row<K>=>[key,...values]

// 个人核心保持一致，商业方案明确标记发布状态。
export const ABOUT_PLAN_MESSAGE_ROWS=[

 r("about.plans.title","版本与方案","版本與方案","Versions and plans","バージョンとプラン","버전 및 플랜","Phiên bản và gói","Versiones y planes","Versions et offres","Versionen und Tarife","Versões e planos"),
 r("about.plans.more","了解详情：","了解詳情：","Learn more:","詳細：","자세히:","Tìm hiểu thêm:","Más información:","En savoir plus :","Mehr erfahren:","Saiba mais:"),
 r("about.plans.planned","规划中","規劃中","Planned","開発予定","출시 예정","Dự kiến","Previsto","Prévu","Geplant","Planejado"),
 r("about.plans.relation","Free 与 Pro 共享个人核心功能。Cloud 提供托管服务，可独立使用。所有版本均需自备模型 API 密钥，模型费用另计。","Free 與 Pro 共享個人核心功能。Cloud 提供託管服務，可獨立使用。所有版本均需自備模型 API 金鑰，模型費用另計。","Free and Pro share the personal core. Cloud offers independent managed hosting. All versions require your own model API keys; model usage is billed separately.","Free と Pro の個人向け基本機能は共通です。Cloud は単独で利用できるホスティングサービスです。全バージョンでモデル API キーの用意が必要で、モデル利用料は別途かかります。","Free와 Pro는 개인 핵심 기능을 공유합니다. Cloud는 독립적으로 이용 가능한 호스팅 서비스입니다. 모든 버전은 모델 API 키가 필요하며 모델 비용은 별도입니다.","Free và Pro dùng chung các chức năng cá nhân cốt lõi. Cloud cung cấp dịch vụ lưu trữ độc lập. Mọi phiên bản đều cần khóa API mô hình riêng; phí mô hình tính riêng.","Free y Pro comparten las funciones personales esenciales. Cloud ofrece alojamiento gestionado independiente. Todas las versiones requieren tus claves API; el uso del modelo se factura aparte.","Free et Pro partagent les fonctions personnelles essentielles. Cloud propose un hébergement géré indépendant. Chaque version nécessite vos clés API ; les frais de modèle sont séparés.","Free und Pro bieten dieselben persönlichen Kernfunktionen. Cloud bietet unabhängig nutzbares Hosting. Alle Versionen benötigen eigene Modell-API-Schlüssel; Modellkosten fallen separat an.","Free e Pro compartilham as funções pessoais essenciais. Cloud oferece hospedagem gerenciada independente. Todas as versões exigem suas chaves API; o uso do modelo é cobrado à parte."),
 r("about.plans.card.free.badge","当前版本 · Alpha","目前版本 · Alpha","Current · Alpha","現在のバージョン · Alpha","현재 버전 · Alpha","Hiện tại · Alpha","Actual · Alpha","Actuelle · Alpha","Aktuell · Alpha","Atual · Alpha"),
 r("about.plans.card.free.tagline","开源 Web","開源 Web","Open-source Web","オープンソース Web","오픈소스 Web","Web mã nguồn mở","Web de código abierto","Web open source","Open-Source-Web","Web de código aberto"),
 r("about.plans.card.free.item1","AI 员工与群协作","AI 員工與群協作","AI employees and group collaboration","AI 従業員とグループ協働","AI 직원와 그룹 협업","Nhân viên AI và cộng tác nhóm","Empleados de IA y colaboración grupal","Employés IA et travail en groupe","KI-Mitarbeiter und Gruppenarbeit","Funcionários de IA e colaboração em grupo"),
 r("about.plans.card.free.item2","任务、自动化与记忆","任務、自動化與記憶","Tasks, automation and memory","タスク・自動化・記憶","작업, 자동화, 기억","Nhiệm vụ, tự động hóa và ghi nhớ","Tareas, automatización y memoria","Tâches, automatisation et mémoire","Aufgaben, Automatisierung und Gedächtnis","Tarefas, automação e memória"),
 r("about.plans.card.free.item3","业务、技能与市场","業務、技能與市集","Business, skills and marketplace","業務・スキル・マーケット","업무, 스킬, 마켓","Nghiệp vụ, kỹ năng và chợ","Negocios, habilidades y mercado","Activités, compétences et catalogue","Geschäftsbereiche, Skills und Marktplatz","Negócios, competências e mercado"),
 r("about.plans.card.free.item4","代码可修改，自行部署","程式碼可修改，自行部署","Editable code, self-hosted","コードを変更して自己運用","코드 수정 및 자체 배포","Sửa mã và tự triển khai","Código modificable y autoalojamiento","Code modifiable, auto-hébergement","Code anpassen und selbst hosten","Código editável e hospedagem própria"),
 r("about.plans.card.pro.tagline","桌面端与手机伴侣端","桌面端與手機伴侶端","Desktop app and mobile companion","デスクトップアプリとモバイルコンパニオン","데스크톱 앱과 모바일 동반 앱","Ứng dụng máy tính và ứng dụng di động đồng hành","App de escritorio y acompañante móvil","Application de bureau et compagnon mobile","Desktop-App und mobile Begleit-App","Aplicativo de desktop e complemento móvel"),
 r("about.plans.card.pro.item1","Free 的全部个人核心功能","Free 的全部個人核心功能","All personal core features in Free","Free の個人向け基本機能すべて","Free의 모든 개인 핵심 기능","Mọi chức năng cá nhân cốt lõi của Free","Todas las funciones personales de Free","Toutes les fonctions personnelles de Free","Alle persönlichen Kernfunktionen von Free","Todas as funções pessoais do Free"),
 r("about.plans.card.pro.item2","本机文件与快捷操作","本機檔案與快捷操作","Local files and shortcuts","ローカルファイルとショートカット","로컬 파일 및 단축키","Tệp cục bộ và phím tắt","Archivos locales y atajos","Fichiers locaux et raccourcis","Lokale Dateien und Kurzbefehle","Arquivos locais e atalhos"),
 r("about.plans.card.pro.item3","官方业务套件","官方業務套件","Official business kits","公式業務キット","공식 업무 패키지","Bộ nghiệp vụ chính thức","Paquetes oficiales de negocio","Kits métier officiels","Offizielle Branchenpakete","Pacotes oficiais de negócios"),
 r("about.plans.card.pro.item4","备份恢复与更新维护","備份還原與更新維護","Backup, restore and updates","バックアップ・復元・更新","백업, 복원 및 업데이트","Sao lưu, khôi phục và cập nhật","Copias, restauración y actualizaciones","Sauvegarde, restauration et mises à jour","Sicherung, Wiederherstellung und Updates","Backup, restauração e atualizações"),
 r("about.plans.card.pro.item5","手机派任务、跟进与审批","手機派任務、追蹤與審批","Assign, track and approve from your phone","スマートフォンで依頼・進捗確認・承認","휴대폰으로 작업 할당, 진행 확인, 승인","Giao việc, theo dõi và duyệt trên điện thoại","Asigna, sigue y aprueba desde el móvil","Attribuez, suivez et approuvez depuis le mobile","Aufgaben mobil vergeben, verfolgen und freigeben","Atribua, acompanhe e aprove pelo celular"),
 r("about.plans.card.pro.item6","远程执行需桌面端在线","遠端執行需桌面端上線","Remote work requires an online desktop","リモート実行にはデスクトップの接続が必要","원격 실행에는 온라인 데스크톱 필요","Thực thi từ xa cần máy tính trực tuyến","La ejecución remota requiere el equipo conectado","L’exécution distante nécessite un ordinateur en ligne","Remote-Ausführung erfordert einen erreichbaren Desktop","A execução remota exige o computador online"),
 r("about.plans.card.cloud.tagline","官方托管服务","官方託管服務","Managed hosting","公式ホスティング","공식 호스팅 서비스","Dịch vụ lưu trữ chính thức","Alojamiento gestionado","Hébergement géré","Offizielles Hosting","Hospedagem gerenciada"),
 r("about.plans.card.cloud.item1","浏览器直接使用","瀏覽器直接使用","Work in your browser","ブラウザーですぐ利用","브라우저에서 바로 사용","Dùng ngay trong trình duyệt","Uso desde el navegador","Accès depuis le navigateur","Direkt im Browser nutzen","Use no navegador"),
 r("about.plans.card.cloud.item2","在线运行定时任务","線上執行排程任務","Scheduled tasks run online","スケジュールタスクをオンライン実行","예약 작업 온라인 실행","Chạy nhiệm vụ theo lịch trực tuyến","Tareas programadas en línea","Tâches planifiées en ligne","Geplante Aufgaben online ausführen","Tarefas agendadas online"),
 r("about.plans.card.cloud.item3","托管运维与备份","託管維運與備份","Managed operations and backups","運用管理とバックアップ","운영 관리 및 백업","Quản lý vận hành và sao lưu","Operaciones y copias gestionadas","Exploitation et sauvegardes gérées","Verwalteter Betrieb und Backups","Operações e backups gerenciados"),
 r("about.plans.card.cloud.item4","数据导出与迁移","資料匯出與遷移","Data export and migration","データのエクスポートと移行","데이터 내보내기 및 이전","Xuất và di chuyển dữ liệu","Exportación y migración de datos","Export et migration des données","Datenexport und Migration","Exportação e migração de dados"),
 r("about.plans.card.enterprise.tagline","企业私有化部署","企業私有化部署","Enterprise private deployment","企業向けプライベート導入","기업 전용 배포","Triển khai riêng cho doanh nghiệp","Despliegue privado empresarial","Déploiement privé en entreprise","Private Unternehmensbereitstellung","Implantação privada empresarial"),
 r("about.plans.card.enterprise.item1","多种智能体引擎","多種智慧代理引擎","Multiple agent engines","複数のエージェントエンジン","다중 에이전트 엔진","Nhiều công cụ tác tử AI","Varios motores de agentes","Plusieurs moteurs d’agents","Mehrere Agent-Engines","Vários motores de agentes"),
 r("about.plans.card.enterprise.item2","分布式部署","分散式部署","Distributed deployment","分散デプロイ","분산 배포","Triển khai phân tán","Despliegue distribuido","Déploiement distribué","Verteilte Bereitstellung","Implantação distribuída"),
 r("about.plans.card.enterprise.item3","安全合规与权限隔离","安全合規與權限隔離","Security, compliance and access isolation","セキュリティ・コンプライアンス・権限分離","보안, 규정 준수 및 권한 격리","Bảo mật, tuân thủ và cách ly quyền","Seguridad, cumplimiento y aislamiento de permisos","Sécurité, conformité et isolation des accès","Sicherheit, Compliance und Rechtetrennung","Segurança, conformidade e isolamento de acesso"),
 r("about.plans.card.enterprise.item4","操作审计与追溯","操作稽核與追溯","Audit trails and traceability","操作監査と追跡","작업 감사 및 추적","Kiểm toán và truy vết thao tác","Auditoría y trazabilidad","Audit et traçabilité","Aktionsaudit und Nachverfolgbarkeit","Auditoria e rastreabilidade"),
 r("about.plans.card.enterprise.item5","安全网关","安全閘道","Security gateway","セキュリティゲートウェイ","보안 게이트웨이","Cổng bảo mật","Pasarela de seguridad","Passerelle de sécurité","Sicherheitsgateway","Gateway de segurança"),
 r("about.plans.card.enterprise.item6","SSO、共享员工与企业集成","SSO、共享員工與企業整合","SSO, shared employees and integrations","SSO・共有従業員・企業連携","SSO, 공유 직원 및 기업 연동","SSO, nhân viên dùng chung và tích hợp","SSO, empleados compartidos e integraciones","SSO, employés partagés et intégrations","SSO, gemeinsame Mitarbeiter und Integrationen","SSO, funcionários compartilhados e integrações"),
] as const
