type Values=readonly [string,string,string,string,string,string,string,string,string,string]
type Row<K extends string=string>=readonly [K,...Values]
const r=<K extends string>(key:K,...values:Values):Row<K>=>[key,...values]

// 三版本的产品定位与使用场景；开发进度和实际授权不在这里描述。
export const ABOUT_PLAN_MESSAGE_ROWS=[

 r("about.plans.title","版本定位","版本定位","Product editions","製品エディション","제품 에디션","Định vị phiên bản","Ediciones del producto","Éditions du produit","Produkteditionen","Edições do produto"),
 r("about.plans.more","了解详情：","了解詳情：","Learn more:","詳細：","자세히:","Tìm hiểu thêm:","Más información:","En savoir plus :","Mehr erfahren:","Saiba mais:"),
 r("about.plans.relation","三个版本共用 Teloa 核心。社区版适合自行部署；Pro 围绕个人 Mac 与手机接续工作；Enterprise 面向企业云、内网和组织协作。自备模型 API 密钥，模型费用另计。","三個版本共用 Teloa 核心。社區版適合自行部署；Pro 圍繞個人 Mac 與手機接續工作；Enterprise 面向企業雲、內網與組織協作。自備模型 API 金鑰，模型費用另計。","All three editions share the Teloa core. Community is for self-hosting; Pro brings together your Mac and phone to continue personal work; Enterprise is for company clouds, private networks and organizational collaboration. Bring your own model API keys; model usage is billed separately.","3 つのエディションは Teloa のコアを共有します。Community は自己運用、Pro は個人の Mac とスマートフォンでの継続作業、Enterprise は企業クラウド・社内ネットワーク・組織の協働に対応します。モデル API キーは持参が必要で、モデル利用料は別途かかります。","세 에디션은 Teloa 코어를 공유합니다. Community는 자체 배포, Pro는 개인 Mac과 휴대폰에서 이어지는 작업, Enterprise는 기업 클라우드와 내부망 및 조직 협업을 위한 에디션입니다. 모델 API 키를 직접 준비하며 모델 사용료는 별도입니다.","Ba phiên bản dùng chung lõi Teloa. Community dành cho tự triển khai; Pro kết nối công việc cá nhân trên Mac và điện thoại; Enterprise dành cho đám mây doanh nghiệp, mạng nội bộ và cộng tác trong tổ chức. Cần khóa API mô hình riêng; phí sử dụng mô hình tính riêng.","Las tres ediciones comparten el núcleo de Teloa. Community permite el autoalojamiento; Pro une tu Mac y teléfono para continuar el trabajo personal; Enterprise está orientada a nubes empresariales, redes privadas y colaboración organizativa. Usa tus propias claves API; el uso de modelos se factura aparte.","Les trois éditions partagent le cœur de Teloa. Community permet l’auto-hébergement ; Pro relie votre Mac et votre téléphone pour poursuivre votre travail personnel ; Enterprise vise les clouds d’entreprise, les réseaux privés et la collaboration au sein des organisations. Fournissez vos clés API ; les modèles sont facturés séparément.","Alle drei Editionen teilen den Teloa-Kern. Community ist für Selbsthosting gedacht; Pro verbindet Ihren Mac und Ihr Smartphone für persönliche Arbeit; Enterprise richtet sich an Unternehmensclouds, interne Netzwerke und die Zusammenarbeit in Organisationen. Eigene Modell-API-Schlüssel sind erforderlich; die Modellnutzung wird separat berechnet.","As três edições partilham o núcleo Teloa. Community permite hospedagem própria; Pro liga o seu Mac e telemóvel para continuar o trabalho pessoal; Enterprise destina-se a clouds empresariais, redes internas e colaboração organizacional. Forneça as suas chaves API; o uso de modelos é cobrado separadamente."),
 r("about.plans.card.community.position","开源","開源","Open source","オープンソース","오픈소스","Mã nguồn mở","Código abierto","Open source","Open Source","Código aberto"),
 r("about.plans.card.community.tagline","开源核心 · 自行部署","開源核心 · 自行部署","Open-source core · Self-hosted","オープンソースコア · 自己運用","오픈소스 코어 · 자체 배포","Lõi mã nguồn mở · Tự triển khai","Núcleo abierto · Autoalojamiento","Cœur open source · Auto-hébergement","Open-Source-Kern · Selbsthosting","Núcleo aberto · Hospedagem própria"),
 r("about.plans.card.community.item1","AI 员工与群协作","AI 員工與群協作","AI employees and group collaboration","AI 従業員とグループ協働","AI 직원와 그룹 협업","Nhân viên AI và cộng tác nhóm","Empleados de IA y colaboración grupal","Employés IA et travail en groupe","KI-Mitarbeiter und Gruppenarbeit","Funcionários de IA e colaboração em grupo"),
 r("about.plans.card.community.item2","任务、自动化与记忆","任務、自動化與記憶","Tasks, automation and memory","タスク・自動化・記憶","작업, 자동화, 기억","Nhiệm vụ, tự động hóa và ghi nhớ","Tareas, automatización y memoria","Tâches, automatisation et mémoire","Aufgaben, Automatisierung und Gedächtnis","Tarefas, automação e memória"),
 r("about.plans.card.community.item3","业务、技能与市场","業務、技能與市集","Business, skills and marketplace","業務・スキル・マーケット","업무, 스킬, 마켓","Nghiệp vụ, kỹ năng và chợ","Negocios, habilidades y mercado","Activités, compétences et catalogue","Geschäftsbereiche, Skills und Marktplatz","Negócios, competências e mercado"),
 r("about.plans.card.community.item4","代码可修改，自行部署","程式碼可修改，自行部署","Editable code, self-hosted","コードを変更して自己運用","코드 수정 및 자체 배포","Sửa mã và tự triển khai","Código modificable y autoalojamiento","Code modifiable, auto-hébergement","Code anpassen und selbst hosten","Código editável e hospedagem própria"),
 r("about.plans.card.pro.position","个人 / 专业","個人 / 專業","Personal / professional","個人 / プロ","개인 / 전문가","Cá nhân / chuyên gia","Personal / profesional","Particuliers / professionnels","Privat / professionell","Pessoal / profissional"),
 r("about.plans.card.pro.tagline","个人与专业用户的 Mac 工作台","個人與專業使用者的 Mac 工作台","Mac workspace for individuals and professionals","個人とプロのための Mac ワークスペース","개인 및 전문가를 위한 Mac 작업 공간","Không gian làm việc Mac cho cá nhân và chuyên gia","Espacio Mac para particulares y profesionales","Espace Mac pour particuliers et professionnels","Mac-Arbeitsbereich für Einzelanwender und Profis","Espaço Mac para indivíduos e profissionais"),
 r("about.plans.card.pro.item1","开箱即用的 Mac 原生应用","開箱即用的 Mac 原生應用程式","Ready-to-use native Mac app","すぐに使える Mac ネイティブアプリ","바로 사용할 수 있는 Mac 네이티브 앱","Ứng dụng Mac gốc sẵn sàng sử dụng","Aplicación nativa para Mac lista para usar","Application native pour Mac prête à l’emploi","Sofort nutzbare native Mac-App","Aplicação nativa para Mac pronta a usar"),
 r("about.plans.card.pro.item2","在自己的 Mac 本机执行工作","在自己的 Mac 本機執行工作","Run work locally on your own Mac","自分の Mac 上でローカル実行","자신의 Mac에서 로컬로 작업 실행","Thực thi cục bộ trên Mac của bạn","Ejecuta el trabajo localmente en tu Mac","Exécuter le travail localement sur votre Mac","Arbeit lokal auf dem eigenen Mac ausführen","Executar o trabalho localmente no seu Mac"),
 r("about.plans.card.pro.item3","经授权使用本机文件与应用","經授權使用本機檔案與應用程式","Authorized access to local files and apps","許可されたローカルファイルとアプリの利用","허용된 로컬 파일 및 앱 사용","Truy cập tệp và ứng dụng cục bộ được cấp quyền","Acceso autorizado a archivos y aplicaciones locales","Accès autorisé aux fichiers et applications locaux","Autorisierter Zugriff auf lokale Dateien und Apps","Acesso autorizado a ficheiros e aplicações locais"),
 r("about.plans.card.pro.item4","AI 团队协作与自动化","AI 團隊協作與自動化","AI team collaboration and automation","AI チームの協働と自動化","AI 팀 협업 및 자동화","Cộng tác nhóm AI và tự động hóa","Colaboración de equipos de IA y automatización","Collaboration d’équipes IA et automatisation","KI-Teamarbeit und Automatisierung","Colaboração de equipas de IA e automação"),
 r("about.plans.card.pro.item5","手机随时新建、跟进与接续工作","手機隨時新增、追蹤與接續工作","Start, follow and continue work on your phone","スマートフォンでいつでも作業を開始・確認・継続","휴대폰에서 언제든 작업 시작, 확인 및 이어가기","Tạo, theo dõi và tiếp tục công việc trên điện thoại","Inicia, sigue y continúa el trabajo desde el teléfono","Créer, suivre et poursuivre le travail sur votre téléphone","Arbeit auf dem Smartphone starten, verfolgen und fortsetzen","Iniciar, acompanhar e continuar o trabalho no telemóvel"),
 r("about.plans.card.pro.item6","任务、审批与成果统一工作流","任務、審批與成果統一工作流程","One workflow for tasks, approvals and results","タスク・承認・成果をひとつのワークフローで扱う","작업, 승인 및 결과를 하나의 흐름으로 처리","Một quy trình cho nhiệm vụ, phê duyệt và kết quả","Un flujo para tareas, aprobaciones y resultados","Un même flux pour tâches, validations et résultats","Ein Ablauf für Aufgaben, Freigaben und Ergebnisse","Um fluxo para tarefas, aprovações e resultados"),
 r("about.plans.card.enterprise.position","企业团队","企業團隊","Enterprise teams","企業チーム","기업 팀","Nhóm doanh nghiệp","Equipos empresariales","Équipes d’entreprise","Unternehmensteams","Equipas empresariais"),
 r("about.plans.card.enterprise.tagline","企业团队的独立部署与治理","企業團隊的獨立部署與治理","Independent deployment and governance for enterprise teams","企業チームの独立導入とガバナンス","기업 팀을 위한 독립 배포 및 거버넌스","Triển khai độc lập và quản trị cho nhóm doanh nghiệp","Despliegue independiente y gobernanza para equipos empresariales","Déploiement indépendant et gouvernance pour les équipes d’entreprise","Unabhängige Bereitstellung und Steuerung für Unternehmensteams","Implantação independente e governação para equipas empresariais"),
 r("about.plans.card.enterprise.item1","企业云或内网部署","企業雲或內網部署","Deployment in company clouds or private networks","企業クラウドまたは社内ネットワークへの導入","기업 클라우드 또는 내부망 배포","Triển khai trên đám mây doanh nghiệp hoặc mạng nội bộ","Despliegue en nubes empresariales o redes privadas","Déploiement dans un cloud d’entreprise ou un réseau privé","Bereitstellung in Unternehmensclouds oder internen Netzwerken","Implantação em clouds empresariais ou redes internas"),
 r("about.plans.card.enterprise.item2","客户掌控执行与数据","客戶掌控執行與資料","Customer control of execution and data","顧客が実行環境とデータを管理","고객이 실행과 데이터 제어","Khách hàng kiểm soát thực thi và dữ liệu","Control del cliente sobre ejecución y datos","Contrôle de l’exécution et des données par le client","Kundenseitige Kontrolle über Ausführung und Daten","Controlo da execução e dos dados pelo cliente"),
 r("about.plans.card.enterprise.item3","组织成员与共享 AI 员工","組織成員與共享 AI 員工","Organization members and shared AI employees","組織メンバーと共有 AI 従業員","조직 구성원 및 공유 AI 직원","Thành viên tổ chức và nhân viên AI dùng chung","Miembros de la organización y empleados de IA compartidos","Membres de l’organisation et employés IA partagés","Organisationsmitglieder und gemeinsame KI-Mitarbeiter","Membros da organização e funcionários de IA partilhados"),
 r("about.plans.card.enterprise.item4","权限隔离与操作审计","權限隔離與操作稽核","Access isolation and audit trails","権限分離と操作監査","권한 격리 및 작업 감사","Cách ly quyền và kiểm toán thao tác","Aislamiento de permisos y auditoría","Isolation des accès et audit des opérations","Rechtetrennung und Aktionsaudit","Isolamento de acesso e auditoria de operações"),
 r("about.plans.card.enterprise.item5","SSO 与组织身份管理","SSO 與組織身分管理","SSO and organizational identity management","SSO と組織の ID 管理","SSO 및 조직 신원 관리","SSO và quản lý danh tính tổ chức","SSO y gestión de identidades de la organización","SSO et gestion des identités de l’organisation","SSO und Identitätsverwaltung der Organisation","SSO e gestão de identidades da organização"),
 r("about.plans.card.enterprise.item6","企业数据与业务系统集成","企業資料與業務系統整合","Enterprise data and business system integrations","企業データと業務システムの連携","기업 데이터 및 업무 시스템 연동","Tích hợp dữ liệu và hệ thống nghiệp vụ doanh nghiệp","Integración de datos y sistemas empresariales","Intégration des données et systèmes métier de l’entreprise","Integration von Unternehmensdaten und Geschäftssystemen","Integração de dados empresariais e sistemas de negócio"),
] as const
