export const APPLICATION_CAPABILITY_MESSAGE_ROWS=[
 ['application.capability.aria','高级功能权益','進階功能權益','Advanced feature access','高度な機能の利用権','고급 기능 이용 권한','Quyền dùng tính năng nâng cao','Acceso a funciones avanzadas','Accès aux fonctions avancées','Zugriff auf erweiterte Funktionen','Acesso a recursos avançados'],
 ['application.capability.subscription-required','此功能需要 Pro。已有内容可查看。','此功能需要 Pro。既有內容可檢視。','This feature requires Pro. Existing content remains available to view.','この機能には Pro が必要です。既存の内容は閲覧できます。','이 기능은 Pro가 필요합니다. 기존 콘텐츠는 볼 수 있습니다.','Tính năng này cần Pro. Bạn vẫn có thể xem nội dung hiện có.','Esta función requiere Pro. Puedes consultar el contenido existente.','Cette fonction nécessite Pro. Le contenu existant reste consultable.','Diese Funktion erfordert Pro. Vorhandene Inhalte bleiben lesbar.','Este recurso requer Pro. O conteúdo existente continua disponível para consulta.'],
 ['application.capability.subscription-expired','Pro 高级权益已到期。已有内容保留为只读。','Pro 進階權益已到期。既有內容保留為唯讀。','Pro access has expired. Existing content is preserved as read only.','Pro の利用権が期限切れです。既存の内容は読み取り専用で保持されます。','Pro 이용 권한이 만료되었습니다. 기존 콘텐츠는 읽기 전용으로 유지됩니다.','Quyền Pro đã hết hạn. Nội dung hiện có được giữ ở chế độ chỉ đọc.','El acceso Pro ha caducado. El contenido existente se conserva en modo de solo lectura.','L’accès Pro a expiré. Le contenu existant est conservé en lecture seule.','Der Pro-Zugriff ist abgelaufen. Vorhandene Inhalte bleiben schreibgeschützt erhalten.','O acesso Pro expirou. O conteúdo existente é preservado como somente leitura.'],
 ['application.capability.checking','正在核对高级权益。已有内容可查看。','正在核對進階權益。既有內容可檢視。','Checking feature access. Existing content remains available to view.','利用権を確認しています。既存の内容は閲覧できます。','이용 권한을 확인 중입니다. 기존 콘텐츠는 볼 수 있습니다.','Đang kiểm tra quyền truy cập. Bạn vẫn có thể xem nội dung hiện có.','Comprobando el acceso. Puedes consultar el contenido existente.','Vérification de l’accès. Le contenu existant reste consultable.','Zugriff wird geprüft. Vorhandene Inhalte bleiben lesbar.','Verificando o acesso. O conteúdo existente continua disponível para consulta.'],
 ['application.capability.unavailable','暂时无法核对高级权益。已有内容可查看。','暫時無法核對進階權益。既有內容可檢視。','Feature access could not be verified. Existing content remains available to view.','利用権を確認できませんでした。既存の内容は閲覧できます。','이용 권한을 확인할 수 없습니다. 기존 콘텐츠는 볼 수 있습니다.','Chưa thể xác minh quyền truy cập. Bạn vẫn có thể xem nội dung hiện có.','No se pudo verificar el acceso. Puedes consultar el contenido existente.','L’accès n’a pas pu être vérifié. Le contenu existant reste consultable.','Der Zugriff konnte nicht geprüft werden. Vorhandene Inhalte bleiben lesbar.','Não foi possível verificar o acesso. O conteúdo existente continua disponível para consulta.'],
 ['application.capability.basic','基础 Agent 仍可使用。','基礎 Agent 仍可使用。','The basic Agent is still available.','基本 Agent は引き続き利用できます。','기본 Agent는 계속 사용할 수 있습니다.','Agent cơ bản vẫn dùng được.','El Agent básico sigue disponible.','L’Agent de base reste disponible.','Der grundlegende Agent bleibt verfügbar.','O Agent básico continua disponível.'],
 ['application.capability.subscription','查看 Pro 订阅','檢視 Pro 訂閱','View Pro subscription','Pro サブスクリプションを見る','Pro 구독 보기','Xem gói Pro','Ver suscripción Pro','Voir l’abonnement Pro','Pro-Abonnement ansehen','Ver assinatura Pro'],
 ['application.capability.account','核对账号','核對帳號','Check account','アカウントを確認','계정 확인','Kiểm tra tài khoản','Comprobar cuenta','Vérifier le compte','Konto prüfen','Verificar conta'],
 ['application.capability.openFailed','账号入口未能打开，请稍后重试。','帳號入口未能開啟，請稍後重試。','The account could not be opened. Please try again later.','アカウントを開けませんでした。後でもう一度お試しください。','계정을 열 수 없습니다. 나중에 다시 시도해 주세요.','Không mở được tài khoản. Vui lòng thử lại sau.','No se pudo abrir la cuenta. Inténtalo más tarde.','Impossible d’ouvrir le compte. Réessayez plus tard.','Das Konto konnte nicht geöffnet werden. Bitte später erneut versuchen.','Não foi possível abrir a conta. Tente novamente mais tarde.'],
 ['application.capability.viewConfiguration','查看配置','檢視設定','View configuration','設定を見る','설정 보기','Xem cấu hình','Ver configuración','Voir la configuration','Konfiguration ansehen','Ver configuração'],
] as const
