/**
 * 业务定制层台账组件的固定文案（规格 §5.3）。声明自带的 title/label/lead/unit/values 不在这里，
 * 它们是模板作者的内容，只当文本节点渲染、不翻译。
 *
 * `business.ledger.missingFields` 与简报草稿不同：T4 的 `missingFields` 只给字段名、不给条数
 * （task-4-report 修复轮 HIGH-1，判据是「该字段上至少有一个对象解析失败」），
 * 界面没有可填的 `{count}`，因此文案按「部分缺少」写，不编一个数字出来。
 */
export const BUSINESS_DEFINITION_MESSAGE_ROWS = [
 ['business.ledger.title','业务数据','業務資料','Business data','業務データ','업무 데이터','Dữ liệu nghiệp vụ','Datos de negocio','Données métier','Geschäftsdaten','Dados de negócio'],
 ['business.ledger.note','按类型查看业务数据、处理进度和更新时间。','按類型查看業務資料、處理進度和更新時間。','View business data, progress, and update times by type.','種類ごとに業務データ、進捗、更新時刻を確認できます。','유형별 업무 데이터, 진행 상황 및 업데이트 시각을 확인하세요.','Xem dữ liệu nghiệp vụ, tiến độ và thời gian cập nhật theo loại.','Consulta los datos de negocio, el progreso y la hora de actualización por tipo.','Consultez les données métier, la progression et les heures de mise à jour par type.','Sehen Sie Geschäftsdaten, Fortschritt und Aktualisierungszeiten nach Typ an.','Consulte dados de negócio, progresso e horas de atualização por tipo.'],
 /** 原型 B5：数字只来自对象类型声明的 `progress` 和已固定快照，未声明时这两行不会出现。 */
 ['business.ledger.progress.unfinished','待完成 {unfinished} 项','待完成 {unfinished} 項','{unfinished} items unfinished','未完了 {unfinished} 件','미완료 항목 {unfinished}개','{unfinished} mục chưa hoàn thành','{unfinished} elementos pendientes','{unfinished} éléments à terminer','{unfinished} offene Einträge','{unfinished} itens por concluir'],
 ['business.ledger.progress.waiting','待完成 {unfinished} 项 · 待你处理 {waiting} 项','待完成 {unfinished} 項 · 待你處理 {waiting} 項','{unfinished} items unfinished · {waiting} need your action','未完了 {unfinished} 件・対応が必要 {waiting} 件','미완료 {unfinished}개 · 처리할 항목 {waiting}개','{unfinished} mục chưa hoàn thành · {waiting} mục cần bạn xử lý','{unfinished} pendientes · {waiting} requieren tu acción','{unfinished} à terminer · {waiting} nécessitent votre action','{unfinished} offen · {waiting} erfordern Ihre Aktion','{unfinished} por concluir · {waiting} requerem a sua ação'],
 ['business.ledger.change','最近变化 {at}','最近變化 {at}','Latest change {at}','最終更新 {at}','최근 변경 {at}','Thay đổi gần nhất {at}','Último cambio {at}','Dernière modification {at}','Letzte Änderung {at}','Última alteração {at}'],
 ['business.ledger.empty.types','暂无可显示的业务数据','暫無可顯示的業務資料','No business data to display yet','表示できる業務データはまだありません','아직 표시할 업무 데이터가 없습니다','Chưa có dữ liệu nghiệp vụ để hiển thị','Todavía no hay datos de negocio que mostrar','Aucune donnée métier à afficher pour le moment','Noch keine Geschäftsdaten zum Anzeigen','Ainda não há dados de negócio para mostrar'],
 ['business.ledger.empty.typesHint','请先配置业务数据类型并接入数据源。','請先設定業務資料類型並接入資料來源。','Configure business data types and connect a data source first.','まず業務データの種類を設定し、データソースを接続してください。','먼저 업무 데이터 유형을 설정하고 데이터 소스를 연결하세요.','Hãy cấu hình loại dữ liệu nghiệp vụ và kết nối nguồn dữ liệu trước.','Configura los tipos de datos de negocio y conecta una fuente de datos.','Configurez les types de données métier et connectez une source de données.','Konfigurieren Sie zuerst die Geschäftsdaten-Typen und verbinden Sie eine Datenquelle.','Configure os tipos de dados de negócio e ligue uma fonte de dados primeiro.'],
 ['business.ledger.source.notConnected','数据源未连接','資料來源未連線','Data source not connected','データソースは未接続','데이터 소스 연결 안 됨','Nguồn dữ liệu chưa kết nối','Fuente de datos no conectada','Source de données non connectée','Datenquelle nicht verbunden','Fonte de dados não ligada'],
 ['business.ledger.snapshotOnly','来源尚未连接；当前显示的是上次保存的存档，不会实时更新。','來源尚未連接；目前顯示的是上次儲存的存檔，不會即時更新。','The source is not connected. The saved copy shown here will not update in real time.','ソースは未接続です。現在表示している保存コピーはリアルタイムには更新されません。','소스가 연결되지 않았습니다. 현재 표시된 저장본은 실시간으로 업데이트되지 않습니다.','Nguồn chưa được kết nối. Bản lưu gần nhất đang hiển thị sẽ không cập nhật theo thời gian thực.','La fuente no está conectada. La copia guardada que se muestra no se actualizará en tiempo real.','La source n’est pas connectée. La copie enregistrée affichée ne sera pas actualisée en temps réel.','Die Quelle ist nicht verbunden. Die angezeigte gespeicherte Kopie wird nicht in Echtzeit aktualisiert.','A fonte não está ligada. A cópia guardada apresentada não será atualizada em tempo real.'],
 ['business.ledger.source.connect','去连接这个来源','去連接這個來源','Connect this source','このソースを接続','이 소스 연결하기','Kết nối nguồn này','Conectar esta fuente','Connecter cette source','Diese Quelle verbinden','Ligar esta fonte'],
 ['business.ledger.empty.objects','暂无业务记录','暫無業務記錄','No business records yet','業務レコードはまだありません','아직 업무 기록이 없습니다','Chưa có bản ghi nghiệp vụ','Todavía no hay registros de negocio','Aucun enregistrement métier pour le moment','Noch keine Geschäftsdatensätze','Ainda não há registos de negócio'],
 ['business.ledger.coverage','统计基于已同步的 {count} 条，最近同步 {at}。','統計基於已同步的 {count} 筆，最近同步 {at}。','Based on {count} synced records; last synced {at}.','同期済み {count} 件に基づきます。最終同期は {at}。','동기화된 {count}건을 기준으로 합니다. 마지막 동기화 {at}.','Thống kê dựa trên {count} bản ghi đã đồng bộ, lần gần nhất {at}.','Basado en {count} registros sincronizados; última sincronización {at}.','Basé sur {count} enregistrements synchronisés ; dernière synchronisation {at}.','Basiert auf {count} synchronisierten Datensätzen; zuletzt synchronisiert {at}.','Com base em {count} registos sincronizados; última sincronização {at}.'],
 ['business.ledger.coverage.never','统计基于已同步的 {count} 条，还没有同步记录。','統計基於已同步的 {count} 筆，還沒有同步記錄。','Based on {count} synced records; no sync recorded yet.','同期済み {count} 件に基づきます。同期記録はまだありません。','동기화된 {count}건을 기준으로 합니다. 동기화 기록이 아직 없습니다.','Thống kê dựa trên {count} bản ghi đã đồng bộ; chưa có lần đồng bộ nào được ghi lại.','Basado en {count} registros sincronizados; aún no hay sincronizaciones registradas.','Basé sur {count} enregistrements synchronisés ; aucune synchronisation enregistrée.','Basiert auf {count} synchronisierten Datensätzen; noch keine Synchronisierung erfasst.','Com base em {count} registos sincronizados; ainda sem sincronizações registadas.'],
 ['business.ledger.coverage.snapshot','当前存档共 {count} 条，记录截止 {at}。','目前存檔共 {count} 筆，記錄截至 {at}。','The current saved copy contains {count} records through {at}.','現在の保存コピーは {count} 件で、{at} までの記録です。','현재 저장본에는 {at}까지의 기록 {count}건이 있습니다.','Bản lưu hiện tại có {count} bản ghi đến {at}.','La copia guardada actual contiene {count} registros hasta {at}.','La copie enregistrée actuelle contient {count} enregistrements jusqu’au {at}.','Die aktuelle gespeicherte Kopie enthält {count} Datensätze bis {at}.','A cópia guardada atual contém {count} registos até {at}.'],
 ['business.ledger.coverage.snapshotNever','当前存档共 {count} 条，没有可用的记录时间。','目前存檔共 {count} 筆，沒有可用的記錄時間。','The current saved copy contains {count} records without a recorded timestamp.','現在の保存コピーは {count} 件ですが、記録時刻はありません。','현재 저장본에는 {count}건이 있으며 기록 시각은 없습니다.','Bản lưu hiện tại có {count} bản ghi nhưng không có thời gian ghi nhận.','La copia guardada actual contiene {count} registros sin hora registrada.','La copie enregistrée actuelle contient {count} enregistrements sans horodatage disponible.','Die aktuelle gespeicherte Kopie enthält {count} Datensätze ohne erfassten Zeitpunkt.','A cópia guardada atual contém {count} registos sem hora registada.'],
 ['business.ledger.truncated','只统计了最近 5000 条，结论可能不完整。','只統計了最近 5000 筆，結論可能不完整。','Only the latest 5,000 records were counted; the picture may be incomplete.','直近 5,000 件のみを集計しています。結論は不完全な可能性があります。','최근 5,000건만 집계했습니다. 결론이 불완전할 수 있습니다.','Chỉ thống kê 5.000 bản ghi gần nhất; kết luận có thể chưa đầy đủ.','Solo se contaron los últimos 5000 registros; la conclusión puede ser incompleta.','Seuls les 5 000 derniers enregistrements ont été comptés ; la conclusion peut être incomplète.','Es wurden nur die letzten 5.000 Datensätze gezählt; das Bild kann unvollständig sein.','Foram contados apenas os últimos 5000 registos; a conclusão pode ser incompleta.'],
 ['business.ledger.missingFields','部分记录缺少 {fields}，未纳入统计。','部分記錄缺少 {fields}，未納入統計。','Some records are missing {fields} and are excluded from the statistics.','一部のレコードに {fields} がないため、集計から除外しています。','일부 기록에 {fields}이(가) 없어 통계에서 제외했습니다.','Một số bản ghi thiếu {fields} nên được loại khỏi thống kê.','A algunos registros les falta {fields} y se han excluido de las estadísticas.','Certains enregistrements n’ont pas {fields} et sont exclus des statistiques.','Bei einigen Datensätzen fehlt {fields}; sie sind von der Statistik ausgeschlossen.','Alguns registos não têm {fields} e foram excluídos das estatísticas.'],
 ['business.ledger.rowsShown','共 {total} 项，显示前 {count} 项。','共 {total} 項，顯示前 {count} 項。','{total} entries in total; the first {count} are shown.','全 {total} 項目のうち、先頭 {count} 項目を表示しています。','전체 {total}개 중 앞의 {count}개를 표시합니다.','Tổng cộng {total} mục, hiển thị {count} mục đầu tiên.','{total} entradas en total; se muestran las primeras {count}.','{total} entrées au total ; les {count} premières sont affichées.','Insgesamt {total} Einträge; die ersten {count} werden gezeigt.','{total} entradas no total; são mostradas as primeiras {count}.'],
 ['business.ledger.filteredShown','筛选后，{total} 条中显示 {count} 条。','篩選後，{total} 條中顯示 {count} 條。','{count} of {total} entries match the filters.','フィルター適用後、{total} 件中 {count} 件を表示しています。','필터 적용 후 {total}건 중 {count}건을 표시합니다.','Sau khi lọc, hiển thị {count} trong tổng số {total} mục.','Tras aplicar los filtros, se muestran {count} de {total} entradas.','Après filtrage, {count} entrées sur {total} sont affichées.','Nach dem Filtern werden {count} von {total} Einträgen angezeigt.','Após a filtragem, são mostradas {count} de {total} entradas.'],
 ['business.ledger.openDirectory','打开目录','開啟目錄','Open directory','一覧を開く','목록 열기','Mở danh mục','Abrir el listado','Ouvrir la liste','Verzeichnis öffnen','Abrir a lista'],
 ['business.ledger.backDirectory','返回{type}目录','返回{type}目錄','Back to {type}','{type}一覧に戻る','{type} 목록으로 돌아가기','Quay lại danh sách {type}','Volver a {type}','Retour à {type}','Zurück zu {type}','Voltar a {type}'],
 ['business.ledger.back','回到全部对象','回到全部物件','Back to all objects','すべてのオブジェクトに戻る','전체 객체로 돌아가기','Quay lại tất cả đối tượng','Volver a todos los objetos','Retour à tous les objets','Zurück zu allen Objekten','Voltar a todos os objetos'],
 ['business.ledger.match','只看 {field} 为「{value}」的对象','只看 {field} 為「{value}」的物件','Only objects where {field} is “{value}”','{field} が「{value}」のオブジェクトのみ','{field}이(가) “{value}”인 객체만','Chỉ các đối tượng có {field} là “{value}”','Solo objetos con {field} igual a «{value}»','Seulement les objets dont {field} vaut « {value} »','Nur Objekte, bei denen {field} „{value}“ ist','Só objetos com {field} igual a «{value}»'],
 ['business.ledger.matchClear','看全部','看全部','Show all','すべて表示','모두 보기','Xem tất cả','Ver todo','Tout afficher','Alle anzeigen','Ver tudo'],
 ['business.ledger.column.object','对象','物件','Object','オブジェクト','객체','Đối tượng','Objeto','Objet','Objekt','Objeto'],
 ['business.ledger.column.sourceAndTime','来源 / 时间','來源 / 時間','Source / time','ソース / 時刻','소스 / 시각','Nguồn / thời gian','Fuente / hora','Source / heure','Quelle / Zeit','Fonte / hora'],
 ['business.ledger.column.completeness','完整性','完整性','Completeness','完全性','완전성','Tính đầy đủ','Integridad','Exhaustivité','Vollständigkeit','Integridade'],
 ['business.ledger.definitionUpdated','业务配置已更新，统计结果已重新计算。','業務設定已更新，統計結果已重新計算。','Business settings changed. Statistics have been recalculated.','業務設定が更新され、集計結果を再計算しました。','업무 설정이 변경되어 통계를 다시 계산했습니다.','Cấu hình nghiệp vụ đã thay đổi. Đã tính lại thống kê.','La configuración del negocio cambió. Se recalcularon las estadísticas.','Les réglages métier ont changé. Les statistiques ont été recalculées.','Die Geschäftseinstellungen wurden geändert. Die Statistik wurde neu berechnet.','As configurações do negócio mudaram. As estatísticas foram recalculadas.'],
 ['business.ledger.readFailed','业务数据暂时无法加载，请重新读取。','業務資料暫時無法載入，請重新讀取。','Business data could not be loaded. Please read again.','業務データを読み込めませんでした。再読み込みしてください。','업무 데이터를 불러올 수 없습니다. 다시 읽어 보세요.','Không tải được dữ liệu nghiệp vụ. Hãy đọc lại.','No se pudieron cargar los datos de negocio. Vuelve a leerlos.','Impossible de charger les données métier. Relancez la lecture.','Die Geschäftsdaten konnten nicht geladen werden. Lesen Sie sie erneut ein.','Não foi possível carregar os dados de negócio. Leia novamente.'],
 ['business.ledger.loading','正在加载业务数据和统计结果…','正在載入業務資料和統計結果…','Loading business data and statistics…','業務データと集計結果を読み込んでいます…','업무 데이터와 통계를 불러오는 중…','Đang tải dữ liệu nghiệp vụ và thống kê…','Cargando datos de negocio y estadísticas…','Chargement des données métier et des statistiques…','Geschäftsdaten und Statistik werden geladen…','A carregar dados de negócio e estatísticas…'],
 ['business.ledger.readFailed.forbidden','你没有查看此业务数据的权限。','你沒有查看此業務資料的權限。','You do not have permission to view this business data.','この業務データを閲覧する権限がありません。','이 업무 데이터를 볼 권한이 없습니다.','Bạn không có quyền xem dữ liệu nghiệp vụ này.','No tienes permiso para consultar estos datos de negocio.','Vous n’avez pas l’autorisation de consulter ces données métier.','Sie dürfen diese Geschäftsdaten nicht ansehen.','Não tem permissão para consultar estes dados de negócio.'],
 ['business.ledger.readFailed.corrupt','业务配置校验未通过，暂时无法显示数据。请重新读取。','業務設定驗證未通過，暫時無法顯示資料。請重新讀取。','Business settings failed verification, so data cannot be displayed. Please read again.','業務設定の検証に通らなかったため、データを表示できません。再読み込みしてください。','업무 설정 검증을 통과하지 못해 데이터를 표시할 수 없습니다. 다시 읽어 보세요.','Cấu hình nghiệp vụ chưa vượt qua kiểm tra nên không thể hiển thị dữ liệu. Hãy đọc lại.','La configuración del negocio no superó la verificación y no se pueden mostrar los datos. Vuelve a leerlos.','La vérification des réglages métier a échoué ; les données ne peuvent pas être affichées. Relancez la lecture.','Die Geschäftseinstellungen konnten nicht verifiziert werden. Daten können nicht angezeigt werden. Lesen Sie erneut ein.','As configurações do negócio não passaram na verificação e os dados não podem ser mostrados. Leia novamente.'],
 ['business.ledger.retry','重新读取','重新讀取','Read again','再読み込み','다시 읽기','Đọc lại','Volver a leer','Relire','Erneut lesen','Ler de novo'],
 ['business.ledger.action.explain','按「{template}」创建任务，并自动填入 {count} 项任务资料。','依「{template}」建立任務，並自動填入 {count} 項任務資料。','Create a task from “{template}” and fill in {count} task inputs.','「{template}」からタスクを作成し、{count} 件のタスク情報を入力します。','“{template}”로 작업을 만들고 작업 입력 {count}개를 채웁니다.','Tạo nhiệm vụ từ “{template}” và điền {count} mục dữ liệu nhiệm vụ.','Crea una tarea con «{template}» y rellena {count} datos de la tarea.','Créez une tâche à partir de « {template} » et renseignez {count} données de tâche.','Erstellen Sie eine Aufgabe aus „{template}“ und füllen Sie {count} Aufgabeneingaben aus.','Crie uma tarefa a partir de «{template}» e preencha {count} dados da tarefa.'],
 ['business.ledger.objectDetail','对象详情','物件詳情','Object detail','オブジェクトの詳細','객체 상세','Chi tiết đối tượng','Detalle del objeto','Détail de l’objet','Objektdetails','Detalhe do objeto'],
] as const
