/** 业务日常会话；顺序：简中、繁中、英、日、韩、越、西、法、德、葡。 */
export const BUSINESS_DAILY_MESSAGE_ROWS=[
 ['business.daily.status','业务会话','業務會話','Business conversation','業務の会話','업무 대화','Cuộc trò chuyện nghiệp vụ','Conversación del negocio','Conversation de l’activité','Geschäftsgespräch','Conversa do negócio'],
 ['business.daily.loading','正在准备业务会话…','正在準備業務會話…','Preparing the business conversation…','業務の会話を準備中…','업무 대화 준비 중…','Đang chuẩn bị cuộc trò chuyện…','Preparando la conversación…','Préparation de la conversation…','Geschäftsgespräch wird vorbereitet…','A preparar a conversa…'],
 ['business.daily.pending','请先恢复“{title}”的原会话。','請先恢復「{title}」的原會話。','Restore the original conversation for “{title}” first.','先に「{title}」の元の会話を復元してください。','먼저 “{title}”의 원래 대화를 복원하세요.','Trước tiên hãy khôi phục cuộc trò chuyện gốc của “{title}”.','Primero restaura la conversación original de «{title}».','Restaurez d’abord la conversation d’origine de « {title} ».','Stellen Sie zuerst das ursprüngliche Gespräch „{title}“ wieder her.','Restaure primeiro a conversa original de «{title}».'],
 ['business.daily.recover','恢复业务会话','恢復業務會話','Restore business conversation','業務の会話を復元','업무 대화 복원','Khôi phục cuộc trò chuyện','Restaurar conversación','Restaurer la conversation','Geschäftsgespräch wiederherstellen','Restaurar conversa'],
 ['business.daily.bindingPending','业务会话尚未完成归属，请先恢复原会话。','業務會話尚未完成歸屬，請先恢復原會話。','The business conversation is not linked yet. Restore it before sending.','業務の会話の紐付けが未完了です。先に元の会話を復元してください。','업무 대화가 아직 연결되지 않았습니다. 먼저 원래 대화를 복원하세요.','Cuộc trò chuyện chưa được liên kết. Hãy khôi phục trước khi gửi.','La conversación aún no está vinculada. Restáurala antes de enviar.','La conversation n’est pas encore liée. Restaurez-la avant d’envoyer.','Das Gespräch ist noch nicht verknüpft. Stellen Sie es vor dem Senden wieder her.','A conversa ainda não está vinculada. Restaure-a antes de enviar.'],
 ['business.daily.keepAndSwitch','保留草稿并切换','保留草稿並切換','Keep draft and switch','下書きを保持して切り替え','초안 유지 후 전환','Giữ bản nháp và chuyển','Conservar borrador y cambiar','Garder le brouillon et changer','Entwurf behalten und wechseln','Manter rascunho e mudar'],
 ['business.daily.readyWaiting','正在确认当前输入，请稍候…','正在確認目前輸入，請稍候…','Checking the current input. Please wait…','現在の入力を確認中です。お待ちください…','현재 입력 확인 중입니다. 잠시 기다려 주세요…','Đang kiểm tra nội dung nhập. Vui lòng đợi…','Comprobando la entrada actual. Espera…','Vérification de la saisie. Veuillez patienter…','Aktuelle Eingabe wird geprüft. Bitte warten…','A verificar a entrada atual. Aguarde…'],
] as const
