type Values=readonly [string,string,string,string,string,string,string,string,string,string]
type Row<K extends string=string>=readonly [K,...Values]
const r=<K extends string>(key:K,...values:Values):Row<K>=>[key,...values]

export const EDITION_MESSAGE_ROWS=[
 r('profile.account','账号','帳號','Account','アカウント','계정','Tài khoản','Cuenta','Compte','Konto','Conta'),
 r('profile.accountDescription','资料来自你当前登录的 Teloa 账号。','資料來自你目前登入的 Teloa 帳號。','Profile information comes from your signed-in Teloa account.','現在ログインしている Teloa アカウントのプロフィールです。','현재 로그인한 Teloa 계정의 프로필입니다.','Thông tin hồ sơ từ tài khoản Teloa đang đăng nhập.','Los datos provienen de tu cuenta de Teloa.','Ces informations proviennent de votre compte Teloa connecté.','Die Angaben stammen aus Ihrem angemeldeten Teloa-Konto.','Os dados vêm da sua conta Teloa autenticada.'),
 r('profile.manageAccount','管理账号','管理帳號','Manage account','アカウントを管理','계정 관리','Quản lý tài khoản','Gestionar cuenta','Gérer le compte','Konto verwalten','Gerir conta'),
 r('profile.manageFailed','账号页面暂时打不开，请稍后重试。','帳號頁面暫時無法開啟，請稍後重試。','The account page is unavailable. Please try again.','アカウント画面を開けません。後でもう一度お試しください。','계정 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.','Không mở được trang tài khoản. Vui lòng thử lại.','No se puede abrir la cuenta. Inténtalo de nuevo.','La page du compte est indisponible. Réessayez.','Die Kontoseite ist nicht verfügbar. Bitte versuchen Sie es erneut.','A página da conta está indisponível. Tente novamente.'),
 r('about.plans.current','当前版本','目前版本','Current version','現在のバージョン','현재 버전','Phiên bản hiện tại','Versión actual','Version actuelle','Aktuelle Version','Versão atual'),
 r('about.plans.available','可使用','可使用','Available','利用可能','사용 가능','Có thể sử dụng','Disponible','Disponible','Verfügbar','Disponível'),
 r("edition.gate.body","{action}是 Pro / Enterprise 功能，社区版只有一个工作空间。","{action}是 Pro / Enterprise 功能，社區版只有一個工作空間。","{action} is a Pro / Enterprise feature. Community has a single workspace.","{action}は Pro / Enterprise の機能です。Community のワークスペースは 1 つだけです。","{action}은(는) Pro / Enterprise 기능입니다. Community에는 작업 공간이 하나뿐입니다.","{action} là tính năng của Pro / Enterprise. Community chỉ có một không gian làm việc.","{action} es una función de Pro / Enterprise. Community solo tiene un espacio de trabajo.","{action} est une fonctionnalité Pro / Enterprise. Community ne comporte qu’un seul espace de travail.","{action} ist eine Funktion von Pro / Enterprise. Community hat nur einen Arbeitsbereich.","{action} é um recurso de Pro / Enterprise. Community tem apenas um espaço de trabalho."),
 r('edition.gate.feature.newSpace','新建空间','新增空間','New workspace','新しいワークスペース','새 작업 공간','Không gian làm việc mới','Nuevo espacio de trabajo','Nouvel espace de travail','Neuer Arbeitsbereich','Novo espaço de trabalho'),
 r('market.industry.load.personalDestination','加到 {domain} 这类业务里','加到 {domain} 這類業務裡','Add to your {domain} business','{domain} の業務に追加','{domain} 업무에 추가','Thêm vào nghiệp vụ {domain}','Añadir a tu negocio de {domain}','Ajouter à votre activité {domain}','Zu Ihrem {domain}-Geschäft hinzufügen','Adicionar ao seu negócio de {domain}'),
 r('market.industry.load.newSpace','新建空间…','新增空間…','New workspace…','新しいワークスペース…','새 작업 공간…','Không gian làm việc mới…','Nuevo espacio de trabajo…','Nouvel espace de travail…','Neuer Arbeitsbereich…','Novo espaço de trabalho…'),
 r("market.industry.saved.loadTemplateAria","方案 {name}","方案 {name}","Solution {name}","ソリューション {name}","솔루션 {name}","Giải pháp {name}","Solución {name}","Solution {name}","Lösung {name}","Solução {name}"),
 r('market.industry.saved.role.needsKnowledge','请先准备好员工所需的资料：{names}','請先準備好員工所需的資料：{names}','Prepare the resources this employee needs first: {names}','先にこの従業員に必要な資料を準備してください：{names}','먼저 이 직원에게 필요한 자료를 준비하세요: {names}','Hãy chuẩn bị trước tài liệu mà nhân viên này cần: {names}','Prepara primero los recursos que necesita este empleado: {names}','Préparez d’abord les ressources nécessaires à ce employé : {names}','Bereite zuerst die Unterlagen vor, die dieser Mitarbeiter benötigt: {names}','Prepare primeiro os recursos de que este funcionário precisa: {names}'),
 r('market.workspace.loadedPersonal','已加到我的业务里','已加到我的業務裡','Added to your business','業務に追加済み','업무에 추가됨','Đã thêm vào nghiệp vụ của bạn','Añadido a tu negocio','Ajouté à votre activité','Zu Ihrem Geschäft hinzugefügt','Adicionado ao seu negócio'),
 r('market.industry.load.spaceUnavailable','正在读取业务数据，读到之后才能加载。','正在讀取業務資料，讀到之後才能載入。','Reading your business data; loading becomes available once it’s read.','業務データを読み込み中です。読み込み後に実行できます。','업무 데이터를 읽는 중입니다. 읽은 뒤에 로드할 수 있습니다.','Đang đọc dữ liệu nghiệp vụ; có thể tải sau khi đọc xong.','Leyendo tus datos de negocio; podrás cargar cuando se hayan leído.','Lecture de vos données d’activité ; le chargement sera possible ensuite.','Ihre Geschäftsdaten werden gelesen; das Laden ist danach möglich.','A ler os seus dados de negócio; poderá carregar depois de lidos.'),
 r('market.industry.saved.scopeEmpty','当前业务还没有添加方案。','目前業務還沒有新增方案。','No solutions have been added to this business.','この業務にはまだソリューションが追加されていません。','이 업무에는 아직 솔루션이 추가되지 않았습니다.','Chưa có giải pháp nào được thêm vào nghiệp vụ này.','Aún no se han añadido soluciones a este negocio.','Aucune solution n’a encore été ajoutée à cette activité.','Zu diesem Geschäft wurden noch keine Lösungen hinzugefügt.','Ainda não foram adicionadas soluções a este negócio.'),
 r('navigation.twin','我的分身','我的分身','My twin','私の分身','내 분신','Bản sao của tôi','Mi doble','Mon double','Mein Avatar','Meu duplo'),
 // 三个版本为社区版 / Community、Pro 与 Enterprise；personal 保留为兼容协议值。
] as const
