type Row=readonly [string,string,string,string,string,string,string,string,string,string,string]
const r=(...row:Row)=>row

export const FORMAL_UI_P6_MESSAGE_ROWS=[
 r('p6.approvalNotes.unavailable','审批意见暂不可用。','審批意見暫時無法使用。','Approval notes are unavailable.','承認メモを利用できません。','승인 메모를 사용할 수 없습니다.','Ghi chú phê duyệt hiện không khả dụng.','Las notas de aprobación no están disponibles.','Les notes d’approbation sont indisponibles.','Genehmigungsnotizen sind nicht verfügbar.','As notas de aprovação não estão disponíveis.'),
 r('p6.guidedSetup.path','配置步骤','設定步驟','Setup steps','設定手順','설정 단계','Các bước thiết lập','Pasos de configuración','Étapes de configuration','Einrichtungsschritte','Passos de configuração'),
 r('p6.guidedSetup.complete','已完成','已完成','Done','完了','완료','Đã xong','Hecho','Terminé','Erledigt','Concluído'),
 r('p6.guidedSetup.current','当前','目前','Current','現在','현재','Hiện tại','Actual','Actuel','Aktuell','Atual'),
 r('p6.guidedSetup.upcoming','待完成','待完成','Next','次へ','다음','Tiếp theo','Siguiente','À suivre','Als Nächstes','Seguinte'),
 r('p6.preparedPrompt.aria.task','任务会话准备','任務對話準備','Task conversation setup','タスク会話の準備','작업 대화 준비','Chuẩn bị cuộc trò chuyện nhiệm vụ','Preparación de la conversación de tarea','Préparation de la conversation de tâche','Aufgabengespräch vorbereiten','Preparação da conversa da tarefa'),
 r('p6.preparedPrompt.aria.home','工作台会话准备','工作台對話準備','Workspace conversation setup','ワークスペース会話の準備','작업 공간 대화 준비','Chuẩn bị cuộc trò chuyện không gian làm việc','Preparación de la conversación del espacio de trabajo','Préparation de la conversation de l’espace de travail','Arbeitsbereichsgespräch vorbereiten','Preparação da conversa do espaço de trabalho'),
 r('p6.preparedPrompt.aria.market','市场会话准备','市集對話準備','Market conversation setup','マーケット会話の準備','마켓 대화 준비','Chuẩn bị cuộc trò chuyện từ chợ','Preparación de la conversación del mercado','Préparation de la conversation du marché','Market-Gespräch vorbereiten','Preparação da conversa do mercado'),
 r('p6.preparedPrompt.title','待带入的工作需求','待帶入的工作需求','Ready to add','追加する作業内容','추가할 작업 요청','Nội dung sẵn sàng thêm','Listo para añadir','Prêt à ajouter','Bereit zum Einfügen','Pronto para adicionar'),
 r('p6.preparedPrompt.description','核对目标与资料后再发送；不会安装、授权或覆盖当前草稿。','核對目標與資料後再傳送；不會安裝、授權或覆蓋目前草稿。','Review the goal and sources before sending. This won’t install, grant access, or replace your draft.','送信前に目標と資料を確認してください。インストール、権限付与、下書きの上書きは行いません。','보내기 전에 목표와 자료를 검토하세요. 설치, 권한 부여 또는 현재 초안 덮어쓰기는 하지 않습니다.','Kiểm tra mục tiêu và tài liệu trước khi gửi. Thao tác này không cài đặt, cấp quyền hay ghi đè bản nháp.','Revisa el objetivo y las fuentes antes de enviar. No se instalará nada, no se concederá acceso ni se reemplazará el borrador.','Vérifiez l’objectif et les sources avant l’envoi. Rien ne sera installé, aucun accès accordé et le brouillon ne sera pas remplacé.','Prüfen Sie Ziel und Quellen vor dem Senden. Es wird nichts installiert, freigegeben oder im Entwurf überschrieben.','Reveja o objetivo e as fontes antes de enviar. Nada será instalado, nenhum acesso será concedido e o rascunho não será substituído.'),
 r('p6.preparedPrompt.homeSource','{title} · 当时的目标','{title} · 當時的目標','{title} · Goal at that time','{title}・当時の目標','{title} · 당시 목표','{title} · Mục tiêu lúc đó','{title} · Objetivo en ese momento','{title} · Objectif à ce moment-là','{title} · Ziel zu diesem Zeitpunkt','{title} · Objetivo naquele momento'),
 r('p6.preparedPrompt.versionedSource','{title} · 来源草案 v{version}','{title} · 來源草稿 v{version}','{title} · Source draft v{version}','{title}・元の下書き v{version}','{title} · 원본 초안 v{version}','{title} · Bản nháp nguồn v{version}','{title} · Borrador de origen v{version}','{title} · Brouillon source v{version}','{title} · Quellentwurf v{version}','{title} · Rascunho de origem v{version}'),
 r('p6.preparedPrompt.review','查看准备内容','查看準備內容','Review content','内容を確認','내용 검토','Xem nội dung','Revisar contenido','Vérifier le contenu','Inhalt prüfen','Rever conteúdo'),
 r('p6.preparedPrompt.inserted','已带入','已帶入','Added','追加済み','추가됨','Đã thêm','Añadido','Ajouté','Hinzugefügt','Adicionado'),
 r('p6.preparedPrompt.reviewNeeded','待核对','待核對','Review','要確認','검토 필요','Cần kiểm tra','Revisar','À vérifier','Prüfen','Rever'),
 r('p6.preparedPrompt.removeSkill','移除技能：{name}','移除技能：{name}','Remove skill: {name}','スキルを削除：{name}','스킬 제거: {name}','Xóa kỹ năng: {name}','Quitar habilidad: {name}','Retirer la compétence : {name}','Skill entfernen: {name}','Remover competência: {name}'),
 r('p6.preparedPrompt.removeResource','移除：{title}','移除：{title}','Remove: {title}','削除：{title}','제거: {title}','Xóa: {title}','Quitar: {title}','Retirer : {title}','Entfernen: {title}','Remover: {title}'),
 r('p6.preparedPrompt.partial','目标文字已带入；继续操作只会添加剩余资料。','目標文字已帶入；繼續操作只會加入其餘資料。','The goal is already added. Continuing adds only the remaining sources.','目標は追加済みです。続行すると残りの資料だけが追加されます。','목표가 이미 추가되었습니다. 계속하면 남은 자료만 추가됩니다.','Mục tiêu đã được thêm. Tiếp tục chỉ thêm các tài liệu còn lại.','El objetivo ya está añadido. Al continuar solo se añadirán las fuentes restantes.','L’objectif est déjà ajouté. Continuer ajoutera uniquement les sources restantes.','Das Ziel wurde bereits eingefügt. Beim Fortfahren werden nur die übrigen Quellen hinzugefügt.','O objetivo já foi adicionado. Continuar adiciona apenas as fontes restantes.'),
 r('p6.preparedPrompt.stale','来源或目标已变化，请返回来源核对当前版本。','來源或目標已變更，請返回來源核對目前版本。','The source or goal changed. Return to the source and review the current version.','元の内容または目標が変更されました。元の画面で現在のバージョンを確認してください。','원본 또는 목표가 변경되었습니다. 원본으로 돌아가 현재 버전을 검토하세요.','Nguồn hoặc mục tiêu đã thay đổi. Quay lại nguồn để kiểm tra phiên bản hiện tại.','La fuente o el objetivo cambió. Vuelve al origen y revisa la versión actual.','La source ou l’objectif a changé. Revenez à la source pour vérifier la version actuelle.','Quelle oder Ziel wurden geändert. Kehren Sie zur Quelle zurück und prüfen Sie die aktuelle Version.','A fonte ou o objetivo mudou. Volte à origem e reveja a versão atual.'),
 r('p6.preparedPrompt.insert','带入输入框','帶入輸入框','Add to prompt','入力欄に追加','입력창에 추가','Thêm vào ô nhập','Añadir al mensaje','Ajouter au message','In Eingabe übernehmen','Adicionar à mensagem'),
 r('p6.preparedPrompt.backTask','返回任务','返回任務','Back to task','タスクに戻る','작업으로 돌아가기','Quay lại nhiệm vụ','Volver a la tarea','Retour à la tâche','Zurück zur Aufgabe','Voltar à tarefa'),
 r('p6.preparedPrompt.backHome','返回工作台','返回工作台','Back to workspace','ワークスペースに戻る','작업 공간으로 돌아가기','Quay lại không gian làm việc','Volver al espacio de trabajo','Retour à l’espace de travail','Zurück zum Arbeitsbereich','Voltar ao espaço de trabalho'),
 r('p6.preparedPrompt.backSource','返回来源','返回來源','Back to source','元の画面に戻る','원본으로 돌아가기','Quay lại nguồn','Volver al origen','Retour à la source','Zurück zur Quelle','Voltar à origem'),
 r('p6.preparedPrompt.dismiss','移除准备内容','移除準備內容','Dismiss','削除','닫기','Bỏ','Descartar','Ignorer','Verwerfen','Descartar'),
 r('p6.preparedPrompt.skillUnavailable','当前会话无法读取技能。','目前對話無法讀取技能。','Skills are unavailable in this conversation.','この会話ではスキルを利用できません。','이 대화에서는 스킬을 사용할 수 없습니다.','Cuộc trò chuyện này chưa dùng được kỹ năng.','Las habilidades no están disponibles en esta conversación.','Les compétences sont indisponibles dans cette conversation.','Skills sind in diesem Gespräch nicht verfügbar.','As competências não estão disponíveis nesta conversa.'),
 r('p6.preparedPrompt.inputUnavailable','输入框尚未就绪。','輸入框尚未就緒。','The prompt isn’t ready yet.','入力欄の準備ができていません。','입력창이 아직 준비되지 않았습니다.','Ô nhập chưa sẵn sàng.','El mensaje aún no está listo.','Le champ de saisie n’est pas encore prêt.','Die Eingabe ist noch nicht bereit.','O campo de entrada ainda não está pronto.'),
 r('p6.planSource.manual.label','手动创建','手動建立','Created manually','手動作成','직접 생성','Tạo thủ công','Creado manualmente','Créé manuellement','Manuell erstellt','Criado manualmente'),
 r('p6.planSource.manual.summary','由本人创建，未关联市场模板。','由本人建立，未關聯市集範本。','Created directly, with no market template linked.','マーケットテンプレートに紐づけず直接作成されました。','마켓 템플릿 연결 없이 직접 생성되었습니다.','Được tạo trực tiếp, không liên kết mẫu từ chợ.','Creado directamente, sin plantilla del mercado vinculada.','Créé directement, sans modèle du marché associé.','Direkt und ohne verknüpfte Market-Vorlage erstellt.','Criado diretamente, sem modelo do mercado associado.'),
 r('p6.planSource.market.label','市场模板','市集範本','Market template','マーケットテンプレート','마켓 템플릿','Mẫu từ chợ','Plantilla del mercado','Modèle du marché','Market-Vorlage','Modelo do mercado'),
 r('p6.planSource.market.summary','基于已保存的市场内容创建。','根據已儲存的市集內容建立。','Created from saved market content.','保存済みのマーケットコンテンツから作成されました。','저장된 마켓 콘텐츠로 생성되었습니다.','Được tạo từ nội dung chợ đã lưu.','Creado a partir de contenido guardado del mercado.','Créé à partir d’un contenu enregistré du marché.','Aus gespeicherten Market-Inhalten erstellt.','Criado a partir de conteúdo guardado do mercado.'),
] as const

function assertLocaleRows(rows:readonly Row[]){for(const row of rows)if(row.length!==11||row.slice(1).some(value=>!value.trim()))throw new Error(`invalid locale row: ${row[0]}`)}
assertLocaleRows(FORMAL_UI_P6_MESSAGE_ROWS)
