// 群提及一期（2026-09-21 AutoDream一期与群提及 功能验证）。
// 明确不新增：`group.task.noAssigneeWarning` / `group.task.grantStatus` 已在 0 期落地为 `collaboration.task.assigneeHint` / `collaboration.task.grantMissing`，复用既有两条，不再重复。
// 明确不新增：`group.relay.*` 属 2 期范围，本计划不加。
// 正文 @ 触发改造（2026-09-21）新增一条：`group.mention.allName`——正文里插入的 @全员 标记词，与候选项标签 `group.mention.all` 分开，标记词要短。
// 用户裁定 B（2026-09-21）新增一条：`group.task.scopeHint`——群成员不限业务范围，但建任务负责人必须支持本群范围（tasks.ts:107），候选按范围过滤，这里给一句静态说明。
// 11 列：[key, zh-CN, zh-Hant, en, ja, ko, vi, es, fr, de, pt]。
export const GROUP_MENTION_MESSAGE_ROWS = [
 ['group.mention.pick','提及员工','提及員工','Mention an employee','従業員をメンション','직원 멘션','Nhắc đến nhân viên','Mencionar a un empleado','Mentionner un employé','Mitarbeiter erwähnen','Mencionar um funcionário'],
 ['group.mention.limit','一条消息最多提及 8 位员工。','一則訊息最多提及 8 位員工。','A single message can mention up to 8 employees.','1 件のメッセージで最大 8 人までメンションできます。','메시지 한 건에 직원을 최대 8명까지 멘션할 수 있습니다.','Một tin nhắn chỉ nhắc đến tối đa 8 nhân viên.','Un mensaje puede mencionar hasta 8 empleados.','Un message peut mentionner jusqu’à 8 employés.','Eine Nachricht kann höchstens 8 Mitarbeitende erwähnen.','Uma mensagem pode mencionar até 8 funcionários.'],
 ['group.mention.notMember','该员工不在本群，无法提及。','該員工不在本群，無法提及。','This employee isn’t in the group, so they can’t be mentioned.','この従業員はこのグループにいないため、メンションできません。','이 직원은 이 그룹에 없어 멘션할 수 없습니다.','Nhân viên này không có trong nhóm nên không thể nhắc đến.','Este empleado no está en el grupo, así que no se puede mencionar.','Ce employé n’est pas dans le groupe, il ne peut donc pas être mentionné.','Diese Mitarbeiterin oder dieser Mitarbeiter ist nicht in der Gruppe und kann daher nicht erwähnt werden.','Este funcionário não está no grupo, por isso não pode ser mencionado.'],
 ['group.mention.formOpened','已为你打开建任务表单，负责人已填好。','已為你開啟建立任務表單，負責人已填好。','The task form is open for you, with the owner already filled in.','タスク作成フォームを開きました。担当者は入力済みです。','작업 생성 양식을 열었습니다. 담당자는 이미 입력되어 있습니다.','Đã mở biểu mẫu tạo nhiệm vụ cho bạn, người phụ trách đã được điền sẵn.','Se abrió el formulario para crear la tarea; el responsable ya está completado.','Le formulaire de création de tâche est ouvert pour vous, avec le responsable déjà renseigné.','Das Formular zum Erstellen der Aufgabe ist geöffnet; die Zuständigkeit ist bereits ausgefüllt.','O formulário de criação de tarefa foi aberto para você, com o responsável já preenchido.'],
 ['group.mention.readyOnly','提及只会新建待办任务，不会自动开始、完成或审批。','提及只會建立待辦任務，不會自動開始、完成或審批。','Mentioning only creates a pending task; it never starts, completes, or approves anything automatically.','メンションは未着手タスクを作成するだけで、自動的に開始・完了・承認されることはありません。','멘션은 대기 중인 작업만 생성하며 자동으로 시작, 완료, 승인되지 않습니다.','Nhắc đến chỉ tạo một nhiệm vụ đang chờ; sẽ không tự động bắt đầu, hoàn tất hay phê duyệt.','Mencionar solo crea una tarea pendiente; nunca se inicia, completa ni aprueba automáticamente.','Mentionner ne fait que créer une tâche en attente ; rien n’est jamais démarré, terminé ou approuvé automatiquement.','Eine Erwähnung erstellt nur eine ausstehende Aufgabe; nichts wird automatisch gestartet, abgeschlossen oder genehmigt.','Mencionar apenas cria uma tarefa pendente; nada é iniciado, concluído ou aprovado automaticamente.'],
 ['group.mention.all','提及全员','提及全員','Mention everyone','全員をメンション','전체 멘션','Nhắc đến tất cả','Mencionar a todos','Mentionner tout le monde','Alle erwähnen','Mencionar todos'],
 ['group.mention.allName','全员','全員','everyone','全員','전체','tất cả','todos','tout-le-monde','alle','todos'],
 ['group.mention.allNotice','已通知全员，员工会各自回应。','已通知全員，員工會各自回應。','Everyone has been notified; employees will each respond.','全員に通知しました。それぞれの従業員が返信します。','전체에 알림을 보냈으며 직원들이 각자 답변합니다.','Đã thông báo cho tất cả; từng nhân viên sẽ phản hồi.','Se notificó a todos; cada empleado responderá por su cuenta.','Tout le monde a été notifié ; chaque employé répondra.','Alle wurden benachrichtigt; jede Mitarbeiterin und jeder Mitarbeiter wird antworten.','Todos foram notificados; cada funcionário responderá.'],
 ['group.grant.canAutoRun','允许本群自动开始运行','允許本群自動開始執行','Allow this group to start runs automatically','このグループでの自動実行開始を許可','이 그룹에서 자동 실행 시작 허용','Cho phép nhóm này tự động bắt đầu chạy','Permitir que este grupo inicie ejecuciones automáticamente','Autoriser ce groupe à démarrer automatiquement les exécutions','Dieser Gruppe erlauben, Ausführungen automatisch zu starten','Permitir que este grupo inicie execuções automaticamente'],
 ['group.grant.canAutoRunHint','关掉时，提及这位员工只会新建待办任务。','關掉時，提及這位員工只會建立待辦任務。','When this is off, mentioning this employee only creates a pending task.','オフのときは、この従業員をメンションしても未着手タスクが作成されるだけです。','꺼져 있으면 이 직원을 멘션해도 대기 중인 작업만 생성됩니다.','Khi tắt, việc nhắc đến nhân viên này chỉ tạo một nhiệm vụ đang chờ.','Cuando está desactivado, mencionar a este empleado solo crea una tarea pendiente.','Lorsque c’est désactivé, mentionner ce employé ne fait que créer une tâche en attente.','Ist dies deaktiviert, erstellt eine Erwähnung dieser Mitarbeiterin oder dieses Mitarbeiter nur eine ausstehende Aufgabe.','Quando desativado, mencionar este funcionário apenas cria uma tarefa pendente.'],
 ['group.task.scopeHint','只有支持本群业务范围的员工才能作为负责人。','只有支援本群業務範圍的員工才能作為負責人。','Only employees who support this group’s business scope can be the owner.','このグループの業務範囲に対応する従業員だけが担当者になれます。','이 그룹의 업무 범위를 지원하는 직원만 담당자가 될 수 있습니다.','Chỉ nhân viên hỗ trợ phạm vi nghiệp vụ của nhóm này mới có thể làm người phụ trách.','Solo los empleados que admiten el ámbito empresarial de este grupo pueden ser el responsable.','Seuls les employés prenant en charge le périmètre métier de ce groupe peuvent être responsables.','Nur Mitarbeitende, die den Geschäftsbereich dieser Gruppe unterstützen, können die Zuständigkeit übernehmen.','Apenas funcionários que suportam o âmbito de negócio deste grupo podem ser o responsável.'],
] as const
