// 群附件一期（2026-09-21 群附件与三类引用 功能验证）。
// `collaboration.attachment.pending` 原本逐字复用 `capabilities.attachments.pending`
// （`locales/formal-ui-residual.ts:82`）的「仅在本页暂存」措辞，T12 修复轮 1 改掉：群里的待发送附件
// 存在跨挂载的草稿仓（`saved-collaboration-drafts.ts` 的模块级单例），切页面／回话题都不丢，只是不跨
// 刷新，「仅在本页暂存」与实际行为不符。两处不再同文，`capabilities.*` 那条维持原样。
// `collaboration.attachment.withdrawConfirm` 的中文逐字含「已存的字节不会被删除。」（用户 Q3 裁定）。
// `collaboration.attachment.unsupported` 把 GIF 归在文件一侧，不在图片集合里（编排者裁定 1）。
// 单件超限按类型分两条：`imageTooLarge`（8 MiB）与 `fileTooLarge`（16 MiB，GIF 走这条），数字与契约两档逐字一致。
// `collaboration.attachment.modelNoVision` / `collaboration.attachment.partialFailed` 的中文
// 与后端 `task-run-group-context.ts` 里的同名常量逐字相同，由宿主在回帖正文前拼接，不进一步本地化。
// 11 列：[key, zh-CN, zh-Hant, en, ja, ko, vi, es, fr, de, pt]。
export const GROUP_ATTACHMENT_MESSAGE_ROWS = [
 ['collaboration.attachment.add','附件','附件','Attachment','添付ファイル','첨부 파일','Tệp đính kèm','Adjunto','Pièce jointe','Anhang','Anexo'],
 ['collaboration.attachment.dropHint','把图片或文件拖到这里','把圖片或檔案拖到這裡','Drop images or files here','画像やファイルをここにドラッグ','이미지나 파일을 여기로 끌어다 놓으세요','Kéo hình ảnh hoặc tệp vào đây','Arrastra imágenes o archivos aquí','Déposez des images ou des fichiers ici','Bilder oder Dateien hierher ziehen','Arraste imagens ou ficheiros para aqui'],
 ['collaboration.attachment.uploading','上传中…','上傳中…','Uploading…','アップロード中…','업로드 중…','Đang tải lên…','Subiendo…','Téléversement…','Wird hochgeladen…','A carregar…'],
 ['collaboration.attachment.retry','上传失败 · 重试','上傳失敗 · 重試','Upload failed · Retry','アップロード失敗 · 再試行','업로드 실패 · 다시 시도','Tải lên thất bại · Thử lại','Error al subir · Reintentar','Échec du téléversement · Réessayer','Hochladen fehlgeschlagen · Erneut versuchen','Falha ao carregar · Tentar novamente'],
 ['collaboration.attachment.remove','移除 {name}','移除 {name}','Remove {name}','{name} を削除','{name} 제거','Xóa {name}','Quitar {name}','Retirer {name}','{name} entfernen','Remover {name}'],
 ['collaboration.attachment.pending','{count} 个待发送附件在切换页面后仍会保留，刷新后需重新添加。','{count} 個待傳送附件在切換頁面後仍會保留，重新整理後需重新加入。','{count} pending attachments are kept when you switch pages, but must be added again after refresh.','未送信の添付ファイル {count} 件はページを切り替えても保持されますが、更新後は再追加が必要です。','보내지 않은 첨부 파일 {count}개는 페이지를 전환해도 유지되지만 새로고침 후에는 다시 추가해야 합니다.','{count} tệp đính kèm đang chờ vẫn được giữ khi bạn chuyển trang, nhưng phải thêm lại sau khi tải lại.','{count} adjuntos pendientes se conservan al cambiar de página, pero deben añadirse de nuevo tras actualizar.','{count} pièces jointes en attente sont conservées lorsque vous changez de page, mais devront être ajoutées de nouveau après actualisation.','{count} ausstehende Anhänge bleiben beim Seitenwechsel erhalten, müssen nach dem Aktualisieren aber erneut hinzugefügt werden.','{count} anexos pendentes são mantidos ao mudar de página, mas têm de ser adicionados novamente após atualizar.'],
 ['collaboration.attachment.imageTooLarge','单张图片不能超过 8 MiB。','單張圖片不能超過 8 MiB。','A single image can’t exceed 8 MiB.','画像 1 枚は 8 MiB を超えられません。','이미지 한 장은 8 MiB를 넘을 수 없습니다.','Một hình ảnh không được vượt quá 8 MiB.','Una sola imagen no puede superar los 8 MiB.','Une image ne peut pas dépasser 8 Mio.','Ein einzelnes Bild darf 8 MiB nicht überschreiten.','Uma única imagem não pode exceder 8 MiB.'],
 ['collaboration.attachment.fileTooLarge','单个文件不能超过 16 MiB。','單一檔案不能超過 16 MiB。','A single file can’t exceed 16 MiB.','ファイル 1 件は 16 MiB を超えられません。','파일 하나는 16 MiB를 넘을 수 없습니다.','Một tệp không được vượt quá 16 MiB.','Un solo archivo no puede superar los 16 MiB.','Un fichier ne peut pas dépasser 16 Mio.','Eine einzelne Datei darf 16 MiB nicht überschreiten.','Um único ficheiro não pode exceder 16 MiB.'],
 ['collaboration.attachment.tooMany','一条消息最多引用 8 项。','一則訊息最多引用 8 項。','A single message can reference up to 8 items.','1 件のメッセージで参照できるのは最大 8 件です。','메시지 한 건에는 최대 8개까지 참조할 수 있습니다.','Một tin nhắn chỉ tham chiếu tối đa 8 mục.','Un mensaje puede referenciar hasta 8 elementos.','Un message peut référencer jusqu’à 8 éléments.','Eine Nachricht kann höchstens 8 Elemente referenzieren.','Uma mensagem pode referenciar até 8 itens.'],
 ['collaboration.attachment.unsupported','只接受 PNG／JPEG／WebP 图片与 GIF／PDF／TXT／Markdown／CSV／JSON／日志文件。','只接受 PNG／JPEG／WebP 圖片與 GIF／PDF／TXT／Markdown／CSV／JSON／日誌檔案。','Only PNG/JPEG/WebP images and GIF/PDF/TXT/Markdown/CSV/JSON/log files are accepted.','対応するのは PNG／JPEG／WebP 画像と GIF／PDF／TXT／Markdown／CSV／JSON／ログファイルのみです。','PNG／JPEG／WebP 이미지와 GIF／PDF／TXT／Markdown／CSV／JSON／로그 파일만 허용됩니다.','Chỉ chấp nhận hình ảnh PNG／JPEG／WebP và tệp GIF／PDF／TXT／Markdown／CSV／JSON／nhật ký.','Solo se aceptan imágenes PNG／JPEG／WebP y archivos GIF／PDF／TXT／Markdown／CSV／JSON／de registro.','Seules les images PNG／JPEG／WebP et les fichiers GIF／PDF／TXT／Markdown／CSV／JSON／journaux sont acceptés.','Es werden nur PNG-/JPEG-/WebP-Bilder sowie GIF-/PDF-/TXT-/Markdown-/CSV-/JSON-/Protokolldateien akzeptiert.','Só são aceites imagens PNG／JPEG／WebP e ficheiros GIF／PDF／TXT／Markdown／CSV／JSON／de registo.'],
 ['collaboration.attachment.nameMismatch','文件名的扩展名与文件类型不一致，请改回正确的扩展名。','檔名的副檔名與檔案類型不一致，請改回正確的副檔名。','The file name’s extension doesn’t match its file type; please change it back to the correct extension.','ファイル名の拡張子がファイル形式と一致しません。正しい拡張子に戻してください。','파일 이름의 확장자가 파일 형식과 일치하지 않습니다. 올바른 확장자로 다시 바꿔 주세요.','Phần mở rộng của tên tệp không khớp với loại tệp; vui lòng đổi lại thành phần mở rộng đúng.','La extensión del nombre del archivo no coincide con su tipo; cámbiela de nuevo a la extensión correcta.','L’extension du nom de fichier ne correspond pas à son type ; veuillez la remettre à l’extension correcte.','Die Dateiendung stimmt nicht mit dem Dateityp überein; bitte auf die richtige Endung zurücksetzen.','A extensão do nome do ficheiro não corresponde ao seu tipo; reponha a extensão correta.'],
 ['collaboration.attachment.groupFull','附件总量已达上限，请先撤回不再需要的附件。','附件總量已達上限，請先撤回不再需要的附件。','The attachment total has reached the limit; withdraw attachments you no longer need first.','添付ファイルの総容量が上限に達しました。不要な添付ファイルを先に撤回してください。','첨부 파일 총량이 한도에 도달했습니다. 더 이상 필요하지 않은 첨부 파일을 먼저 철회하세요.','Tổng dung lượng tệp đính kèm đã đạt giới hạn; hãy rút các tệp không còn cần trước.','El total de adjuntos alcanzó el límite; retire primero los que ya no necesite.','Le total des pièces jointes a atteint la limite ; retirez d’abord celles dont vous n’avez plus besoin.','Die Gesamtmenge der Anhänge hat das Limit erreicht; ziehen Sie zuerst nicht mehr benötigte Anhänge zurück.','O total de anexos atingiu o limite; retire primeiro os que já não são necessários.'],
 ['collaboration.attachment.open','查看大图 {name}','檢視大圖 {name}','View full image {name}','画像を拡大表示 {name}','큰 이미지 보기 {name}','Xem ảnh lớn {name}','Ver imagen ampliada {name}','Voir l’image en grand {name}','Großansicht von {name}','Ver imagem ampliada {name}'],
 ['collaboration.attachment.dialogTitle','{name}','{name}','{name}','{name}','{name}','{name}','{name}','{name}','{name}','{name}'],
 ['collaboration.attachment.close','关闭大图','關閉大圖','Close full image','拡大表示を閉じる','큰 이미지 닫기','Đóng ảnh lớn','Cerrar imagen ampliada','Fermer l’image agrandie','Großansicht schließen','Fechar imagem ampliada'],
 ['collaboration.attachment.download','下载 {name}','下載 {name}','Download {name}','{name} をダウンロード','{name} 다운로드','Tải xuống {name}','Descargar {name}','Télécharger {name}','{name} herunterladen','Transferir {name}'],
 ['collaboration.attachment.size','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}','{size} · {type}'],
 ['collaboration.attachment.withdraw','撤回附件','撤回附件','Withdraw attachment','添付ファイルを撤回','첨부 파일 철회','Rút tệp đính kèm','Retirar adjunto','Retirer la pièce jointe','Anhang zurückziehen','Retirar anexo'],
 ['collaboration.attachment.withdrawConfirm','撤回后本人与员工都不能再读取它；已存的字节不会被删除。','撤回後本人與員工都不能再讀取它；已存的位元組不會被刪除。','After withdrawal, neither you nor your employees can read it anymore; the stored bytes are not deleted.','撤回すると本人も従業員も読み取れなくなります。保存済みのバイトは削除されません。','철회하면 본인과 직원 모두 더 이상 읽을 수 없습니다. 저장된 바이트는 삭제되지 않습니다.','Sau khi rút, cả bạn và nhân viên đều không thể đọc lại nó; các byte đã lưu sẽ không bị xóa.','Tras retirarlo, ni usted ni sus empleados podrán volver a leerlo; los bytes almacenados no se eliminan.','Après le retrait, ni vous ni vos employés ne pourrez plus le lire ; les octets déjà stockés ne sont pas supprimés.','Nach dem Zurückziehen können weder Sie noch Ihre Mitarbeitende darauf zugreifen; die gespeicherten Bytes werden nicht gelöscht.','Depois de retirado, nem você nem os funcionários podem voltar a lê-lo; os bytes armazenados não são eliminados.'],
 ['collaboration.attachment.withdrawn','该附件已撤回','該附件已撤回','This attachment has been withdrawn','この添付ファイルは撤回されました','이 첨부 파일은 철회되었습니다','Tệp đính kèm này đã bị rút','Este adjunto se retiró','Cette pièce jointe a été retirée','Dieser Anhang wurde zurückgezogen','Este anexo foi retirado'],
 ['collaboration.reference.resourceWithdrawn','该资料已撤回','該資料已撤回','This material has been withdrawn','この資料は撤回されました','이 자료는 철회되었습니다','Tài liệu này đã bị rút','Este material se retiró','Ce document a été retiré','Dieses Material wurde zurückgezogen','Este material foi retirado'],
 ['collaboration.reference.artifactUnavailable','该成果不可用','該成果不可用','This result is unavailable','この成果は利用できません','이 결과는 사용할 수 없습니다','Kết quả này không khả dụng','Este resultado no está disponible','Ce résultat n’est pas disponible','Dieses Ergebnis ist nicht verfügbar','Este resultado está indisponível'],
 ['collaboration.reference.artifactCard','成果 {title} · v{version} · {count} 个文件','成果 {title} · v{version} · {count} 個檔案','Result {title} · v{version} · {count} files','成果 {title} · v{version} · ファイル {count} 件','결과 {title} · v{version} · 파일 {count}개','Kết quả {title} · v{version} · {count} tệp','Resultado {title} · v{version} · {count} archivos','Résultat {title} · v{version} · {count} fichiers','Ergebnis {title} · v{version} · {count} Dateien','Resultado {title} · v{version} · {count} ficheiros'],
 ['collaboration.reference.openArtifact','在成果里查看','在成果裡檢視','View in results','成果で確認','결과에서 보기','Xem trong kết quả','Ver en resultados','Voir dans les résultats','In den Ergebnissen ansehen','Ver nos resultados'],
 ['collaboration.attachment.modelNoVision','【本轮模型没有读图能力，以下回答只基于文件名与元数据，未看到图片内容。】','【本輪模型沒有讀圖能力，以下回答只根據檔名與中繼資料，未看到圖片內容。】','[The model in this run cannot see images; the following answer is based only on file names and metadata, not image content.]','【今回のモデルには画像を読む能力がなく、以下の回答はファイル名とメタデータのみに基づき、画像の内容は見ていません。】','【이번 실행의 모델은 이미지를 읽을 수 없어, 아래 답변은 파일 이름과 메타데이터에만 근거하며 이미지 내용은 보지 못했습니다.】','【Mô hình của lượt chạy này không có khả năng đọc ảnh; câu trả lời sau chỉ dựa trên tên tệp và siêu dữ liệu, không nhìn thấy nội dung ảnh.】','【El modelo de esta ejecución no puede leer imágenes; la siguiente respuesta se basa solo en el nombre del archivo y los metadatos, sin ver el contenido de la imagen.】','【Le modèle de cette exécution ne peut pas lire les images ; la réponse suivante se fonde uniquement sur le nom du fichier et les métadonnées, sans avoir vu le contenu de l’image.】','【Das Modell dieses Laufs kann keine Bilder lesen; die folgende Antwort basiert nur auf Dateiname und Metadaten, ohne den Bildinhalt gesehen zu haben.】','【O modelo desta execução não consegue ler imagens; a resposta a seguir baseia-se apenas no nome do ficheiro e nos metadados, sem ver o conteúdo da imagem.】'],
 ['collaboration.attachment.partialFailed','【有 {count} 件文件未能贴出。】','【有 {count} 件檔案未能貼出。】','[{count} files could not be posted.]','【{count} 件のファイルを貼り出せませんでした。】','【{count}개 파일을 게시하지 못했습니다.】','【Có {count} tệp không thể đăng.】','【No se pudieron publicar {count} archivos.】','【{count} fichiers n’ont pas pu être publiés.】','【{count} Dateien konnten nicht gepostet werden.】','【{count} ficheiros não puderam ser publicados.】'],
 ['collaboration.access.materials.title','资料与文件','資料與檔案','Materials and files','資料とファイル','자료 및 파일','Tài liệu và tệp','Materiales y archivos','Documents et fichiers','Material und Dateien','Materiais e ficheiros'],
 ['collaboration.attachment.section','文件','檔案','Files','ファイル','파일','Tệp','Archivos','Fichiers','Dateien','Ficheiros'],
 ['collaboration.attachment.sectionEmpty','这个群还没有文件。','這個群組還沒有檔案。','This group has no files yet.','このグループにはまだファイルがありません。','이 그룹에는 아직 파일이 없습니다.','Nhóm này chưa có tệp nào.','Este grupo aún no tiene archivos.','Ce groupe n’a pas encore de fichiers.','Diese Gruppe hat noch keine Dateien.','Este grupo ainda não tem ficheiros.'],
 ['collaboration.attachment.sectionHint','这里列的是在本群上传的文件；被本群消息引用的成果在消息里查看。文件上传后不能修改；员工默认看不见，需要在「员工授权」里逐条勾选。','這裡列出的是在本群上傳的檔案；被本群訊息引用的成果請在訊息裡檢視。檔案上傳後不能修改；員工預設看不見，需要在「員工授權」裡逐條勾選。','This lists files uploaded in this group; results referenced by group messages are viewed in the message itself. Files cannot be changed after upload; employees can’t see them by default and must be checked one by one in “Employee permissions.”','ここに表示されるのはこのグループでアップロードされたファイルです。グループのメッセージが参照する成果はメッセージ内で確認してください。ファイルはアップロード後に変更できません。従業員は既定では見えず、「従業員の権限」で個別にチェックする必要があります。','여기에는 이 그룹에서 업로드한 파일이 나열됩니다. 그룹 메시지가 참조하는 결과는 메시지에서 확인하세요. 파일은 업로드 후 변경할 수 없습니다. 직원은 기본적으로 볼 수 없으며 "직원 권한"에서 하나씩 선택해야 합니다.','Đây là danh sách các tệp đã tải lên trong nhóm này; kết quả được tin nhắn nhóm tham chiếu thì xem trong tin nhắn. Tệp không thể thay đổi sau khi tải lên; nhân viên mặc định không thấy được, cần chọn từng mục trong "Ủy quyền nhân viên".','Aquí se listan los archivos subidos en este grupo; los resultados referenciados por los mensajes del grupo se ven en el propio mensaje. Los archivos no se pueden cambiar después de subirlos; los empleados no los ven de forma predeterminada y deben marcarse uno por uno en “Permisos del empleado”.','Cette liste présente les fichiers téléversés dans ce groupe ; les résultats référencés par les messages du groupe se consultent dans le message lui-même. Les fichiers ne peuvent plus être modifiés après le téléversement ; les employés ne les voient pas par défaut et doivent être cochés un par un dans « Autorisations du employé ».','Hier werden die in dieser Gruppe hochgeladenen Dateien aufgelistet; Ergebnisse, auf die Gruppennachrichten verweisen, werden in der Nachricht selbst angezeigt. Dateien können nach dem Hochladen nicht mehr geändert werden; Mitarbeiter sehen sie standardmäßig nicht und müssen in „Berechtigungen der Mitarbeiter“ einzeln angehakt werden.','Aqui aparecem os ficheiros carregados neste grupo; os resultados referenciados pelas mensagens do grupo veem-se na própria mensagem. Os ficheiros não podem ser alterados depois de carregados; os funcionários não os veem por predefinição e têm de ser marcados um a um em "Permissões do funcionário".'],
 ['collaboration.grant.section.resources','资料','資料','Materials','資料','자료','Tài liệu','Materiales','Documents','Material','Materiais'],
 ['collaboration.grant.section.attachments','文件','檔案','Files','ファイル','파일','Tệp','Archivos','Fichiers','Dateien','Ficheiros'],
 ['collaboration.grant.section.artifacts','成果','成果','Results','成果','결과','Kết quả','Resultados','Résultats','Ergebnisse','Resultados'],
 ['collaboration.grant.section.artifactsEmpty','群里还没有出现过成果引用。','群組裡還沒有出現過成果引用。','No results have been referenced in this group yet.','このグループではまだ成果への参照が出ていません。','이 그룹에는 아직 결과 참조가 나온 적이 없습니다.','Nhóm này chưa từng xuất hiện tham chiếu kết quả nào.','Este grupo aún no tiene ninguna referencia a resultados.','Ce groupe n’a encore reçu aucune référence à un résultat.','In dieser Gruppe wurde noch kein Ergebnis referenziert.','Este grupo ainda não teve nenhuma referência a resultados.'],
 ['collaboration.grant.canPost.attachmentNote','允许发言时，它也能把本次运行产出的文件定版成成果并贴回群；它不能贴别处的文件。','允許發言時，它也能把本次執行產出的檔案定版成成果並貼回群組；它不能貼別處的檔案。','When posting is allowed, it can also finalize files produced by this run into a result and post it back to the group; it cannot post files from anywhere else.','発言を許可すると、今回の実行で生成したファイルを成果として確定しグループに貼り戻すこともできます。他の場所のファイルは貼り出せません。','게시가 허용되면 이번 실행에서 생성된 파일을 결과로 확정해 그룹에 다시 게시할 수도 있습니다. 다른 곳의 파일은 게시할 수 없습니다.','Khi được phép đăng, nó cũng có thể chốt các tệp do lần chạy này tạo ra thành kết quả và đăng lại vào nhóm; nó không thể đăng tệp từ nơi khác.','Cuando se permite publicar, también puede finalizar los archivos producidos en esta ejecución como un resultado y publicarlo de nuevo en el grupo; no puede publicar archivos de otro lugar.','Lorsque la publication est autorisée, il peut aussi finaliser les fichiers produits par cette exécution en un résultat et le republier dans le groupe ; il ne peut pas publier de fichiers provenant d’ailleurs.','Wenn das Posten erlaubt ist, kann es auch die in diesem Lauf erzeugten Dateien zu einem Ergebnis finalisieren und in die Gruppe zurückposten; Dateien von anderswo kann es nicht posten.','Quando a publicação é permitida, também pode finalizar os ficheiros produzidos por esta execução num resultado e publicá-lo de volta no grupo; não pode publicar ficheiros de outro lugar.'],
] as const
