// 市场方案卡与产品页（规格 §5.2/§5.3）的固定文案，落点见 T6/T7 报告：MarketPage.tsx、SolutionCards.tsx
// 已经在用这批键，词表值集中留给 T8 一次性补齐，避免两次返工。11 列按 core-pages.ts 的既定顺序：
// key, zh-CN, zh-Hant, en, ja, ko, vi, es, fr, de, pt。
export const MARKET_SOLUTION_MESSAGE_ROWS = [
  ['market.solution.addedTab','已添加','已新增','Added','追加済み','추가됨','Đã thêm','Añadidos','Ajoutés','Hinzugefügt','Adicionados'],
  ['market.solution.addedDescription','已经加入你团队的方案。','已經加入你團隊的方案。','Solutions already added to your team.','チームに追加済みのソリューションです。','팀에 이미 추가된 솔루션입니다.','Các giải pháp đã được thêm vào nhóm của bạn.','Soluciones ya añadidas a tu equipo.','Solutions déjà ajoutées à votre équipe.','Bereits zu Ihrem Team hinzugefügte Lösungen.','Soluções já adicionadas à sua equipa.'],
  ['market.solution.addedEmptyTitle','还没有添加方案','還沒有新增方案','No solutions added yet','追加済みのソリューションはありません','아직 추가된 솔루션이 없습니다','Chưa có giải pháp nào được thêm','Aún no has añadido soluciones','Aucune solution ajoutée pour le moment','Noch keine Lösungen hinzugefügt','Ainda não adicionou soluções'],
  ['market.solution.addedEmptyDescription','从方案开始，按一整套工作方式加入员工、能力、接入、计划和资料。','從方案開始，按一整套工作方式加入員工、能力、接入、計畫和資料。','Start with a solution to add employees, capabilities, connections, schedules, and materials as one working setup.','ソリューションから始めると、従業員、機能、接続、予定、資料をひとつの仕事の仕組みとして追加できます。','솔루션으로 시작하면 직원, 역량, 연결, 일정, 자료를 하나의 업무 구성으로 추가할 수 있습니다.','Bắt đầu từ giải pháp để thêm nhân viên, năng lực, kết nối, lịch và tài liệu thành một cách làm việc hoàn chỉnh.','Empieza con una solución para añadir empleados, capacidades, conexiones, planes y materiales como una forma de trabajo completa.','Commencez par une solution pour ajouter employés, capacités, connexions, plans et documents comme un mode de travail complet.','Beginnen Sie mit einer Lösung, um Mitarbeitende, Fähigkeiten, Verbindungen, Pläne und Materialien als Arbeitsweise hinzuzufügen.','Comece com uma solução para adicionar funcionários, capacidades, ligações, planos e materiais como uma forma de trabalho completa.'],
  ['market.solution.browseSolutions','查看方案','查看方案','Browse solutions','ソリューションを見る','솔루션 보기','Xem giải pháp','Ver soluciones','Voir les solutions','Lösungen ansehen','Ver soluções'],
  ['market.solution.ask','问一问','問一問','Ask','聞いてみる','물어보기','Hỏi thử','Preguntar','Demander','Nachfragen','Perguntar'],
  ['market.solution.askDraft','我想找一个能帮我做 {query} 的方案，有推荐吗？','我想找一個能幫我做 {query} 的方案，有推薦嗎？','I’m looking for a solution that can help me with {query}. Any recommendations?','{query} を手伝ってくれる方案を探しています。おすすめはありますか？','{query}을(를) 도와줄 방안을 찾고 있어요. 추천해 주실 수 있나요?','Tôi đang tìm một giải pháp giúp tôi làm {query}. Bạn có gợi ý nào không?','Busco una solución que me ayude con {query}. ¿Alguna recomendación?','Je cherche une solution pour m’aider à {query}. Avez-vous des recommandations ?','Ich suche eine Lösung, die mir bei {query} hilft. Haben Sie Empfehlungen?','Procuro uma solução que me ajude com {query}. Tem recomendações?'],
  ['market.solution.askDraftEmpty','我想找一个适合我的方案，有推荐吗？','我想找一個適合我的方案，有推薦嗎？','I’m looking for a solution that fits me. Any recommendations?','自分に合う方案を探しています。おすすめはありますか？','저에게 맞는 방안을 찾고 있어요. 추천해 주실 수 있나요?','Tôi đang tìm một giải pháp phù hợp với mình. Bạn có gợi ý nào không?','Busco una solución que me convenga. ¿Alguna recomendación?','Je cherche une solution qui me convienne. Avez-vous des recommandations ?','Ich suche eine Lösung, die zu mir passt. Haben Sie Empfehlungen?','Procuro uma solução adequada para mim. Tem recomendações?'],
  ['market.solution.back','回到市场','回到市場','Back to marketplace','マーケットに戻る','마켓으로 돌아가기','Quay lại chợ ứng dụng','Volver al mercado','Retour à la place de marché','Zurück zum Marktplatz','Voltar ao mercado'],
  ['market.solution.added','已在我的团队里','已在我的團隊裡','Already on your team','すでにチームに追加済み','이미 팀에 있음','Đã có trong đội của bạn','Ya está en tu equipo','Déjà dans votre équipe','Bereits in Ihrem Team','Já está na sua equipa'],
  ['market.solution.openLoad','看看它带进来什么','看看它帶進來什麼','See what it brought in','何が追加されたか見る','무엇이 추가됐는지 보기','Xem nó mang lại những gì','Ver qué se añadió','Voir ce que ça a ajouté','Ansehen, was hinzugekommen ist','Ver o que foi adicionado'],
  ['market.solution.askFitDraft','我在考虑「{name}」。请先看我现在有什么，再说说加了之后会多出哪些能力、还要准备什么。','我在考慮「{name}」。請先看我現在有什麼，再說說加了之後會多出哪些能力、還要準備什麼。','I’m considering "{name}". Please look at what I already have, then tell me what new abilities it would add and what I’d still need to prepare.','「{name}」の導入を検討しています。まず今の状況を確認したうえで、追加後にどんな能力が増えるか、何を準備すべきか教えてください。','"{name}"을(를) 검토 중입니다. 지금 제가 가진 걸 먼저 확인한 다음, 추가하면 어떤 능력이 늘어나고 무엇을 더 준비해야 하는지 알려주세요.','Tôi đang cân nhắc "{name}". Hãy xem trước những gì tôi đang có, rồi cho tôi biết thêm vào sẽ có thêm năng lực gì và cần chuẩn bị gì.','Estoy considerando "{name}". Primero revisa lo que ya tengo y luego dime qué capacidades nuevas añadiría y qué más necesitaría preparar.','J’envisage « {name} ». Regarde d’abord ce que j’ai déjà, puis dis-moi quelles capacités cela ajouterait et ce qu’il faudrait encore préparer.','Ich überlege mir "{name}". Schau dir zuerst an, was ich schon habe, und sag mir dann, welche Fähigkeiten dadurch hinzukämen und was ich noch vorbereiten müsste.','Estou a considerar "{name}". Vê primeiro o que já tenho e depois diz-me que capacidades novas isso traria e o que ainda preciso de preparar.'],
  ['market.solution.askFit','先问问它适不适合我','先問問它適不適合我','Ask if it’s right for me first','まず自分に合うか聞いてみる','나에게 맞는지 먼저 물어보기','Hỏi xem có phù hợp với mình không','Preguntar primero si me conviene','Demander d’abord si ça me convient','Zuerst fragen, ob es passt','Perguntar primeiro se é adequado para mim'],
  ['market.solution.youGet','添加后你会得到','新增後你會得到','What you’ll get after adding','追加すると得られるもの','추가하면 얻게 되는 것','Sau khi thêm bạn sẽ có','Lo que obtendrás al añadirlo','Ce que vous obtiendrez après l’ajout','Was Sie nach dem Hinzufügen bekommen','O que vai obter depois de adicionar'],
  ['market.solution.contains','包含：{list}','包含：{list}','Includes: {list}','含まれるもの：{list}','포함: {list}','Bao gồm: {list}','Incluye: {list}','Comprend : {list}','Enthält: {list}','Inclui: {list}'],
  ['market.solution.provenance','来源与版本','來源與版本','Source & version','提供元とバージョン','출처 및 버전','Nguồn và phiên bản','Origen y versión','Source et version','Quelle & Version','Origem e versão'],
  ['market.solution.provenance.notice','添加只是加入，不等于已经能用：数据、账号和批准条件仍要一样一样接。','新增只是加入，不等於已經能用：資料、帳號和核准條件仍要一樣一樣接上。','Adding it only brings it in — it isn’t ready to use yet: data, accounts, and approval conditions still need to be connected one by one.','追加はあくまで取り込むだけで、すぐ使えるわけではありません。データ、アカウント、承認条件は一つずつつなぐ必要があります。','추가는 단지 들여오는 것일 뿐 바로 쓸 수 있는 건 아닙니다. 데이터, 계정, 승인 조건을 하나씩 연결해야 합니다.','Thêm vào chỉ là đưa vào, chưa có nghĩa là dùng được ngay: dữ liệu, tài khoản và điều kiện phê duyệt vẫn phải kết nối từng cái một.','Añadirlo solo lo incorpora, no significa que ya esté listo para usar: los datos, las cuentas y las condiciones de aprobación aún deben conectarse una por una.','L’ajouter ne fait que l’intégrer, ça ne veut pas dire que c’est déjà utilisable : les données, les comptes et les conditions d’approbation doivent encore être connectés un par un.','Hinzufügen bedeutet nur, dass es aufgenommen wird – nicht, dass es schon einsatzbereit ist: Daten, Konten und Genehmigungsbedingungen müssen noch einzeln verbunden werden.','Adicionar só significa incorporar, não que já esteja pronto a usar: dados, contas e condições de aprovação ainda têm de ser ligados um a um.'],
  ['market.solution.contents','它到底带进来哪些东西','它到底帶進來哪些東西','What it actually brings in','実際に何が追加されるのか','실제로 무엇이 들어오는지','Nó thực sự mang lại những gì','Qué trae realmente','Ce que ça apporte réellement','Was dabei tatsächlich mitkommt','O que realmente traz'],
  ['market.solution.mark.added','已添加','已新增','Added','追加済み','추가됨','Đã thêm','Añadido','Ajouté','Hinzugefügt','Adicionado'],
  ['market.solution.mark.restart','需重启','需重新啟動','Needs restart','再起動が必要','재시작 필요','Cần khởi động lại','Necesita reinicio','Redémarrage requis','Neustart erforderlich','Requer reinício'],
  ['market.solution.mark.available','可添加','可新增','Available to add','追加可能','추가 가능','Có thể thêm','Disponible para añadir','Disponible à l’ajout','Verfügbar zum Hinzufügen','Disponível para adicionar'],
  // 同一标识两份内容对不上时的第四档记号：只说「有冲突」，原委仍在右侧详情里逐条写明。
  ['market.mark.conflict','有冲突','有衝突','Has a conflict','競合あり','충돌 있음','Có xung đột','Hay un conflicto','Conflit détecté','Konflikt vorhanden','Há um conflito'],
  // 空库兜底那一屏的抬头：目录里还没有任何方案时，首页列的是 Teloa 内置行业方案。
  ['market.solution.builtinTitle','推荐行业方案','推薦行業方案','Recommended industry solutions','おすすめの業界ソリューション','추천 산업 솔루션','Giải pháp ngành được đề xuất','Soluciones sectoriales recomendadas','Solutions sectorielles recommandées','Empfohlene Branchenlösungen','Soluções setoriais recomendadas'],
  ['market.solution.builtinTag','内置示例','內建範例','Built-in example','組み込みサンプル','기본 예시','Ví dụ có sẵn','Ejemplo incluido','Exemple intégré','Mitgeliefertes Beispiel','Exemplo incluído'],
  ['market.solution.builtinNotice','Teloa 内置示例：目录里还没有你自己的方案，先从这几份内置行业方案开始。','Teloa 內建範例：目錄裡還沒有你自己的方案，先從這幾份內建行業方案開始。','Teloa built-in examples: your catalog has no solutions yet, so start with these built-in industry solutions.','Teloa 組み込みサンプル：カタログにはまだ独自のソリューションがありません。まずはこれらの組み込み業界ソリューションから始めてください。','Teloa 기본 제공 예시: 목록에 아직 직접 추가한 솔루션이 없습니다. 먼저 이 기본 산업 솔루션부터 시작하세요.','Ví dụ tích hợp sẵn của Teloa: danh mục chưa có giải pháp nào của bạn, hãy bắt đầu từ các giải pháp ngành tích hợp sẵn này.','Ejemplos integrados de Teloa: tu catálogo aún no tiene soluciones propias; empieza por estas soluciones sectoriales integradas.','Exemples intégrés Teloa : votre catalogue ne contient pas encore de solutions ; commencez par ces solutions sectorielles intégrées.','In Teloa integrierte Beispiele: Ihr Katalog enthält noch keine eigenen Lösungen; beginnen Sie mit diesen integrierten Branchenlösungen.','Exemplos integrados do Teloa: o seu catálogo ainda não tem soluções próprias; comece por estas soluções setoriais integradas.'],
] as const
