type Row=readonly [string,string,string,string,string,string,string,string,string,string,string]
const r=(key:string,zh:string,hant:string,en:string,ja:string,ko:string,vi:string,es:string,fr:string,de:string,pt:string):Row=>[key,zh,hant,en,ja,ko,vi,es,fr,de,pt]

export const PRESENTATION_HELPER_MESSAGE_ROWS:readonly Row[]=[
 r('presentation.changeTo','改为','改為','changes to','から変更：','에서 변경:','đổi thành','cambia a','devient','wird zu','passa a'),
 r('presentation.collaboration.members','{count} 位成员','{count} 位成員','{count} members','{count} 人のメンバー','구성원 {count}명','{count} thành viên','{count} miembros','{count} membres','{count} Mitglieder','{count} membros'),
 r('presentation.collaboration.membersWithOneSaved','{count} 位成员 · {saved} 位已保存员工','{count} 位成員 · {saved} 位已儲存員工','{count} members · {saved} saved employee','{count} 人のメンバー · 保存済み従業員 {saved} 件','구성원 {count}명 · 저장된 직원 {saved}개','{count} thành viên · {saved} nhân viên đã lưu','{count} miembros · {saved} empleado guardado','{count} membres · {saved} employé enregistré','{count} Mitglieder · {saved} gespeicherter Mitarbeiter','{count} membros · {saved} funcionário guardado'),
 r('presentation.collaboration.membersWithSaved','{count} 位成员 · {saved} 位已保存员工','{count} 位成員 · {saved} 位已儲存員工','{count} members · {saved} saved employees','{count} 人のメンバー · 保存済み従業員 {saved} 件','구성원 {count}명 · 저장된 직원 {saved}개','{count} thành viên · {saved} nhân viên đã lưu','{count} miembros · {saved} empleados guardados','{count} membres · {saved} employés enregistrés','{count} Mitglieder · {saved} gespeicherte Mitarbeiter','{count} membros · {saved} funcionários guardados'),
 r('presentation.collaboration.formerRole','历史员工','歷史員工','Former employee','過去の従業員','이전 직원','Nhân viên trước đây','Empleado anterior','Ancien employé','Früherer Mitarbeiter','Funcionário anterior'),
 r('presentation.collaboration.digitalEmployee','员工','員工','Employee','従業員','직원','Nhân viên','Empleado','Employé','Mitarbeiter','Funcionário'),
 r('presentation.collaboration.memberState','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}','{kind} · {state}'),
 r('presentation.continuous.mode.saved','已保存计划与真实执行','已儲存計畫與真實執行','Saved plans and real runs','保存済み計画と実際の実行','저장된 계획과 실제 실행','Kế hoạch đã lưu và lần chạy thật','Planes guardados y ejecuciones reales','Plans enregistrés et exécutions réelles','Gespeicherte Pläne und echte Ausführungen','Planos guardados e execuções reais'),
 r('presentation.continuous.mode.sandbox','界面沙盒 · 数据不会写入计划或执行服务','介面沙盒 · 資料不會寫入計畫或執行服務','Interface sandbox · Data is not written to plan or execution services','画面サンドボックス · データは計画または実行サービスに書き込まれません','화면 샌드박스 · 데이터는 계획 또는 실행 서비스에 기록되지 않습니다','Hộp cát giao diện · Dữ liệu không được ghi vào dịch vụ kế hoạch hay thực thi','Entorno de prueba · Los datos no se escriben en los servicios de planes o ejecución','Bac à sable de l’interface · Les données ne sont pas écrites dans les services de planification ou d’exécution','Oberflächen-Sandbox · Daten werden nicht in Planungs- oder Ausführungsdienste geschrieben','Ambiente de teste da interface · Os dados não são gravados nos serviços de planos ou execução'),
 r('task.history.created','创建任务','建立任務','Task created','タスクを作成','작업 생성','Đã tạo nhiệm vụ','Tarea creada','Tâche créée','Aufgabe erstellt','Tarefa criada'),
 r('task.history.edited','修改目标，形成任务 v{version}；历史审批记录保留。','修改目標，形成任務 v{version}；保留歷史審批記錄。','Task updated to v{version}; previous approval records were kept.','目標を変更してタスク v{version} を作成。過去の承認記録は保持されます。','목표를 수정해 작업 v{version}을 만들었습니다. 이전 승인 기록은 유지됩니다.','Đã cập nhật mục tiêu thành nhiệm vụ v{version}; các bản ghi phê duyệt trước vẫn được giữ.','Tarea actualizada a v{version}; se conservaron los registros de aprobación anteriores.','Tâche mise à jour vers la v{version} ; les approbations précédentes sont conservées.','Aufgabe auf v{version} aktualisiert; frühere Genehmigungsdatensätze bleiben erhalten.','Tarefa atualizada para v{version}; os registos anteriores de aprovação foram mantidos.'),
 r('task.history.approvalDecision','{status}：{note}','{status}：{note}','{status}: {note}','{status}：{note}','{status}: {note}','{status}: {note}','{status}: {note}','{status} : {note}','{status}: {note}','{status}: {note}'),
 r('task.history.submitted','提交任务 v{version} 供本人审批。','提交任務 v{version} 供本人審批。','Task v{version} submitted for my approval.','タスク v{version} を自分の承認用に提出しました。','작업 v{version}을 본인 승인용으로 제출했습니다.','Đã gửi nhiệm vụ v{version} để tôi phê duyệt.','Tarea v{version} enviada para mi aprobación.','Tâche v{version} soumise à mon approbation.','Aufgabe v{version} zur eigenen Genehmigung eingereicht.','Tarefa v{version} enviada para minha aprovação.'),
 r('task.history.supplemented','补充资料，等待核验；原缺口继续保留。','補充資料，等待核驗；原缺口繼續保留。','Materials added and awaiting review; the original gap remains open.','資料を追加し、確認待ちです。元の不足は引き続き残ります。','자료를 보완했으며 검토 대기 중입니다. 기존 자료 공백은 유지됩니다.','Đã bổ sung tài liệu và đang chờ kiểm tra; khoảng trống ban đầu vẫn được giữ.','Material añadido y pendiente de revisión; la carencia original sigue abierta.','Documents ajoutés et en attente de vérification ; le manque initial reste ouvert.','Unterlagen ergänzt und zur Prüfung vorgemerkt; die ursprüngliche Lücke bleibt offen.','Materiais adicionados e a aguardar revisão; a lacuna original permanece aberta.'),
 r('task.history.materialAccepted','核验通过，原任务可接续。','核驗通過，原任務可接續。','Review passed; the original task can continue.','確認に合格し、元のタスクを続行できます。','검토를 통과해 기존 작업을 계속할 수 있습니다.','Đã kiểm tra đạt yêu cầu; có thể tiếp tục nhiệm vụ ban đầu.','Revisión superada; la tarea original puede continuar.','Vérification réussie ; la tâche initiale peut reprendre.','Prüfung bestanden; die ursprüngliche Aufgabe kann fortgesetzt werden.','Revisão aprovada; a tarefa original pode continuar.'),
 r('task.history.materialRejected','核验未通过，保留资料缺口。','核驗未通過，保留資料缺口。','Review did not pass; the material gap remains open.','確認に合格せず、資料不足は未解決のままです。','검토를 통과하지 못해 자료 공백이 유지됩니다.','Chưa đạt yêu cầu kiểm tra; khoảng trống tài liệu vẫn còn.','La revisión no se superó; la carencia de material sigue abierta.','La vérification a échoué ; le manque de documents reste ouvert.','Prüfung nicht bestanden; die Unterlagenlücke bleibt offen.','A revisão não foi aprovada; a lacuna de materiais permanece aberta.'),
 r('task.history.retrySucceeded','重新读取成功，原任务可接续。','重新讀取成功，原任務可接續。','Reload succeeded; the original task can continue.','再読み込みに成功し、元のタスクを続行できます。','다시 읽기에 성공해 기존 작업을 계속할 수 있습니다.','Đọc lại thành công; có thể tiếp tục nhiệm vụ ban đầu.','La nueva lectura se completó; la tarea original puede continuar.','Nouvelle lecture réussie ; la tâche initiale peut reprendre.','Erneutes Lesen erfolgreich; die ursprüngliche Aufgabe kann fortgesetzt werden.','Nova leitura concluída; a tarefa original pode continuar.'),
 r('task.history.retryFailed','重新读取失败，保留原异常。','重新讀取失敗，保留原異常。','Reload failed; the original error remains.','再読み込みに失敗し、元のエラーは残ります。','다시 읽기에 실패해 기존 오류가 유지됩니다.','Đọc lại thất bại; lỗi ban đầu vẫn được giữ.','La nueva lectura falló; se conserva el error original.','La nouvelle lecture a échoué ; l’erreur initiale est conservée.','Erneutes Lesen fehlgeschlagen; der ursprüngliche Fehler bleibt bestehen.','A nova leitura falhou; o erro original foi mantido.'),
 r('task.history.handoff','交接给 {assignee}：{note}','交接給 {assignee}：{note}','Handed off to {assignee}: {note}','{assignee} に引き継ぎ：{note}','{assignee}에게 인계: {note}','Đã bàn giao cho {assignee}: {note}','Traspasada a {assignee}: {note}','Transmise à {assignee} : {note}','An {assignee} übergeben: {note}','Transferida para {assignee}: {note}'),
 r('task.history.progress.start','任务已开始','任務已開始','Task started','タスクを開始','작업 시작','Đã bắt đầu nhiệm vụ','Tarea iniciada','Tâche démarrée','Aufgabe gestartet','Tarefa iniciada'),
 r('task.history.progress.pause','任务已暂停','任務已暫停','Task paused','タスクを一時停止','작업 일시 중지','Đã tạm dừng nhiệm vụ','Tarea pausada','Tâche mise en pause','Aufgabe pausiert','Tarefa pausada'),
 r('task.history.progress.resume','任务已继续','任務已繼續','Task resumed','タスクを再開','작업 재개','Đã tiếp tục nhiệm vụ','Tarea reanudada','Tâche reprise','Aufgabe fortgesetzt','Tarefa retomada'),
 r('task.history.progress.cancel','任务已取消；未撤销在途外部操作。','任務已取消；未撤銷進行中的外部操作。','Task cancelled; in-flight external actions were not revoked.','タスクをキャンセルしました。進行中の外部操作は取り消されていません。','작업이 취소되었습니다. 진행 중인 외부 작업은 취소되지 않았습니다.','Đã hủy nhiệm vụ; các thao tác bên ngoài đang diễn ra chưa bị thu hồi.','Tarea cancelada; no se revocaron las acciones externas en curso.','Tâche annulée ; les actions externes en cours n’ont pas été révoquées.','Aufgabe abgebrochen; laufende externe Aktionen wurden nicht widerrufen.','Tarefa cancelada; as ações externas em curso não foram revogadas.'),
 r('task.history.progress.complete','任务已完成','任務已完成','Task completed','タスクが完了','작업 완료','Đã hoàn thành nhiệm vụ','Tarea completada','Tâche terminée','Aufgabe abgeschlossen','Tarefa concluída'),
 r('task.history.sampleWaiting','示例工作等待本人处理','範例工作等待本人處理','Sample work is waiting for me','サンプル作業は自分の対応待ちです','예시 작업이 본인 처리를 기다리고 있습니다','Công việc mẫu đang chờ tôi xử lý','El trabajo de muestra espera mi intervención','Le travail d’exemple attend mon intervention','Die Beispielarbeit wartet auf meine Bearbeitung','O trabalho de exemplo aguarda minha intervenção'),
 r('task.approval.subject','任务','任務','Task','タスク','작업','Nhiệm vụ','Tarea','Tâche','Aufgabe','Tarefa'),
 r('task.approval.object.general','通用任务','通用任務','General task','一般タスク','일반 작업','Nhiệm vụ chung','Tarea general','Tâche générale','Allgemeine Aufgabe','Tarefa geral'),
 r('task.approval.risk.none','未提出外部动作','未提出外部動作','No external action proposed','外部操作は提案されていません','제안된 외부 작업 없음','Không đề xuất thao tác bên ngoài','No se propuso ninguna acción externa','Aucune action externe proposée','Keine externe Aktion vorgeschlagen','Nenhuma ação externa proposta'),
 r('task.approval.risk.highInterruption','高风险 · 隔离将中断这台主机的业务连接。','高風險 · 隔離將中斷這台主機的業務連線。','High risk · Isolation will interrupt this machine’s business connections.','高リスク · 隔離するとこのマシンの業務接続が中断されます。','고위험 · 격리하면 이 컴퓨터의 업무 연결이 중단됩니다.','Rủi ro cao · Cách ly sẽ làm gián đoạn kết nối nghiệp vụ của máy này.','Riesgo alto · El aislamiento interrumpirá las conexiones de negocio de este equipo.','Risque élevé · L’isolement interrompra les connexions métier de cette machine.','Hohes Risiko · Die Isolation unterbricht die Geschäftsverbindungen dieses Rechners.','Risco elevado · O isolamento interromperá as ligações empresariais deste equipamento.'),
 r('task.approval.effect','仅对当前对象与提交版本形成决定；执行受理、目标系统的答复和效果核验分别记录。','僅對目前物件與提交版本形成決定；執行受理、目標系統的答覆和效果核驗分別記錄。','The decision covers only the current object and submitted version; execution acceptance, the target system’s response, and outcome review are recorded separately.','決定の対象は現在のオブジェクトと提出バージョンのみです。実行受理、対象システムの応答、効果確認は個別に記録されます。','결정은 현재 대상과 제출 버전에만 적용됩니다. 실행 접수, 대상 시스템의 회신 및 효과 검토는 별도로 기록됩니다.','Quyết định chỉ áp dụng cho đối tượng hiện tại và phiên bản đã gửi; việc tiếp nhận, phản hồi của hệ thống đích và kiểm tra hiệu quả được ghi riêng.','La decisión solo cubre el objeto actual y la versión enviada; la aceptación, la respuesta del sistema de destino y la revisión del efecto se registran por separado.','La décision ne couvre que l’objet actuel et la version soumise ; l’acceptation, la réponse du système cible et la vérification de l’effet sont consignées séparément.','Die Entscheidung gilt nur für das aktuelle Objekt und die eingereichte Version; Annahme, Rückmeldung des Zielsystems und Wirkungsprüfung werden getrennt erfasst.','A decisão abrange apenas o objeto atual e a versão enviada; a aceitação, a resposta do sistema de destino e a verificação do efeito são registadas separadamente.'),
] as const

for(const row of PRESENTATION_HELPER_MESSAGE_ROWS)if(row.length!==11||row.slice(1).some(value=>!value.trim()))throw new Error(`invalid locale row: ${row[0]}`)
