// 同事上网一期（2026-09-21 同事上网一期 功能验证）。
// 本文件词条覆盖：同事「能力」页里上网两项授权与分身页提示（`roleGrant.web.*`）、技能接口代发授权（`roleGrant.skillHttp.*`，
// 规格 2026-09-27 §5.1）、运行详情里的
// 上网记录节、连接与运行环境中的网页搜索与读取策略（`webAccess.*`）。
// `webAccess.deny.*`（四条）与 `webAccess.run.empty` 一期已删除（T10 接线收尾时核实：一期只记「已放行」
// 的外发，没有任何界面把「本次访问被拒绝的原因」回传给人看，也没有「运行了但零条上网记录」这个可渲染
// 的边界态，四＋一条键在一期没有消费面，属于死词条）；界面回传被拒原因、以及运行记录节的显式空态若
// 二期要做，再重新开词条，不要复活这里删掉的键。
// `roleGrant.` 与 `webAccess.` 两个命名空间今天已纳入 `i18n-orphan-keys.test.ts` 的 `NAMESPACES`
// 管辖（T10 接线收尾时加入 `webAccess.` 一行；`roleGrant.` 命名空间下已有的既有键很多，仍不在管辖内，
// 本次不新增该命名空间的整体管辖，只保证 `roleGrant.web.*` 这几条本身在界面里有引用）。
// 11 列：[key, zh-CN, zh-Hant, en, ja, ko, vi, es, fr, de, pt]。
export const WEB_ACCESS_MESSAGE_ROWS = [
 ["roleGrant.web.title", "网页搜索与读取", "網頁搜尋與讀取", "Web search and reading", "ウェブ検索と読み取り", "웹 검색 및 읽기", "Tìm kiếm và đọc web", "Búsqueda y lectura web", "Recherche et lecture web", "Websuche und Seitenabruf", "Pesquisa e leitura web"],
 ['roleGrant.web.description','开启后，这位员工干活时可以自己搜索和打开网页。查询词与网址会外发，每次都记在运行记录里。','開啟後，這位員工工作時可以自己搜尋和開啟網頁。查詢詞與網址會外送，每次都會記在執行記錄裡。','Once turned on, this employee can search and open web pages on their own while working. Queries and URLs are sent out, and every one is recorded in the run history.','オンにすると、この従業員は作業中に自分で検索したりウェブページを開いたりできるようになります。検索語句と URL は外部に送信され、毎回実行記録に残ります。','켜면 이 직원은 작업 중에 스스로 검색하고 웹페이지를 열 수 있습니다. 검색어와 URL은 외부로 전송되며 매번 실행 기록에 남습니다.','Khi bật, nhân viên này có thể tự tìm kiếm và mở trang web khi làm việc. Từ khóa tìm kiếm và địa chỉ web sẽ được gửi ra ngoài, và mỗi lần đều được ghi vào nhật ký chạy.','Al activarlo, este empleado puede buscar y abrir páginas web por su cuenta mientras trabaja. Las consultas y las URL se envían al exterior, y cada una queda registrada en el historial de ejecución.','Une fois activé, ce employé peut rechercher et ouvrir des pages web par lui-même pendant son travail. Les termes de recherche et les URL sont envoyés à l’extérieur, et chacun est consigné dans l’historique d’exécution.','Ist dies aktiviert, kann diese Mitarbeiterin oder dieser Mitarbeiter bei der Arbeit selbstständig suchen und Webseiten öffnen. Suchbegriffe und URLs werden nach außen gesendet und jedes Mal im Ausführungsverlauf festgehalten.','Depois de ativado, este funcionário pode pesquisar e abrir páginas web por conta própria durante o trabalho. As consultas e os URLs são enviados para fora e cada um fica registado no histórico de execução.'],
 ['roleGrant.web.search','搜索网页','搜尋網頁','Search the web','ウェブを検索','웹 검색','Tìm kiếm trên web','Buscar en la web','Rechercher sur le web','Im Internet suchen','Pesquisar na web'],
 ['roleGrant.web.searchHint','只发出检索词，不发出你的资料正文。','只會送出搜尋詞，不會送出你的資料內文。','Only the search terms are sent out; the body of your materials is never sent.','送信されるのは検索語句のみで、あなたの資料本文は送信されません。','검색어만 전송되며 자료 본문은 전송되지 않습니다.','Chỉ gửi đi từ khóa tìm kiếm, không gửi nội dung tài liệu của bạn.','Solo se envían los términos de búsqueda; el contenido de tus materiales nunca se envía.','Seuls les termes de recherche sont envoyés ; le contenu de vos documents n’est jamais transmis.','Es werden nur die Suchbegriffe gesendet, niemals der Inhalt Ihres Materials.','Só são enviados os termos de pesquisa; o conteúdo dos seus materiais nunca é enviado.'],
 ['roleGrant.web.fetch','打开网页','開啟網頁','Open web pages','ウェブページを開く','웹페이지 열기','Mở trang web','Abrir páginas web','Ouvrir des pages web','Webseiten öffnen','Abrir páginas web'],
 ['roleGrant.web.fetchHint','按网址取回正文。只能打开公开网页，不带任何登录信息。','依網址取回內文。只能開啟公開網頁，不會帶上任何登入資訊。','Fetches the page content by URL. Only public web pages can be opened, without any sign-in details.','URL を指定して本文を取得します。開けるのは公開されたウェブページのみで、ログイン情報は一切付与されません。','URL로 본문을 가져옵니다. 공개된 웹페이지만 열 수 있으며 로그인 정보는 전혀 포함되지 않습니다.','Lấy nội dung theo địa chỉ web. Chỉ có thể mở các trang web công khai, không kèm bất kỳ thông tin đăng nhập nào.','Recupera el contenido según la URL. Solo se pueden abrir páginas web públicas, sin ninguna información de inicio de sesión.','Récupère le contenu à partir de l’URL. Seules les pages web publiques peuvent être ouvertes, sans aucune information de connexion.','Ruft den Inhalt über die URL ab. Es können nur öffentliche Webseiten geöffnet werden, ohne jegliche Anmeldedaten.','Obtém o conteúdo a partir do URL. Só é possível abrir páginas web públicas, sem quaisquer dados de início de sessão.'],
 ["roleGrant.web.disabledByGlobal", "网页搜索与读取已在连接与运行环境中关闭，已有授权会保留。", "網頁搜尋與讀取已在連線與執行環境中關閉，既有授權會保留。", "Web search and reading are disabled in Connections and environment. Existing grants are kept.", "接続と実行環境でウェブ検索と読み取りが無効になっています。既存の権限は保持されます。", "연결 및 실행 환경에서 웹 검색과 읽기가 꺼져 있습니다. 기존 권한은 유지됩니다.", "Tìm kiếm và đọc web đã tắt trong Kết nối và môi trường chạy. Các quyền đã cấp được giữ lại.", "La búsqueda y lectura web están desactivadas en Conexiones y entorno de ejecución. Se conservan los permisos.", "La recherche et la lecture web sont désactivées dans Connexions et environnement d’exécution. Les autorisations sont conservées.", "Websuche und Seitenabruf sind unter Verbindungen und Ausführungsumgebung deaktiviert. Bestehende Berechtigungen bleiben erhalten.", "A pesquisa e leitura web estão desativadas em Ligações e ambiente de execução. As permissões existentes são mantidas."],
 ['roleGrant.web.twinNote','分身没有单独的上网授权：它只在你正打开的对话里代你查，查了什么都在这条对话里。','分身沒有單獨的上網授權：它只會在你正開啟的對話裡代你查詢，查了什麼都會留在這則對話裡。','The twin has no separate web-access authorization: it only looks things up on your behalf inside the conversation you have open, and whatever it looks up stays in that conversation.','分身には独立したウェブアクセス権限はありません。今開いている会話の中でのみあなたに代わって調べ、調べた内容はすべてその会話に残ります。','분신은 별도의 웹 접속 권한이 없습니다. 지금 열려 있는 대화 안에서만 당신을 대신해 조회하며, 조회한 내용은 모두 그 대화 안에 남습니다.','Bản sao không có quyền truy cập web riêng: nó chỉ tra cứu thay bạn trong cuộc trò chuyện bạn đang mở, và những gì đã tra cứu đều nằm trong cuộc trò chuyện đó.','El doble no tiene autorización de acceso web independiente: solo consulta en tu nombre dentro de la conversación que tienes abierta, y todo lo que consulte queda en esa misma conversación.','Le double numérique n’a pas d’autorisation d’accès web distincte : il ne fait des recherches en votre nom que dans la conversation que vous avez ouverte, et tout ce qu’il consulte reste dans cette conversation.','Der Zwilling hat keine eigene Internetzugriffsberechtigung: Er recherchiert nur innerhalb der von Ihnen gerade geöffneten Unterhaltung in Ihrem Auftrag, und alles, was er nachschlägt, bleibt in dieser Unterhaltung.','O duplo não tem autorização de acesso à web separada: só pesquisa em seu nome dentro da conversa que você tem aberta, e tudo o que pesquisar fica nessa conversa.'],
 ["roleGrant.otherCandidates","本栏没有资料或工具可授予；可授予的权限见下方：{groups}。","本欄沒有資料或工具可授予；可授予的權限見下方：{groups}。","No materials or tools to grant here; see the sections below: {groups}.","ここで付与できる資料やツールはありません。付与できる権限は下の欄にあります：{groups}。","여기에서 부여할 자료나 도구가 없습니다. 부여할 수 있는 권한은 아래 항목에 있습니다: {groups}.","Không có tài liệu hoặc công cụ nào để cấp ở đây; xem các mục bên dưới: {groups}.","No hay materiales ni herramientas que conceder aquí; consulta las secciones de abajo: {groups}.","Aucun document ni outil à accorder ici ; voir les sections ci-dessous : {groups}.","Hier gibt es keine Unterlagen oder Werkzeuge zum Freigeben; siehe die Abschnitte unten: {groups}.","Não há materiais nem ferramentas a conceder aqui; veja as secções abaixo: {groups}."],
 ["roleGrant.skillHttp.title","技能接口代发","技能介面代發","Skill API calls","スキル API の代理呼び出し","스킬 API 대리 호출","Gọi API qua kỹ năng","Llamadas a API de habilidades","Appels d’API des compétences","API-Aufrufe über Skills","Chamadas de API das competências"],
 ["roleGrant.skillHttp.description","逐项勾选允许这位员工在任务中代为调用接口的技能；没勾选的技能（包括以后新增的）一律不能用。密钥由 Teloa 在请求时注入，员工看不到；只能访问技能写明的地址，会改动数据的请求每次仍要你在工作台确认。","逐項勾選允許這位員工在任務中代為呼叫介面的技能；沒勾選的技能（包括之後新增的）一律不能用。密鑰由 Teloa 在請求時注入，員工看不到；只能存取技能寫明的位址，會變更資料的請求每次仍需你在工作台確認。","Tick each skill this employee may use to call APIs during tasks; any skill left unticked, including skills added later, cannot be used. Teloa injects the keys at request time and the employee never sees them. Only the addresses the skill lists are reachable, and every request that changes data still needs your confirmation on the workbench.","スキルごとにチェックを入れると、従業員がタスク中にそのスキルで API を呼び出せます。チェックしていないスキル（後から追加されたものを含む）は使えません。キーは Teloa がリクエスト時に注入し、従業員からは見えません。スキルに記載されたアドレスにしかアクセスできず、データを変更するリクエストは毎回ワークベンチでの確認が必要です。","이 직원이 작업 중 API를 호출할 수 있는 스킬을 하나씩 체크하세요. 체크하지 않은 스킬(나중에 추가된 스킬 포함)은 사용할 수 없습니다. 키는 Teloa가 요청 시점에 주입하며 직원에게는 보이지 않습니다. 스킬에 명시된 주소만 접근할 수 있고, 데이터를 바꾸는 요청은 매번 워크벤치에서 확인해야 합니다.","Đánh dấu từng kỹ năng mà nhân viên này được dùng để gọi API trong nhiệm vụ; kỹ năng không được đánh dấu, kể cả kỹ năng thêm sau này, đều không dùng được. Teloa chèn khóa vào lúc gửi yêu cầu, nhân viên không nhìn thấy khóa. Chỉ truy cập được các địa chỉ mà kỹ năng ghi rõ, và mỗi yêu cầu làm thay đổi dữ liệu vẫn cần bạn xác nhận trên bàn làm việc.","Marca cada habilidad con la que este empleado puede llamar a API durante las tareas; las habilidades sin marcar, incluidas las que se añadan después, no se pueden usar. Teloa inyecta las claves en el momento de la solicitud y el empleado nunca las ve. Solo puede acceder a las direcciones que indica la habilidad, y cada solicitud que modifique datos sigue necesitando tu confirmación en el panel de trabajo.","Cochez chaque compétence avec laquelle ce employé peut appeler des API pendant ses tâches ; les compétences non cochées, y compris celles ajoutées plus tard, ne peuvent pas être utilisées. Teloa injecte les clés au moment de la requête et le employé ne les voit jamais. Seules les adresses indiquées par la compétence sont accessibles, et chaque requête qui modifie des données doit toujours être confirmée par vous sur le poste de travail.","Haken Sie jeden Skill an, mit dem dieser Mitarbeiter bei Aufgaben APIs aufrufen darf; nicht angehakte Skills, auch später hinzugefügte, sind nicht nutzbar. Teloa fügt die Schlüssel beim Aufruf ein; der Mitarbeiter sieht sie nie. Nur die vom Skill angegebenen Adressen sind erreichbar, und jede Anfrage, die Daten ändert, müssen Sie weiterhin jedes Mal in der Arbeitsoberfläche bestätigen.","Marque cada competência com que este funcionário pode chamar APIs durante as tarefas; as competências não marcadas, incluindo as adicionadas mais tarde, não podem ser usadas. O Teloa injeta as chaves no momento da solicitação e o funcionário nunca as vê. Só os endereços indicados pela competência ficam acessíveis, e cada solicitação que altera dados continua a precisar da sua confirmação na área de trabalho."],
 ["roleGrant.skillHttp.skill","{skill}（访问 {origins}）","{skill}（存取 {origins}）","{skill} (calls {origins})","{skill}（アクセス先: {origins}）","{skill} (접근 대상: {origins})","{skill} (gọi {origins})","{skill} (llama a {origins})","{skill} (appelle {origins})","{skill} (ruft {origins} auf)","{skill} (chama {origins})"],
 ["roleGrant.skillHttp.sourceRole","员工技能","員工技能","Employee skill","従業員のスキル","직원 스킬","Kỹ năng của nhân viên","Habilidad del empleado","Compétence du employé","Skill des Mitarbeiters","Competência do funcionário"],
 ["roleGrant.skillHttp.sourceIndustry","行业职责技能","行業職責技能","Industry duty skill","業界職務のスキル","업종 직무 스킬","Kỹ năng nhiệm vụ ngành","Habilidad de funciones del sector","Compétence de mission sectorielle","Skill aus Branchenaufgaben","Competência de funções do setor"],
 ["roleGrant.skillHttp.configured","已保存密钥","已儲存密鑰","Key saved","キー保存済み","키 저장됨","Đã lưu khóa","Clave guardada","Clé enregistrée","Schlüssel gespeichert","Chave guardada"],
 ["roleGrant.skillHttp.missing","尚未保存密钥：请到 市场 > 技能 > 该技能 > 密钥 填写。","尚未儲存密鑰：請到 市場 > 技能 > 該技能 > 密鑰 填寫。","No key saved yet: enter it under Market > Skills > the skill > Keys.","キーがまだ保存されていません。マーケット > スキル > 該当スキル > キー で入力してください。","아직 키가 저장되지 않았습니다. 마켓 > 스킬 > 해당 스킬 > 키에서 입력하세요.","Chưa lưu khóa: hãy nhập tại Thị trường > Kỹ năng > kỹ năng đó > Khóa.","Aún no hay clave guardada: introdúcela en Mercado > Habilidades > la habilidad > Claves.","Aucune clé enregistrée : saisissez-la dans Marché > Compétences > la compétence > Clés.","Noch kein Schlüssel gespeichert: Geben Sie ihn unter Markt > Skills > der Skill > Schlüssel ein.","Ainda não há chave guardada: introduza-a em Mercado > Competências > a competência > Chaves."],
 ["roleGrant.skillHttp.granted","技能接口代发：{skill}","技能介面代發：{skill}","Skill API calls: {skill}","スキル API の代理呼び出し: {skill}","스킬 API 대리 호출: {skill}","Gọi API qua kỹ năng: {skill}","Llamadas a API de habilidades: {skill}","Appels d’API des compétences : {skill}","API-Aufrufe über Skills: {skill}","Chamadas de API das competências: {skill}"],
 ['webAccess.run.title','本次运行上网记录','本次執行上網記錄','Web access during this run','今回の実行のウェブアクセス記録','이번 실행의 웹 접속 기록','Nhật ký truy cập web của lần chạy này','Registro de acceso web de esta ejecución','Journal d’accès web de cette exécution','Internetzugriff bei diesem Lauf','Registo de acesso à web desta execução'],
 ['webAccess.run.search','搜索','搜尋','Search','検索','검색','Tìm kiếm','Buscar','Recherche','Suche','Pesquisa'],
 ['webAccess.run.fetch','打开','開啟','Open','開く','열기','Mở','Abrir','Ouvrir','Öffnen','Abrir'],
 ['webAccess.run.copy','复制','複製','Copy','コピー','복사','Sao chép','Copiar','Copier','Kopieren','Copiar'],
 ["webAccess.settings.title", "网页搜索与读取策略", "網頁搜尋與讀取策略", "Web search and reading policy", "ウェブ検索・読み取りポリシー", "웹 검색 및 읽기 정책", "Chính sách tìm kiếm và đọc web", "Política de búsqueda y lectura web", "Politique de recherche et de lecture web", "Richtlinie für Websuche und Seitenabruf", "Política de pesquisa e leitura web"],
 ["webAccess.settings.enabled", "允许网页搜索与读取", "允許網頁搜尋與讀取", "Allow web search and reading", "ウェブ検索と読み取りを許可", "웹 검색 및 읽기 허용", "Cho phép tìm kiếm và đọc web", "Permitir búsqueda y lectura web", "Autoriser la recherche et la lecture web", "Websuche und Seitenabruf erlauben", "Permitir pesquisa e leitura web"],
 ["webAccess.settings.enabledHint", "关闭并保存后，对话和任务将不能发起新的网页搜索与读取。已有员工授权会保留。", "關閉並儲存後，對話和任務將無法發起新的網頁搜尋與讀取。既有員工授權會保留。", "After you turn this off and save, conversations and tasks cannot start new web searches or page reads. Existing employee grants are kept.", "オフにして保存すると、会話とタスクは新しいウェブ検索やページ読み取りを開始できません。従業員の既存の権限は保持されます。", "끄고 저장하면 대화와 작업에서 새 웹 검색이나 페이지 읽기를 시작할 수 없습니다. 직원의 기존 권한은 유지됩니다.", "Sau khi tắt và lưu, hội thoại và tác vụ không thể bắt đầu tìm kiếm hoặc đọc trang web mới. Quyền của nhân viên được giữ lại.", "Al desactivar y guardar, las conversaciones y tareas no podrán iniciar nuevas búsquedas ni lecturas web. Se conservan los permisos de los empleados.", "Après désactivation et enregistrement, les conversations et tâches ne peuvent plus lancer de recherches ou de lectures web. Les autorisations des employés sont conservées.", "Nach dem Deaktivieren und Speichern können Unterhaltungen und Aufgaben keine neuen Websuchen oder Seitenabrufe starten. Berechtigungen der Mitarbeiter bleiben erhalten.", "Depois de desativar e guardar, as conversas e tarefas não podem iniciar novas pesquisas ou leituras web. As permissões dos funcionários são mantidas."],
 ["webAccess.settings.blockTitle", "禁止直接读取的网站", "禁止直接讀取的網站", "Block direct page reads", "直接読み取りを禁止するサイト", "직접 읽기를 차단할 웹사이트", "Chặn đọc trực tiếp trang web", "Bloquear lectura directa de sitios", "Bloquer la lecture directe de sites", "Direkten Seitenabruf blockieren", "Bloquear leitura direta de sites"],
 ["webAccess.settings.blockHint", "输入域名，例如 example.com，包含其子域名。仅检查直接读取的网址，不过滤搜索结果或重定向目标。", "輸入網域，例如 example.com，包含其子網域。僅檢查直接讀取的網址，不過濾搜尋結果或重新導向目標。", "Enter a domain such as example.com, including its subdomains. Only the requested page URL is checked; search results and redirect destinations are not filtered by this list.", "example.com などのドメインを入力します。サブドメインも含みます。このリストは最初に読み取る URL のみを確認し、検索結果やリダイレクト先は対象外です。", "example.com과 같은 도메인을 입력하세요. 하위 도메인도 포함됩니다. 이 목록은 직접 요청한 URL만 확인하며 검색 결과나 리디렉션 대상은 필터링하지 않습니다.", "Nhập tên miền như example.com, bao gồm các tên miền phụ. Danh sách chỉ kiểm tra URL được yêu cầu trực tiếp, không lọc kết quả tìm kiếm hay đích chuyển hướng.", "Introduce un dominio como example.com; incluye sus subdominios. La lista solo comprueba la URL solicitada, no filtra resultados de búsqueda ni destinos de redirección.", "Saisissez un domaine comme example.com, sous-domaines inclus. Cette liste vérifie uniquement l’URL demandée, sans filtrer les résultats de recherche ni les destinations de redirection.", "Geben Sie eine Domain wie example.com ein; Subdomains sind eingeschlossen. Die Liste prüft nur die angeforderte URL, keine Suchergebnisse oder Weiterleitungsziele.", "Introduza um domínio como example.com, incluindo os subdomínios. A lista verifica apenas o URL pedido, sem filtrar resultados de pesquisa ou destinos de redirecionamento."],
 ['webAccess.settings.blockAdd','添加','新增','Add','追加','추가','Thêm','Añadir','Ajouter','Hinzufügen','Adicionar'],
 ['webAccess.settings.blockRemove','移除','移除','Remove','削除','제거','Xóa','Quitar','Retirer','Entfernen','Remover'],
 ['webAccess.settings.blockEmpty','还没有拦住任何网站。','還沒有攔住任何網站。','No websites are blocked yet.','まだブロックしたウェブサイトはありません。','아직 차단된 웹사이트가 없습니다.','Chưa chặn trang web nào.','Todavía no hay ningún sitio bloqueado.','Aucun site n’est encore bloqué.','Es sind noch keine Websites gesperrt.','Ainda não há sites bloqueados.'],
 ['webAccess.settings.blockInvalid','这不是一个网站名，请只填域名，不要带 http:// 或路径。','這不是一個網站名稱，請只填網域，不要帶 http:// 或路徑。','This isn’t a valid website name; enter only the domain, without “http://” or a path.','これはウェブサイト名として無効です。ドメインのみを入力し、「http://」やパスは付けないでください。','유효한 웹사이트 이름이 아닙니다. http:// 나 경로 없이 도메인만 입력하세요.','Đây không phải là tên trang web hợp lệ, vui lòng chỉ nhập tên miền, không kèm http:// hay đường dẫn.','Esto no es un nombre de sitio web válido; escribe solo el dominio, sin “http://” ni ninguna ruta.','Ce n’est pas un nom de site valide ; saisissez uniquement le domaine, sans « http:// » ni chemin.','Das ist kein gültiger Website-Name; geben Sie nur die Domain ein, ohne „http://“ oder einen Pfad.','Isto não é um nome de site válido; introduza apenas o domínio, sem “http://” nem caminho.'],
 ["webAccess.settings.disclosure", "检索词会发送给已配置的搜索服务；读取网页时，目标网站会看到运行环境的出口地址。", "搜尋詞會傳送給已設定的搜尋服務；讀取網頁時，目標網站會看到執行環境的對外位址。", "Search terms are sent to the configured search service. When reading a page, the destination sees the outbound address of the device running Teloa.", "検索語句は設定された検索サービスに送信されます。ページの読み取り時、アクセス先には実行環境の送信元アドレスが表示されます。", "검색어는 설정된 검색 서비스로 전송됩니다. 페이지를 읽으면 대상 사이트에 실행 환경의 외부 주소가 표시됩니다.", "Từ khóa được gửi đến dịch vụ tìm kiếm đã cấu hình. Khi đọc trang, trang đích thấy địa chỉ ra ngoài của môi trường chạy.", "Los términos se envían al servicio de búsqueda configurado. Al leer una página, el destino ve la dirección de salida del entorno de ejecución.", "Les termes sont envoyés au service de recherche configuré. Lors de la lecture, le site voit l’adresse de sortie de l’environnement d’exécution.", "Suchbegriffe werden an den konfigurierten Suchdienst gesendet. Beim Seitenabruf sieht die Zielseite die ausgehende Adresse der Ausführungsumgebung.", "Os termos são enviados ao serviço de pesquisa configurado. Ao ler uma página, o destino vê o endereço de saída do ambiente de execução."],
 ["webAccess.settings.scope", "此策略不控制浏览器、电脑操作、终端或 MCP 的联网。", "此策略不控制瀏覽器、電腦操作、終端或 MCP 的連網。", "This policy does not control network access through Browser Use, Computer Use, terminal commands, or MCP.", "このポリシーは Browser Use、Computer Use、端末、MCP のネットワーク接続を制御しません。", "이 정책은 Browser Use, Computer Use, 터미널 또는 MCP의 네트워크 접속을 제어하지 않습니다.", "Chính sách này không kiểm soát truy cập mạng qua Browser Use, Computer Use, lệnh terminal hoặc MCP.", "Esta política no controla el acceso a la red mediante Browser Use, Computer Use, terminal o MCP.", "Cette politique ne contrôle pas l’accès réseau via Browser Use, Computer Use, le terminal ou MCP.", "Diese Richtlinie steuert nicht den Netzwerkzugriff über Browser Use, Computer Use, Terminal oder MCP.", "Esta política não controla o acesso à rede por Browser Use, Computer Use, terminal ou MCP."],
] as const
