type Values=readonly [string,string,string,string,string,string,string,string,string,string]
type Row<K extends string=string>=readonly [K,...Values]
const r=<K extends string>(key:K,...values:Values):Row<K>=>[key,...values]

export const WORKSPACE_SEARCH_MESSAGE_ROWS=[
 r('workspaceSearch.title','搜索','搜尋','Search','検索','검색','Tìm kiếm','Buscar','Rechercher','Suchen','Pesquisar'),
 r('workspaceSearch.closeAria','关闭业务搜索','關閉工作空間搜尋','Close workspace search','ワークスペース検索を閉じる','작업 공간 검색 닫기','Đóng tìm kiếm không gian làm việc','Cerrar búsqueda','Fermer la recherche','Arbeitsbereichssuche schließen','Fechar pesquisa'),
 r('workspaceSearch.inputAria','全局搜索','全域搜尋','Global search','全体検索','전체 검색','Tìm kiếm toàn cục','Búsqueda global','Recherche globale','Globale Suche','Pesquisa global'),
 r('workspaceSearch.placeholder','搜索任务、会话、群或员工…','搜尋任務、對話、群組或員工…','Search tasks, conversations, groups, or employees…','タスク、会話、グループ、従業員を検索…','작업, 대화, 그룹 또는 직원 검색…','Tìm nhiệm vụ, cuộc trò chuyện, nhóm hoặc nhân viên…','Buscar tareas, conversaciones, grupos o empleados…','Rechercher tâches, conversations, groupes ou employés…','Aufgaben, Gespräche, Gruppen oder Mitarbeiter durchsuchen…','Pesquisar tarefas, conversas, grupos ou funcionários…'),
 r('workspaceSearch.emptyTitle','没有匹配结果','沒有符合結果','No matching results','一致する結果がありません','일치하는 결과가 없습니다','Không có kết quả phù hợp','No hay resultados coincidentes','Aucun résultat correspondant','Keine passenden Ergebnisse','Nenhum resultado correspondente'),
 r('workspaceSearch.emptyDescription','更换关键词再试。','更換關鍵詞再試。','Try a different keyword.','別のキーワードでもう一度お試しください。','다른 키워드로 다시 시도하세요.','Hãy thử từ khóa khác.','Prueba con otra palabra clave.','Essayez un autre mot-clé.','Versuchen Sie ein anderes Stichwort.','Tente outra palavra-chave.'),
 r('workspaceSearch.searchMessagesTitle','在会话正文里搜索“{query}”','在對話正文裡搜尋「{query}」','Search conversation content for “{query}”','会話本文で「{query}」を検索','대화 본문에서 “{query}” 검색','Tìm “{query}” trong nội dung cuộc trò chuyện','Buscar “{query}” en el contenido de las conversaciones','Rechercher « {query} » dans le contenu des conversations','„{query}“ im Gesprächsinhalt suchen','Pesquisar “{query}” no conteúdo das conversas'),
 r('workspaceSearch.detail.messages','会话正文','對話正文','Conversation content','会話本文','대화 본문','Nội dung trò chuyện','Contenido de conversación','Contenu des conversations','Gesprächsinhalt','Conteúdo das conversas'),
 r('workspaceSearch.close','关闭','關閉','Close','閉じる','닫기','Đóng','Cerrar','Fermer','Schließen','Fechar'),
 r('workspaceSearch.conversationsUnavailable','会话目录尚未就绪；当前结果不包含会话。','對話目錄尚未就緒；目前結果不包含對話。','The conversation directory is not ready; current results exclude conversations.','会話一覧が未準備のため、現在の結果に会話は含まれません。','대화 목록이 준비되지 않아 현재 결과에 대화가 포함되지 않습니다.','Danh mục trò chuyện chưa sẵn sàng; kết quả hiện tại không gồm cuộc trò chuyện.','El directorio de conversaciones no está listo; los resultados actuales no incluyen conversaciones.','Le répertoire des conversations n’est pas prêt ; les résultats actuels n’en contiennent pas.','Das Gesprächsverzeichnis ist noch nicht bereit; Gespräche fehlen in den aktuellen Ergebnissen.','O diretório de conversas ainda não está pronto; os resultados atuais não incluem conversas.'),
 r('workspaceSearch.detail.group','群协作','群組協作','Group collaboration','グループ協業','그룹 협업','Cộng tác nhóm','Colaboración en grupo','Collaboration de groupe','Gruppenzusammenarbeit','Colaboração em grupo'),
 r('workspaceSearch.detail.business','业务空间','業務空間','Business space','業務スペース','업무 공간','Không gian nghiệp vụ','Espacio de negocio','Espace métier','Geschäftsbereich','Espaço de negócio'),
 r('workspaceSearch.detail.knowledge','知识文档','知識文件','Knowledge document','ナレッジ文書','지식 문서','Tài liệu tri thức','Documento de conocimiento','Document de connaissance','Wissensdokument','Documento de conhecimento'),
 r('workspaceSearch.detail.market','市场内容','市場內容','Market item','マーケット項目','마켓 항목','Mục trong chợ','Elemento del mercado','Élément du marché','Markteintrag','Item do mercado'),
 r('workspaceSearch.knowledgeLoading','正在读取知识目录…','正在讀取知識目錄…','Loading the knowledge directory…','ナレッジ一覧を読み込んでいます…','지식 목록을 불러오는 중…','Đang tải danh mục tri thức…','Cargando el directorio de conocimiento…','Chargement du répertoire de connaissances…','Wissensverzeichnis wird geladen…','A carregar o diretório de conhecimento…'),
 r('workspaceSearch.knowledgeUnavailable','知识目录暂不可用；已加载的结果会继续保留。','知識目錄暫時無法使用；已載入的結果會繼續保留。','The knowledge directory is unavailable; previously loaded results are retained.','ナレッジ一覧を読み込めません。読み込み済みの結果は保持されます。','지식 목록을 불러올 수 없습니다. 이전에 불러온 결과는 유지됩니다.','Danh mục tri thức hiện không khả dụng; kết quả đã tải vẫn được giữ lại.','El directorio de conocimiento no está disponible; se conservan los resultados ya cargados.','Le répertoire de connaissances est indisponible ; les résultats déjà chargés sont conservés.','Das Wissensverzeichnis ist nicht verfügbar; bereits geladene Ergebnisse bleiben erhalten.','O diretório de conhecimento está indisponível; os resultados já carregados são mantidos.'),
 r('workspaceSearch.detail.skill','可用技能','可用技能','Available Skill','利用可能なスキル','사용 가능한 스킬','Kỹ năng khả dụng','Habilidad disponible','Compétence disponible','Verfügbarer Skill','Competência disponível'),
 r('workspaceSearch.detail.plugin','已激活扩展','已啟用擴充','Active extension','有効な拡張機能','활성 확장 기능','Tiện ích mở rộng đang hoạt động','Extensión activa','Extension active','Aktive Erweiterung','Extensão ativa'),
 r('workspaceSearch.detail.mcp','可用 MCP 工具','可用 MCP 工具','Available MCP tool','利用可能な MCP ツール','사용 가능한 MCP 도구','Công cụ MCP khả dụng','Herramienta MCP disponible','Outil MCP disponible','Verfügbares MCP-Werkzeug','Ferramenta MCP disponível'),
 r('workspaceSearch.capabilityLoading','正在核验技能…','正在核驗技能…','Checking skills…','スキルを確認しています…','스킬을 확인하는 중…','Đang kiểm tra kỹ năng…','Comprobando las habilidades…','Vérification des compétences…','Skills werden geprüft…','A verificar as competências…'),
 r('workspaceSearch.capabilityUnavailable','部分技能来源暂不可用；仅显示本次已核验结果。','部分技能來源暫時無法使用；僅顯示本次已核驗結果。','Some skill sources are unavailable; only results verified in this check are shown.','一部のスキルソースを利用できません。今回確認できた結果のみ表示します。','일부 스킬 소스를 사용할 수 없어 이번에 확인된 결과만 표시합니다.','Một số nguồn kỹ năng hiện không khả dụng; chỉ hiển thị kết quả đã được xác minh trong lần kiểm tra này.','Algunas fuentes de habilidades no están disponibles; solo se muestran los resultados verificados en esta comprobación.','Certaines sources de compétences sont indisponibles ; seuls les résultats vérifiés lors de ce contrôle sont affichés.','Einige Skill-Quellen sind nicht verfügbar; angezeigt werden nur bei dieser Prüfung bestätigte Ergebnisse.','Algumas fontes de competências estão indisponíveis; apenas são mostrados os resultados verificados nesta verificação.'),
] as const
