import {test,before,after} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,writeFile,rm,readFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {join} from 'node:path'
import {build} from 'vite'
// @ts-expect-error 既有独立无界面浏览器夹具。
import {launchOptions,loadPlaywright} from './fixtures/load-playwright.mjs'
const root=fileURLToPath(new URL('../../../../',import.meta.url)),client=fileURLToPath(new URL('../src/client/',import.meta.url))
let browser:any,script:string,styles:string,temp:string
const entry=`
import React from 'react';import {createRoot} from 'react-dom/client';import {BusinessConfigurationPage} from '${client}BusinessConfigurationPage.tsx';import {BusinessRecordFlow} from '${client}business-record-flow.ts';import {createBusinessRecordApi} from '${client}business-record-api.ts';import {createBusinessImportFlowFactory} from '${client}business-import-integration.ts';import {I18nProvider} from '${client}i18n/provider.tsx';import {translateMessage} from '${client}i18n/messages.ts';
const hash='a'.repeat(64),fixedHash='b'.repeat(64),stamp='2026-09-30T00:00:00.000Z',namespace='teloa.business-builder/v1/personal-space/11111111-1111-4111-8111-111111111111',token={},draftId='22222222-2222-4222-8222-222222222222',newId='33333333-3333-4333-8333-333333333333',oldId='44444444-4444-4444-8444-444444444444';
const fixture=window.entryFixture={calls:[],factoryCalls:[],lostStage:false,emptyStageReceipt:false};let draft,receipt,imported=false;
const old={scope:'sales',type:'customer',id:oldId,version:2,snapshotHash:hash,title:'当前旧客户',summary:'',source:'本地记录',observedAt:stamp,receivedAt:stamp,quality:'complete',fields:[]},fixed={...old,version:1,snapshotHash:fixedHash,title:'固定旧客户'};
const call=async(method,input)=>{fixture.calls.push({method,input});let value;switch(method){
case 'business-records/list':value={schema:'teloa.business-data-page/v1',sourceId:'records',capturedAt:stamp,items:input.type==='customer'?[old,...(imported?[{...old,id:newId,version:1,title:'新客户'}]:[])]:[]};break;
case 'business-records/get':value=input.version===1?fixed:old;break;
case 'business-imports/stage':{const bytes=Uint8Array.from(atob(input.dataBase64),c=>c.charCodeAt(0)),sha=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');draft={format:'teloa.business-record-import/v1',id:draftId,stageRequestId:input.requestId,ownerId:'local:teloa-owner',scope:input.scope,type:input.type,sourceIdentity:hash,revision:1,status:'ready',file:{attachmentId:'attachment',name:input.name,bytes:input.bytes,sha256:sha},createdAt:stamp,updatedAt:stamp};if(fixture.lostStage)throw Error('lost');value=draft;break}
case 'business-imports/stage-receipt':value=fixture.emptyStageReceipt?null:draft;break;
case 'business-imports/get':value=draft;break;
case 'business-imports/inspect':value={format:'teloa.business-import-inspection/v1',draftId,scope:draft.scope,type:draft.type,fileHash:draft.file.sha256,revision:draft.revision,delimiter:input.delimiter,parserVersion:'csv-v1',headerRow:1,columns:[{column:0,header:'编号'},{column:1,header:'名称'}],sampleRows:[{rowNumber:2,cells:['001','新客户']}],sampleRowsOmitted:0,dataRows:1,issues:[],complete:true,canMap:true};break;
case 'business-imports/preview':draft={...draft,status:'previewed',revision:draft.revision+1,mapping:input.mapping,preview:{revision:draft.revision+1,digest:hash,schemaFingerprint:hash,writeSchemaFingerprint:hash,configurationVersion:1,sourceIdentity:hash,sourcePolicyDigest:hash,contentKey:hash,mapping:input.mapping,rows:[{rowNumber:2,primaryKey:['001'],operation:{operation:'create',type:draft.type,title:'新客户',summary:'',fields:[]}}],issues:[],canApply:true}};value=draft;break;
case 'business-imports/apply':imported=true;receipt={requestId:input.requestId,canonicalRequestId:input.requestId,draftId,scope:draft.scope,type:draft.type,fileHash:draft.file.sha256,previewDigest:input.previewDigest,sourceIdentity:hash,sourcePolicyDigest:hash,contentKey:hash,created:1,references:[{scope:draft.scope,type:draft.type,id:newId,version:1,snapshotHash:hash}],appliedAt:stamp};value=receipt;break;
case 'business-imports/receipt':value=receipt??null;break;
default:throw Error('unexpected '+method)
}return {ok:true,value}};
const factory=createBusinessImportFlowFactory({ownerId:'local:teloa-owner',identity:()=>({status:'ready',namespace,api:token}),generation:()=>token,storage:localStorage,call});
const records=new BusinessRecordFlow(createBusinessRecordApi(async(...args)=>{const result=await call(...args);if(!result.ok)throw Error('rejected');return result.value}));
const importer=(scope,type)=>{fixture.factoryCalls.push([scope,type]);if(fixture.identityUnavailable)throw Error('identity unverified');return factory.forTarget(namespace,token,scope,type)};fixture.target=()=>factory.forTarget(namespace,token,'sales','customer');
const snapshot={locale:'zh-CN',dshLocale:'zh-CN',revision:1},runtime={t:(key,params)=>translateMessage('zh-CN',key,params),subscribe:()=>()=>{},getSnapshot:()=>snapshot};
const app=createRoot(document.getElementById('root'));fixture.render=(options={})=>{const type=options.type??'customer',preview=options.preview??false,projection={scope:'sales',configurationHash:hash,mode:preview?'preview':'saved',...(preview?{draftId,revision:1}:{configurationVersion:1}),page:{kind:'records',definition:{id:type+'s',kind:'records',title:type==='customer'?'客户记录':'联系人记录',objectType:type,fields:[],allowCreate:options.allowCreate??true,allowEdit:true,allowArchive:true},objectType:{format:'teloa.business-object-type/v1',domain:'sales',id:type,version:'1.0.0',sourceId:'records',title:type==='customer'?'客户':'联系人',unit:'条',lead:'',fields:[]},emptyState:'no-records'}};app.render(<I18nProvider runtime={runtime}><BusinessConfigurationPage projection={projection} recordFlow={records} capabilities={{create:options.canCreate??true,edit:true,archive:true}} importFlow={importer} recordReference={options.fixed?{scope:'sales',type:'customer',id:oldId,version:1,snapshotHash:fixedHash}:undefined} colorScheme="light"/></I18nProvider>)};fixture.render({preview:true});
`
before(async()=>{temp=await mkdtemp(join(root,'.runtime-import-entry-'));await writeFile(join(temp,'fixture.tsx'),entry);const result=await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,rollupOptions:{external:(id:string)=>id.startsWith('node:'),treeshake:{moduleSideEffects:false}},lib:{entry:join(temp,'fixture.tsx'),name:'ImportEntryFixture',formats:['iife']}}});const bundle=Array.isArray(result)?result[0]:result;assert.ok(bundle&&'output'in bundle);script=bundle.output.find(item=>item.type==='chunk')!.code;styles=bundle.output.flatMap(item=>item.type==='asset'&&item.fileName.endsWith('.css')?[String(item.source)]:[]).join('\n');browser=await loadPlaywright().chromium.launch(launchOptions())})
after(async()=>{await browser?.close();if(temp)await rm(temp,{recursive:true,force:true})})
async function mount(t:any,width=390){const page=await browser.newPage({viewport:{width,height:1100}}),errors:string[]=[];page.setDefaultTimeout(6000);page.on('pageerror',(e:Error)=>errors.push(e.message));t.after(async()=>{await page.close();assert.deepEqual(errors,[])});await page.route('**/*',(route:any)=>route.request().isNavigationRequest()?route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><div id="root"></div></body></html>'}):route.abort());await page.goto('https://fixture.invalid');await page.addStyleTag({content:'*{box-sizing:border-box}body{margin:0;padding:16px;font-family:system-ui;--teloa-border:#ddd;--teloa-surface:#fff;--teloa-subtle:#f4f4f4;--teloa-text:#222;--teloa-muted:#666;--teloa-accent:#8e4226;--teloa-focus:#4076db}'+styles});await page.addScriptTag({content:script});await page.getByText('采用后从第一条记录开始',{exact:false}).count();return page}
async function saved(page:any,options={}){await page.evaluate((o:unknown)=>(window as any).entryFixture.render(o),options);await page.getByRole('button',{name:'刷新记录',exact:true}).waitFor()}
async function upload(page:any){await page.getByRole('button',{name:'导入表格',exact:true}).click();await page.getByLabel('CSV 或 XLSX 文件',{exact:true}).setInputFiles({name:'客户.csv',mimeType:'text/csv',buffer:Buffer.from('编号,名称\n001,新客户')})}
test('only_adopted_records_with_actual_create_right_show_import_entry_and_preview_never_accesses_factory',async t=>{const page=await mount(t);assert.equal(await page.getByRole('button',{name:'导入表格',exact:true}).count(),0);assert.deepEqual(await page.evaluate(()=>(window as any).entryFixture.factoryCalls),[]);for(const options of [{canCreate:false},{allowCreate:false}]){await saved(page,options);assert.equal(await page.getByRole('button',{name:'导入表格',exact:true}).count(),0);assert.deepEqual(await page.evaluate(()=>(window as any).entryFixture.factoryCalls),[])}await saved(page);assert.equal(await page.getByRole('button',{name:'导入表格',exact:true}).count(),1)})
test('unknown_import_survives_close_reopen_and_page_switch_with_original_target_and_id',async t=>{const page=await mount(t);await saved(page);await page.evaluate(()=>{(window as any).entryFixture.lostStage=true;(window as any).entryFixture.emptyStageReceipt=true});await upload(page);await page.getByText('原请求结果未知，文件和映射已冻结。空回执不代表未受理。',{exact:true}).waitFor();await page.getByRole('button',{name:'关闭导入',exact:true}).click();await saved(page,{type:'contact'});await saved(page);await page.getByRole('button',{name:'导入表格',exact:true}).click();await page.getByText('原请求结果未知，文件和映射已冻结。空回执不代表未受理。',{exact:true}).waitFor();await page.getByRole('button',{name:'核对原请求',exact:true}).click();assert.equal(await page.getByRole('button',{name:'确认导入',exact:true}).isDisabled(),true);const calls=await page.evaluate(()=>(window as any).entryFixture.calls);assert.equal(calls.filter((c:any)=>c.method.endsWith('/stage')).length,1);const a=calls.find((c:any)=>c.method.endsWith('/stage')),b=calls.find((c:any)=>c.method.endsWith('/stage-receipt'));assert.equal(b.input.requestId,a.input.requestId);assert.equal(b.input.type,'customer')})
test('successful_import_refreshes_directory_once_and_keeps_fixed_source_detail',async t=>{const page=await mount(t,1280);await saved(page,{fixed:true});await page.getByRole('heading',{name:'固定旧客户',exact:true}).waitFor();await upload(page);await page.getByText('文件已保存：客户.csv',{exact:true}).waitFor();await page.getByLabel('分隔符',{exact:true}).selectOption(',');await page.getByRole('button',{name:'读取表头与样例',exact:true}).click();await page.getByLabel('主键第1列',{exact:true}).selectOption('0');await page.getByLabel('标题列',{exact:true}).selectOption('1');await page.getByRole('button',{name:'生成全部行预览',exact:true}).click();await page.getByText('全部1行规范结果',{exact:true}).waitFor();const before=await page.evaluate(()=>(window as any).entryFixture.calls.filter((c:any)=>c.method==='business-records/list').length);await page.getByRole('checkbox',{name:'我已核对全部行并确认导入',exact:true}).check();await page.getByRole('button',{name:'确认导入',exact:true}).click();await page.getByText('已导入批次：1条记录',{exact:true}).waitFor();await page.getByRole('button',{name:/新客户/}).waitFor();assert.equal(await page.getByRole('heading',{name:'固定旧客户',exact:true}).count(),1);assert.equal(await page.evaluate(()=>(window as any).entryFixture.calls.filter((c:any)=>c.method==='business-records/list').length),before+1);await page.getByRole('button',{name:'关闭导入',exact:true}).click();await page.getByRole('button',{name:'导入表格',exact:true}).click();await page.getByText('已导入批次：1条记录',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).entryFixture.calls.filter((c:any)=>c.method==='business-records/list').length),before+1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)})
test('formal_index_surface_and_frame_pass_the_import_factory_through_without_preview_injection',async()=>{const files=await Promise.all(['index.ts','WorkbenchFrame.tsx','BusinessConfigurationSurface.tsx'].map(name=>readFile(join(client,name),'utf8')));assert.match(files[0]!,/createBusinessImportFlowFactory/);assert.match(files[0]!,/businessImports\.dispose/);assert.match(files[1]!,/importFlow:/);assert.match(files[2]!,/importFlow=\{services\.importFlow\}/)})
test('unverified_identity_disables_formal_import_entry_instead_of_claiming_readiness',async t=>{const page=await mount(t);await page.evaluate(()=>{(window as any).entryFixture.identityUnavailable=true});await saved(page);await page.getByRole('alert').filter({hasText:'本人业务连接尚未确认'}).waitFor();assert.equal(await page.getByRole('button',{name:'导入表格',exact:true}).isDisabled(),true);assert.equal(await page.getByLabel('CSV 或 XLSX 文件',{exact:true}).count(),0);assert.equal(await page.evaluate(()=>(window as any).entryFixture.calls.some((c:any)=>c.method.startsWith('business-imports/'))),false)})
test('applied_import_allows_the_next_file_without_reusing_the_previous_batch_and_freezes_new_unknown',async t=>{
 const page=await mount(t);await saved(page);await upload(page)
 await page.getByText('文件已保存：客户.csv',{exact:true}).waitFor();await page.getByLabel('分隔符',{exact:true}).selectOption(',');await page.getByRole('button',{name:'读取表头与样例',exact:true}).click()
 await page.getByLabel('主键第1列',{exact:true}).selectOption('0');await page.getByLabel('标题列',{exact:true}).selectOption('1');await page.getByRole('button',{name:'生成全部行预览',exact:true}).click()
 await page.getByText('全部1行规范结果',{exact:true}).waitFor();await page.getByRole('checkbox',{name:'我已核对全部行并确认导入',exact:true}).check();await page.getByRole('button',{name:'确认导入',exact:true}).click();await page.getByText('已导入批次：1条记录',{exact:true}).waitFor()
 assert.equal(await page.getByLabel('CSV 或 XLSX 文件',{exact:true}).isDisabled(),false,'成功批次不能永久封死同类型下一份文件')
 await page.evaluate(()=>{(window as any).entryFixture.lostStage=true;(window as any).entryFixture.emptyStageReceipt=true})
 await page.getByLabel('CSV 或 XLSX 文件',{exact:true}).setInputFiles({name:'另一批客户.csv',mimeType:'text/csv',buffer:Buffer.from('编号,名称\n002,另一批客户')})
 await page.getByText('原请求结果未知，文件和映射已冻结。空回执不代表未受理。',{exact:true}).waitFor()
 assert.equal(await page.getByText('已导入批次：1条记录',{exact:true}).count(),0)
 const calls=await page.evaluate(()=>(window as any).entryFixture.calls),stages=calls.filter((row:any)=>row.method==='business-imports/stage')
 assert.equal(stages.length,2);assert.notEqual(stages[0].input.requestId,stages[1].input.requestId);assert.equal(stages[1].input.name,'另一批客户.csv');assert.equal(calls.filter((row:any)=>row.method==='business-imports/apply').length,1)
 assert.equal(await page.getByRole('button',{name:'确认导入',exact:true}).isDisabled(),true)
})
