import assert from 'node:assert/strict'
import {test,before,after} from 'node:test'
import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {join} from 'node:path'
import {build} from 'vite'
// @ts-expect-error 既有测试浏览器夹具为无声明的 MJS 模块。
import {launchOptions,loadPlaywright} from './fixtures/load-playwright.mjs'
const root=fileURLToPath(new URL('../../../../',import.meta.url)),client=fileURLToPath(new URL('../src/client/',import.meta.url))
const {chromium}=loadPlaywright();let browser:any,script:string,styles:string,temp:string
const entry=`
import React from 'react';import {createRoot} from 'react-dom/client';
import {readBusinessConfigurationPageProjectionVersioned} from '@teloa/contract';
import {BusinessConfigurationPage} from '${client}BusinessConfigurationPage.tsx';
import {BusinessRecordFlow} from '${client}business-record-flow.ts';import {createBusinessRecordApi} from '${client}business-record-api.ts';
import {I18nProvider} from '${client}i18n/provider.tsx';import {translateMessage} from '${client}i18n/messages.ts';
const locale=document.documentElement.lang,en=locale==='en',snapshot={locale,dshLocale:en?'en':'zh',revision:1},runtime={t:(key,params)=>translateMessage(locale,key,params),subscribe:()=>()=>{},getSnapshot:()=>snapshot};
const stamp='2026-09-30T00:00:00.000Z',hash='a'.repeat(64),titles={'customer-a':en?'Customer Alpha':'客户甲','customer-b':en?'Customer Beta':'客户乙','customer-c':en?'Customer Gamma':'客户丙'};
const make=(id,type='customer')=>({scope:'sales',type,id,version:1,snapshotHash:hash,title:titles[id]??'Customer '+id.slice(-4),summary:'',source:'本地记录',observedAt:stamp,receivedAt:stamp,quality:'complete',fields:[]});
const original='["customer-a","customer-b"]';let rows=[{...make('order-one','order'),title:en?'Order One':'订单一',fields:[{label:'客户关联',value:original}]}],stored=null,receipts=new Map(),sequence=0;
const state=window.multiRelationsFixture={calls:[],go:[],reads:{},writeMode:'ok',pageMode:'ok',slowChoice:false,pending:[]};
let objectType={format:'teloa.business-object-type/v2',id:'order',version:'1.0.0',domain:'sales',title:en?'Order':'订单',unit:en?'records':'条',lead:en?'Order follow-up':'跟进订单',fields:[{format:'teloa.business-rich-field/v2',name:'customers',label:en?'Customers':'客户',from:'客户关联',type:'multi-reference',required:true,referenceType:'customer'}],sourceId:'records',constraints:{uniqueFields:['customers']}};
const definition={id:'orders',title:en?'Orders':'订单记录',kind:'records',objectType:'order',fields:['customers'],allowCreate:true,allowEdit:true,allowArchive:true};
const api=createBusinessRecordApi(async(endpoint,input)=>{
 state.calls.push([endpoint,input]);
 if(endpoint.endsWith('/list')){if(input.type==='order')return {schema:'teloa.business-data-page/v1',sourceId:'records',capturedAt:stamp,items:rows};if(input.cursor&&state.pageMode==='failed')throw Error('offline');return {schema:'teloa.business-data-page/v1',sourceId:'records',capturedAt:stamp,items:input.cursor?[make('customer-b'),make('customer-c')]:[make('customer-a')],...(input.cursor?{}:{nextCursor:'page-two'})}}
 if(endpoint.endsWith('/get')){if(input.type==='order')return rows.find(row=>row.id===input.id);if(state.slowChoice&&input.id==='customer-c')return await new Promise(resolve=>state.pending.push(()=>resolve(make(input.id))));const mode=state.reads[input.id];if(mode==='forbidden')throw Object.assign(Error('private '+input.id),{code:'teloa/forbidden'});if(mode==='missing')throw Object.assign(Error('private '+input.id),{code:'teloa/not-found'});if(mode==='failed')throw Error('private '+input.id);return {...make(input.id),...(mode==='archived'?{deletedAt:stamp}:{})}}
 if(endpoint.endsWith('/receipt'))return receipts.get(input.requestId)??null;
 if(endpoint.endsWith('/create')||endpoint.endsWith('/edit')){if(state.writeMode==='unique')throw Object.assign(Error('private duplicate'),{code:'teloa/conflict',details:{field:'customers',reason:'unique-field'}});if(state.writeMode==='conflict')throw Object.assign(Error('changed'),{code:'teloa/version-conflict'});if(state.writeMode==='before')throw Error('offline');const result={...make(input.id??'order-two','order'),title:input.title,summary:input.summary,version:input.expectedVersion?input.expectedVersion+1:1,fields:input.fields.filter(f=>f.value).map(f=>({label:'客户关联',value:f.value}))};receipts.set(input.requestId,result);rows=[result];if(state.writeMode==='lost')throw Error('lost');return result}
 throw Error('unexpected endpoint');
});
const journal=()=>({read:()=>stored,write:raw=>{stored=raw},clear:()=>{stored=null}});let flow=new BusinessRecordFlow(api,()=> '22222222-2222-4222-8222-'+String(++sequence).padStart(12,'0'),journal);const app=createRoot(document.getElementById('root'));
state.render=()=>{const projection=readBusinessConfigurationPageProjectionVersioned({format:'teloa.business-configuration-page/v2',mode:'saved',scope:'sales',configurationHash:hash,page:{kind:'records',definition,objectType,emptyState:'no-records'},configurationVersion:1});app.render(<I18nProvider runtime={runtime}><BusinessConfigurationPage projection={projection} recordFlow={flow} capabilities={{create:true,edit:true,archive:true}} colorScheme="light" go={target=>state.go.push(target)}/></I18nProvider>)};
state.rename=()=>{titles['customer-a']=en?'Renamed Alpha':'客户甲新名称'};state.restore=()=>{flow=new BusinessRecordFlow(api,()=>'33333333-3333-4333-8333-333333333333',journal);state.render()};state.changeType=()=>{objectType={...objectType,fields:objectType.fields.map(f=>({...f,referenceType:'project'}))};state.render()};state.optional=()=>{objectType={...objectType,fields:objectType.fields.map(f=>({...f,required:false}))};state.render()};state.fill=(ids)=>flow.forTarget('sales','order').changeField('customers',JSON.stringify(ids.sort()));state.flush=()=>{state.slowChoice=false;state.pending.splice(0).forEach(resolve=>resolve())};state.form=()=>flow.forTarget('sales','order').getSnapshot();state.render();
`
before(async()=>{await mkdir(join(client,'../../.runtime'),{recursive:true});temp=await mkdtemp(join(client,'../../.runtime/multi-relation-record-ui-'));await writeFile(join(temp,'fixture.tsx'),entry);const result=await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,rollupOptions:{external:(id:string)=>id.startsWith('node:'),treeshake:{moduleSideEffects:false}},lib:{entry:join(temp,'fixture.tsx'),name:'MultiRelationFixture',formats:['iife']}}});const bundle=Array.isArray(result)?result[0]:result;assert.ok(bundle&&'output'in bundle);script=bundle.output.find(item=>item.type==='chunk')!.code;styles=bundle.output.flatMap(item=>item.type==='asset'&&item.fileName.endsWith('.css')?[String(item.source)]:[]).join('\n');browser=await chromium.launch(launchOptions())})
after(async()=>{await browser?.close();if(temp)await rm(temp,{recursive:true,force:true})})
async function setup(t:{after:(fn:()=>Promise<void>)=>void},locale='zh-CN',width=390){const page=await browser.newPage({viewport:{width,height:1100}});page.setDefaultTimeout(5000);const errors:string[]=[],requests:string[]=[];page.on('pageerror',(error:Error)=>errors.push(error.message));await page.route('**/*',(route:any)=>{requests.push(route.request().url());return route.abort()});t.after(async()=>{await page.close();assert.deepEqual(errors,[]);assert.deepEqual(requests,[])});await page.setContent('<!doctype html><html lang="'+locale+'"><body><div id="root"></div></body></html>');await page.addStyleTag({content:':root{--teloa-font-section:18px;--teloa-font-body:14px;--teloa-font-caption:12px;--teloa-font-control:14px;--teloa-weight-heading:600;--teloa-weight-medium:500;--teloa-leading-heading:1.4;--teloa-border:#ddd;--teloa-surface:#fff;--teloa-subtle:#f5f5f2;--teloa-text:#252823;--teloa-muted:#646a62;--teloa-accent:#9e4226;--teloa-on-accent:#fff}body{font-family:system-ui;margin:16px}'+styles});await page.addScriptTag({content:script});return page}
for(const locale of ['zh-CN','en'])for(const width of [390,1400])test(locale+'/'+width+' 多选独立标题、分页增删和拒绝保稿',async t=>{
 const page=await setup(t,locale,width),en=locale==='en',alpha=en?'Customer Alpha':'客户甲',beta=en?'Customer Beta':'客户乙',gamma=en?'Customer Gamma':'客户丙';try{await page.getByText(alpha,{exact:true}).waitFor()}catch(error){t.diagnostic(await page.locator('body').innerText());t.diagnostic(JSON.stringify(await page.evaluate(()=>(window as any).multiRelationsFixture.calls)));throw error};await page.getByText(beta,{exact:true}).waitFor();await page.getByRole('button',{name:en?'Order One':'订单一'}).click();await page.getByRole('button',{name:alpha,exact:true}).click();await page.waitForFunction(()=>(window as any).multiRelationsFixture.go.length===1);const go=await page.evaluate(()=>(window as any).multiRelationsFixture.go[0]);assert.deepEqual(go.recordReference,{scope:'sales',type:'customer',id:'customer-a',version:1,snapshotHash:'a'.repeat(64)});await page.getByRole('button',{name:en?'Edit record':'编辑记录',exact:true}).click();const select=page.getByRole('combobox',{name:en?'Customers':'客户',exact:true});await select.waitFor();await page.getByRole('button',{name:en?'Load more':'加载更多',exact:true}).click();await select.selectOption({label:gamma});await page.waitForFunction(()=>(window as any).multiRelationsFixture.form().form.values.customers==='["customer-a","customer-b","customer-c"]');await page.getByRole('button',{name:(en?'Remove link: ':'移除关联：')+beta,exact:true}).click();await page.waitForFunction(()=>(window as any).multiRelationsFixture.form().form.values.customers==='["customer-a","customer-c"]');await page.evaluate(()=>(window as any).multiRelationsFixture.writeMode='unique');await page.getByRole('button',{name:en?'Save record':'保存记录',exact:true}).click();await page.getByText(en?'Saving failed. Your content is preserved. Check it and retry.':'保存未完成，内容已保留。请检查后重试。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-c"]');assert.equal((await page.locator('body').innerText()).includes('customer-a'),false);assert.equal(await page.locator('button button').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mkdir(join(root,'.runtime/record-multi-relations-ui'),{recursive:true});await page.getByText(en?'Each linked record can belong to only one active record.':'每条关联只能属于一条未归档记录。',{exact:true}).waitFor();await page.getByText(en?'This value is already used by another active record. Change it and retry. Your selection is preserved.':'此项已被其他未归档记录使用，请修改后重试。你的选择已保留。',{exact:true}).waitFor();await page.screenshot({path:join(root,'.runtime/record-multi-relations-ui',locale+'-'+width+'.png'),fullPage:true});
 await page.evaluate(()=>(window as any).multiRelationsFixture.writeMode='before');await page.getByRole('button',{name:en?'Save record':'保存记录',exact:true}).click();await page.getByRole('button',{name:en?'Check save result':'核对保存结果',exact:true}).waitFor();assert.equal(await select.isDisabled(),true);assert.equal(await page.getByRole('button',{name:(en?'Remove link: ':'移除关联：')+alpha,exact:true}).isDisabled(),true);await page.evaluate(()=>(window as any).multiRelationsFixture.restore());await page.getByRole('button',{name:en?'Check save result':'核对保存结果',exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-c"]');await page.screenshot({path:join(root,'.runtime/record-multi-relations-ui',locale+'-'+width+'-frozen.png'),fullPage:true});await page.getByRole('button',{name:en?'Check save result':'核对保存结果',exact:true}).click();await page.evaluate(()=>(window as any).multiRelationsFixture.writeMode='ok');await page.getByRole('button',{name:en?'Retry original operation':'重试原操作',exact:true}).click();await page.waitForFunction(()=>(window as any).multiRelationsFixture.form().phase==='saved');const writes=await page.evaluate(()=>(window as any).multiRelationsFixture.calls.filter((row:any)=>row[0]==='business-records/edit'));assert.deepEqual(writes[1][1],writes[2][1]);assert.equal(writes[2][1].fields[0].value,'["customer-a","customer-c"]')
})


test('逐目标改名与归档/不可用独立展示；分页失败和读取失败不删任何原选择',async t=>{
 const page=await setup(t);await page.getByRole('button',{name:/订单一/}).click();await page.getByRole('button',{name:'客户甲',exact:true}).waitFor();await page.evaluate(()=>(window as any).multiRelationsFixture.rename());await page.getByRole('button',{name:'刷新记录',exact:true}).click();await page.getByRole('button',{name:'客户甲新名称',exact:true}).waitFor();await page.getByRole('button',{name:'编辑记录',exact:true}).click();const select=page.getByRole('combobox',{name:'客户',exact:true});await select.waitFor();await page.evaluate(()=>(window as any).multiRelationsFixture.pageMode='failed');await page.getByRole('button',{name:'加载更多',exact:true}).click();await page.getByRole('alert').getByText('关联记录读取失败',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');
 for(const [mode,message] of [['archived','关联记录已归档'],['forbidden','无权查看关联记录'],['missing','关联记录不可用'],['failed','关联记录读取失败']]){
  await page.evaluate((mode:string)=>{(window as any).multiRelationsFixture.reads['customer-b']=mode},mode);
  await page.locator('form').getByRole('button',{name:/^(刷新记录|重试)$/,exact:true}).click();await page.getByRole('list',{name:'已选关联记录'}).getByText(message,{exact:true}).waitFor();await page.getByRole('list',{name:'已选关联记录'}).getByText('客户甲新名称',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');assert.equal((await page.locator('body').innerText()).includes('customer-b'),false)
 }
})

test('选择必须等真实get；核对中禁止保存，声明变化丢弃迟到回包并冻结原数组',async t=>{
 const page=await setup(t);await page.getByRole('button',{name:/订单一/}).click();await page.getByRole('button',{name:'编辑记录',exact:true}).click();const select=page.getByRole('combobox',{name:'客户',exact:true});await page.getByRole('button',{name:'加载更多',exact:true}).click();await page.evaluate(()=>(window as any).multiRelationsFixture.slowChoice=true);await select.selectOption({label:'客户丙'});await page.waitForFunction(()=>(window as any).multiRelationsFixture.pending.length===1);assert.equal(await page.getByRole('button',{name:'保存记录',exact:true}).isDisabled(),true);assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');await page.evaluate(()=>(window as any).multiRelationsFixture.changeType());await page.getByText('业务字段已改变，请关闭旧表单后重新打开。原内容仍保留在这里。',{exact:true}).waitFor();await page.evaluate(()=>(window as any).multiRelationsFixture.flush());assert.equal(await select.isDisabled(),true);assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.calls.filter((row:any)=>row[0]==='business-records/edit').length),0)
})

test('必填清空、32条和2000字符上限拒绝保留选择；可选逐项移除与清空',async t=>{
 const page=await setup(t);await page.getByRole('button',{name:/订单一/}).click();await page.getByRole('button',{name:'编辑记录',exact:true}).click();await page.getByRole('button',{name:'清空关联',exact:true}).click();await page.getByRole('alert').getByText('至少保留一条关联，原选择已保留。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');await page.getByRole('button',{name:'移除关联：客户乙',exact:true}).click();await page.getByRole('button',{name:'移除关联：客户甲',exact:true}).click();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a"]');
 await page.evaluate(()=>{(window as any).multiRelationsFixture.fill(Array.from({length:32},(_,i)=>'c-'+String(i).padStart(2,'0')))});await page.getByRole('button',{name:'加载更多',exact:true}).click();await page.getByRole('combobox',{name:'客户',exact:true}).selectOption({label:'客户丙'});await page.getByRole('alert').getByText('最多选择 32 条且关联内容不能过长，原选择已保留。请减少选择。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse((window as any).multiRelationsFixture.form().form.values.customers).length),32);
 const long=Array.from({length:10},(_,i)=>'x'.repeat(194)+i);await page.evaluate((ids:string[])=>(window as any).multiRelationsFixture.fill(ids),long);await page.getByRole('combobox',{name:'客户',exact:true}).selectOption({label:'客户丙'});await page.waitForFunction(()=>JSON.parse((window as any).multiRelationsFixture.form().form.values.customers).length===11);
 await page.evaluate((ids:string[])=>{(window as any).multiRelationsFixture.fill(ids)},Array.from({length:10},(_,i)=>'x'.repeat(195)+i));await page.getByRole('combobox',{name:'客户',exact:true}).selectOption({label:'客户丙'});await page.getByRole('alert').getByText('最多选择 32 条且关联内容不能过长，原选择已保留。请减少选择。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse((window as any).multiRelationsFixture.form().form.values.customers).length),10);
 await page.getByRole('button',{name:'取消',exact:true}).click();await page.evaluate(()=>(window as any).multiRelationsFixture.optional());await page.getByRole('button',{name:'编辑记录',exact:true}).click();await page.getByRole('button',{name:'移除关联：客户乙',exact:true}).click();await page.getByRole('button',{name:'清空关联',exact:true}).click();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'');assert.equal(await page.getByRole('list',{name:'已选关联记录'}).getByRole('listitem').count(),0)
})

test('受理后失回包重建原稿，目标随后归档仍以原成功回执结算且不重发',async t=>{
 const page=await setup(t);await page.getByRole('button',{name:/订单一/}).click();await page.getByRole('button',{name:'编辑记录',exact:true}).click();await page.evaluate(()=>(window as any).multiRelationsFixture.writeMode='lost');await page.getByRole('button',{name:'保存记录',exact:true}).click();await page.getByRole('button',{name:'核对保存结果',exact:true}).waitFor();await page.evaluate(()=>{(window as any).multiRelationsFixture.reads['customer-a']='archived';(window as any).multiRelationsFixture.restore()});await page.getByRole('button',{name:'核对保存结果',exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');await page.getByRole('button',{name:'核对保存结果',exact:true}).click();await page.waitForFunction(()=>(window as any).multiRelationsFixture.form().phase==='saved');assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.calls.filter((row:any)=>row[0]==='business-records/edit').length),1)
})

test('候选存在仍须授权get；目标拒绝或归档保持完整原选择',async t=>{
 const page=await setup(t);await page.getByRole('button',{name:/订单一/}).click();await page.getByRole('button',{name:'编辑记录',exact:true}).click();await page.getByRole('button',{name:'加载更多',exact:true}).click();
 for(const [mode,message] of [['archived','关联记录已归档'],['forbidden','无权查看关联记录'],['missing','关联记录不可用'],['failed','关联记录读取失败']]){
  await page.evaluate((mode:string)=>{(window as any).multiRelationsFixture.reads['customer-c']=mode},mode);await page.getByRole('combobox',{name:'客户',exact:true}).selectOption({label:'客户丙'});await page.getByRole('alert').getByText(message,{exact:true}).waitFor();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');assert.equal(await page.getByRole('button',{name:'保存记录',exact:true}).isDisabled(),false)
 }
})

test('版本冲突冻结全部选择，明确比较继续才允许移除',async t=>{
 const page=await setup(t);await page.getByRole('button',{name:/订单一/}).click();await page.getByRole('button',{name:'编辑记录',exact:true}).click();await page.evaluate(()=>(window as any).multiRelationsFixture.writeMode='conflict');await page.getByRole('button',{name:'保存记录',exact:true}).click();await page.getByRole('button',{name:'重读最新内容',exact:true}).waitFor();assert.equal(await page.getByRole('combobox',{name:'客户',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'移除关联：客户甲',exact:true}).isDisabled(),true);assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a","customer-b"]');await page.getByRole('button',{name:'重读最新内容',exact:true}).click();await page.getByRole('button',{name:'保留我的内容，以新版本继续编辑',exact:true}).click();await page.getByRole('button',{name:'移除关联：客户乙',exact:true}).click();assert.equal(await page.evaluate(()=>(window as any).multiRelationsFixture.form().form.values.customers),'["customer-a"]')
})
