import test,{before,after} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {join} from 'node:path'
import {build} from 'vite'
// @ts-expect-error 既有无头浏览器夹具没有声明。
import {launchOptions,loadPlaywright} from './fixtures/load-playwright.mjs'
const root=fileURLToPath(new URL('../../../../',import.meta.url)),client=fileURLToPath(new URL('../src/client/',import.meta.url))
let browser:any,script:string,styles:string,temp:string
const entry=`
import React from 'react';import {createRoot} from 'react-dom/client';
import {BusinessReassignment} from '${client}BusinessReassignment.tsx';
import {insertBusinessReassignmentInput} from '${client}business-reassignment-input.ts';
const old='11111111-1111-4111-8111-111111111111',role='22222222-2222-4222-8222-222222222222',next='33333333-3333-4333-8333-333333333333',stamp='2026-09-30T00:00:00.000Z';
const state=window.reassignmentFixture={scope:'sales',sessionId:'daily',contextRoleId:null,contextVersion:1,originals:[{oldRequestId:old,oldSessionId:'daily',scope:'sales',title:'订单跟进 / Follow up order',oldRoleId:old,stopSubmitted:true}],writes:[],navigation:[],busy:false,hold:false,release:null,outcome:null,input:{draft:'',draftRev:1,phase:'plain',attachmentIds:[],occurrences:[],queue:[]}};
const listeners=new Set(),app=createRoot(document.getElementById('root'));
const onPrepare=async selection=>{const scope=state.scope,sessionId=state.sessionId,contextVersion=state.contextVersion,contextRoleId=state.contextRoleId;state.busy=true;try{await insertBusinessReassignmentInput(selection,sessionId,{locale:document.documentElement.lang,switching:{read:()=>({mainSessionId:state.sessionId,bindingSessionId:state.sessionId,bindingReady:true,input:state.input,pendingSubmissions:[],monitor:{getSnapshot:()=>state.unknown,check:async()=>{}}})},isCurrent:()=>scope===state.scope&&sessionId===state.sessionId&&contextVersion===state.contextVersion&&contextRoleId===state.contextRoleId,verify:async()=>{if(state.hold)await new Promise(resolve=>state.release=resolve);return {...selection,scope:state.scope,context:{sessionId:state.sessionId,scopeId:state.scope,version:state.contextVersion,roleId:state.contextRoleId,locked:state.contextRoleId!==null}}},state:{getSnapshot:()=>state.input,subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn)}},insertText:request=>{state.writes.push(request);state.input={...state.input,draft:request.text,draftRev:state.input.draftRev+1};for(const fn of listeners)fn();return true}})}finally{state.busy=false}};
const onNewDaily=async intent=>{state.navigation.push(intent)};
state.render=()=>app.render(<div data-session-id={state.sessionId} data-business-scope={state.scope} data-context-version={state.contextVersion} data-context-role-id={state.contextRoleId??'none'}><BusinessReassignment locale={document.documentElement.lang} scope={state.scope} sessionId={state.sessionId} context={{scope:state.scope,sessionId:state.sessionId,version:state.contextVersion,roleId:state.contextRoleId}} originals={state.originals} carriedOldRequestId={state.carriedOldRequestId} roles={[{id:role,name:'Mina',kind:'employee',state:'active',version:2,scopes:[state.scope],ownerId:'owner',duty:'Follow up',dataScope:'Orders',executionScope:'Read',skills:[],knowledge:[],createdAt:stamp,updatedAt:stamp},{id:next,name:'Paused colleague',kind:'employee',state:'paused',version:1,scopes:[state.scope],ownerId:'owner',duty:'',dataScope:'',executionScope:'',skills:[],knowledge:[],createdAt:stamp,updatedAt:stamp}]} outcome={state.outcome??undefined} onPrepare={onPrepare} onNewDaily={onNewDaily}/></div>);
state.change=patch=>{Object.assign(state,patch);state.render()};state.render();
`
before(async()=>{
 await mkdir(join(client,'../../.runtime'),{recursive:true});temp=await mkdtemp(join(client,'../../.runtime/business-reassignment-'));await writeFile(join(temp,'fixture.tsx'),entry)
 const result=await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,rollupOptions:{external:(id:string)=>id.startsWith('node:'),treeshake:{moduleSideEffects:false}},lib:{entry:join(temp,'fixture.tsx'),name:'ReassignmentFixture',formats:['iife']}}})
 const bundle=Array.isArray(result)?result[0]:result;assert.ok(bundle&&'output'in bundle);script=bundle.output.find(item=>item.type==='chunk')!.code;styles=bundle.output.flatMap(item=>item.type==='asset'&&item.fileName.endsWith('.css')?[String(item.source)]:[]).join('\n')
 browser=await loadPlaywright().chromium.launch(launchOptions())
})
after(async()=>{await browser?.close();if(temp)await rm(temp,{recursive:true,force:true})})
async function fixture(t:any,locale='zh-CN',width=390){
 const page=await browser.newPage({viewport:{width,height:1000}});page.setDefaultTimeout(1500);const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',(error:Error)=>errors.push(error.message));await page.route('**/*',(route:any)=>{requests.push(route.request().url());return route.abort()});t.after(async()=>{await page.close();assert.deepEqual(errors,[]);assert.deepEqual(requests,[])})
 await page.setContent('<html lang="'+locale+'"><body><div id="root"></div></body></html>');await page.addStyleTag({content:':root{--teloa-font-section:18px;--teloa-font-body:14px;--teloa-border:#ddd;--teloa-surface:#fff;--teloa-text:#252823;--teloa-muted:#646a62;--teloa-accent:#9e4226;--teloa-on-accent:#fff}body{font-family:system-ui;margin:0}#root{width:100%}'+styles});await page.addScriptTag({content:script});return page
}
/** 等待真实React host提交新上下文；原生回调结束不代表DOM已完成更新。 */
async function committed(page:any,scope:string,sessionId:string){await page.locator('[data-business-scope="'+scope+'"][data-session-id="'+sessionId+'"]').waitFor()}
for(const locale of ['zh-CN','en'])for(const width of [390,1280])test(locale+'/'+width+' 显式选择后键盘只带入一次原输入，原停止意图不承诺后继',async t=>{
 const p=await fixture(t,locale,width),en=locale==='en',prepare=p.getByRole('button',{name:en?'Prepare in conversation input':'带入原输入',exact:true})
 await prepare.waitFor();assert.equal(await prepare.isDisabled(),true);assert.match(await p.getByRole('status').innerText(),en?/Stop request submitted/:/停止请求已提交/)
 await p.getByLabel(en?'Original work request':'原交办',{exact:true}).selectOption('11111111-1111-4111-8111-111111111111');await p.getByLabel(en?"New employee":'新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222');assert.equal(await p.getByText('Paused employee',{exact:true}).count(),0)
 await prepare.focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>(window as any).reassignmentFixture.writes.length===1);assert.match(await p.getByRole('status').innerText(),en?/Send it yourself/:/请本人发送/);await prepare.click();assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.writes.length),1)
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
})
test('已有草稿/附件/queue/unknown拒绝并保留；保稿失败不显示已带入',async t=>{
 const p=await fixture(t);await p.getByLabel('原交办',{exact:true}).selectOption('11111111-1111-4111-8111-111111111111');await p.getByLabel('新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222')
 for(const patch of [{draft:'原稿'},{attachmentIds:['file']},{queue:[{}]},{unknown:true}]){await p.evaluate((patch:any)=>{const s=(window as any).reassignmentFixture;s.change({input:{draft:'',draftRev:1,phase:'plain',attachmentIds:[],occurrences:[],queue:[],...patch},unknown:patch.unknown===true})},patch);await p.getByRole('button',{name:'带入原输入',exact:true}).click();await p.getByRole('alert').waitFor();assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.writes.length),0);assert.doesNotMatch(await p.getByRole('status').innerText(),/请本人发送/)}
})
test('锁定旧岗位只输出显式新建daily意图，跨daily仅保留选定oldRequestId',async t=>{
 const p=await fixture(t);await p.getByLabel('原交办',{exact:true}).selectOption('11111111-1111-4111-8111-111111111111');await p.getByLabel('新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222');await p.evaluate(()=>(window as any).reassignmentFixture.change({contextRoleId:'11111111-1111-4111-8111-111111111111'}));await p.locator('[data-context-role-id="11111111-1111-4111-8111-111111111111"]').waitFor();await p.getByLabel('新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222');assert.equal(await p.getByRole('button',{name:'带入原输入',exact:true}).isDisabled(),true)
 await p.evaluate(()=>{const s=(window as any).reassignmentFixture;s.input={...s.input,draft:'原会话稿'};s.originalInput=s.input});await p.getByRole('button',{name:'新建日常会话',exact:true}).click();assert.deepEqual(await p.evaluate(()=>(window as any).reassignmentFixture.navigation),[{scope:'sales',newConversation:true,oldRequestId:'11111111-1111-4111-8111-111111111111'}]);assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.contextRoleId),'11111111-1111-4111-8111-111111111111');assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.writes.length),0)
 await p.evaluate(()=>{const s=(window as any).reassignmentFixture;s.change({sessionId:'new-daily',contextRoleId:null,originals:[],carriedOldRequestId:'11111111-1111-4111-8111-111111111111',input:{draft:'',draftRev:1,phase:'plain',attachmentIds:[],occurrences:[],queue:[]}})});await committed(p,'sales','new-daily');assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.originalInput.draft),'原会话稿');assert.doesNotMatch(await p.locator('body').innerText(),/订单跟进/);assert.equal(await p.getByLabel('新员工',{exact:true}).inputValue(),'');assert.equal(await p.getByRole('alert').count(),0);await p.getByLabel('新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222');await p.getByRole('button',{name:'带入原输入',exact:true}).click();await p.waitForFunction(()=>(window as any).reassignmentFixture.writes.length===1)
})
test('异步核对期间切业务会话使旧操作失效且清选择，迟到回包不写新稿',async t=>{
 const p=await fixture(t);await p.getByLabel('原交办',{exact:true}).selectOption('11111111-1111-4111-8111-111111111111');await p.getByLabel('新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222');await p.evaluate(()=>{const s=(window as any).reassignmentFixture;s.originalInput=s.input;s.change({hold:true})});await p.getByRole('button',{name:'带入原输入',exact:true}).click();await p.waitForFunction(()=>typeof(window as any).reassignmentFixture.release==='function');await p.evaluate(()=>{const s=(window as any).reassignmentFixture;s.change({scope:'support',sessionId:'new-daily',originals:[],input:{draft:'新业务原稿',draftRev:7,phase:'plain',attachmentIds:[],occurrences:[],queue:[]}});s.release()});await p.waitForFunction(()=>!(window as any).reassignmentFixture.busy);await committed(p,'support','new-daily');assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.writes.length),0);assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.input.draft),'新业务原稿');assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.originalInput.draft),'');assert.equal(await p.getByLabel('新员工',{exact:true}).inputValue(),'');assert.equal(await p.getByRole('alert').count(),0)
})
test('真实四阶段及严格回执：核对/零后继/已建立，错误new ID或scope不显示成功',async t=>{
 const p=await fixture(t);await p.getByLabel('原交办',{exact:true}).selectOption('11111111-1111-4111-8111-111111111111')
 for(const [phase,label]of [['reconciling','仍在核对'],['no-successor','尚未创建后继']] as const){await p.evaluate((phase:string)=>(window as any).reassignmentFixture.change({outcome:{oldRequestId:'11111111-1111-4111-8111-111111111111',phase}}),phase);assert.match(await p.getByRole('status').innerText(),new RegExp(label))}
 await p.evaluate(()=>{const expected={oldRequestId:'11111111-1111-4111-8111-111111111111',newRequestId:'33333333-3333-4333-8333-333333333333',oldSessionId:'daily',newSessionId:'daily',scope:'sales',snapshotHash:'a'.repeat(64)};(window as any).reassignmentFixture.change({outcome:{oldRequestId:expected.oldRequestId,phase:'established',expected,receipt:{...expected,createdAt:'2026-09-30T00:00:00.000Z'}}})});assert.match(await p.getByRole('status').innerText(),/已建立后继/)
 for(const patch of [{newRequestId:'22222222-2222-4222-8222-222222222222'},{scope:'support'}]){await p.evaluate((patch:any)=>{const s=(window as any).reassignmentFixture;s.change({outcome:{...s.outcome,receipt:{...s.outcome.receipt,...patch}}})},patch);await p.getByRole('alert').waitFor();assert.doesNotMatch(await p.getByRole('status').innerText(),/已建立后继/)}
})

for(const [version,roleId] of [[2,null],[2,'22222222-2222-4222-8222-222222222222'],[1,'22222222-2222-4222-8222-222222222222'],[2,'11111111-1111-4111-8111-111111111111']] as const)test('同scope/session屏障后context v'+version+'/'+(roleId??'null')+'失效旧选择与prepared/failed，保留原输入零写',async t=>{
 const p=await fixture(t);await p.getByLabel('原交办',{exact:true}).selectOption('11111111-1111-4111-8111-111111111111');await p.getByLabel('新员工',{exact:true}).selectOption('22222222-2222-4222-8222-222222222222');await p.evaluate(()=>{const s=(window as any).reassignmentFixture;s.originalInput=s.input;s.change({hold:true})});await p.getByRole('button',{name:'带入原输入',exact:true}).click();await p.waitForFunction(()=>typeof(window as any).reassignmentFixture.release==='function')
 await p.evaluate(([version,roleId]:[number,string|null])=>(window as any).reassignmentFixture.change({contextVersion:version,contextRoleId:roleId}),[version,roleId]);await p.locator('[data-session-id="daily"][data-business-scope="sales"][data-context-version="'+version+'"][data-context-role-id="'+(roleId??'none')+'"]').waitFor();const chosen=await p.getByLabel('新员工',{exact:true}).inputValue();await p.evaluate(()=>(window as any).reassignmentFixture.release());await p.waitForFunction(()=>!(window as any).reassignmentFixture.busy)
 assert.equal(chosen,'');assert.equal(await p.getByLabel('新员工',{exact:true}).inputValue(),'');assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.writes.length),0);assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.input===(window as any).reassignmentFixture.originalInput),true);assert.equal(await p.evaluate(()=>(window as any).reassignmentFixture.input.draft),'');assert.doesNotMatch(await p.getByRole('status').innerText(),/请本人发送/);assert.equal(await p.getByRole('alert').count(),0)
})
