import assert from 'node:assert/strict'
import {test} from 'node:test'
import {mkdtemp,writeFile,rm} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {join} from 'node:path'
import {build} from 'vite'
// @ts-expect-error 既有无头浏览器加载器。
import {launchOptions,loadPlaywright} from './fixtures/load-playwright.mjs'

const root=fileURLToPath(new URL('../../../../',import.meta.url))
const entry=fileURLToPath(new URL('../src/client/guest.tsx',import.meta.url))

test('访客复用工作导航、保留输入，浏览不读取本人存储或连接服务，使用时才请求准入',async t=>{
 const temp=await mkdtemp(join(root,'.runtime-guest-workbench-'))
 t.after(()=>rm(temp,{recursive:true,force:true}))
 await writeFile(join(temp,'entry.ts'),`import {mountGuestWorkbench} from ${JSON.stringify(entry)}; const state=window.guestTest={calls:[],prompt:'原草稿'};state.handle=mountGuestWorkbench(document.getElementById('root'),{product:'Pro',initialPrompt:state.prompt,maxPromptLength:4000,onPromptChange:value=>{state.prompt=value},onStart:()=>state.calls.push('start'),onAccount:()=>state.calls.push('account')});`)
 const result=await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,lib:{entry:join(temp,'entry.ts'),name:'GuestWorkbenchTest',formats:['iife']}}})
 const bundle=Array.isArray(result)?result[0]:result
 assert.ok(bundle&&'output'in bundle)
 const script=bundle.output.find(item=>item.type==='chunk')!.code
 const styles=bundle.output.flatMap(item=>item.type==='asset'&&item.fileName.endsWith('.css')?[String(item.source)]:[]).join('\n')
 const browser=await loadPlaywright().chromium.launch(launchOptions());t.after(()=>browser.close())
 const page=await browser.newPage({viewport:{width:1400,height:900}});t.after(()=>page.close())
 const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',(error:Error)=>errors.push(error.message))
 await page.route('**/*',(route:any)=>{requests.push(route.request().url());return route.abort()})
 await page.setContent('<!doctype html><html lang="zh-CN"><body style="margin:0"><main id="root"></main></body></html>')
 await page.evaluate(()=>{
  for(const property of ['localStorage','sessionStorage'])Object.defineProperty(window,property,{get(){throw Error('访客不能读取本人存储')}})
  for(const property of ['teloaApplication','teloaProWorkspace','__ModuleLoader__','dshDesktopBoot'])Object.defineProperty(window,property,{get(){throw Error('访客不能装配在线服务')}})
 })
 await page.addStyleTag({content:styles});await page.addScriptTag({content:script})
 const navigation=page.getByRole('navigation',{name:'主导航',exact:true})
 await navigation.waitFor()
 for(const label of ['工作台','需要你','对话','任务','项目','自动化','员工','业务','资料','能力中心'])assert.equal(await navigation.getByRole('button',{name:label,exact:true}).count(),1,label)
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'原草稿')
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).getAttribute('maxlength'),'4000')
 const longPrompt='长'.repeat(4000)
 await page.getByLabel('想完成什么工作？',{exact:true}).fill(longPrompt+'额外')
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),longPrompt)
 assert.equal(await page.evaluate(()=>(window as any).guestTest.prompt),longPrompt)
 await navigation.getByRole('button',{name:'项目',exact:true}).click()
 await navigation.getByRole('button',{name:'工作台',exact:true}).click()
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),longPrompt)
 await page.getByLabel('想完成什么工作？',{exact:true}).fill('整理这一周反馈')
 await navigation.getByRole('button',{name:'项目',exact:true}).click()
 await page.getByText('登录后查看你的项目和相关工作。',{exact:true}).waitFor()
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.calls),[])
 await navigation.getByRole('button',{name:'工作台',exact:true}).click()
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'整理这一周反馈')
 await page.getByRole('button',{name:'开始工作',exact:true}).click()
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.calls),['start'])
 await page.getByRole('button',{name:'登录',exact:true}).first().click()
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.calls),['start','account'])
 await page.evaluate(()=>(window as any).guestTest.handle.update({account:{displayName:'Max Luo'}}))
 assert.equal(await page.getByRole('button',{name:'登录',exact:true}).count(),0)
 assert.equal(await page.getByText('ML',{exact:true}).count(),2)
 const sidebar=page.getByRole('complementary',{name:'主导航',exact:true})
 assert.equal(await sidebar.getByText('Max Luo',{exact:true}).count(),0)
 assert.equal(await sidebar.getByRole('button',{name:'账号',exact:true}).textContent(),'ML')
 await page.getByRole('button',{name:'账号',exact:true}).first().click()
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.calls),['start','account','account'])
 await page.evaluate(()=>(window as any).guestTest.handle.update({prompt:'',account:{displayName:'max@example.test'}}))
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'')
 assert.equal(await page.getByText('max@example.test',{exact:true}).count(),0)
 assert.equal(await page.evaluate(()=>(window as any).guestTest.prompt),'整理这一周反馈','宿主更新草稿不回写为用户编辑')
 await page.evaluate(()=>(window as any).guestTest.handle.update({account:null}))
 await page.getByRole('button',{name:'切换深色主题',exact:true}).click()
 assert.equal(await page.locator('[data-guest-workbench]').getAttribute('data-theme'),'dark')
 await page.setViewportSize({width:390,height:844})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await page.evaluate(()=>(window as any).guestTest.handle.dispose())
 assert.equal(await page.locator('#root').textContent(),'')
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[])
})

test('宿主设置复用平台布局与主题，导航保留真实节点及草稿且不会触发宿主动作',async t=>{
 const temp=await mkdtemp(join(root,'.runtime-guest-settings-'))
 t.after(()=>rm(temp,{recursive:true,force:true}))
 await writeFile(join(temp,'entry.ts'),`import {mountGuestWorkbench} from ${JSON.stringify(entry)};
 const state=window.guestTest={calls:[],selected:[],prompt:'未发送的草稿',mount:mountGuestWorkbench};
 const account=document.createElement('section');account.hidden=true;account.innerHTML='<label>宿主输入<input value="保留的输入"></label><button type="button">宿主操作</button>';
 account.querySelector('button').onclick=()=>state.calls.push('host-action');
 const appearance=document.createElement('section');appearance.textContent='宿主外观内容';
 const original=document.getElementById('original');original.append(account,appearance);state.account=account;
 state.handle=mountGuestWorkbench(document.getElementById('root'),{product:'Pro',initialPrompt:state.prompt,onPromptChange:value=>{state.prompt=value},onStart:()=>state.calls.push('start'),onAccount:()=>state.calls.push('account'),settings:{entries:[{id:'account',label:'账号',content:account},{id:'appearance',label:'外观',content:appearance}],onSelect:id=>state.selected.push(id),onClose:async()=>{state.calls.push('close');throw Error('宿主关闭守卫拒绝')}}});`)
 const result=await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,lib:{entry:join(temp,'entry.ts'),name:'GuestSettingsTest',formats:['iife']}}})
 const bundle=Array.isArray(result)?result[0]:result
 assert.ok(bundle&&'output'in bundle)
 const script=bundle.output.find(item=>item.type==='chunk')!.code
 const styles=bundle.output.flatMap(item=>item.type==='asset'&&item.fileName.endsWith('.css')?[String(item.source)]:[]).join('\n')
 const browser=await loadPlaywright().chromium.launch(launchOptions());t.after(()=>browser.close())
 const page=await browser.newPage({viewport:{width:1400,height:900},colorScheme:'light'});t.after(()=>page.close())
 const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',(error:Error)=>errors.push(error.message))
 await page.route('**/*',(route:any)=>{requests.push(route.request().url());return route.abort()})
 await page.setContent('<!doctype html><html lang="zh-CN"><body style="margin:0"><div id="original" hidden></div><main id="root"></main></body></html>')
 await page.addStyleTag({content:styles});await page.addScriptTag({content:script})
 const navigation=page.getByRole('navigation',{name:'主导航',exact:true})
 await navigation.getByRole('button',{name:'项目',exact:true}).click()
 await page.evaluate(()=>{
  const state=(window as any).guestTest
  if(typeof state.handle.openSettings!=='function')throw Error('宿主设置导航接口尚未实现')
  state.handle.openSettings('account')
 })
 const settings=page.locator('[data-teloa-settings-layout]')
 await settings.waitFor()
 assert.equal(await page.evaluate(()=>document.querySelector('#settings-content section')===(window as any).guestTest.account),true)
 assert.equal(await page.getByLabel('宿主输入',{exact:true}).inputValue(),'保留的输入')
 assert.equal(await page.evaluate(()=>(window as any).guestTest.account.hidden),false)
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.calls),[])
 assert.equal(await settings.getByRole('navigation',{name:'设置',exact:true}).getByRole('button',{name:'账号',exact:true}).getAttribute('aria-current'),'page')
 assert.equal(await page.evaluate(()=>getComputedStyle((window as any).guestTest.account).color),'rgb(36, 39, 35)')
 assert.equal(await page.evaluate(()=>getComputedStyle((window as any).guestTest.account).getPropertyValue('--teloa-font-body').trim()),'14px')
 await page.getByLabel('宿主输入',{exact:true}).fill('宿主保留的新输入')
 await settings.getByRole('button',{name:'外观',exact:true}).click()
 assert.equal(await page.locator('#original section').first().evaluate((node:HTMLElement)=>node===(window as any).guestTest.account),true)
 assert.equal(await page.evaluate(()=>(window as any).guestTest.account.hidden),true)
 await page.evaluate(()=>(window as any).guestTest.handle.openSettings('account'))
 assert.equal(await page.getByLabel('宿主输入',{exact:true}).inputValue(),'宿主保留的新输入')
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.selected),['account','appearance','account'])
 assert.equal(await page.evaluate(()=>{try{(window as any).guestTest.handle.openSettings('missing');return false}catch{return true}}),true)
 assert.equal(await page.getByLabel('宿主输入',{exact:true}).inputValue(),'宿主保留的新输入')
 await page.getByRole('button',{name:'切换深色主题',exact:true}).click()
 assert.equal(await page.evaluate(()=>getComputedStyle((window as any).guestTest.account).color),'rgb(233, 236, 228)')
 await page.getByRole('button',{name:'宿主操作',exact:true}).click()
 await page.setViewportSize({width:390,height:844})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await page.setViewportSize({width:1400,height:900})
 await page.evaluate(()=>(window as any).guestTest.handle.closeSettings())
 assert.equal(await settings.count(),0)
 await page.getByText('登录后查看你的项目和相关工作。',{exact:true}).waitFor()
 assert.equal(await page.evaluate(()=>document.querySelector('#original section')===(window as any).guestTest.account),true)
 await navigation.getByRole('button',{name:'工作台',exact:true}).click()
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'未发送的草稿')
 await page.evaluate(()=>(window as any).guestTest.handle.openSettings('appearance'))
 await page.getByRole('button',{name:'关闭设置',exact:true}).click()
 await page.getByText('暂时无法继续，请重试。',{exact:true}).waitFor()
 assert.equal(await settings.count(),1,'关闭守卫拒绝不能提前切走')
 await page.locator('#settings-entry-appearance').focus()
 await page.keyboard.press('Escape')
 await page.waitForFunction(()=>(window as any).guestTest.calls.filter((value:string)=>value==='close').length===2)
 assert.equal(await settings.count(),1,'Escape 同样只请求宿主关闭')
 await page.evaluate(()=>(window as any).guestTest.handle.closeSettings())
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'未发送的草稿')
 assert.deepEqual(await page.evaluate(()=>(window as any).guestTest.calls),['host-action','close','close'])
 assert.equal(await page.evaluate(()=>{
  const state=(window as any).guestTest,target=document.createElement('div'),content=document.createElement('section')
  try{state.mount(target,{product:'Free',onPromptChange:()=>{},onStart:()=>{},onAccount:()=>{},settings:{entries:[{id:'same',label:'一',content},{id:'same',label:'二',content:document.createElement('section')}],onClose:()=>{}}});return false}catch{return true}
 }),true)
 await page.evaluate(()=>(window as any).guestTest.handle.dispose())
 assert.equal(await page.locator('#root').textContent(),'')
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[])
})

test('设置左导航等宿主确认关闭，拒绝或未确认时保留设置且不重复请求，确认后保留草稿',async t=>{
 const temp=await mkdtemp(join(root,'.runtime-guest-settings-navigation-'))
 t.after(()=>rm(temp,{recursive:true,force:true}))
 await writeFile(join(temp,'entry.ts'),`import {mountGuestWorkbench} from ${JSON.stringify(entry)};
 const state=window.guestTest={closeCalls:0,mode:'reject'};
 const content=document.createElement('section');content.textContent='宿主设置内容';
 state.handle=mountGuestWorkbench(document.getElementById('root'),{product:'Pro',initialPrompt:'不能丢失的草稿',onPromptChange:()=>{},onStart:()=>{},onAccount:()=>{},settings:{entries:[{id:'account',label:'用户中心',content}],onClose:()=>{state.closeCalls++;if(state.mode==='reject')throw Error('尚不能关闭');return new Promise(resolve=>state.resolveClose=resolve)}}});`)
 const result=await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,lib:{entry:join(temp,'entry.ts'),name:'GuestSettingsNavigationTest',formats:['iife']}}})
 const bundle=Array.isArray(result)?result[0]:result
 assert.ok(bundle&&'output'in bundle)
 const script=bundle.output.find(item=>item.type==='chunk')!.code
 const styles=bundle.output.flatMap(item=>item.type==='asset'&&item.fileName.endsWith('.css')?[String(item.source)]:[]).join('\n')
 const browser=await loadPlaywright().chromium.launch(launchOptions());t.after(()=>browser.close())
 const page=await browser.newPage({viewport:{width:1400,height:900}});t.after(()=>page.close())
 const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',(error:Error)=>errors.push(error.message))
 await page.route('**/*',(route:any)=>{requests.push(route.request().url());return route.abort()})
 await page.setContent('<!doctype html><html lang="zh-CN"><body style="margin:0"><main id="root"></main></body></html>')
 await page.addStyleTag({content:styles});await page.addScriptTag({content:script})
 const settings=page.locator('[data-teloa-settings-layout]'),navigation=page.getByRole('navigation',{name:'主导航',exact:true})
 await page.evaluate(()=>(window as any).guestTest.handle.openSettings('account'))
 await page.getByRole('button',{name:'新建',exact:true}).click()
 assert.equal(await settings.count(),1,'新建不能绕过宿主关闭守卫')
 await page.getByText('暂时无法继续，请重试。',{exact:true}).waitFor()
 assert.equal(await page.evaluate(()=>(window as any).guestTest.closeCalls),1)
 await navigation.getByRole('button',{name:'项目',exact:true}).click()
 await page.waitForFunction(()=>(window as any).guestTest.closeCalls===2)
 assert.equal(await settings.count(),1,'其他左导航同样不能绕过守卫')
 await page.getByRole('button',{name:'关闭设置',exact:true}).waitFor({state:'visible'})
 await page.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('[data-teloa-settings-layout] header button')?.disabled)
 await page.evaluate(()=>(window as any).guestTest.mode='hold')
 await navigation.getByRole('button',{name:'项目',exact:true}).click()
 await page.waitForFunction(()=>(window as any).guestTest.closeCalls===3)
 await navigation.getByRole('button',{name:'任务',exact:true}).click()
 await page.getByRole('button',{name:'新建',exact:true}).click()
 assert.equal(await settings.count(),1)
 assert.equal(await page.evaluate(()=>(window as any).guestTest.closeCalls),3,'关闭等待中不能重复请求或覆盖目的页')
 await page.evaluate(()=>(window as any).guestTest.resolveClose())
 await page.evaluate(()=>Promise.resolve())
 await navigation.getByRole('button',{name:'任务',exact:true}).click()
 assert.equal(await settings.count(),1,'回调返回不等于宿主已确认关闭')
 assert.equal(await page.evaluate(()=>(window as any).guestTest.closeCalls),3)
 await page.evaluate(()=>(window as any).guestTest.handle.closeSettings())
 assert.equal(await settings.count(),0)
 await page.getByText('登录后查看你的项目和相关工作。',{exact:true}).waitFor()
 await navigation.getByRole('button',{name:'工作台',exact:true}).click()
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'不能丢失的草稿')
 await page.evaluate(()=>(window as any).guestTest.handle.openSettings('account'))
 await page.getByRole('button',{name:'新建',exact:true}).click()
 await page.waitForFunction(()=>(window as any).guestTest.closeCalls===4)
 await page.evaluate(()=>{const state=(window as any).guestTest;state.handle.closeSettings();state.resolveClose()})
 assert.equal(await page.getByLabel('想完成什么工作？',{exact:true}).inputValue(),'不能丢失的草稿')
 await page.evaluate(()=>(window as any).guestTest.handle.dispose())
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[])
})
