import test from 'node:test'
import assert from 'node:assert/strict'
import {createIndustryTaskApi} from '../src/client/industry-task-api.ts'

const request={requestId:'11111111-1111-4111-8111-111111111111',loadId:'22222222-2222-4222-8222-222222222222',itemInstanceId:'33333333-3333-4333-8333-333333333333',goal:'完成本次研究',inputs:['东南亚市场'],assignee:{roleId:'44444444-4444-4444-8444-444444444444',expectedVersion:3}}
const task={id:'55555555-5555-4555-8555-555555555555',ownerId:'owner',version:1,state:'ready' as const,createdAt:'2026-09-12T00:00:00.000Z',updatedAt:'2026-09-12T00:00:00.000Z',title:'行业研究',goal:request.goal,scope:'space-66666666-6666-4666-8666-666666666666',groupId:null,skills:[],assigneeRoleId:request.assignee.roleId,assigneeRoleVersion:request.assignee.expectedVersion}
const source={taskId:task.id,ownerId:task.ownerId,loadId:request.loadId,itemInstanceId:request.itemInstanceId,itemLocalId:'research-work',contentId:'77777777-7777-4777-8777-777777777777',contentHash:'a'.repeat(64),templateId:'research',templateVersion:'1.0.0',fileHash:'b'.repeat(64),title:task.title,method:'先核对来源，再形成结论。',requirements:['研究范围'],inputs:request.inputs,output:'研究报告',skills:[{id:'research-skill',title:'研究方法',version:'1.0.0'}],scope:task.scope,createdAssignee:{roleId:request.assignee.roleId,roleVersion:3},createdAt:task.createdAt}
const preview=((({taskId,ownerId,inputs,createdAssignee,createdAt,...value})=>value)(source))
test('回包丢失保留完整请求并以相同参数恢复',async()=>{let raw:string|null=null,calls:unknown[]=[];const api=createIndustryTaskApi(async(method,payload)=>{calls.push([method,payload]);if(calls.length===1)throw Error('断线');return {task,source}},{read:()=>raw,write:value=>{raw=value},clear:()=>{raw=null}});await assert.rejects(api.create(request),/断线/);assert.deepEqual(api.pending(),request);assert.deepEqual(await api.recover(),{task,source});assert.equal(raw,null);assert.deepEqual(calls,[['industry-tasks/create',request],['industry-tasks/create',request]])})
test('严格解析固定来源并允许普通任务来源为空',async()=>{const api=createIndustryTaskApi(async method=>method==='industry-tasks/source'?source:{task,source});assert.deepEqual(await api.source(task.id),source);assert.equal(await createIndustryTaskApi(async()=>null).source(task.id),null);for(const value of [{...source,inputs:[]},{...source,scope:''},{...source,scope:'x'.repeat(81)},{...source,createdAssignee:{...source.createdAssignee!,roleVersion:0}},{...source,skills:[{...source.skills[0],extra:true}]},{...source,extra:true}])await assert.rejects(createIndustryTaskApi(async()=>value).source(task.id),/格式/)})
test('创建响应必须对应请求、任务和来源身份，坏响应保留journal',async()=>{let raw:string|null=null;const api=createIndustryTaskApi(async()=>({task,source:{...source,itemInstanceId:'88888888-8888-4888-8888-888888888888'}}),{read:()=>raw,write:value=>{raw=value},clear:()=>{raw=null}});await assert.rejects(api.create(request),/一致|格式/);assert.deepEqual(api.pending(),request);assert.ok(raw)})
test('创建严格拒绝损坏的真实任务字段',async()=>{await assert.rejects(createIndustryTaskApi(async()=>({task:{...task,ownerId:''},source})).create(request),/格式/)})
test('未分配任务合法且来源明确记录未分配',async()=>{const {assignee:_assignee,...input}=request,unassignedTask={...task,assigneeRoleId:null,assigneeRoleVersion:null},unassignedSource={...source,createdAssignee:null};assert.deepEqual(await createIndustryTaskApi(async()=>({task:unassignedTask,source:unassignedSource})).create(input),{task:unassignedTask,source:unassignedSource})})
test('preview读取服务端固定模板并核对load和item身份',async()=>{const calls:unknown[]=[];const api=createIndustryTaskApi(async(method,payload)=>{calls.push([method,payload]);return preview});assert.deepEqual(await api.preview(request.loadId,request.itemInstanceId),preview);assert.deepEqual(calls,[['industry-tasks/preview',{loadId:request.loadId,itemInstanceId:request.itemInstanceId}]]);await assert.rejects(createIndustryTaskApi(async()=>({...preview,loadId:'88888888-8888-4888-8888-888888888888'})).preview(request.loadId,request.itemInstanceId),/一致/)})

test('明确未提交拒绝释放请求，未知失败与冲突继续保留',async()=>{for(const code of ['teloa/invalid-input','teloa/forbidden','teloa/version-conflict','teloa/source-unavailable']){let raw:string|null=null;const api=createIndustryTaskApi(async()=>{throw Object.assign(Error(code),{rejected:true,code})},{read:()=>raw,write:value=>{raw=value},clear:()=>{raw=null}});await assert.rejects(api.create(request));assert.equal(api.pending(),undefined);assert.equal(raw,null)}for(const code of ['teloa/conflict','teloa/storage-unavailable']){const api=createIndustryTaskApi(async()=>{throw Object.assign(Error(code),{rejected:true,code})});await assert.rejects(api.create(request));assert.deepEqual(api.pending(),request)}})
test('幂等恢复允许返回创建后已合法编辑目标的当前任务',async()=>{const edited={...task,version:2,goal:'后来调整的目标',updatedAt:'2026-09-12T00:01:00.000Z'};assert.equal((await createIndustryTaskApi(async()=>({task:edited,source})).create(request)).task.goal,edited.goal)})
