import test from 'node:test'
import assert from 'node:assert/strict'
import {createIndustryKnowledgeApi} from '../src/client/industry-knowledge-api.ts'
import {industryKnowledgeAction,mergeIndustryKnowledgeInstances} from '../src/client/industry-knowledge-state.ts'

const request={requestId:'11111111-1111-4111-8111-111111111111',loadId:'22222222-2222-4222-8222-222222222222',itemInstanceId:'33333333-3333-4333-8333-333333333333'}
const resource={id:'44444444-4444-4444-8444-444444444444',ownerId:'owner',title:'行业手册',sourceId:`industry_${request.loadId}_${request.itemInstanceId}`,sourceVersion:'a'.repeat(64),scopeIds:['space-55555555-5555-4555-8555-555555555555'],version:2,status:'active' as const,createdAt:'2026-09-12T00:00:00.000Z',updatedAt:'2026-09-12T00:01:00.000Z'}
const active={id:'66666666-6666-4666-8666-666666666666',ownerId:'owner',loadId:request.loadId,itemInstanceId:request.itemInstanceId,itemLocalId:'knowledge-guide',title:'行业手册',scope:resource.scopeIds[0]!,sourceId:resource.sourceId,sourceVersion:resource.sourceVersion,revision:3,state:'active' as const,resource,failure:null,createdAt:'2026-09-12T00:00:00.000Z',updatedAt:'2026-09-12T00:01:00.000Z'}

test('实例化失败保留原请求并以完全相同参数恢复',async()=>{let raw:string|null=null;const calls:unknown[]=[];const journal={read:()=>raw,write:(value:string)=>{raw=value},clear:()=>{raw=null}};const api=createIndustryKnowledgeApi(async(method,payload)=>{calls.push([method,payload]);if(calls.length===1)throw Error('连接断开');return active},journal);await assert.rejects(api.instantiate(request),/连接断开/);assert.deepEqual(api.pending(),request);assert.deepEqual(await api.recover(),active);assert.deepEqual(calls,[['industry-knowledge/instantiate',request],['industry-knowledge/instantiate',request]]);assert.equal(raw,null)})

test('非法宿主响应和未证明无写入的拒绝都保留待恢复请求',async()=>{let raw:string|null=null;const journal={read:()=>raw,write:(value:string)=>{raw=value},clear:()=>{raw=null}};let api=createIndustryKnowledgeApi(async()=>({...active,extra:true}),journal);await assert.rejects(api.instantiate(request),/格式/);assert.ok(api.pending());api=createIndustryKnowledgeApi(async()=>{throw Object.assign(Error('禁止'),{rejected:true,code:'teloa/forbidden'})},journal);await assert.rejects(api.recover(),/禁止/);assert.deepEqual(api.pending(),request)})

test('pending和failed回包保留原请求继续核对',async()=>{for(const result of [{...active,state:'pending' as const,resource:null},{...active,state:'failed' as const,resource:null,failure:{code:'teloa/source-unavailable',message:'来源暂不可用'}}]){let raw:string|null=null;const api=createIndustryKnowledgeApi(async()=>result,{read:()=>raw,write:value=>{raw=value},clear:()=>{raw=null}});assert.deepEqual(await api.instantiate(request),result);assert.deepEqual(api.pending(),request);assert.ok(raw)}})

test('严格校验实例、单空间资料和状态组合',async()=>{const bad=[{...active,revision:0},{...active,scope:'x'.repeat(81),resource:{...resource,scopeIds:['x'.repeat(81)]}},{...active,scope:'  ',resource:{...resource,scopeIds:['  ']}},{...active,resource:{...resource,scopeIds:['general']}},{...active,state:'withdrawn',resource},{...active,state:'pending',resource},{...active,state:'failed',resource:null,failure:null},{...active,resource:{...resource,extra:true}}];for(const value of bad)await assert.rejects(createIndustryKnowledgeApi(async()=>value).get(active.id),/格式/);assert.deepEqual(await createIndustryKnowledgeApi(async()=>active).get(active.id),active)})

test('目录拒绝重复映射和跨记录不一致',async()=>{await assert.rejects(createIndustryKnowledgeApi(async()=>({items:[active,active]})).list(),/重复/);await assert.rejects(createIndustryKnowledgeApi(async()=>({items:[{...active,itemInstanceId:'77777777-7777-4777-8777-777777777777'}],extra:true})).list(),/目录格式/)})

test('合并按实例revision并按资源version阻止撤回回退',()=>{const withdrawn={...active,revision:4,state:'withdrawn' as const,resource:{...resource,version:4,status:'withdrawn' as const}};assert.deepEqual(mergeIndustryKnowledgeInstances([withdrawn],[active]),[withdrawn]);const staleActive={...active,revision:4,resource:{...resource,version:3}};assert.deepEqual(mergeIndustryKnowledgeInstances([withdrawn],[staleActive]),[withdrawn]);const pending={...active,revision:5,state:'pending' as const,resource:null};assert.deepEqual(mergeIndustryKnowledgeInstances([withdrawn],[pending]),[{...withdrawn,revision:5,updatedAt:pending.updatedAt}]);const newerResource={...withdrawn,revision:2,resource:{...withdrawn.resource!,version:6}};assert.deepEqual(mergeIndustryKnowledgeInstances([active],[newerResource]),[{...active,state:'withdrawn',resource:newerResource.resource}]);assert.deepEqual(mergeIndustryKnowledgeInstances([pending],[active]),[{...pending,state:'active',resource:active.resource,failure:null}])})

test('服务端目录恢复的未完成实例可用新请求继续核对，终态不再创建',()=>{assert.equal(industryKnowledgeAction(undefined,undefined),'create');assert.equal(industryKnowledgeAction({...active,state:'pending',resource:null},undefined),'continue');assert.equal(industryKnowledgeAction({...active,state:'failed',resource:null,failure:{code:'teloa/source-unavailable',message:'稍后重试'}},undefined),'continue');assert.equal(industryKnowledgeAction(active,undefined),'none');assert.equal(industryKnowledgeAction(undefined,request),'recover')})
