import test from 'node:test';import assert from 'node:assert/strict';import {createIndustryPlanApi} from '../src/client/industry-plan-api.ts';import type {SavedPlan} from '../src/client/plan-api.ts'
const t={kind:'schedule' as const,cadence:'daily' as const,weekday:1,time:'09:00',timezone:'Asia/Singapore' as const},q={requestId:'11111111-1111-4111-8111-111111111111',loadId:'22222222-2222-4222-8222-222222222222',itemInstanceId:'33333333-3333-4333-8333-333333333333',goal:'目标',delivery:'交付',notificationPolicy:'attention' as const,trigger:t,roleId:'44444444-4444-4444-8444-444444444444',expectedRoleVersion:2},w={loadId:q.loadId,itemInstanceId:'55555555-5555-4555-8555-555555555555',itemLocalId:'work',contentId:'66666666-6666-4666-8666-666666666666',contentHash:'a'.repeat(64),templateId:'work',templateVersion:'1.0.0',fileHash:'b'.repeat(64),title:'工作',method:'方法',requirements:['资料'],output:'交付',skills:[],scope:'space-77777777-7777-4777-8777-777777777777'},p={loadId:q.loadId,itemInstanceId:q.itemInstanceId,itemLocalId:'plan',contentId:w.contentId,contentHash:w.contentHash,planVersion:'1.0.0',planFileHash:'c'.repeat(64),title:'计划',work:w,dataScope:'范围',trigger:t,scope:w.scope},src={...p,planId:'88888888-8888-4888-8888-888888888888',ownerId:'owner',requestId:q.requestId,goal:q.goal,delivery:q.delivery,notificationPolicy:q.notificationPolicy,createdRole:{roleId:q.roleId,roleVersion:2},selectedTrigger:t,createdAt:'2026-09-12T00:00:00.000Z'},plan={id:src.planId,ownerId:'owner',state:'active',notificationPolicy:q.notificationPolicy} as unknown as SavedPlan,read=()=>plan
test('未知创建结果保留含通知策略的完整请求并恢复当前状态计划',async()=>{let raw:string|null=null,n=0;const api=createIndustryPlanApi(async()=>{if(!n++)throw Error('断线');return {plan,source:src}},{read:()=>raw,write:x=>raw=x,clear:()=>raw=null},read);await assert.rejects(api.create(q),/断线/);assert.deepEqual(api.pending(),q);await assert.rejects(api.create({...q,notificationPolicy:'silent'}),/先核对/);assert.equal((await api.recover()).plan.state,'active');assert.equal(raw,null)})
test('四种通知策略逐项透传并核对计划与来源回执',async()=>{for(const notificationPolicy of ['always','attention','failure','silent'] as const){let sent:unknown;const request={...q,requestId:crypto.randomUUID(),notificationPolicy},source={...src,requestId:'',notificationPolicy},saved={...plan,notificationPolicy};source.requestId=request.requestId;const api=createIndustryPlanApi(async(_method,payload)=>{sent=payload;return {plan:saved,source:{...source,planId:saved.id}}},undefined,()=>saved as SavedPlan);const result=await api.create(request);assert.equal((sent as typeof request).notificationPolicy,notificationPolicy);assert.equal(result.source.notificationPolicy,notificationPolicy)}})
test('创建必须显式提交合法通知策略且回执不能串策略',async()=>{let calls=0;const api=createIndustryPlanApi(async()=>{calls++;return {plan,source:src}},undefined,read),{notificationPolicy:_,...missing}=q;await assert.rejects(api.create(missing as typeof q),/格式/);await assert.rejects(api.create({...q,notificationPolicy:'unexpected' as 'attention'}),/格式/);assert.equal(calls,0);const wrong=createIndustryPlanApi(async()=>({plan:{...plan,notificationPolicy:'silent'},source:src}),undefined,()=>({...plan,notificationPolicy:'silent'} as SavedPlan));await assert.rejects(wrong.create(q),/不一致/)})
test('旧行业计划来源缺少通知策略时仍可读取和列出',async()=>{const {notificationPolicy:_,...legacy}=src,api=createIndustryPlanApi(async(method)=>method==='industry-plans/source'?legacy:{items:[legacy]},undefined,read),source=await api.source(src.planId),items=await api.list(q.loadId);assert.equal(Object.hasOwn(source!,'notificationPolicy'),false);assert.equal(Object.hasOwn(items[0]!,'notificationPolicy'),false)})
test('预览严格核父子来源，目录拒重复和错load',async()=>{assert.deepEqual(await createIndustryPlanApi(async()=>p,undefined,read).preview(q.loadId,q.itemInstanceId),p);for(const bad of [{...p,work:{...w,scope:'space-99999999-9999-4999-8999-999999999999'}},{...p,work:{...w,skills:[{id:'x',title:'x',version:'bad'}]}}])await assert.rejects(createIndustryPlanApi(async()=>bad,undefined,read).preview(q.loadId,q.itemInstanceId));await assert.rejects(createIndustryPlanApi(async()=>({items:[src,src]}),undefined,read).list())})
test('明确未提交拒绝释放，存储错误与并发核对保留',async()=>{const clear=createIndustryPlanApi(async()=>{throw Object.assign(Error(),{rejected:true,code:'teloa/version-conflict'})},undefined,read);await assert.rejects(clear.create(q));assert.equal(clear.pending(),undefined);let release!:()=>void;const wait=new Promise<void>(r=>release=r),keep=createIndustryPlanApi(async()=>{await wait;throw Error('断线')},undefined,read),first=keep.create(q);await assert.rejects(keep.recover(),/正在核对/);release();await assert.rejects(first);assert.deepEqual(keep.pending(),q)})

test('本地journal写入失败释放busy并保留原请求供恢复',async()=>{let writes=0;const api=createIndustryPlanApi(async()=>({plan,source:src}),{read:()=>null,write:()=>{if(!writes++)throw Error('本地写入失败')},clear:()=>{}},read);await assert.rejects(api.create(q),/本地写入失败/);assert.deepEqual(api.pending(),q);assert.equal((await api.recover()).plan.id,plan.id)})
