import assert from 'node:assert/strict'
import test from 'node:test'
import {writeFile,mkdir} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {build} from 'vite'
// @ts-expect-error 既有无头浏览器加载器。
import {loadPlaywright,launchOptions} from './fixtures/load-playwright.mjs'

test('新版资料库桌面：访问视图、搜索、收藏、阅读、文件夹和任务准备',async t=>{
 const result=await build({configFile:false,plugins:[{name:'forbid-host-crypto',enforce:'pre',resolveId(id){if(id==='node:crypto')return '\0forbid-host-crypto'},load(id){if(id==='\0forbid-host-crypto')return "function blocked(){throw Error('本浏览器验收不允许执行宿主摘要算法')} export {blocked as createHash,blocked as createPublicKey,blocked as verify}"}}],root:fileURLToPath(new URL('../../../../',import.meta.url)),logLevel:'error',define:{'process.env.NODE_ENV':'"development"'},build:{write:false,minify:false,lib:{entry:fileURLToPath(new URL('./fixtures/library.tsx',import.meta.url)),name:'CapabilityCenterTest',formats:['iife']}}})
 const bundle=Array.isArray(result)?result[0]:result
 assert.ok(bundle&&'output'in bundle)
 const script=bundle.output.find(item=>item.type==='chunk')!.code
 const style=bundle.output.filter(item=>item.type==='asset'&&item.fileName.endsWith('.css')).map(item=>String((item as any).source)).join('\n')
 const html='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>资料库开发预览</title><style>body{margin:0}*{box-sizing:border-box}'+style+'</style><body><div id="root"></div><script>'+script.replace(/<\/script/gi,'<\\/script')+'</script></body></html>'
 const previewDir=process.env.TELOA_LIBRARY_PREVIEW_DIR
 if(previewDir){await mkdir(previewDir,{recursive:true});await writeFile(previewDir+'/资料库开发预览.html',html)}
 const browser=await loadPlaywright().chromium.launch(launchOptions());t.after(()=>browser.close())
 const page=await browser.newPage({viewport:{width:1440,height:1050}})
 page.setDefaultTimeout(7000)
 const errors:string[]=[];page.on('pageerror',(error:Error)=>{errors.push(error.message);console.error(error.stack)})
 const requests:string[]=[];await page.route('**/*',(route:any)=>{if(route.request().url()==='http://127.0.0.1:3199/library-test')return route.fulfill({contentType:'text/html',body:html});requests.push(route.request().url());return route.abort()})
 await page.goto('http://127.0.0.1:3199/library-test')
 const mine=page.getByRole('button',{name:'全部资料',exact:true})
 await mine.waitFor().catch(async (error:unknown)=>{console.error((await page.locator('body').innerText()).slice(0,3000));throw error})
 const directory=page.locator('[data-teloa-pane=directory]')
 const content=page.locator('main[data-teloa-pane=detail]')
 assert.equal(await directory.getByRole('button',{name:'最近访问',exact:true}).count(),0,'左侧只展示空间目录')
 assert.equal(await content.getByRole('button',{name:'最近访问',exact:true}).getAttribute('aria-current'),'page','首次进入显示最近访问')
 assert.equal(await page.getByRole('table').count(),0,'默认选中和加载不产生访问记录')
 if(previewDir)await page.screenshot({path:previewDir+'/资料库-最近访问-开发.png'})
 await content.getByRole('button',{name:'查看全部资料',exact:true}).click()
 assert.equal(await page.getByRole('table').count(),1)
 if(previewDir)await page.screenshot({path:previewDir+'/资料库-列表-开发.png'})
 await page.getByRole('button',{name:'产品定位',exact:true}).last().click()
 if(previewDir)await page.screenshot({path:previewDir+'/资料库-阅读-开发.png'})
 await page.getByRole('button',{name:'用于任务',exact:true}).click()
 assert.deepEqual(await page.evaluate(()=>(window as any).__libraryCalls),['use:11111111-1111-4111-8111-111111111111'])
 await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.getByRole('button',{name:'返回列表',exact:true}).click()
 await page.locator('summary').filter({hasText:'产品资料'}).click()
 assert.equal(await page.getByRole('row').count(),3)
 await page.getByRole('button',{name:'产品定位',exact:true}).last().click()
 await page.getByRole('button',{name:'返回列表',exact:true}).click()
 assert.equal(await page.getByRole('row').count(),3,'返回仍展示原文件夹两份资料')
 await page.getByRole('button',{name:'产品定位',exact:true}).last().click()
 await page.getByRole('tab',{name:'编辑',exact:true}).click()
 await page.locator('textarea').fill('# 未保存修改')
 await page.getByRole('navigation',{name:'知识路径',exact:true}).getByRole('button',{name:'产品资料',exact:true}).click()
 await page.getByText('资料有未保存的修改。离开会丢弃这些修改。',{exact:true}).waitFor()
 await page.getByRole('button',{name:'继续编辑',exact:true}).click()
 assert.equal(await page.locator('textarea').inputValue(),'# 未保存修改')
 assert.equal(await page.getByRole('button',{name:'用于任务',exact:true}).isDisabled(),true)
 await page.getByRole('button',{name:'返回列表',exact:true}).click()
 await page.getByRole('button',{name:'放弃修改并离开',exact:true}).click()
 await page.getByRole('button',{name:'收藏 产品定位',exact:true}).click()
 await page.getByRole('button',{name:'我的收藏',exact:true}).click()
 assert.equal(await page.getByRole('row').count(),2)
 await page.getByRole('button',{name:'重载验收组件',exact:true}).click()
 await page.getByRole('table').waitFor()
 assert.equal(await page.getByRole('row').count(),2,'重新挂载后收藏仍按本人空间恢复')
 assert.equal(await page.getByRole('button',{name:'我的收藏',exact:true}).getAttribute('aria-current'),'page')
 await page.getByRole('button',{name:'最近访问',exact:true}).click()
 assert.equal(await page.getByRole('row').count(),2)
 await page.getByRole('button',{name:'本地文件',exact:true}).first().click()
 assert.equal(await page.getByRole('row').count(),2)
 await page.getByRole('button',{name:'发布检查.md',exact:true}).last().click()
 await page.getByText('核对产物与版本。',{exact:true}).waitFor()
 await page.getByRole('button',{name:'返回列表',exact:true}).click()
 const search=page.getByRole('searchbox',{name:'搜索资料名称或所在位置',exact:true})
 await search.fill('没有这个资料')
 await page.getByText('没有找到匹配的资料',{exact:true}).waitFor()
 await page.getByRole('button',{name:'清空搜索',exact:true}).click()
 await page.getByRole('button',{name:'新建文件夹',exact:true}).click()
 await page.getByPlaceholder('文件夹名称', {exact:true}).fill('交付资料')
 await page.getByRole('button',{name:'新建文件夹',exact:true}).last().click()
 await page.getByText('交付资料',{exact:true}).waitFor()
 await page.getByRole('button',{name:'切换主题',exact:true}).click()
 if(previewDir)await page.screenshot({path:previewDir+'/资料库-深色-开发.png'})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false)
 await page.setViewportSize({width:1100,height:900})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false)
 await page.getByRole('button',{name:'全部资料',exact:true}).click()
 await page.getByRole('button',{name:'产品定位',exact:true}).last().click()
 await page.getByRole('tab',{name:'编辑',exact:true}).click()
 await page.locator('textarea').fill('# 等待保存的版本')
 await page.evaluate(()=>(window as any).__libraryPauseSave())
 await page.getByRole('button',{name:'保存新版本',exact:true}).click()
 await page.getByRole('button',{name:'返回列表',exact:true}).click()
 await page.getByRole('button',{name:'放弃修改并离开',exact:true}).click()
 await page.getByRole('button',{name:'发布检查.md',exact:true}).last().click()
 await page.evaluate(()=>(window as any).__libraryReleaseSave())
 await page.waitForTimeout(100)
 await page.getByText('核对产物与版本。',{exact:true}).waitFor()
 assert.equal(await page.getByRole('heading',{name:'产品定位',exact:true}).count(),0,'旧正文保存晚到不会重新打开资料')
 await page.getByRole('button',{name:'返回列表',exact:true}).click()
 await page.getByRole('button',{name:'产品定位',exact:true}).last().click()
 await page.evaluate(()=>(window as any).__libraryPauseWithdraw())
 await page.getByLabel('更多知识操作',{exact:true}).click()
 await page.getByRole('button',{name:'撤回当前引用',exact:true}).click()
 await page.getByRole('button',{name:'切换验收身份',exact:true}).click()
 await page.getByText('还没有访问记录',{exact:true}).waitFor()
 await page.evaluate(()=>(window as any).__libraryReleaseWithdraw())
 await page.waitForTimeout(100)
 await page.getByRole('button',{name:'我的收藏',exact:true}).click()
 assert.equal(await page.getByText('产品定位',{exact:true}).count(),0)
 assert.equal(await page.getByRole('row').count(),0)
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[])
})
