import {isSkillName} from '@deepseek-ai/dsh-skill'
import {WorkError,isRecord,taskInput} from '@teloa/contract'
import type {SkillInstallationService} from '@teloa/backend'
export const skillInstallationEndpoints=['skill-installations/preview','skill-installations/install','skill-installations/get','skill-installations/list','skill-installations/observe'] as const
type Ports=Pick<SkillInstallationService,'preview'|'install'|'get'|'list'>
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v),hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const invalid=()=>new WorkError('teloa/invalid-input','技能安装请求格式不正确。'),bad=()=>new WorkError('teloa/invalid-host-response','技能安装服务返回了不一致的记录。')
function source(v:unknown){const row=taskInput(v,['kind','contentId','loadId','itemInstanceId']);if(row.kind==='atomic'){taskInput(row,['kind','contentId']);if(!uuid(row.contentId))throw invalid();return {kind:'atomic' as const,contentId:row.contentId.toLowerCase()}}taskInput(row,['kind','loadId','itemInstanceId']);if(row.kind!=='industry'||!uuid(row.loadId)||!uuid(row.itemInstanceId))throw invalid();return {kind:'industry' as const,loadId:row.loadId.toLowerCase(),itemInstanceId:row.itemInstanceId.toLowerCase()}}
const exact=(v:unknown,keys:readonly string[])=>{if(!isRecord(v)||Object.keys(v).length!==keys.length||Object.keys(v).some(k=>!keys.includes(k)))throw bad();return v}
function trust(v:unknown){const r=exact(v,['publisher','repository','license','signature','compatibility','plugins','externalCapabilities','permissions','review']);if(typeof r.publisher!=='string'||!r.publisher||!isRecord(r.license)||!isRecord(r.signature)||!['verified','unverified','invalid'].includes(String(r.signature.status))||!isRecord(r.compatibility)||!Array.isArray(r.plugins)||!Array.isArray(r.externalCapabilities)||!Array.isArray(r.permissions)||!isRecord(r.review))throw bad();return r}
const stable=(v:unknown)=>typeof v==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9-]{0,119}$/.test(v),semver=(v:unknown)=>typeof v==='string'&&v.length<=80&&/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(v)
function identity(v:unknown){if(!isRecord(v))throw bad();const common=['kind','contentId','contentHash','resourceId','resourceVersion'],industry=['loadId','itemInstanceId'];const r=exact(v,v.kind==='atomic'?common:v.kind==='industry-local'?[...common,...industry]:v.kind==='industry-public'?[...common,...industry,'sourceContentId','sourceContentHash','sourceResourceId','sourceResourceVersion']:[]);if(!uuid(r.contentId)||!hash(r.contentHash)||!stable(r.resourceId)||!semver(r.resourceVersion))throw bad();if(r.kind!=='atomic'&&(!uuid(r.loadId)||!uuid(r.itemInstanceId)))throw bad();if(r.kind==='industry-public'&&(!uuid(r.sourceContentId)||!hash(r.sourceContentHash)||!stable(r.sourceResourceId)||!semver(r.sourceResourceVersion)))throw bad();return r}
function canonical(v:unknown){const r=identity(v);return JSON.stringify(r.kind==='industry-public'?['atomic',r.sourceContentId,r.sourceContentHash,r.sourceResourceId,r.sourceResourceVersion]:[r.kind==='atomic'?'atomic':'industry-local',r.contentId,r.contentHash,r.resourceId,r.resourceVersion])}
function native(v:unknown){const r=exact(v,['name','description','modelInvocable','userInvocable','bodyHash']);if(typeof r.name!=='string'||!isSkillName(r.name)||typeof r.description!=='string'||!r.description||r.description.length>2*1024*1024||typeof r.modelInvocable!=='boolean'||typeof r.userInvocable!=='boolean'||!hash(r.bodyHash))throw bad();return r}
function timestamp(v:unknown){try{if(typeof v!=='string'||new Date(v).toISOString()!==v)throw bad()}catch{throw bad()}}
function record(v:unknown,owner:string){if(!isRecord(v))throw bad();const hasTrust=Object.hasOwn(v,'trust')||Object.hasOwn(v,'trustHash'),r=exact(v,hasTrust?['id','ownerId','source','bundleHash','native','trust','trustHash','state','version','createdAt','updatedAt']:['id','ownerId','source','bundleHash','native','state','version','createdAt','updatedAt']);if(!uuid(r.id)||r.ownerId!==owner||!hash(r.bundleHash)||!['preparing','installed'].includes(String(r.state))||!Number.isSafeInteger(r.version)||Number(r.version)<1||Number(r.version)>2147483647)throw bad();identity(r.source);native(r.native);if(hasTrust){trust(r.trust);if(!hash(r.trustHash))throw bad()}timestamp(r.createdAt);timestamp(r.updatedAt);if(String(r.updatedAt)<String(r.createdAt))throw bad();return r}
function preview(v:unknown){const r=exact(v,['source','bundleHash','native','files']);identity(r.source);native(r.native);if(!hash(r.bundleHash)||!Array.isArray(r.files)||r.files.length<1||r.files.length>500)throw bad();let total=0,previous='',entries=0;for(const f of r.files){const row=exact(f,['path','hash','size']);if(typeof row.path!=='string'||!row.path||row.path.length>500||row.path.startsWith('/')||/[\\:?%#\u0000-\u001f\u007f]/.test(row.path)||row.path.split('/').some(x=>!x||x==='.'||x==='..')||row.path<=previous||!hash(row.hash)||!Number.isSafeInteger(row.size)||Number(row.size)<0||Number(row.size)>2*1024*1024)throw bad();previous=row.path;total+=Number(row.size);if(row.path.split('/').at(-1)==='SKILL.md')entries++}if(total>20*1024*1024||entries!==1||!r.files.some(f=>f.path==='SKILL.md'))throw bad();return r}
function matches(input:ReturnType<typeof source>,v:unknown){return isRecord(v)&&(input.kind==='atomic'?v.kind==='atomic'&&v.contentId===input.contentId:(v.kind==='industry-local'||v.kind==='industry-public')&&v.loadId===input.loadId&&v.itemInstanceId===input.itemInstanceId)}
/** 认证工作台只传固定来源身份；绝对目录、本人身份与安装路径全部由宿主决定。 */
export function createSkillInstallationsHandler(owner:string,get:()=>Promise<Ports>,observe?:(installationId:string)=>Promise<unknown>){return async(method:string,payload:unknown)=>{
 if(method==='skill-installations/observe'){const row=taskInput(payload,['installationId']);if(!uuid(row.installationId))throw invalid();if(!observe)throw new WorkError('teloa/host-unavailable','原生安装观测未接通。');const value=await observe(row.installationId.toLowerCase());if(!isRecord(value)||Object.keys(value).some(k=>!['installationId','scope','state','reason','current'].includes(k))||value.installationId!==row.installationId.toLowerCase()||value.scope!=='default-workspace'||!['available','shadowed','missing','disabled'].includes(String(value.state)))throw bad();if(value.state==='shadowed'){if(value.reason!=='different-source'&&value.reason!=='content-changed')throw bad()}else if(value.reason!==undefined)throw bad();if(value.state==='missing'||value.state==='disabled'){if(value.current!==null)throw bad()}else{const current=exact(value.current,['name','description','modelInvocable','userInvocable','bodyHash','provider','source']);const {provider,source:origin,...metadata}=current;native(metadata);if(typeof provider!=='string'||!provider||typeof origin!=='string'||!origin)throw bad()}return value}
 if(method==='skill-installations/preview'){const row=taskInput(payload,['source']),fixed=source(row.source),result=await(await get()).preview(owner,{source:fixed});preview({source:result.source,bundleHash:result.bundleHash,native:result.native,files:result.files});if(result.trust!==undefined||result.trustHash!==undefined||result.installationPlan!==undefined){trust(result.trust);if(!hash(result.trustHash)||!isRecord(result.installationPlan))throw bad()}if(!matches(fixed,result.source))throw bad();return result}
 if(method==='skill-installations/install'){const row=taskInput(payload,['requestId','source','expectedBundleHash','expectedTrustHash']);if(!uuid(row.requestId)||!hash(row.expectedBundleHash)||row.expectedTrustHash!==undefined&&!hash(row.expectedTrustHash))throw invalid();const fixed=source(row.source),result=await(await get()).install(owner,{requestId:row.requestId.toLowerCase(),source:fixed,expectedBundleHash:row.expectedBundleHash,...(row.expectedTrustHash?{expectedTrustHash:row.expectedTrustHash}:{})});exact(result,['installation','source']);record(result.installation,owner);if(canonical(result.installation.source)!==canonical(result.source))throw bad();if(!matches(fixed,result.source)||result.installation.bundleHash!==row.expectedBundleHash||row.expectedTrustHash!==undefined&&result.installation.trustHash!==row.expectedTrustHash)throw bad();return result}
 if(method==='skill-installations/get'){const row=taskInput(payload,['installationId']);if(!uuid(row.installationId))throw invalid();const result=await(await get()).get(owner,{installationId:row.installationId.toLowerCase()});record(result,owner);if(result.id!==row.installationId.toLowerCase())throw bad();return result}
 if(method==='skill-installations/list'){taskInput(payload,[]);const result=await(await get()).list(owner,{}),ids=new Set<string>();exact(result,['items','usages']);if(!Array.isArray(result.items)||!Array.isArray(result.usages))throw bad();for(const item of result.items){record(item,owner);if(ids.has(item.id))throw bad();ids.add(item.id)}const uses=new Set<string>();for(const use of result.usages){exact(use,['loadId','itemInstanceId','installationId']);const key=use.loadId+':'+use.itemInstanceId;if(!uuid(use.loadId)||!uuid(use.itemInstanceId)||!ids.has(use.installationId)||uses.has(key))throw bad();uses.add(key)}return result}
 throw new WorkError('teloa/not-found','未提供此技能安装接口。')
}}
