import {createHash} from 'node:crypto'
import type {PoolClient} from 'pg'
import {WorkError,isRecord,readScheduleTrigger,type ScheduleTrigger} from '@teloa/contract'
import {validateManifest,type MarketContentStore} from '../market/content-store.ts'
import type {IndustryLoadService} from './industry-loads.ts'
import type {IndustryWorkSnapshot,IndustryWorkSource} from './industry-work-source.ts'

export type IndustryPlanSnapshot={loadId:string;itemInstanceId:string;itemLocalId:string;contentId:string;contentHash:string;planVersion:string;planFileHash:string;title:string;work:IndustryWorkSnapshot;dataScope:string;trigger:ScheduleTrigger;scope:string}
const unavailable=(message:string)=>new WorkError('teloa/source-unavailable',message)
export class IndustryPlanSource{
 private readonly market:Pick<MarketContentStore,'get'|'getInTransaction'>;private readonly loads:Pick<IndustryLoadService,'get'|'getInTransaction'>;private readonly works:Pick<IndustryWorkSource,'read'|'assertModelsReady'>
 constructor(market:Pick<MarketContentStore,'get'|'getInTransaction'>,loads:Pick<IndustryLoadService,'get'|'getInTransaction'>,works:Pick<IndustryWorkSource,'read'|'assertModelsReady'>){this.market=market;this.loads=loads;this.works=works}
 async assertModelsReady(owner:string,snapshot:IndustryPlanSnapshot,client?:PoolClient){await this.works.assertModelsReady(owner,snapshot.work,client)}
 async read(owner:string,loadId:string,itemInstanceId:string,client?:PoolClient):Promise<IndustryPlanSnapshot>{const load=client?await this.loads.getInTransaction(client,owner,{loadId}):await this.loads.get(owner,{loadId}),item=load.items.find(row=>row.instanceId===itemInstanceId);if(!item||item.kind!=='plan'||item.status!=='pending-adapter')throw unavailable('目标不是可使用的行业持续计划。');const content=client?await this.market.getInTransaction(client,{ownerId:owner,kind:'human'},{contentId:load.contentId}):await this.market.get({ownerId:owner,kind:'human'},{contentId:load.contentId});if(content.kind!=='industry-template'||content.hash!==load.contentHash)throw unavailable('持续计划固定内容与加载记录不一致。');const manifest=validateManifest(content.metadata),resource=manifest.resources.find(row=>row.id===item.localId);if(!resource||resource.kind!=='plan'||resource.version!==item.version||resource.source.kind!=='local')throw unavailable('持续计划声明与加载记录不一致。');const root=content.manifestPath.includes('/')?content.manifestPath.slice(0,content.manifestPath.lastIndexOf('/')+1):'',path=root+resource.source.path,provided=content.provides.find(row=>row.resourceId===item.localId),file=content.files.find(row=>row.path===path);if(!provided||provided.kind!=='plan'||provided.version!==item.version||provided.path!==path||!file||file.bytes.byteLength>128*1024)throw unavailable('持续计划文件不存在、过大或身份不一致。');let raw:string;try{raw=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(file.bytes)}catch{throw unavailable('持续计划不是有效 UTF-8。')}let value:unknown;try{value=JSON.parse(raw)}catch{throw unavailable('持续计划不是有效 JSON。')}if(!isRecord(value)||Object.keys(value).length!==6||Object.keys(value).some(key=>!['format','version','title','workTemplate','dataScope','trigger'].includes(key))||value.format!=='teloa.plan/v1'||value.version!==item.version||typeof value.workTemplate!=='string')throw unavailable('持续计划格式或版本不正确。');const workItem=load.items.find(row=>row.localId===value.workTemplate);if(!workItem||workItem.kind!=='work-template'||workItem.status!=='pending-adapter')throw unavailable('持续计划引用的工作模板不可不存在或不可用。');let trigger:ScheduleTrigger;try{trigger=readScheduleTrigger(value.trigger)}catch{throw unavailable('持续计划日程不合法。')}const text=(v:unknown,max:number)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw unavailable('持续计划文本字段不合法。');return v.trim()},work=await this.works.read(owner,load.id,workItem.instanceId,client);return {loadId:load.id,itemInstanceId:item.instanceId,itemLocalId:item.localId,contentId:load.contentId,contentHash:load.contentHash,planVersion:item.version,planFileHash:createHash('sha256').update(file.bytes).digest('hex'),title:text(value.title,120),work,dataScope:text(value.dataScope,8000),trigger,scope:load.space.scope}}
}
