import test from 'node:test'
import assert from 'node:assert/strict'
import {SessionId,SessionSeq,type SessionEvent} from '@deepseek-ai/dsh-session'
import {inspectNativeAbort,NativeReassignmentAttestor,inspectColdTeamSettlement,readNativeReassignmentInspection,collectNativeJobOwnerSettlement,withNativeResourceInspection} from '../src/business-reassignment-native.ts'
const run={id:'run',taskId:'task',sessionId:'session',nativeRequestId:'rpc',state:'ended',stopRequestedAt:'2026-09-30',evidence:{state:'ended',turn:0,messageSeq:1,endSeq:2,reason:'aborted'}}
const start=(turn=0)=>({type:'turn/start',data:{turn}})
const message=(rpcId='rpc',kind='user')=>({type:'user/message',surfaceOp:'append',data:{id:'message',source:{kind,rpcId},role:'user',content:[]}})
const end=(turn=0,kind='aborted',cause='user')=>({type:'turn/end',data:{turn,reason:{kind,reason:{kind:cause}}}})
const inspection=(rows:object[]=[start(),message(),end()],inheritedEventCount=0)=>({meta:{id:SessionId('session')},inheritedEventCount,events:rows.map((row,seq)=>({seq:SessionSeq(seq),time:seq,...row})) as SessionEvent[]})
const inspect=(rows?:object[],fixed=run,inherited=0)=>inspectNativeAbort(fixed,inspection(rows,inherited)) as {turn:number;ownedEndTurn:number;endSeq:number;eventHash:string}
test('real_native_aborted_has_precise_event_hash',()=>{const proof=inspect();assert.equal(proof.endSeq,2);assert.equal(proof.turn,0);assert.match(proof.eventHash,/^[a-f0-9]{64}$/)})
test('idle_without_native_end_is_not_abort_proof',()=>assert.throws(()=>inspect([start(),message()]),/原生/))
test('stop_requested_plus_completed_is_rejected',()=>{for(const reason of ['completed','error','interrupted','forked'])assert.throws(()=>inspect([start(),message(),end(0,reason)]),/原生/)})
test('wrong_rpc_turn_or_end_seq_is_rejected',()=>{assert.throws(()=>inspect([start(),message('other'),end()]));assert.throws(()=>inspect([start(),message(),end(1)]));assert.throws(()=>inspect(undefined,{...run,evidence:{...run.evidence,endSeq:3}}));const log=inspection();log.events[1]={...log.events[1]!,seq:SessionSeq(4)};assert.throws(()=>inspectNativeAbort(run,log))})
test('synthetic_historical_aborted_requires_reinspection',()=>{assert.throws(()=>inspect([start(),message()]));assert.throws(()=>inspect([start(),message(),end(0,'aborted','legacy')]));assert.throws(()=>inspect([start(),message(),end(0,'aborted','import')]))})
test('inherited_rpc_id_is_not_own_request',()=>assert.throws(()=>inspect(undefined,run,2)))
test('duplicate_or_foreign_request_blocks',()=>{assert.throws(()=>inspect([start(),message(),message(),end()]));assert.throws(()=>inspect([start(),message(),message('other'),end()]))})
test('continuation_uses_owned_end_turn',()=>{const fixed={...run,evidence:{...run.evidence,endSeq:5}};const proof=inspect([start(),message(),end(0,'completed'),start(1),message('notice','tool-jobs'),end(1)],fixed);assert.equal(proof.turn,0);assert.equal(proof.ownedEndTurn,1);assert.equal(proof.endSeq,5)})
test('projection_unregistered_or_failed_blocks',()=>{for(const registry of [undefined,{restore:()=>({snapshot:{values:{}}})},{restore:()=>({snapshot:{values:{agentTeam:{failure:'broken',members:[],tasks:[]}}}})}])assert.throws(()=>inspectColdTeamSettlement(inspection() as never,registry as never))})
test('team_pending_mailbox_or_task_blocks',()=>{const registry={restore:()=>({snapshot:{values:{agentTeam:{members:[],tasks:[{status:'pending'}]}}}})};assert.throws(()=>inspectColdTeamSettlement(inspection() as never,registry as never));const queued={type:'team/message/queued',data:{teamId:'session',message:{id:'m',targetId:'child'}}};const clean={restore:()=>({snapshot:{values:{agentTeam:{members:[],tasks:[]}}}})};assert.throws(()=>inspectColdTeamSettlement(inspection([start(),message(),end(),queued]) as never,clean as never))})
test('attestation_rechecks_tuple_and_associations_outside_native_io',async()=>{let snapshot='first',inTransaction=false,records=0;const targets={oldRequestId:'old',oldSessionId:'daily',scope:'business',targets:[{roleId:'role',taskRequestId:'child',taskId:'task',runs:[{id:'run',taskId:'task',sessionId:'session',nativeRequestId:'rpc'}]}]};const ports={withRunTransaction:async(_owner:unknown,_identity:unknown,work:Function)=>{inTransaction=true;try{return await work({},run)}finally{inTransaction=false}},readSettlement:async()=>snapshot,hashSettlement:()=> 'a'.repeat(64),readInspection:async()=>{assert.equal(inTransaction,false);snapshot='changed';return inspection()},recordProof:async()=>{records++}};await assert.rejects(new NativeReassignmentAttestor(ports as never).attestReassignmentRuns('owner',targets,new AbortController().signal));assert.equal(records,0)})
test('aborted_or_late_inspection_writes_zero_proof',async()=>{const controller=new AbortController();let records=0;const ports={withRunTransaction:async(_owner:unknown,_identity:unknown,work:Function)=>work({},run),readSettlement:async()=> 'fixed',hashSettlement:()=> 'a'.repeat(64),readInspection:async()=>{controller.abort();return inspection()},recordProof:async()=>{records++}};await assert.rejects(new NativeReassignmentAttestor(ports as never).attestReassignmentRuns('owner',{oldRequestId:'old',oldSessionId:'daily',scope:'business',targets:[{roleId:'role',taskRequestId:'child',taskId:'task',runs:[{id:'run',taskId:'task',sessionId:'session',nativeRequestId:'rpc'}]}]},controller.signal));assert.equal(records,0)})
test('attestation_fixed_snapshot_records_once_without_changing_old_evidence',async()=>{let records=0;const previous=JSON.stringify(run.evidence);const ports={withRunTransaction:async(_owner:unknown,_identity:unknown,work:Function)=>work({},run),readSettlement:async()=> 'fixed',hashSettlement:()=> 'a'.repeat(64),readInspection:async()=>inspection(),recordProof:async()=>{records++}};await new NativeReassignmentAttestor(ports as never).attestReassignmentRuns('owner',{oldRequestId:'old',oldSessionId:'daily',scope:'business',targets:[{roleId:'role',taskRequestId:'child',taskId:'task',runs:[{id:'run',taskId:'task',sessionId:'session',nativeRequestId:'rpc'}]}]},new AbortController().signal);assert.equal(records,1);assert.equal(JSON.stringify(run.evidence),previous)})
test('attached_read_flushes_and_cold_inspect_never_activates',async()=>{let flushed=0,cold=0;const original=inspection();let attached={header:original.meta,inheritedEventCount:0,snapshotEvents:()=>original.events};const ports={get:()=>attached,flush:async()=>{flushed++;return true},inspect:async()=>{cold++;return original}};const signal=new AbortController().signal;assert.deepEqual(await readNativeReassignmentInspection(ports as never,run,signal),original);assert.equal(flushed,1);assert.equal(cold,0);attached=undefined as never;assert.deepEqual(await readNativeReassignmentInspection(ports as never,run,signal),original);assert.equal(cold,1)})
test('attached_flush_failure_or_wrong_cold_identity_blocks',async()=>{const original=inspection(),ports={get:()=>({header:original.meta,inheritedEventCount:0,snapshotEvents:()=>original.events}),flush:async()=>false,inspect:async()=>original};await assert.rejects(readNativeReassignmentInspection(ports as never,run,new AbortController().signal));await assert.rejects(readNativeReassignmentInspection({...ports,get:()=>undefined,inspect:async()=>({...original,meta:{id:SessionId('other')}})} as never,run,new AbortController().signal))})
test('exact_live_owner_jobs_collect_terminal_facts_not_idle_boolean',()=>{const owner={runId:'run',kind:'job',nativeId:'owner:current:session',sessionId:'session',payload:{record:'owner',runtimeId:'current',requestId:'rpc'}};const job={runId:'run',kind:'job',nativeId:'current:job',sessionId:'session',payload:{record:'job',runtimeId:'current',requestId:'rpc',jobId:'job',status:'killed'}};const jobs={list:()=>[{id:'job',owner:'session',status:'killed',startedAt:1,finishedAt:2}],get:()=>({id:'job',owner:'session',status:'killed',startedAt:1,finishedAt:2})};const facts=collectNativeJobOwnerSettlement(run,inspection(),[owner,job] as never,'current',jobs as never,{nextTurn:[],nextStep:[]});assert.equal(facts.owners[0]?.jobs[0]?.id,'job');assert.equal(facts.owners[0]?.jobs[0]?.status,'killed')})
test('missing_or_old_owner_job_and_inbox_are_unknown',()=>{const owner={runId:'run',kind:'job',nativeId:'owner:old:session',sessionId:'session',payload:{record:'owner',runtimeId:'old',requestId:'rpc'}};const jobs={list:()=>[],get:()=>{throw Error('missing')}};assert.throws(()=>collectNativeJobOwnerSettlement(run,inspection(),[owner] as never,'current',jobs as never,{nextTurn:[],nextStep:[]}));const current={...owner,nativeId:'owner:current:session',payload:{...owner.payload,runtimeId:'current'}};const job={...current,nativeId:'current:missing',payload:{record:'job',runtimeId:'current',requestId:'rpc',jobId:'missing',status:'killed'}};assert.throws(()=>collectNativeJobOwnerSettlement(run,inspection(),[current,job] as never,'current',jobs as never,{nextTurn:[],nextStep:[]}));assert.throws(()=>collectNativeJobOwnerSettlement(run,inspection(),[current] as never,'current',jobs as never,{nextTurn:[{id:'pending'}],nextStep:[]} as never))})
test('live_maintenance_without_atomic_input_fence_cannot_enter_record_callback',async()=>{let received=false;const original=inspection();const agent={id:'session',inbox:{nextTurn:[],nextStep:[]},whenIdle:async()=>{},runMaintenance:async()=>{throw Error('不能把maintenance当输入冻结闸')}};const ports={get:()=>({header:original.meta,inheritedEventCount:0,snapshotEvents:()=>original.events}),flush:async()=>true,inspect:async()=>original};await assert.rejects(withNativeResourceInspection(agent as never,ports as never,run,{list:async()=>[]} as never,'current',{list:()=>[],get:()=>{throw Error('no job')}} as never,new AbortController().signal,async()=>{received=true}));assert.equal(received,false)})
test('untracked_job_without_owner_link_is_unknown',()=>assert.throws(()=>collectNativeJobOwnerSettlement(run,inspection(),[],'current',{list:()=>[{owner:'session',status:'running'}],get:()=>{throw Error('missing')}} as never,{nextTurn:[],nextStep:[]})))
test('unregistered_team_events_cannot_bypass_association_store',()=>assert.throws(()=>inspect([start(),message(),end(),{type:'team/task',data:{version:2,teamId:'session',task:{id:'pending',status:'pending'}}}])))
test('live_collector_rejects_terminal_jobs_without_exact_owner',()=>{
 const orphan={runId:'run',kind:'job',nativeId:'old:job',sessionId:'session',payload:{record:'job',runtimeId:'old',requestId:'rpc',jobId:'job',status:'killed'}}
 const owner={runId:'run',kind:'job',nativeId:'owner:current:session',sessionId:'session',payload:{record:'owner',runtimeId:'current',requestId:'rpc'}}
 for(const links of [[orphan],[owner,orphan]])assert.throws(()=>collectNativeJobOwnerSettlement(run,inspection(),links as never,'current',{list:()=>[],get:()=>{throw Error('uncovered job')}} as never,{nextTurn:[],nextStep:[]}))
})
for(const window of ['record','commit'])test('late_inbox_during_'+window+'_cannot_persist_facts_or_proof',async()=>{
 const original=inspection(),inbox={nextTurn:[] as unknown[],nextStep:[] as unknown[]}
 const agent={id:'session',inbox,whenIdle:async()=>{},runMaintenance:async(work:Function)=>work(new AbortController().signal)}
 const inspectionPorts={get:()=>({header:original.meta,inheritedEventCount:0,snapshotEvents:()=>original.events}),flush:async()=>true,inspect:async()=>original}
 const owner={runId:'run',kind:'job',nativeId:'owner:current:session',sessionId:'session',payload:{record:'owner',runtimeId:'current',requestId:'rpc'}}
 let persistedFacts=0,persistedProofs=0,stagedFacts=0,stagedProofs=0
 const enqueue=()=>inbox.nextTurn.push({id:'late',source:{kind:'tool-jobs'}})
 const ports={
  withRunTransaction:async(_owner:unknown,_identity:unknown,work:Function)=>{
   const result=await work({},run)
   if(stagedFacts||stagedProofs){if(window==='commit')await Promise.resolve().then(enqueue);persistedFacts+=stagedFacts;persistedProofs+=stagedProofs}
   return result
  },readSettlement:async()=> 'fixed',hashSettlement:()=> 'a'.repeat(64),readInspection:async()=>original,
  withInspection:(identity:unknown,signal:AbortSignal,work:Function)=>withNativeResourceInspection(agent as never,inspectionPorts as never,identity as never,{list:async()=>[owner]} as never,'current',{list:()=>[],get:()=>{throw Error('no job')}} as never,signal,work as never),
  recordResources:async()=>{stagedFacts++;if(window==='record')await Promise.resolve().then(enqueue)},recordProof:async()=>{stagedProofs++},
 }
 await assert.rejects(new NativeReassignmentAttestor(ports as never).attestReassignmentRuns('owner',{oldRequestId:'old',oldSessionId:'daily',scope:'business',targets:[{roleId:'role',taskRequestId:'child',taskId:'task',runs:[{id:'run',taskId:'task',sessionId:'session',nativeRequestId:'rpc'}]}]},new AbortController().signal))
 assert.equal(persistedFacts,0);assert.equal(persistedProofs,0)
})
