// 正式产品主题令牌的源码真源；沿用已核验的原型主题数值，构建直接使用本文件。
export const prototypeThemes:Record<'light'|'dark',Record<string,string>> = {
  "light": {
    "--teloa-design-bg": "#fcfcfb",
    "--teloa-design-sidebar": "#f3f2ef",
    "--teloa-design-surface": "#ffffff",
    "--teloa-design-subtle": "#f7f7f5",
    "--teloa-design-hover": "#eae9e5",
    "--teloa-design-text": "#242723",
    "--teloa-design-muted": "#646860",
    "--teloa-design-border": "#e3e4de",
    "--teloa-design-accent": "#a34529",
    "--teloa-design-accent-bg": "#fbede7",
    "--teloa-design-on-accent": "#ffffff",
    "--teloa-design-good": "#2f6c51",
    "--teloa-design-good-bg": "#eaf3ed",
    "--teloa-design-warn": "#865511",
    "--teloa-design-warn-bg": "#fcf1db",
    "--teloa-design-info": "#44617e",
    "--teloa-design-info-bg": "#eaf0f7",
    "--teloa-design-overlay": "#10181466",
    "--teloa-design-shadow": "0 12px 40px #111b1412",
    "--teloa-design-font": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    "--teloa-design-mono": "ui-monospace, SFMono-Regular, Menlo, monospace",
    "--teloa-design-text-xs": "12px",
    "--teloa-design-text-sm": "13px",
    "--teloa-design-text-base": "14px",
    "--teloa-design-text-body": "15px",
    "--teloa-design-text-lg": "18px",
    "--teloa-design-text-xl": "24px",
    "--teloa-design-text-title": "30px",
    "--teloa-design-lh": "1.6",
    "--teloa-design-s1": "4px",
    "--teloa-design-s2": "8px",
    "--teloa-design-s3": "12px",
    "--teloa-design-s4": "16px",
    "--teloa-design-s5": "20px",
    "--teloa-design-s6": "24px",
    "--teloa-design-s8": "32px",
    "--teloa-design-s10": "40px",
    "--teloa-design-s12": "48px",
    "--teloa-design-r1": "6px",
    "--teloa-design-r2": "10px",
    "--teloa-design-r3": "16px",
    "--teloa-design-round": "999px"
  },
  "dark": {
    "--teloa-design-bg": "#20221f",
    "--teloa-design-sidebar": "#191b18",
    "--teloa-design-surface": "#282b26",
    "--teloa-design-subtle": "#242721",
    "--teloa-design-hover": "#33372e",
    "--teloa-design-text": "#e9ece4",
    "--teloa-design-muted": "#a8b09f",
    "--teloa-design-border": "#3c4235",
    "--teloa-design-accent": "#f2a386",
    "--teloa-design-accent-bg": "#3c2a22",
    "--teloa-design-on-accent": "#281c16",
    "--teloa-design-good": "#9bceb0",
    "--teloa-design-good-bg": "#263c30",
    "--teloa-design-warn": "#e7bf74",
    "--teloa-design-warn-bg": "#3c3424",
    "--teloa-design-info": "#a2bfdf",
    "--teloa-design-info-bg": "#293440",
    "--teloa-design-overlay": "#10181466",
    "--teloa-design-shadow": "0 12px 40px #111b1412",
    "--teloa-design-font": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    "--teloa-design-mono": "ui-monospace, SFMono-Regular, Menlo, monospace",
    "--teloa-design-text-xs": "12px",
    "--teloa-design-text-sm": "13px",
    "--teloa-design-text-base": "14px",
    "--teloa-design-text-body": "15px",
    "--teloa-design-text-lg": "18px",
    "--teloa-design-text-xl": "24px",
    "--teloa-design-text-title": "30px",
    "--teloa-design-lh": "1.6",
    "--teloa-design-s1": "4px",
    "--teloa-design-s2": "8px",
    "--teloa-design-s3": "12px",
    "--teloa-design-s4": "16px",
    "--teloa-design-s5": "20px",
    "--teloa-design-s6": "24px",
    "--teloa-design-s8": "32px",
    "--teloa-design-s10": "40px",
    "--teloa-design-s12": "48px",
    "--teloa-design-r1": "6px",
    "--teloa-design-r2": "10px",
    "--teloa-design-r3": "16px",
    "--teloa-design-round": "999px"
  }
}
